### ISSUE TITLE
Disc type detection fails in LXC / Container environments

### ISSUE THREAD

**Issue by duckfullstop** [automatic-ripping-machine/automatic-ripping-machine#100]
I've spent a few weeks trying to get ARM's current HEAD to work in a Proxmox / LXC stack, and I've traced it down to a recent systemd merge being the culprit (#76). Containers don't properly execute udev rules, so running `udevadm` at script runtime is effectively useless in this situation.

The workaround I came up with is effectively to rollback to the last tag before that merge (v1.4.0) and use the old udev execution method to pass through the requisite `ID_` labels into the container / wrapper script, but that's obviously less than ideal, so I would propose possibly making an alternate flow with either a flag or a different entry point that allows for retaining the traditional functionality. You could also potentially automatically detect this case by querying for the existence of the udev rules in the environment during execution, and using those (falling back to `udevadm` if they're not available).

I realise this is a fairly niche use case, but there's a fair number of homelabbers that use Proxmox, and a workaround like the above should (hopefully) be fairly simple to implement!

Further detail on my workaround: https://www.reddit.com/r/homelab/comments/7bgtu9/a_simple_solution_for_getting_automated_ripping/

**Comment by luaduck** [comment]
I'm happy to quickly fork and MR back in (it's a fairly simple fix), but considering udev is fairly fundamental to how ARM works, I figured it was worth raising this issue first to see if anyone had a better idea.

**Comment by ahnooie** [comment]
Hi, @luaduck, the main reason we moved from udev to systemd is we couldn't get the udev method to work on Ubuntu 16.10 LTS so I figured we had to move to systemd by the time 18.04 LTS came out.  I'm wondering if your solution is going to be a problem once you go past 16.04 LTS.  That said, it's great to have it working on LXC containers, I have an LXD host so I may try this workaround!  If there's anything the ARM can do to make your workaround easier without breaking the standard environments feel free to do a PR.

**Comment by miriad** [comment]
I used an LXC to pass through the device (both /dev/sr0 and /dev/sg2), make an automount script to create the device nodes (using mknode) to match those in the host. I then set lxc.mount.auto: sys:rw (so udev can run in the container).

I also needed to create a new apparmor profile that allowed for cgroupfs and udf/iso9660 mounts.

(Settings from proxmox lxc config):

<VMID>.conf:

lxc.apparmor.profile: lxc-container-default-cgns-mounting
lxc.cgroup.devices.allow: b 11:0 rwm
lxc.cgroup.devices.allow: c 21:2 rwm
lxc.autodev: 1
lxc.hook.autodev: /var/lib/lxc/111/mount-hook.sh
lxc.mount.auto: sys:rw



cat /etc/apparmor.d/lxc/lxc-default-cgns-mounting 
# Do not load this file.  Rather, load /etc/apparmor.d/lxc-containers, which
# will source all profiles under /etc/apparmor.d/lxc

profile lxc-container-default-cgns-mounting flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/lxc/container-base>

  # the container may never be allowed to mount devpts.  If it does, it
  # will remount the host's devpts.  We could allow it to do it with
  # the newinstance option (but, right now, we don't).
  deny mount fstype=devpts,
  mount fstype=cgroup -> /sys/fs/cgroup/**,
  mount fstype=cgroup2 -> /sys/fs/cgroup/**,
  mount fstype=ext*,
  mount fstype=xfs,
  mount fstype=btrfs,
  mount fstype=udf,
  mount fstype=iso9660,
}



With these settings, ARM works correctly, without any other components in the host. (using 2.1_dev branch)

**Comment by monkeyclass** [comment]
I used a combination of @miriad and the guide from @duckfullstop which got it to work in the latest version, rather than 1.4.0. The formatting on @miriad. I couldn't get the profile to work, but using the unconfined profile did work. I then have a script running using the containers crontab:
```
#!/bin/sh
mknod -m 666 /dev/sr0 b 11 0
ln -s /dev/sr0 /dev/cdrom
```
I then just followed the Readme on the latest version and it seems to work. I would like to get a more restrictive profile though.
