### ISSUE TITLE
Incorrect script in docker instalation guide📚 <title>

### ISSUE THREAD

**Issue by SzymonBaprawski** [automatic-ripping-machine/automatic-ripping-machine#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

Hi, in docker install guide there is line:
wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/v2_devel/scripts/installers/docker-setup.sh

But it is pointing to file with error, that causes new arm user to not be added to docker group. The error has been already fixed but the manual isn't pointing to corrected file.

The instruction should be: wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/main/scripts/docker-setup.sh

### The page

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker

### If you are able please provide the correction here

The instruction should be: wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/main/scripts/docker-setup.sh

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Corrected, thanks for catching that!
