### ISSUE TITLE
🔧 Baremetal: Support alternate installation paths

### ISSUE THREAD

**Issue by Fen-nix** [automatic-ripping-machine/automatic-ripping-machine#1022]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I generally tend to keep /home/ reserved for real users of the system, rather than services, so it would be nice to have the ability to have an alternate installation path.

Unfortunately it's not as simple as just changing the INSTALLPATH setting in the arm.yaml file, as many many scripts have hardcoded paths and make assumptions about where files will be located. The existence of the INSTALLPATH setting made me consider treating this as a bug rather than an enhancement.

For example, despite setting INSTALLPATH in the arm.yaml, the logger for the ripper is set up to the hardcoded path `/home/arm/logs`

```
if file:
    # create file logger handler
    file_handler = logging.FileHandler('/home/arm/logs/arm.log')
```

This occurs in a number of other spots as well.

### Describe the solution you'd like?

Ideally, everything that launches from arm should respect the INSTALLPATH defined in arm.yaml.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
When you are running ARM you are doing it on bare metal?
Can you clarify, are you expecting the install path to be the ARM scripts folder '/opt/arm' or the user folders '/home/arm?

**Comment by microtechno9000** [comment]
Had a look through the code, something like this would be possible, using something like a .env file to get the configuration.
However, noting the way ARM is currently setup and built, whilst not a large change the /opt/arm directory is called out in multiple places. To avoid breakage, sufficient testing would be required. 
I have added this issue/feature request to the ARM backlog and the Devs will work towards it in 2024.

If you have any coding experience, you are welcome to implement the change yourself and submit a PR
