### ISSUE TITLE
🐛 Little error in "docker-setup.sh" Line 86

### ISSUE THREAD

**Issue by Poweruser7** [automatic-ripping-machine/automatic-ripping-machine#1026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

There is an error in the script "docker-setup.sh" on Line 86.
it should back up the script but there is a dot "." missing before the first filename. 
from
        sudo mv /start_arm_container.sh ./start_arm_container.sh.bak
to
        sudo mv ./start_arm_container.sh ./start_arm_container.sh.bak

### To Reproduce

run the script "docker-setup.sh"

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

2.6.67

### Expected behavior?

Script should be backed up.

### Relevant log output

```shell
mv: the call of stat for '/start_arm_container.sh' is not possible: file or directory not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
If you are able, you can raise a PR to resolve the issue. Attach a log with the script reporting the correct behavior. If not, I will raise a PR.

**Comment by Poweruser7** [comment]
I'm sorry. I think this is over my github skills. Could you raise the pull request so I can learn how to do this? (This is my first activity on github)

**Comment by microtechno9000** [comment]
PR raised and linked, no issues doing that
Have a look through some of the github guides and reference information, It sounds like you have some experience with code and fault finding.
We always welcome additional help and support in fixing and resolving bugs, or even contributing features.
Have a look through the [contribution guide](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Contribute) if you would like to get into helping ARM
