### ISSUE TITLE
🐛 Docker fails to start with a danging abcde.conf file

### ISSUE THREAD

**Issue by microtechno9000** [automatic-ripping-machine/automatic-ripping-machine#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Following a rebuild of docker containers, having left arm config and /home/arm alone, docker failed to start

```
Adding arm user to 'render' group
cp: not writing through dangling symlink '/etc/arm/config/abcde.conf'
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1

*** Killing all processes...
```

abcde config in folder

```
ls -la /home/arm/config/
total 24
drwxr-xr-x  2 arm arm  4096 Dec 29 10:00 .
drwxr-xr-x 15 arm arm  4096 Dec 29 21:49 ..
lrwxrwxrwx  1 arm arm    16 Dec 29 10:00 abcde.conf -> /etc/.abcde.conf
-rwxr-xr-x  1 arm arm  1825 Dec 29 06:47 apprise.yaml
-rwxr-xr-x  1 arm arm 11723 Dec 29 06:48 arm.yaml
```

### To Reproduce

1. Docker setup and running
2. Remove docker container and images
3. Rebuild docker from the ARM script, or from ARM devtools
4. ARM won't start

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

A.R.M version: 2.6.67

### Expected behavior?

Docker container starts

### Relevant log output

```shell
Captured above
```

### Anything else?

Resolved the issue by moving the existing file
`sudo mv /home/arm/config/abcde.conf /home/arm/config/abcde.conf.bak`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Not sure when this was fixed, but as of v2.6.69 this bug no longer occurs
