### ISSUE TITLE
🐛 ARM db API key page shows as "Coming Soon"

### ISSUE THREAD

**Issue by joelishness** [automatic-ripping-machine/automatic-ripping-machine#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Link for ARM db API key is dead

### To Reproduce

1. "Send DVDs to API" page
2. Click link for API key form in "You can get one for free from here"
3. Get served a "Coming Soon!" page

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

Python version: 3.8.10
A.R.M version: 2.6.67
Current git version: ecbba569b20d61f455c47669dc96657ae8756455

### Expected behavior?

I expect to be served a form for requesting an ARM db API key

### Relevant log output

```shell
n/a
```

### Anything else?

![ARMdbAPIpage](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/5108006/493554d1-c969-4ff8-8e86-de94ba8f7ffe)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Site had expired, should be back online!
