### ISSUE TITLE
📚 Document contributing to the wiki?

### ISSUE THREAD

**Issue by pacohope** [automatic-ripping-machine/automatic-ripping-machine#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

I am willing to write a little bit of info related to launching this with `docker-compose`. Off the back of a comment in another issue, I built a `docker-compose.yaml` that successfully launches the ARM (I do mine from Portainer, but it's general). I can't find practical steps for how to contribute documentation to the Wiki.

I've reviewed the [contributing guide](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/a0d9175f2f8340609d98bdbff635b517374a5e1e/CONTRIBUTING.md) and the only mention of the wiki is _please submit a howto to the [wiki](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki)_. That's what I want to do, but I'm struggling to figure out how.

Reading [this stackoverflow answer](https://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki/77294223), it seems like forking the wiki repo and doing a pull request on it is fairly complicated, because GitHub treats those wiki repos a bit weird.

Before I went and did a bunch of work the wrong way, I thought I'd ask how to contribute docs the right way. It isn't obvious and a few searches didn't give me anything I was confident to spend time on.

Thanks for this project!

### The page

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Contribute

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
At the moment the wiki is locked for editing, with only the devs able to edit.

It can be pulled down and edited like the main repo, but at the moment the permissions are set so other users can't push changes.

If you have changes to add, you can put them into this issue and we can then add them into the wiki
