### ISSUE TITLE
🔧 FDD Support

### ISSUE THREAD

**Issue by TheRealGramdalf** [automatic-ripping-machine/automatic-ripping-machine#1031]
### Is this feature missing in the latest version?

- [ ] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I have many FDDs (Floppy Disk Drives) that need ripping - they are old, but have data on them that I would like to aggregate and peruse.

### Describe the solution you'd like?

In my case, an ISO would suffice; but the option to extract the directory structure would be appreciated (ideally in addition, rather than instead of - the ISO is the "Full" backup, in case there's an issue such as corrupted files/filesystem etc).

### Describe alternatives you've considered?

Don't support FDDs

### Anything else?

It might make sense to separate this into an optional feature flag/docker image etc, since the vast majority of people most likely won't need this functionality.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Unfortunately, this project is not intended for floppy disk or tape drive archiving, and both are permanently outside scope. I would recommend asking r/datahoarders about what to do with those.

**Comment by TheRealGramdalf** [comment]
Just as an update on this, would it be possible for me to write this as a custom plugin (or something of the like) with the arrival of v3? ARM seems to have most of the infrastructure in place already, so it wouldn't be just some hacky script - and I could use my ripping machine which is already set up with ARM to do it.
I'm not expecting anyone from ARM to develop something, but I'm not quite sure how it would work (i.e. just an extra python script adding more logic, patching the source code directly, will there be native plugin support to an extent etc).
