### ISSUE TITLE
🐛 404 Error for Luading Packages

### ISSUE THREAD

**Issue by Grumpypjs08** [automatic-ripping-machine/automatic-ripping-machine#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The software will not install

### To Reproduce

Run Install Script

Error:
Err:8 https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
Err:9 https://ppa.launchpadcontent.net/stebbins/handbrake-releases/ubuntu jammy Release
  404  Not Found [IP: 2620:2d:4000:1::81 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/stebbins/handbrake-releases/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

2.6.2

### Expected behavior?

For it to install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Which install script are you running?

**Comment by shitwolfymakes** [comment]
[These](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker) are the instructions you should be following, and v2.6.2 is wildly out of date
