### ISSUE TITLE
System crash on processing BluRay🐋 <title>

### ISSUE THREAD

**Issue by mrhobbeys** [automatic-ripping-machine/automatic-ripping-machine#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I put in a BluRay and waited for the copy to finish; then it ejected the disc. When it got to 18%, the entire system shut off.

### To Reproduce

1. Ubuntu 20.04 using Docker
2. Most basic config from the instructions. MKV key, OMDB key
3. Watching the web browser
4. No errors or indications, just a hard crash of the entire system

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

The continued operation of the ARM system to transcode the data

### Relevant log output

```shell
Encoding: task 1 of 1, 17.85 % (226.67 fps, avg 231.38 fps, ETA 00h01m24s)
Encoding: task 1 of 1, 17.98 % (226.67 fps, avg 231.38 fps, ETA 00h01m24s)
Encoding: task 1 of 1, 18.26 % (226.67 fps, avg 231.38 fps, ETA 00h01m24s)
Encoding: task 1 of 1, 18.39 % (226.67 fps, avg 231.38 fps, ETA 00h01m24s)

Sat Feb  3 23:19:44 UTC 2024 Entering docker wrapper
Sat Feb  3 23:19:44 UTC 2024 [[ARM] Starting ARM for Data Disk on sdc2 with File System ntfs
Sat Feb  3 23:19:44 UTC 2024 Entering docker wrapper
Sat Feb  3 23:19:44 UTC 2024 [[ARM] Starting ARM for Data Disk on sdb2 with File System ntfs
```

### Anything else?

I've tried with DVD and get the same result.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Can you post your docker configuration? It is odd that both DVD and Bluray don't work. Have you been able to get Music to work?

**Comment by mrhobbeys** [comment]
I'm not sure if this is the intended method of use but I started logging into the arm user instead of my regular user and it started working.

**Comment by microtechno9000** [comment]
Can you clarify, on the webpage or in the docker config?

could you post your docker config, and any logs please

**Comment by microtechno9000** [comment]
closing as stale
