### ISSUE TITLE
Not CD, Blu-ray, DVD or Data. Bailing out on sr0

### ISSUE THREAD

**Issue by mmorley0395** [automatic-ripping-machine/automatic-ripping-machine#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

hi all, I got the docker image pulled and configured, admin portal up and running, but any disk i've tried spits out 
```
Feb 24 18:13:30 caa02ad11ad4 ARM: [ARM] Entering docker wrapper
Feb 24 18:13:30 caa02ad11ad4 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Feb 24 18:13:32 caa02ad11ad4 ARM: [ARM] Entering docker wrapper
Feb 24 18:13:32 caa02ad11ad4 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
```
i've searched discord and other related github issues, and i've seen that a few others have had this issue. i'm using a wintale bluray/dvd drive. others have mentioned commenting out lines 63/64 in `/opt/arm/scripts/docker/docker_arm_wrapper.sh`, which didn't work for me. it did stop the disk from spitting out, but didn't continue with the rip. 

I've tried all three types of media, of varying vintages. all of them produce the same error. 

I'm running the latest docker image on a raspberry pi 4. optical drive is in the usb3 port.

` $ docker exec arm-rippers makemkvcon -r info` yields: 

```
MSG:1005,0,1,"MakeMKV v1.17.6 linux(armhf-release) started","%1 started","MakeMKV v1.17.6 linux(armhf-release)"
MSG:3338,0,2,"Downloading latest SDF to /root/.MakeMKV ...","Downloading latest %1 to %2 ...","SDF","/root/.MakeMKV"
MSG:3339,0,1,"Automatic SDF downloading is disabled or failed.","Automatic %1 downloading is disabled or failed.","SDF"
DRV:0,1,999,0,"BD-ROM hp BDDVDRW CT21L 1.02 K0OA7CJ0551","","/dev/sr0"
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
Use: makemkvcon [switches] Command [Parameters]
```

Thanks for your time!

### To Reproduce

1. Follow standard setup for docker image, on a Raspberry pi. There are other containers running, including a reverse proxy, but ARM is not routed into the reverse proxy at all. 
2. Insert disk into drive
3. Disk spins, ejects, log says `Not CD, Blu-ray, DVD or Data. Bailing out on sr0`

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

2.6.70

### Expected behavior?

Expect ARM to run, then handbrake to encode

### Anything else?

Raspbian OS, but running the docker image on the main iste.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mmorley0395** [comment]
Other info: I figured that I'd try to run MakeMKV directly to see if it's successful on its own. It was not, and yielded: 
 `User Automatic SDF downloading is disabled or failed.` 
I tried pulling the .bin from makemkv's site (https://www.makemkv.com/svq/[sdf.bin](https://www.makemkv.com/svq/sdf.bin) into the .MakeMKV directory in the container, but to no avail. 

Anything I should configure differently in docker or otherwise to try to address this?

**Comment by microtechno9000** [comment]
Within the docker container, what happens if you run ARM manually?

`python3 /opt/arm/arm/arm/ripper/main.py -d sr0`

**Comment by mmorley0395** [comment]
I get:
```
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 154, in <module>
    job = Job(devpath)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/state.py", line 567, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/opt/arm/arm/models/job.py", line 72, in __init__
    self.parse_udev()
  File "/opt/arm/arm/models/job.py", line 97, in parse_udev
    device = pyudev.Devices.from_device_file(context, self.devpath)
  File "/usr/local/lib/python3.8/dist-packages/pyudev/device/_device.py", line 226, in from_device_file
    return cls.from_device_number(context, device_type, device_number)
  File "/usr/local/lib/python3.8/dist-packages/pyudev/device/_device.py", line 183, in from_device_number
    raise DeviceNotFoundByNumberError(typ, number)
pyudev._errors.DeviceNotFoundByNumberError: No block device with number 2816
```

**Comment by microtechno9000** [comment]
looks like it is not reporting a drive to the system, can you share your docker start config. Also, can you provide the output from outside and within the docker container of `lssci`

**Comment by mmorley0395** [comment]
Yes for sure- I removed the other devices because sometimes sr0 wasn't recognized.
```
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -e ARM_UID="1001" \
    -e ARM_GID="1001" \
    -v "/home/arm:/home/arm" \
    -v "/home/pi/jellyfin/media/Music:/home/arm/music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/home/pi/jellyfin/media:/home/arm/media" \
    -v "/etc/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='1-3' \
    automaticrippingmachine/automatic-ripping-machine:latest
```
Output from host: `[1:0:0:0]    cd/dvd  hp       BDDVDRW CT21L    1.02  /dev/sr1 `
Output from container `[0:0:0:0]    cd/dvd  hp       BDDVDRW CT21L    1.02  -   `


I also want to note: when I first ran the python script, I got 'No such file or directory /dev/sr0', so I removed the other devs in the shell script above. Then I got the 'no block number 2816' error above. In either scenario, the outputs for lsscsi are the same.

**Comment by rabidoyster** [comment]
I've had the same experience
same "Not CD, Blu-ray, DVD or Data. Bailing out on sr0"
running ARM in docker on a new Debian 12 install on an x86 system, in my case, with a USB 3.0 enclosure for the optical drive. Commenting out the eject in lines 63/64 of docker_arm_wrapper.sh keeps it from popping out so I can then run main.py manually and that works. 
I also found before I disabled the eject, if I power off my optical drive immediately after inserting the disc, before it can eject, then when I power it back up it will automatically rip but as an unidentified disc (this was with a music cd fwiw)

**Comment by microtechno9000** [comment]
Seems to be an issue with USB drives, I havent seen this on my system but don't have a USB drive.

Looks like there are maybe some additional permissions needed for USB drives? 

I will look to see if I have a usb drive to test this on. If anyone had a solution please provide it or raise a PR

**Comment by rabidoyster** [comment]
Seems like you're on the right track, #572 seems to be related and the last comment indicates a USB drive is involved as well. 
I am not very savvy at these things but I installed usbutils in the ARM container and my drive showed up in lsusb the same as it did on the host: 
Bus 006 Device 005: ID 1e91:de2c Other World Computing Mercury Pro Optical

**Comment by microtechno9000** [comment]
Have a USB CD/DVD drive and initial testing hasn't raised any issues
Host ubuntu 20.04 LTS

Can you confirm the host OS you are running this on, #572 raised issues, with some users on unraid

Host: sr2 is the USB device
```bash
# lsscsi
[1:0:0:0]    cd/dvd  HL-DT-ST BDDVDRW CH12LS28 1.00  /dev/sr0 
[3:0:0:0]    cd/dvd  PLDS     DVD+-RW DH-16ABS PD11  /dev/sr1 
[7:0:0:0]    cd/dvd  IBM      RMBO0040552      SA60  /dev/sr2 
```

ARM config
```
cat start_arm_container.sh 
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -e ARM_UID="1001" \
    -e ARM_GID="1001" \
    -v "/home/arm:/home/arm" \
    -v "/home/arm/Music:/home/arm/Music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/home/arm/media:/home/arm/media" \
    -v "/home/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --privileged \
    --restart "always" \
    --name "automatic-ripping-machine" \
    --cpuset-cpus='2,3' \
    automatic-ripping-machine
```

Output from ARM when opening the settings page for sr2 is below, with no errors presented in the log
```
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug *********
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug Name: Drive 3
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug Type: CD/DVD
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug Mount: /dev/sr2
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug Open: True
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug Job Current: None
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug Job Previous: 11
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug Job - Status: fail
[2024-03-13 11:36:39,300] DEBUG ARM: DriveUtils.drive_status_debug Job - Type: Music
[2024-03-13 11:36:39,301] DEBUG ARM: DriveUtils.drive_status_debug Job - Title: Daft Punk Musique, Volume 1: 1993–2005
[2024-03-13 11:36:39,301] DEBUG ARM: DriveUtils.drive_status_debug Job - Year: 2006
[2024-03-13 11:36:39,301] DEBUG ARM: DriveUtils.drive_status_debug *********
```

**Comment by Natetronn** [comment]
I believe I may be experiencing this issue as well (or something similar).

I'm using a USB DVD Drive. I'm running the Docker version on a Manjaro host (aka Arch)

```
$ lsscsi
[0:0:0:0]    cd/dvd  HL-DT-ST DVDRAM GP40NB40  1.00  /dev/sr0 
```
```
$ nano arm.log
Fri Mar 22 09:46:12 UTC 2024 [ARM] Starting ARM for DVD on sr0
Fri Mar 22 09:52:56 UTC 2024 Entering docker wrapper
Fri Mar 22 09:52:56 UTC 2024 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
...
```
Happy tor provide any more details, just let me know what else you need. I will also update should I figure anything out on my end.

**Comment by microtechno9000** [comment]
If you run the script manually from within docker does that work?

**Comment by Natetronn** [comment]
I've setup another instance of ARM on a different machine and after some time was able to rip one DVD. It took forever on that external DVD burner, so I tried the internal instead. I haven't been able to get it to rip from the internal burner, however, so not sure what's up with that. It never shows up, but does give me the proper info when running it manually; but still doesn't run (I'll keep playing around.) 

For the original machine, which is a Pi 4B 8GB (perhaps that's the issue?), these are the errors I'm currently getting in the disc's logs: 

```
[03-23-2024 01:06:19] INFO ARM: Starting MakeMKV rip. Method is mkv
[03-23-2024 01:06:20] ERROR ARM: Call to MakeMKV failed with code: 1 (b'')
[03-23-2024 01:06:20] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[03-23-2024 01:06:20] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 46, in makemkv
    mdisc = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 53, in makemkv
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 203, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[03-23-2024 01:06:20] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

Same error as before in the arm.log.

**Comment by mmorley0395** [comment]
Switching from my Rasbperry pi to another machine (lenovo mini desktop) and setting it up with the same configuration fixed it- the same external USB drive is working fine, running without any need to change drive permissions. And it's running automatically as intended, no need to manually run the python script. Both used Ubuntu 22 LTS and were running the docker image.

**Comment by microtechno9000** [comment]
Possibly a raspberry pi issue?

**Comment by Natetronn** [comment]
Thanks all! 

Yes, I'm assuming it is something with the Pi at this point. I've since switch to my main machine and added a couple dvd drives. It's working fine, minus automatic rip. But I've created a bash function to get by, since it does work manually. I just run `rip sr0` (sr1 etc.) and it starts up fine.

Nothing fancy:

```
function rip() {
  if [ $# -eq 0 ]; then
    echo "Missing Optical Drive Argument! (sr0, sr1, etc.)"
    echo "Command to list devices: lsscsi -g"
  else
    docker exec arm-rippers python3 /opt/arm/arm/ripper/main.py -d "$1"
  fi
}
```
Note: I'm on an arch based distro, so there may be something there that is stopping the automated rip, but I'm not too worried about it. Maybe when I have more time I'll look into and report back my findings later and perhaps share the updated install script for those who may want it (I realize it and the Pi, for that matter, may not be supported, though.)

**Comment by dbhosttexas** [comment]
I know this is closed, but I am having this same exact issue / error.

Environment is Debian 12 AMD64 fresh load, updated and ARM installed. 

Hardware.
Mainboard MSI 970A-G43 (MS-7693)
AMD FX-8370 8cores 8 threads 4ghz
32GB DDR4
Video GeForce GT710 (Default kernel modules, no Nvidia driver)
1TB SATA HDD
SATA DVD/RW

This issue does not appear to be USB or Raspberry Pi specific as was noted above.

**Comment by irinelturturea** [comment]
i had a similar issue with ARM as container in truenas. I had to restart the container after connecting the usb drive otherwise the sr0 was not passed thru to the container

**Comment by jcl92240** [comment]
Having the same issue on a truenas install. Ripping music cd works bit DVD does not work.
