### ISSUE TITLE
ARM Won't Transcode

### ISSUE THREAD

**Issue by dexter686** [automatic-ripping-machine/automatic-ripping-machine#108]
I'm not sure if this is related to Issue #104, but I just installed ARM again (after using it perfectly a few months ago) on a fresh Ubuntu install.  The MakeMKV part works great, and I now have a small pile of folders in my raw folder.  But, the transcode script either fails out or never gets called, as HandbrakeCLI never runs and nothings ends up in the Unidentified folder.

Anyone have any ideas?  What logs or whatnot can I add to help clarify?

**Comment by muckngrind4** [comment]
You should have a log in /opt/arm/logs named after your DVD title. Post that and I'll see if I can help.

**Comment by designBr** [comment]
I'm having a nearly identical issue, ongoing for months now. Attached are my configs, running processes and logs.

I read through the scripts as best I could, it looks like the logs show the movie going through the ripping successfully and then being sent to the transcode queue, but all the logs stop there, nothing ever seems to come out transcoded.

If it's helpful, 'git rev-list --count HEAD' says '100'

## Processes currently running on server
Just showing it doesn't appear that any Handbrake processes are running
![processes](https://user-images.githubusercontent.com/450430/35599137-4ae92c4c-05f5-11e8-8df0-a191eee8ca31.png)

## Config File (scrubbed)
[config.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/1679986/config.txt)

## Log File (scrubbed, I have more if needed)
[ZACK_MIRI_BB.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/1680005/ZACK_MIRI_BB.log)

**Comment by designBr** [comment]
Just throwing ideas out...

I was looking at the "batch" command/argument that is used in the "video_rip.sh" script, and I see that it will only run "when  the  load  average  drops below 1.5" - [as per this ubuntu documentation.](http://manpages.ubuntu.com/manpages/xenial/en/man1/at.1.html)

When I run a "uptime" at the CLI, it shows that my load average is like 6.xx (I'm also running security camera software which constantly writes to disk), heres a screenshot:
![uptime](https://user-images.githubusercontent.com/450430/35601482-4be2a4f0-0601-11e8-864a-870afa1d700c.png)

Sanity check!?! Could that be the reason none of my vids are transcoding? Seems like a good possibility.

**Comment by designBr** [comment]
**UPDATE:** After stopping those other processes to drop my system load average, the transcoding started up again, and overnight a handful of titles were processed.

**Suggestion:** Perhaps it might be worth noting this in a troubleshooting section of the README in the repo? Something like "Media not transcoding? Check your 'load average', the transcode 'batch' queue will not commence at load averages above 1.5 (per processor core), see t[his documentation for batch details](http://manpages.ubuntu.com/manpages/xenial/en/man1/at.1.html), and [this for explanation](http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages).

Thanks a bunch for this awesome program, its soooooo helpful!
