### ISSUE TITLE
Test apprise:  'str' object has no attribute 'job_id'

### ISSUE THREAD

**Issue by eitch** [automatic-ripping-machine/automatic-ripping-machine#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I am using the latest docker release, and am trying out apprise test and am getting this:

```
        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

'str' object has no attribute 'job_id'
```

### To Reproduce

1. Configure apprise.yaml in arm.yaml
2. added gotify token and host in apprise.yaml UI editor
3. click "Send Test notification"

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

Python version: 3.8.10 
A.R.M version: 2.6.71 
Current git version: 8fcb540 

### Expected behavior?

Should send notification

### Relevant log output

```shell
None that i found
```

### Anything else?

Using Debian 12 with current docker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eitch** [comment]
Thank you @bot, i certainly did read the wiki

**Comment by microtechno9000** [comment]
What page are you getting that on? what is the ARM url please

**Comment by eitch** [comment]
I got this when clicking on the button here: http://10.0.110.174:8080/settings

This changed the URL to: http://10.0.110.174:8080/testapprise

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/245382/114b9fd8-1282-48fb-b6ef-f3334d2032b8)

**Comment by microtechno9000** [comment]
Checking that portion of code, there is no reference to job_id

1. From the settings page or in the arm.yml, set LOGLEVEL to DEBUG
2. from the host machine enter `docker logs -f automaticrippingmachine` (change the container name to what ever you call ARM on your host
3. Run through the same steps as above that caused this error, post the extract of the log from the crash here please

**Comment by eitch** [comment]
The reason i was testing this, was because the gotify apprise doesn't work. I see this now in the logs:

    DEBUG ARM: apprise_bulk.apprise_notify Sent apprise to GOTIFY_TOKEN was successful

But i don't see a call in my gotify web servers logs. I did a curl call with the token, and that works as expected...

**Comment by microtechno9000** [comment]
Thanks that was helpful 

Found where the code is being called, there is a bug. Will look to fix that soon.

With regards to implementing gotify, seems there is still some work with aprise to get all the interfaces working.
