### ISSUE TITLE
Subtitles are not being ripped

### ISSUE THREAD

**Issue by jb2cool** [automatic-ripping-machine/automatic-ripping-machine#109]
First of all, great work, this looks ideal for my purposes (backing up my DVD collection). I do have one issue though and something that i've struggled with in the past and that is forced subtitles for foreign/alien languages.

I've run a test DVD (Da Vinci code) through and both with and without transcoding the subtitles are not there (there should be some 12mins in). At first i thought this was Handbrake stripping these off but then i had a look at the main rip before handbrake transcoding and they are missing from there too.

Any advice?

**Comment by jb2cool** [comment]
Actually i'm not 100% sure they are being stripped off. The program i was using to test these was simply not showing them where it does show them playing the actual DVD.

If i manually rip with MakeMKV in Windows it does the same thing but when i play the file back with VLC i can see 2 subtitle tracks. Weirdly neither of these seem to be the 'forced subtitles', they seem to be subtitles for every bit of dialog, not just the foreign parts.

**Comment by ahnooie** [comment]
Here's what I have in my config... I like to get all subtitles but the native language the displays english when foreign language is spoken should be the first one.  I sometimes have to select the first subtitle track when playing a video. 

`HB_ARGS="--native-language` eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle-forced 1 --audio-lang-list eng --all-audio"

For your case you may want to look at the HandBrake CLI guide, https://handbrake.fr/docs/en/latest/cli/cli-guide.html perhaps subtitle-default or subtitle-burned would help.

**Comment by jb2cool** [comment]
I've had to dismantle my rig for the time being (xmas & new year) but hope to start up again in the next week or so. I'll try this out then on a couple of titles.

**Comment by jb2cool** [comment]
I've had no time to follow up on this, feel free to close the issue
