### ISSUE TITLE
🐋 How to update to latest code when using docker

### ISSUE THREAD

**Issue by littlejeem** [automatic-ripping-machine/automatic-ripping-machine#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [ ] I'm using the latest release

### Describe the bug?

TBH this is not a bug more a documentation need...and a help request. On the Wiki page there aren't any instructions on how to update arm when using the docker image. One of the closed issue #969 seems to reference dev-tools but i'm not sure how to use.

With other docker containers running via docker-compose it would be a ```docker pull``` command but I know arm is not quite ready for docker-compose yet so not sure to update preserving my database and information.

If someone can help get me there i'd be happy to add to the wiki.

### To Reproduce

None

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

Other (Please state in `Anything else` section)

### Expected behavior?

docker

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by littlejeem** [comment]
ok so would it be something like this:

Stop the existing container
```sudo docker stop arm-rippers```

Backup existing set-up
```cd /home
sudo cp -ar arm arm_backup```

```cd /etc/
sudo cp -ar arm arm_backup```

Remove the existing image
```sudo docker rm arm-rippers```

Re-run the install script, you will get errors 
```cd ~/
sudo ./start_arm_container.sh```

copy the backed up config to the live folder
```sudo cp /home/arm_backup/start_arm_container.sh /home/arm/```

start the container
```sudo /home/arm/start_arm_container.sh```

Once you've successfully done this, log into the arm web-ui, you will get a message from arm to say an upgrade has been detected and to choose to migrate the .db to the new version.

**Comment by microtechno9000** [comment]
Agree, some work is required to update the wiki and provide some useful information on updating ARM. 
To update ARM, all you need to do is run the below.
1. Stop the running ARM container
2. Pull the new version of ARM from Docker, this container is updated nightly following any new code changes made to ARM from Github
3. Docker prune, this removes any unused containers, which when running step 4 will cause issues if not run. This doesn't delete any user configurations, only the docker container created from step 4
4. Re-run the start configuration for your ARM setup

```bash
docker stop automatic-ripping-machine
docker pull automaticrippingmachine/automatic-ripping-machine
docker container prune
./start_arm_container.sh
```
