### ISSUE TITLE
🐛 U S E R Error cannot get ARM to work

### ISSUE THREAD

**Issue by 4MAZ** [automatic-ripping-machine/automatic-ripping-machine#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Please treat me like I am dumb. I have walked through the installation multiple times trying installing on Ubuntu and Docker following the instructions to the best of my ability with no luck. Hardware is Ryzen 7 3700X 32GB RAM 500 GB SSD GTX 1050TI.  I am using Ubuntu 20.04.6 LTS During installation I selected install all third party drivers. username is set to arm .Below is the input and output of the terminal when attempting to install via docker image. If I run tail -f /var/log/syslog | grep ARM I see nothing. Any help would be much appreciated. If I left something out I apologize.

### To Reproduce

[terminal input output start script contents.pdf](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/14846088/terminal.input.output.start.script.contents.pdf)

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

Latest As of 4/2/2024 

### Expected behavior?

 .

### Relevant log output

```shell
arm.log output
Wed Apr  3 02:26:30 UTC 2024 Entering docker wrapper
Wed Apr  3 02:26:31 UTC 2024 [ARM] Starting ARM for DVD on sr2
Wed Apr  3 02:42:51 UTC 2024 Entering docker wrapper
Wed Apr  3 02:42:58 UTC 2024 [ARM] Starting ARM for DVD on sr0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SylvainMT** [comment]
Hello there,

1. Install lscsi 'sudo apt update && sudo apt install lsscsi`
2. run `lsscsi -gd` and show us the results pls

**Comment by 4MAZ** [comment]
sudo apt update && sudo apt install lsscsi
[sudo] password for arm: 
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:2 http://ca.archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://ca.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:5 http://ca.archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 114 kB in 0s (280 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
lsscsi is already the newest version (0.30-0.1).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gir1.2-goa-1.0 gstreamer1.0-vaapi libfwupdplugin1
  libgstreamer-plugins-bad1.0-0 libllvm11 libva-wayland2 libxmlb1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
arm@armpc:~$ lsscsi -gd
[3:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr0 [11:0]  /dev/sg0 [21:0]
[4:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr1 [11:1]  /dev/sg1 [21:1]
[7:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr2 [11:2]  /dev/sg2 [21:2]
[8:0:0:0]    disk    ATA      Crucial_CT500MX2 MU02  /dev/sda [8:0]  /dev/sg3 [21:3]

**Comment by microtechno9000** [comment]
Your start script for docker, suggest the volumes point to specific folders otherwise you will end up with a bunch of files just sitting in the /home/arm folder

also, can you confirm docker is running
1. `docker ps`
2. if so, what do the logs say, `docker logs automatic-ripping-machine`

**Comment by 4MAZ** [comment]
docker ps
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/json": dial unix /var/run/docker.sock: connect: permission denied

**Comment by 4MAZ** [comment]
Also looking back at arm.log 
Wed Apr  3 02:26:30 UTC 2024 Entering docker wrapper
Wed Apr  3 02:26:31 UTC 2024 [ARM] Starting ARM for DVD on sr2
Wed Apr  3 02:42:51 UTC 2024 Entering docker wrapper
Wed Apr  3 02:42:58 UTC 2024 [ARM] Starting ARM for DVD on sr0
Wed Apr  3 06:52:36 UTC 2024 Entering docker wrapper
Wed Apr  3 06:52:36 UTC 2024 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on loop6
Wed Apr  3 06:52:36 UTC 2024 Entering docker wrapper
Wed Apr  3 06:52:36 UTC 2024 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on loop6
Wed Apr  3 06:52:36 UTC 2024 Entering docker wrapper
Wed Apr  3 06:52:36 UTC 2024 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on loop6

**Comment by SylvainMT** [comment]
Your `start_arm_container.sh` script's device entries should reflect the devices you have found using lsscsi

> [3:0:0:0] cd/dvd TSSTcorp CDDVDW SH-224DB SB01 /dev/sr0 [11:0] /dev/sg0 [21:0]
[4:0:0:0] cd/dvd TSSTcorp CDDVDW SH-224DB SB01 /dev/sr1 [11:1] /dev/sg1 [21:1]
[7:0:0:0] cd/dvd TSSTcorp CDDVDW SH-224DB SB01 /dev/sr2 [11:2] /dev/sg2 [21:2]

So your device entries in the script should be:

```
--device="/dev/sr0:/dev/sr0" \
--device="/dev/sr1:/dev/sr1" \
--device="/dev/sr2:/dev/sr2" \
```

Remove the line: 

```
--device="/dev/sr3:/dev/sr3" \
```

---

Run the `docker ps` command as sudo so: `sudo docker ps`

---

Finally, can you confirm if you have access to the UI?  http://<The up address of your arm machine>:8080/

**Comment by SylvainMT** [comment]
As @microtechno9000 mentionned.  Your `start_arm_container.sh` script's volume section could be cleaned up a little bit

```
-v "/home/arm:/home/arm" \
-v "/home/arm:/home/arm/music" \
-v "/home/arm:/home/arm/logs" \
-v "/home/arm:/home/arm/media" \
-v "/home/arm:/etc/arm/config" \
```

If not changed, your arm installation will store all the files in your /home/arm directory which might not be idea.

So let's break it down

`-v "/home/arm:/home/arm" \` : Is the location of the arm user home folder.  This line is correct and can stay as it is.  But let's explain it: 
* `-v`  Means you are telling `docker run` you want to specify a volume where docker can store files outside of it's container so they are persistant (never erased).  
* `"/home/arm:/home/arm"` Is the volume definition. These take the form of `"{Path_Outside_Of_Docker}:{Path_Inside_Docker}"`  You should not modify the _Path_Inside_Docker_ portion but you are asked to choose the path's outside of Docker.  
* `\` means you are letting the computer know the there are more lines to this command.

A small explanation of the purpose of each volume is below.  I will only refer to the docker portion of the path
* '/home/arm' is where your various settings files for MakeMKV, HandBrakeCLI, ARM Database files and similar will end up.
* '/home/arm/music' is where A.R.M. will save your rip music CDs.  You can redirect these to any location you wish on your computer.  The default recommended is `/home/arm/music`
* `home/arm/logs` is where A.R.M. will save it's logs.  I recommend you choose the location `home/arm/logs` on your computer as well.
* `/home/arm/media` is where A.R.M. will save your movies from DVDs and Blu-Rays, as well as any Data disk ISOs. A.R.M. will create three sub-folders in here; `raw`, `transcode` and `completed`  Your completed rips will be placed in `completed` The other two are required for the various stages of ripping the movies. Your ISO Data files will also find their way in the completed folder.  The default suggested location for this is `/home/arm/media` but can be placed anywhere you like.
* `/etc/arm/config` is where A.R.M. will look for the configuration files: `arm.yaml`, `apprise.yaml` and `abcde.conf` A clean copy of these will be placed in the folder if present.  The suggested location is `/home/arm/config`

I would rewrite your volumes section like this:

```
-v "/home/arm:/home/arm" \
-v "/home/arm/music:/home/arm/music" \
-v "/home/arm/logs:/home/arm/logs" \
-v "/home/arm/media:/home/arm/media" \
-v "/home/arm/config:/etc/arm/config" \
```

Make sure to create the `music`, `logs`, `media` and `config` directories with the mkdir command, logged in as the arm user (without the use of sudo).
```
mkdir /home/arm/logs
mkdir /home/arm/music
mkdir /home/arm/media
mkdir /home/arm/config
```

**Comment by microtechno9000** [comment]
> As @microtechno9000 mentionned.  Your `start_arm_container.sh` script's volume section could be cleaned up a little bit
> 
> ```
> -v "/home/arm:/home/arm" \
> -v "/home/arm:/home/arm/music" \
> -v "/home/arm:/home/arm/logs" \
> -v "/home/arm:/home/arm/media" \
> -v "/home/arm:/etc/arm/config" \
> ```
> 
> If not changed, your arm installation will store all the files in your /home/arm directory which might not be ideal.
> 
> So let's break it down
> 
> `-v "/home/arm:/home/arm" \` : Is the location of the arm user home folder.  This line is correct and can stay as it is.  But let's explain it: 
> * `-v`  Means you are telling `docker run` you want to specify a volume where docker can store files outside of it's container so they are persistant (never erased).  
> * `"/home/arm:/home/arm"` Is the volume definition. These take the form of `"{Path_Outside_Of_Docker}:{Path_Inside_Docker}"`  You should not modify the _Path_Inside_Docker_ portion but you are asked to choose the path's outside of Docker.  
> * `\` means you are letting the computer know the there are more lines to this command.
> 
> A small explanation of the purpose of each volume is below.  I will only refer to the docker portion of the path
> * `/home/arm` is where your various settings files for MakeMKV, HandBrakeCLI, ARM Database files and similar will end up.
> * `/home/arm/music` is where A.R.M. will save your rip music CDs.  You can redirect these to any location you wish on your computer.  The default recommended is `/home/arm/music`
> * `home/arm/logs` is where A.R.M. will save it's logs.  I recommend you choose the location `home/arm/logs` on your computer as well.
> * `/home/arm/media` is where A.R.M. will save your movies from DVDs and Blu-Rays, as well as any Data disk ISOs. A.R.M. will create three sub-folders in here; `raw`, `transcode` and `completed`  Your completed rips will be placed in `completed` The other two are required for the various stages of ripping the movies. Your ISO Data files will also find their way in the completed folder.  The default suggested location for this is `/home/arm/media` but can be placed anywhere you like.
> * `/etc/arm/config` is where A.R.M. will look for the configuration files: `arm.yaml`, `apprise.yaml` and `abcde.conf` A clean copy of these will be placed in the folder if present.  The suggested location is `/home/arm/config`
> 
> I would rewrite your volumes section like this:
> 
> ```
> -v "/home/arm:/home/arm" \
> -v "/home/arm/music:/home/arm/music" \
> -v "/home/arm/logs:/home/arm/logs" \
> -v "/home/arm/media:/home/arm/media" \
> -v "/home/arm/config:/etc/arm/config" \
> ```
> 
> Make sure to create the `music`, `logs`, `media` and `config` directories with the mkdir command, logged in as the arm user (without the use of sudo).
> ```
> mkdir /home/arm/logs
> mkdir /home/arm/music
> mkdir /home/arm/media
> mkdir /home/arm/config
> ```

Nice you should add this to the wiki

**Comment by 4MAZ** [comment]
Thanks for all that. I will work on doing that I did quickly try connecting to my machine at http://theipofmymachine:8080 and it is unable to connect.

**Comment by SylvainMT** [comment]
> Thanks for all that. I will work on doing that I did quickly try connecting to my machine at http://theipofmymachine:8080 and it is unable to connect.

What does `sudo Docker ps` say?

**Comment by 4MAZ** [comment]
For sanity I reinstalled ubuntu walked through the docker process again and recorded it going along so if any questions arise I can look back. Here is my new script config:
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -v "/home/arm:/home/arm" \
    -v "/home/arm/music:/home/arm/music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/home/arm/media:/home/arm/media" \
    -v "/home/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --privileged \
    --restart "always" \
    --name "automatic-ripping-machine" \
    --cpuset-cpus='2,3,4,5,6,7,8,9,10,11,12,13,14,15' \
    automaticrippingmachine/automatic-ripping-machine:latest

**Sudo Docker PS below**
sudo docker ps
CONTAINER ID   IMAGE                                                      COMMAND           CREATED         STATUS                            PORTS                                       NAMES
169546812f9c   automaticrippingmachine/automatic-ripping-machine:latest   "/sbin/my_init"   2 minutes ago   Up 2 minutes (health: starting)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   automatic-ripping-machine

I still am unable to connect at http://192.x.x.x:8080

**Comment by 4MAZ** [comment]
Terminal input and output of reinstall.

[Terminal output reinstall.pdf](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/14860190/Terminal.output.reinstall.pdf)

**Comment by 4MAZ** [comment]
![Screenshot from 2024-04-03 21-31-52](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/80132850/c9e1eb6f-010c-4b81-ad0d-ad00616c1750)

**Comment by 4MAZ** [comment]
![Screenshot from 2024-04-03 21-33-545](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/80132850/bed80211-5a39-4c45-b170-18e168596d70)

**Comment by 4MAZ** [comment]
rebooted machine and docker container seems to be hung starting.

arm@arm-MS-7C37:~$ sudo docker ps
CONTAINER ID   IMAGE                                                      COMMAND           CREATED          STATUS                             PORTS                                       NAMES
169546812f9c   automaticrippingmachine/automatic-ripping-machine:latest   "/sbin/my_init"   44 minutes ago   Up 12 minutes (health: starting)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   automatic-ripping-machine

**Comment by SylvainMT** [comment]
So when did you edit, the start_arm_container.sh script.

Before calling it or after?

Because from your install terminal logs.  I don`t see you editing the script before calling it...

Below is from your installation logs

```
...
Installation complete. A template command to run the ARM container is located in: /home/arm
arm@arm-MS-7C37:~$ id -u arm
1000
arm@arm-MS-7C37:~$ id -g arm
1000
arm@arm-MS-7C37:~$ mkdir /home/arm/logs
arm@arm-MS-7C37:~$ mkdir /home/arm/music
arm@arm-MS-7C37:~$ mkdir /home/arm/media
arm@arm-MS-7C37:~$ mkdir /home/arm/config
arm@arm-MS-7C37:~$ sudo ./start_arm_container.sh
...
```

I have indicted below where the script should have been edited.
```
...
Installation complete. A template command to run the ARM container is located in: /home/arm
arm@arm-MS-7C37:~$ id -u arm
1000
arm@arm-MS-7C37:~$ id -g arm
1000
arm@arm-MS-7C37:~$ mkdir /home/arm/logs
arm@arm-MS-7C37:~$ mkdir /home/arm/music
arm@arm-MS-7C37:~$ mkdir /home/arm/media
arm@arm-MS-7C37:~$ mkdir /home/arm/config

THIS IS WHERE YOU SHOULD EDIT THE SCRIPT...

arm@arm-MS-7C37:~$ sudo ./start_arm_container.sh
...
```


Try this:

Confirm that everything in the /home/arm folder is owned by arm.

`sudo chown -R arm:arm /home/arm`

`sudo docker stop 169546812f9c`
`sudo docker rm 169546812f9c`
`sudo /home/arm/start_arm_container.sh`

And since you installed this on a desktop Ubuntu, you should be able to verify it is running by opening a browser on that machine and navigating to http://localhost:8080/

**Comment by 4MAZ** [comment]
Looking back at my recording to triple check, I edited the script before I started the container. I had used the GUI text editor rather than a tool like Nano so it was not in my logs. After running the commands and connecting it is working. I am able to connect to the web interface from both the Ubuntu machine itself and my windows machine that appears to have fixed it but I don't understand why. I thought when I ran mkdir like you had recommended above the arm account would own it? I ran the mkdir commands from the arm account as it is the only on the system. 

I did start put in a movie to see if its totally working.

I will update again you guys when it has finished.



sudo chown -R arm:arm /home/arm
[sudo] password for arm: 
arm@arm-MS-7C37:~$ sudo docker stop 169546812f9c
169546812f9c
arm@arm-MS-7C37:~$ sudo docker rm 169546812f9c
169546812f9c
arm@arm-MS-7C37:~$ sudo /home/arm/start_arm_container.sh
cb20ce544ee46ce3c8b28d2a7428c25535608eb7348246c78271a455cd48c24d
arm@arm-MS-7C37:~$

**Comment by 4MAZ** [comment]
Everything is working. I want thank all of you for helping me I greatly appreciate it. I recieved a deceased relatives movie collection. This will help me get it into plex quickly......

One last question....

I followed the guide to get nvenc going but what line do I edit to in the arm.yaml file I would like to use the 1080 preset.

**Comment by SylvainMT** [comment]
> I followed the guide to get nvenc going but what line do I edit to in the arm.yaml file I would like to use the 1080 preset.

For DVDs: "HB_PRESET_DVD" 
For Blu Rays: "HB_PRESET_BD"

Both can be set through the web interface: Arm Settings > Ripper Settings

Be sure the spelling is 100% correct, errors in spelling will cause the rip to fail. (If you have a failed rip, because of this, your logs should show you what the correct spelling is, I think...)

And since everything is resolved, may I suggest that one of the devs close this issue?

**Comment by SylvainMT** [comment]
@4MAZ 
> I received a deceased relatives movie collection.

I'm sorry for your lost.

**Comment by 4MAZ** [comment]
> @4MAZ
> 
> > I received a deceased relatives movie collection.
> 
> I'm sorry for your lost.

Thank you, I have closed the issue and thanks again for all your help
