### ISSUE TITLE
Question: Is there a way to re-trigger the transcode 

### ISSUE THREAD

**Issue by BT25** [automatic-ripping-machine/automatic-ripping-machine#111]
for testing or in case the transcoding failed I'd like to restart the transcoding

**Comment by ahnooie** [comment]
It isn't really designed to do that, but could be possible with some edits to the scripts.  If you have the raw files you could transcode them manually from the command line using the same parameters ARM would.  For testing I found a very short DVD an ran through the entire process including ripping each time.
