### ISSUE TITLE
🐋 Im Having An Issue Running ARM In Portainer

### ISSUE THREAD

**Issue by silvvertnt** [automatic-ripping-machine/automatic-ripping-machine#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Whenever i try to start ARM in portainer i get an error called "failed with status 1" i am using ubuntu 20.04.6 on an I5 3470 8GB ram  and a GT 710 as a Gpu

### To Reproduce

everytime i restart the image in portainer after i give permissions to the file it is stating but i get same result

### Built from source files ?

- [X] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

i was expecting it to work accordingly and i just wanted further clarification if i am doing anything wrong

### Relevant log output

```shell
Updating arm group id from 1000 to 1003...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1001:1003
Removing any link between music and Music
stat: cannot stat '/etc/arm/config': No such file or directory
stat: cannot stat '/etc/arm/config': No such file or directory
Checking ownership of /etc/arm/config
---------------------------------------------
[ERROR]: ARM does not have permissions to /etc/arm/config using 1001:1003
Check your user permissions and restart ARM. Folder permissions--> :
---------------------------------------------
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
*** Killing all processes...
May  5 18:20:43 38d68c10808b syslog-ng[12]: syslog-ng shutting down; version='3.25.1'
*** Running /etc/my_init.d/10_syslog-ng.init...
May  5 18:20:50 38d68c10808b syslog-ng[12]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm user id from 1000 to 1001...
usermod: no changes
Updating arm group id from 1000 to 1003...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1001:1003
Removing any link between music and Music
stat: cannot stat '/etc/arm/config': No such file or directory
stat: cannot stat '/etc/arm/config': No such file or directory
Checking ownership of /etc/arm/config
---------------------------------------------
[ERROR]: ARM does not have permissions to /etc/arm/config using 1001:1003
Check your user permissions and restart ARM. Folder permissions--> :
---------------------------------------------
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
*** Killing all processes...
May  5 18:20:51 38d68c10808b syslog-ng[12]: syslog-ng shutting down; version='3.25.1'
*** Running /etc/my_init.d/10_syslog-ng.init...
May  5 18:21:05 38d68c10808b syslog-ng[12]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm user id from 1000 to 1001...
usermod: no changes
Updating arm group id from 1000 to 1003...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1001:1003
Removing any link between music and Music
stat: cannot stat '/etc/arm/config': No such file or directory
stat: cannot stat '/etc/arm/config': No such file or directory
Checking ownership of /etc/arm/config
---------------------------------------------
[ERROR]: ARM does not have permissions to /etc/arm/config using 1001:1003
Check your user permissions and restart ARM. Folder permissions--> :
---------------------------------------------
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
*** Killing all processes...
May  5 18:21:06 38d68c10808b syslog-ng[12]: syslog-ng shutting down; version='3.25.1'
*** Running /etc/my_init.d/10_syslog-ng.init...
May  5 18:21:32 38d68c10808b syslog-ng[12]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm user id from 1000 to 1001...
usermod: no changes
Updating arm group id from 1000 to 1003...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1001:1003
Removing any link between music and Music
stat: cannot stat '/etc/arm/config': No such file or directory
stat: cannot stat '/etc/arm/config': No such file or directory
Checking ownership of /etc/arm/config
---------------------------------------------
[ERROR]: ARM does not have permissions to /etc/arm/config using 1001:1003
Check your user permissions and restart ARM. Folder permissions--> :
---------------------------------------------
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
*** Killing all processes...
May  5 18:21:34 38d68c10808b syslog-ng[12]: syslog-ng shutting down; version='3.25.1'
*** Running /etc/my_init.d/10_syslog-ng.init...
May  5 18:22:26 38d68c10808b syslog-ng[12]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm user id from 1000 to 1001...
usermod: no changes
Updating arm group id from 1000 to 1003...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1001:1003
Removing any link between music and Music
stat: cannot stat '/etc/arm/config': No such file or directory
stat: cannot stat '/etc/arm/config': No such file or directory
Checking ownership of /etc/arm/config
---------------------------------------------
[ERROR]: ARM does not have permissions to /etc/arm/config using 1001:1003
Check your user permissions and restart ARM. Folder permissions--> :
---------------------------------------------
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
*** Killing all processes...
May  5 18:22:27 38d68c10808b syslog-ng[12]: syslog-ng shutting down; version='3.25.1'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by silvvertnt** [comment]
also this is how i have it set up in portainer
![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/116909518/7bd08ff9-3f79-4f08-8fc4-abf49c2300eb)
![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/116909518/91c6d579-57b9-4d35-bcd5-770014ebc042)

**Comment by silvvertnt** [comment]
This is how i have it set up in portainer

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/116909518/880b5bb9-f881-4eeb-895d-0ee53290940b)
![Screenshot 2024-05-05 122943](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/116909518/0d39580f-3604-4c86-b827-3dab18552bc2)
![Screenshot 2024-05-05 125656](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/116909518/1bc8a04f-f32a-4138-b812-358b206ec8ed)
![Screenshot 2024-05-05 125724](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/116909518/69616bcd-1f53-4374-b3b8-088224a31f17)
![Screenshot 2024-05-05 125738](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/116909518/7c6a1965-6eb3-4f67-a75d-31ea7398b164)
![Screenshot 2024-05-05 125750](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/116909518/beebcbb5-a3fd-402a-aebe-8d1ad9e962b1)

**Comment by microtechno9000** [comment]
The permissions are wrong for the volumes

the error you are getting states the mounted volumes are not able to be accessed by the ARM user

you need to change the ownership or set the UID and GID to align with the host permissions

**Comment by silvvertnt** [comment]
sorry im still a bit new to linux how would i change the ownership if you dont mind me asking?

**Comment by silvvertnt** [comment]
and if your talking about this command "sudo chown 1001:1002 -R /home/arm/config" i did do that but its still saying the same thing in logs "[ERROR]: ARM does not have permissions to /etc/arm/config using 1001:1002
Check your user permissions and restart ARM. Folder permissions--> :"

**Comment by microtechno9000** [comment]
No worries, to change the ownership in linux of the "/home/arm" directory use the below

```bash
sudo chown 1001:1003 -R /home/arm
```

**Comment by silvvertnt** [comment]
ok so i have done that now it says somethign about not having permission to a file that doesnt exist /etc/arm/config so should i make this file and give it permissions?

**Comment by silvvertnt** [comment]
i have done this and it is now saying "[ERROR]: ARM does not have permissions to /etc/arm/config using 1001:1002
Check your user permissions and restart ARM. Folder permissions-->" but this isnt in the volumes section nor is it a folder that i have on my server

**Comment by microtechno9000** [comment]
The last volume you have mounted points to the wrong path

It should be

/home/arm/config:/etc/arm/config

where left side is your host and the right is the docker image. This was your last volume entry

**Comment by silvvertnt** [comment]
ah thanks for clarifying musta missed that works great now thank you
