### ISSUE TITLE
🐋 Data disc dump fails with "invalid cross-device link" with network-mount media/completed volume

### ISSUE THREAD

**Issue by izzy84075** [automatic-ripping-machine/automatic-ripping-machine#1128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Dumping a data disc to ISO fails with a network mount for the media/completed volume, with an "invalid cross-device link" error. Everything works with movies.

### To Reproduce

1. Set up network mount for media/completed volume.
2. Test with DVD movie.
3. Success!
4. Test with data disc
5. Get "invalid cross-device link" error when moving the completed dump from media/raw/\*.part to media/completed/\*.iso.

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

The ISO would get copied to the network mount, not an attempted link/shortcut/symlink.

### Relevant log output

```shell
[05-15-2024 23:02:23] INFO ARM: Ripping data disc to: /home/arm/media/raw/SPACECOLONY/SPACECOLONY.part
1353360+0 records in
1353360+0 records out
692920320 bytes (693 MB, 661 MiB) copied, 160.164 s, 4.3 MB/s
[05-15-2024 23:05:03] INFO ARM: Moving data-disc from '/home/arm/media/raw/SPACECOLONY/SPACECOLONY.part' to '/home/arm/media/completed/unidentified/SPACECOLONY/SPACECOLONY.iso'
[05-15-2024 23:05:03] ERROR ARM: [Errno 18] Invalid cross-device link: '/home/arm/media/raw/SPACECOLONY/SPACECOLONY.part' -> '/home/arm/media/completed/unidentified/SPACECOLONY/SPACECOLONY.iso'
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 203, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 131, in main
    if utils.rip_data(job):
  File "/opt/arm/arm/ripper/utils.py", line 438, in rip_data
    os.rename(incomplete_filename, full_final_file)
OSError: [Errno 18] Invalid cross-device link: '/home/arm/media/raw/SPACECOLONY/SPACECOLONY.part' -> '/home/arm/media/completed/unidentified/SPACECOLONY/SPACECOLONY.iso'
[05-15-2024 23:05:03] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
```

### Anything else?

[SPACECOLONY_171581408246.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/15327821/SPACECOLONY_171581408246.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
This is an edge case with Python's `os` package. The `os.rename` function doesn't support moving files across different filesystems. This is where you'd want to use something like `shutil` to copy the file to it's destination, and `os.remove` to delete the original on a successful completion. 

@SylvainMT Marked this one as GFI for ya. This is a great issue to get your feet wet in ARM's internals, as I'm sure this is probably how we're doing all the file copies.

**Comment by izzy84075** [comment]
I had a quick look around the rest of utils.py, and it looks like the main movie dumping probably uses move_files() and move_files_main(), which look like they are set up to handle this correctly, as an extra "pointer in the right direction". :)

**Comment by SylvainMT** [comment]
Successfully replicated the issue, and I can confirm this bug exists.  Going to work on a fix now.

**Comment by SylvainMT** [comment]
> I had a quick look around the rest of utils.py, and it looks like the main movie dumping probably uses move_files() and move_files_main(), which look like they are set up to handle this correctly, as an extra "pointer in the right direction". :)

You were entirely correct, from what I can see.
