### ISSUE TITLE
Stop disc being re-read

### ISSUE THREAD

**Issue by martin8777** [automatic-ripping-machine/automatic-ripping-machine#113]
Is there a way to stop the DVD from automatically closing itself? 

I'm finding that discs are being ripped multiple times if I don't go and take it out quickly enough. It seems like the disc drawer is automatically closing after a period of time and then the script just rips it and queues it for transcoding again. 

Is there anyone to prevent the DVD drive auto closing? and is it possible to tell ARM not to rip a disc it already has a .log file for ?

thanks.

**Comment by muckngrind4** [comment]
I think some drives automatically pull the drive back after a certain timeout.  I suspect this is what is happening.  Making the eject an option in the config file is probably a good idea or adding logic to check if the inserted dvd was just ripped successfully.  I'll mark this as a enhancement request.  In the short term, you could try commenting out the eject lines in the scripts.  Put a # in front of any line with the "eject "$DEVNAME" command in the video_rip, video_transcode and identify files.  That should keep ARM from automatically ejecting after it's complete.

**Comment by martin8777** [comment]
Yeah, I was thinking of commenting out the eject command since I'm getting notified of when it's done anyway but it is quite nice to be able to tell my wife "if you see a disc ejected, can you take it out and pop in the next one from the big pile!"

**Comment by audioeng** [comment]
Hmm, are you using Ubuntu? What version? Physical or virtual? Any bios
settings regarding disk behavior?

**Comment by martin8777** [comment]
Ubuntu 16.04 LTS physical install. I'll check out the bios again later but pretty sure there's no options like that in there. It's an old HP 6000 SFF PC.

**Comment by muckngrind4** [comment]
@martin8777 Once it ejects, how long transpires before it's pulled back in?

**Comment by audioeng** [comment]
I’m running an old dell and an LG Blu-ray and it stays ejected for days at
least...

**Comment by martin8777** [comment]
looks like it auto closes after 10 minutes

didn't get a chance to check bios last night. grown up stuff took over,
will try tonight.

**Comment by muckngrind4** [comment]
I think the proper way to handle this is with some logic that identifies DVD's that have already been ripped.  I'd like to implement something like that in the not to distant future...

**Comment by martin8777** [comment]
Yeah, that would be nice. If I had any coding skill myself, I'd help out, but I'm more the Ops side of DevOps!

I went through all the BIOS options on that box and couldn't see anything relevant regarding the dvd drive. I may try another drive as I have a couple of spares and see if it does the same with a different brand of drive. I'm also probably going to rebuild the machine and see if a nice clean install makes any difference.

**Comment by budgidiere** [comment]
@martin8777 in #193 should have fixed your issue.

**Comment by martin8777** [comment]
> @martin8777 #193 should have fixed your issue.

Awesome, thanks!
