### ISSUE TITLE
I have tried for days!

### ISSUE THREAD

**Issue by learnlinuxwithme** [automatic-ripping-machine/automatic-ripping-machine#1131]
I have been trying to install this on multiple machines different os every time thinking that was the problem. I really dont know what else to do. I keep getting the same error. when I try to start it up. I am using the docker install currently in ubuntu 20.04.6 here is the error i keep recieving

arm@arm-OptiPlex-7040:~$ sudo ./start_arm_container.sh
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image
./start_arm_container.sh: line 6: -v: command not found
arm@arm-OptiPlex-7040:~$

------------------------------------------------------------------------------
here is what my file is set up as

#!/bin/bash
docker run -d \
    -p "8080:8080" \
    # -e ARM_UID="<id -u arm>" \
    # -e ARM_GID="<id -g arm>" \
    -v "/home/arm:/home/arm" \
    -v "/home/arm/music:/home/arm/music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/home/arm/media:/home/arm/media" \
    -v "/home/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='2,3,4,5,6,7...' \
    automaticrippingmachine/automatic-ripping-machine:latest

--------------------------------------------------------------------------

I have ran all four of these commands

mkdir /home/arm/logs

mkdir /home/arm/music

mkdir /home/arm/media

mkdir /home/arm/config

------------------------------------------------------------------------

here is my output for these

arm@arm-OptiPlex-7040:~$ id -u arm
1000
arm@arm-OptiPlex-7040:~$ id -g arm
1000
arm@arm-OptiPlex-7040:~$

-----------------------------------------------------------------------------

Thank you in advance for any help you can give me,
Andy

**Comment by SylvainMT** [comment]
From what I can see on your post, your `start_arm_container.sh` script contains the following

```
#!/bin/bash
docker run -d
-p "8080:8080"
# -e ARM_UID="<id -u arm>"
# -e ARM_GID="<id -g arm>"
-v "/home/arm:/home/arm"
-v "/home/arm/music:/home/arm/music"
-v "/home/arm/logs:/home/arm/logs"
-v "/home/arm/media:/home/arm/media"
-v "/home/arm/config:/etc/arm/config"
--device="/dev/sr0:/dev/sr0"
--device="/dev/sr1:/dev/sr1"
--device="/dev/sr2:/dev/sr2"
--device="/dev/sr3:/dev/sr3"
--privileged
--restart "always"
--name "arm-rippers"
--cpuset-cpus='2,3,4,5,6,7...'
automaticrippingmachine/automatic-ripping-machine:latest
```

To clear the error you have having it should look like this

```
#!/bin/bash
docker run -d \
-p "8080:8080" \
 -e ARM_UID="1000" \
 -e ARM_GID="1000" \
-v "/home/arm:/home/arm" \
-v "/home/arm/music:/home/arm/music" \
-v "/home/arm/logs:/home/arm/logs" \
-v "/home/arm/media:/home/arm/media" \
-v "/home/arm/config:/etc/arm/config" \
--device="/dev/sr0:/dev/sr0" \
--device="/dev/sr1:/dev/sr1" \
--device="/dev/sr2:/dev/sr2" \
--device="/dev/sr3:/dev/sr3" \
--privileged \
--restart "always" \
--name "arm-rippers" \
--cpuset-cpus='2,3,4,5,6,7' \
automaticrippingmachine/automatic-ripping-machine:latest
```

First notice that the second version has backslashes at the end of every line (except the last one).  This is because the `docker run` command is one command.  For legibility, we split the commands onto multiple lines but we need to tell BASH we are doing so, and the backslash is how we do that.  Everything could be re-written like this:

```
#!/bin/bash
docker run -d -p "8080:8080" -e ARM_UID="1000" -e ARM_GID="1000" -v "/home/arm:/home/arm" -v "/home/arm/music:/home/arm/music" -v "/home/arm/logs:/home/arm/logs" -v "/home/arm/media:/home/arm/media" -v "/home/arm/config:/etc/arm/config" --device="/dev/sr0:/dev/sr0" --device="/dev/sr1:/dev/sr1" --device="/dev/sr2:/dev/sr2" --device="/dev/sr3:/dev/sr3" --privileged --restart "always" --name "arm-rippers" --cpuset-cpus='2,3,4,5,6,7' automaticrippingmachine/automatic-ripping-machine:latest
```

Second, I changed these lines:

```
# -e ARM_UID="<id -u arm>"
# -e ARM_GID="<id -g arm>"
```

To this
```
 -e ARM_UID="1000" \
 -e ARM_GID="1000" \
```

This is necessary to make sure docker knows which UID and GID to use for the arm user and group.

Third, I changed this line:

```
--cpuset-cpus='2,3,4,5,6,7...'
```

to this

```
--cpuset-cpus='2,3,4,5,6,7' \
```

This command tells Docker which CPU cores, specifically to make available to ARM.  The boilerplate was placed there to be modified since there is no core numbered "..."  The setting I entered, assumes the following, you are using a 4-core, multithreaded processor.    (The cpuset-cpus option, treats each thread as a logical core).  In this instance, I am telling Docker to ignore the 1st core (0,1) and to use the 2nd (2,3), 3rd (4,5) and 4th (6,7) cores.  Please modify this entry to fit your current CPU architecture.  

I hope this helps.

**Comment by learnlinuxwithme** [comment]
thank you so much! this machine is 8 core what should i set it at? all it will be doing is ripping till i am finished with my library

**Comment by SylvainMT** [comment]
> thank you so much! this machine is 8 core what should i set it at? all it will be doing is ripping till i am finished with my library

That depends,  Is it a modern (11th gen and later) Intel CPU or an other CPU?

**Comment by learnlinuxwithme** [comment]
https://www.amazon.com/gp/product/B07GNDFSB8/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

Dell OptiPlex 7040 Small Form Factor PC, Intel Quad Core i7-6700 up to 4.0GHz, 16G DDR4, 512G SSD, Windows 10 Pro 64 Bit

upgraded ram to 64

**Comment by SylvainMT** [comment]
Then this is likely what you need

```
--cpuset-cpus='2,3,4,5,6,7' \
```

Since the i7-6700 is a 4-core multithreaded processor.

**Comment by learnlinuxwithme** [comment]
thank you, doing a fresh install of ubuntu as we speak. will let you know. thanks again!

**Comment by learnlinuxwithme** [comment]
thanks a million that worked like a charm. it started and i got to the web interface!
