### ISSUE TITLE
🐋 Using Dockstarter - created a compose file but cannot access WebUI

### ISSUE THREAD

**Issue by charmarkk** [automatic-ripping-machine/automatic-ripping-machine#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I'm using Dockstarter to help learn Docker (great tool!) and think I have got a Docker compose file working. However, I can't access the WebUI with my serverAddr:9090 (I changed the default port). I think it's to do with the network mode or something, somehow, but can someone point me in the right direction? Other services I've set up with Dockstarter and its override file are perfectly accessible. For instance, Jellyfin, which I had to completely override in (and it has no special network things):
[jellyfin-compose.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/15449788/jellyfin-compose.txt)

Here are the logs from `docker logs arm`:
[docker-logs-arm.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/15449761/docker-logs-arm.txt)

And how I've set up my compose:
[arm-compose.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/15449765/arm-compose.txt)

Perhaps notable are these lines in the log? Still new to Docker but I think there might be something missing or not set up right? I followed all the instructions here though.

``` 
[2024-05-27 01:20:52,721] INFO ARM: runui.<module> Starting ARM-UI on interface address - 172.18.0.12:8080
[2024-05-27 01:20:52,734] INFO ARM: wasyncore.log_info Serving on http://172.18.0.12:8080
```

### To Reproduce

Set up ARM with a docker-compose file, doesn't seem I can access the service.

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Accessing the webUI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Sorry to hear you having issues

Docker containers will have the same network address as their host machine, only the port changes. Can you post the output from `docker ps`, it will list what docker is forwarding as a port.

**Comment by charmarkk** [comment]
Mhm!

```
NAMES
8b4390cdd99f   automaticrippingmachine/automatic-ripping
-machine:latest   "/sbin/my_init"          2 hours ago
  Up 2 hours (healthy)      8080/tcp, 0.0.0.0:9090->9090
/tcp, :::9090->9090/tcp
        arm
```

Thanks for the help, still learning a lot about docker. Should I change it to have `9090:8080`? So it's 9090 on the outside but 8080 on the inside (if the WebUI is defaulting to 8080)?

**Comment by microtechno9000** [comment]
Leave the internal as 8080, as thats what the ARM system defaults to. Docker with your run config will then do a port redirect from 9090 to 8080

**Comment by charmarkk** [comment]
Made that change, `docker ps` now says:
```
80d77f0cc907   automaticrippingmachine/automatic-ripping-machine:latest   "/sbin/my_init"          7 minutes ago   Up 7 minutes (health: healthy)   8080/tcp, 0.0.0.0:8080->9090/tcp, :::8080->9090/tcp                                                                                                                                                                                                                                                                                                                                 arm
```
Still no luck, and the logs are otherwise unchanged.

**Comment by microtechno9000** [comment]
Looking at the logs, have you set the ARM config for the webserver IP? When using docker this does nothing, but might be confusing things internally.

**Comment by charmarkk** [comment]
Nope, all I did was the pre-install step to get the disc drives recognized and mounted etc. with the docker-setup script, then pulled the image down with that compose.yml.

**Comment by microtechno9000** [comment]
The ARM Wiki is part of the project. If you can, you are welcome to amend the Wiki and raise a PR. There is guidance on how do do that in the wiki, see https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Contribute-Wiki

**Comment by charmarkk** [comment]
Ah good to know about the wiki, I didn't know that! Thanks for the help troubleshooting yesterday. :)
