### ISSUE TITLE
📚 Getting Started link is improperly formatted

### ISSUE THREAD

**Issue by charmarkk** [automatic-ripping-machine/automatic-ripping-machine#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

The link for "Getting Started" is missing a closing parenthesis. 

### The page

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker

### If you are able please provide the correction here

`[Getting Started](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Getting-Started on your journey with ARM`

should be

`[Getting Started](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Getting-Started) on your journey with ARM`

[Getting Started](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Getting-Started on your journey with ARM
vs.
[Getting Started](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Getting-Started) on your journey with ARM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Resolved in PR #1130
