### ISSUE TITLE
🐋 Cannot edit running job

### ISSUE THREAD

**Issue by Dragonsys** [automatic-ripping-machine/automatic-ripping-machine#1146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When I click on the Edit Settings button for a running job, and then submit the changes, it adjusts the previous job ID instead of the current job ID. For example, if the current running job is ID 79, when I submit the changes it tells me that job ID 78 was changed, and so no changes are made to the current job. This means I am not able to select things such as Main Title, so that extras are not ripped, which takes up a lot of extra time & disk space

### To Reproduce

Start a ripping job
Click the Edit Settings button
make a change and click the Submit button
return to the home page & view the notification popup
Click on Edit Settings button again to verify no changes were made

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

I expect the current running job to be changed instead of the previous job ID

### Relevant log output

```shell
No log, as the previous job has completed, so the logs do not get any further updates, and the current job is not edited, so it does not reflect a change in the log.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Will check it out

**Comment by microtechno9000** [comment]
I started looking into this and cannot replicate the error you have described. If nothing happens in ripping log that is of use, can you try and replicate and also list the URL's

For example, when opening a job I get: `http://ip:8080/jobdetail?job_id=64` and editing the job is completed from `http://ip:8080/changeparams?config_id=64`

Once you have sent through screen captures and the URLs I can work through what is happening, because at the moment I am unable to see anything standing out in the code

**Comment by Dragonsys** [comment]
I think this might have been related to the storage setup I had for the ARM config location. I moved the ARM home (and DB) to SSD disks, as I started seeing a bunch of issues with DB locks, and now it works as expected. I'm not sure why this particular issue occurred, when everything else worked fine, but moving the files around, to fix the DB locks, seems to have fixed this as well.

**Comment by microtechno9000** [comment]
Did you have the database mounted over a network share?

the current database is limited to one read or write operation at a time, so any concurrent activity will cause a software lock up. We are working on resolving this with 3.0, moving to a mysql database container.

**Comment by Dragonsys** [comment]
I did have it on a NFS mount, but I moved it to local SSD. I'm only performing a single operation at a time; however, I think the issue, with the DB locks, was that my NAS has been running slow due to disk operations, and so the DB writes were lagging.

I saw similar issues with the DB on Radarr as well, during this same time.

**Comment by microtechno9000** [comment]
I suggest not running the database over a NAS link, due to the latency in reading a file over a NAS (SMB or NFS) link, it has been known to cause issues.

Suggest if you want to use a NAS, the transcode and completed folders are ok over a network, but config and db should remain on the same host.

**Comment by Dragonsys** [comment]
> I suggest not running the database over a NAS link, due to the latency in reading a file over a NAS (SMB or NFS) link, it has been known to cause issues.
> 
> Suggest if you want to use a NAS, the transcode and completed folders are ok over a network, but config and db should remain on the same host.

yes, that is what I changed my setup to. Everything was fine over NFS, until I started upgrading the drives in the NAS and had to rebuild the Array multiple times
