### ISSUE TITLE
🐛 DEBUG logs created despite LOGLEVEL beeing set to INFO

### ISSUE THREAD

**Issue by GamerBene19** [automatic-ripping-machine/automatic-ripping-machine#1150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I've set 
```
LOGLEVEL: "INFO"
```
in my `/etc/arm/config/arm.yaml`, but `/home/arm/logs/WebUI.log` is still flooded with DEBUG log messages like these
```
[2024-06-16 11:22:13,237] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2024-06-16 11:22:13,290] DEBUG ARM: utils.arm_alembic_get Alembic Head is: b326a3663939
[2024-06-16 11:22:13,340] DEBUG ARM: utils.arm_db_get Database Head is: b326a3663939
[2024-06-16 11:22:13,340] DEBUG ARM: utils.arm_db_check Database is current. Head: b326a3663939DB: b326a3663939
[2024-06-16 11:22:13,343] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7fb7e0b199a0>) (save_remote_images=True) (language=en) (id=1) (database_limit=200) (notify_refresh=6500) (use_icons=True) (bootstrap_skin=spacelab) (index_refresh=10)
```

### To Reproduce

1. Install ARM on Ubuntu 20.04
2. Start with systemd
3. Observe LOGFILE

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.7.0
7c22e2f

### Expected behavior?

I'd expect there not to be any "DEBUG ARM" messages in the logfile, when a non-DEBUG loglevel is set.

### Relevant log output

```shell
See above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GamerBene19** [comment]
The LOGLEVEL option is not set for the "main app". I've temporarily fixed it with this change:
```
diff --git a/arm/ui/__init__.py b/arm/ui/__init__.py
index abcbbfd6..22ba3e71 100644
--- a/arm/ui/__init__.py
+++ b/arm/ui/__init__.py
@@ -1,9 +1,10 @@
 """Main arm ui file"""
 import sys  # noqa: F401
 import os  # noqa: F401
+import logging
 from getpass import getpass  # noqa: F401
 from logging.config import dictConfig
-from flask import Flask, logging, current_app  # noqa: F401
+from flask import Flask, current_app  # noqa: F401
 from flask.logging import default_handler  # noqa: F401
 from flask_sqlalchemy import SQLAlchemy
 from flask_migrate import Migrate
@@ -53,6 +54,7 @@ app.config['SECRET_KEY'] = "Big secret key"  # TODO: make this random!
 app.config['LOGIN_DISABLED'] = cfg.arm_config['DISABLE_LOGIN']
 # Set debug pin as it is hidden normally
 os.environ["WERKZEUG_DEBUG_PIN"] = "12345"  # make this random!
+app.logger.setLevel(logging.INFO)
 app.logger.debug("Debugging pin: " + os.environ["WERKZEUG_DEBUG_PIN"])

 db = SQLAlchemy(app)
 ```

**Comment by microtechno9000** [comment]
Looks like the logging level is not set correctly for Waitress, if you modify your fix to use the below feel free to raise a PR. I can then review.

`cfg.arm_config['LOGLEVEL']`

**Comment by GamerBene19** [comment]
> Looks like the logging level is not set correctly for Waitress, if you modify your fix to use the below feel free to raise a PR. I can then review.
> 
> `cfg.arm_config['LOGLEVEL']`

Sorry for ghosting, I intended to to it right away (that's why I didn't reply) and simply forgot. Thanks for adding the fix ^^
