### ISSUE TITLE
File location remapping on TrueNas

### ISSUE THREAD

**Issue by Joshrs289** [automatic-ripping-machine/automatic-ripping-machine#1168]
I'm running the ARM from the app download of TrueNas Scale, and can't find the pre existing files, like the home/complete, home/transcode, etc, and when I try to remap the file location to a /media/complete file location in my main nas pool, so that I can access the files via SMB, it says that there was an issue with the file path, where do I find the pre existing file system, or how can I change the path of them?

**Comment by microtechno9000** [comment]
TrueNAS is not  officially supported by ARM, if you are having issues with TrueNAS please reach out to the TrueNAS community or some of the users on the ARM Discord
