### ISSUE TITLE
V2 Permission Error on config.yaml

### ISSUE THREAD

**Issue by ahnooie** [automatic-ripping-machine/automatic-ripping-machine#117]
PermissionError: [Errno 13] Permission denied: '/opt/arm/arm/config.yaml'

The first option is to add chown -R arm:arm arm to the install instructions

The other option is the generated config.yaml file could be placed somewhere separate from code (either /tmp or maybe something under /home/arm ?)

What are your thoughts? @muckngrind4

**Comment by muckngrind4** [comment]
I like the idea of /tmp.  As it's used right now it's generated every time ARM runs, so it's really a tmp file.  If we ever change the real config file to be the yaml file, then we'd probably want to move it back.  I'll lagel this as a bug.
