### ISSUE TITLE
🐋 Multiple drives no longer ripping at the same time

### ISSUE THREAD

**Issue by TimVanDyke** [automatic-ripping-machine/automatic-ripping-machine#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When I put a second DVD in (like I used to) and have close the disk I expect it to start a second rip. It spins for a second to scan the disk then does nothing. No output from ARM, no rips started, no ejection (like it didn't recognize the disk)

### To Reproduce

1. Unraid Docker container
2. Insert a disk to start a rip in DVD player 1
> Player1 begins ripping the disk
3. Insert a disk to start a rip in DVD player2
> DVD player 2 will not start

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Both rips start

### Relevant log output

```shell
I don't see any, but I'm open to looking in better places
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimVanDyke** [comment]
Actually don't dig too deep. Maybe I'm having some kind of hardware issue over here. It's maybe intermittent and these drives are crap. I'll close this sorry for the noise.

**Comment by TimVanDyke** [comment]
I can't get consistent repro steps, must be a hardware issue

**Comment by TimVanDyke** [comment]
I can't get consistent repro steps, must be a hardware issue

**Comment by microtechno9000** [comment]
Hardware issues are annoying

For logs, have a look at the arm.log, it generates an entry each time ARM is called on a drive detecting a disk.

Example output from some disks recently having issues, they were pretty scratched unfortunately. 

```
Mon Jul 15 20:37:19 UTC 2024 Entering docker wrapper Mon Jul 15 20:37:20 UTC 2024 [ARM] Starting ARM for DVD on sr0 Mon Jul 15 21:39:38 UTC 2024 Entering docker wrapper Mon Jul 15 21:39:38 UTC 2024 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
```

**Comment by TimVanDyke** [comment]
Thanks I'll take a look if it happens again. I think I may have needed to re-scan my drives with the option in settings. I think I may have unplugged and swapped USBs and ARM might have been confused about who was who because I have 2 identical drives. That fixed it for me (but I have also been having drive issues because these are cheap crap and there's an internal connection dying)
