### ISSUE TITLE
🐋 <title>reinstalled 

### ISSUE THREAD

**Issue by bob5731** [automatic-ripping-machine/automatic-ripping-machine#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I had it working at one time.  I have reinstalled unraid.

Win in installing I get

[docker run](https://forums.unraid.net/topic/57181-docker-faq/?tab=comments#comment-564345)
  -d
  --name='automatic-ripping-machine'
  --net='bridge'
  --privileged=true
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="automatic-ripping-machine"
  -e 'ARM_UID'='1001'
  -e 'ARM_GID'='1001'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/main/favicon.ico'
  -p '8088:8080/tcp'
  -v '/mnt/user/appdata/ARM/':'/home/arm':'rw'
  -v '/mnt/user/appdata/ARM/Music':'/home/arm/Music':'rw'
  -v '/mnt/user/appdata/ARM/config':'/etc/arm/config':'rw'
  -v '/mnt/user/appdata/ARM/logs':'/home/arm/logs':'rw'
  -v '/mnt/user/appdata/ARM/media':'/home/arm/media':'rw'
  --runtime=nvidia
  --gpus all
  --device /dev/sr0
  --device /dev/sg1 '1337server/automatic-ripping-machine:latest'

f12724b94e3ea9553fe445805e48293f8e37a6fb5570425c929bab4deeb7536d
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.

The command failed.

 

how do I fix it?

### To Reproduce

NVIDIA

### Built from source files ?

- [X] I Built the image from source

### What architecture are you seeing the problem on?

all

### Expected behavior?

NVIDIA

### Relevant log output

```shell
NVIDIA
```

### Anything else?

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Sorry to hear it isn't working, Unraid is not an officially supported platform for running ARM.
Please reach out to the discord community to see what support they can give
