### ISSUE TITLE
🐛 Unidentified CDs rip to the home directory rather than the configured directory

### ISSUE THREAD

**Issue by TallPatrick** [automatic-ripping-machine/automatic-ripping-machine#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [ ] I'm using the latest release

### Describe the bug?

When ripping CDs, any CDs that are identified are placed in the correctly specified folder (/arm/media/music/), but any unidentified CDs are put in /home/arm/ and then given a semi-garbage folder name, despite filling out a custom title in the UI.

### To Reproduce

1. set a path for music rips in the abcde.conf file
2. Insert a CD which is not identifiable in Musicbrainz (a custom burned CD should do the trick)
3. Input a custom title for the disc in the web UI (ideally before ripping begins)
4. Wait for rip to complete

Actual results: Disc rips to an abcde.<string> folder in /home/arm/ instead of intended location

### What OS are you seeing the problem on?

all

### ARM Release Version or Git hash (You can find this in the arm settings page)

A.R.M version: 2.6.60
Current git version:
9492c4576925c8e7e9e27fc8cc182ab7c3f6621c

(NOTE: I'm in the process of updating my docker image to see if that changes behavior)

### Expected behavior?

Expected results: Similar to the custom title behavior when ripping DVDs, files are ripped to the configured location and placed in a folder with the provided custom title

### Relevant log output

[abcde.conf.txt](https://github.com/user-attachments/files/16594917/abcde.conf.txt)
[music_cd_172288038508.log](https://github.com/user-attachments/files/16594918/music_cd_172288038508.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Try the latest build as this may have been fixed in the below PR

https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/1159

**Comment by microtechno9000** [comment]
Closed as resolved in previous linked PR
