### ISSUE TITLE
automatic-ripping-machine

### ISSUE THREAD

**Issue by bob5731** [automatic-ripping-machine/automatic-ripping-machine#1181]
I'm running automatic-ripping-machine in docker for windows. I need know how yo add a dvd drive to it?

**Comment by microtechno9000** [comment]
Running ARM in Windows hasn't been tested, with the majority of testing done using docker hosted in Ubuntu or a similar debian variant of Linux.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki

Suggest having a look online to see what variables would need to be passed into support a DVD drive etc. Although I cannot guarantee it will work.

**Comment by bob5731** [comment]
I got it working in unraid by removing all NVIDIA drivers.
I have 6 dvd drive and 400 dvd disks and 10000 data disks that I would like to backup to my unraid box.
How would I go about doing it?
![10136713_4](https://github.com/user-attachments/assets/41dd00b9-e207-40aa-9b5f-3d62498f5e37)
![l_1010132_01](https://github.com/user-attachments/assets/5316808d-15fa-4f7c-a873-10b3273330b3)

**Comment by microtechno9000** [comment]
Having 6 drives will make the ripping process fast, but you will then be constrained on processor usage when transcoding.

**Comment by bob5731** [comment]
but can not find one for sell.

**Comment by microtechno9000** [comment]
Closing issue as there is no ARM software issue. If you would like help with setting up ARM, hardware or any other discussion items please visit:

- [ARM Discussions](https://github.com/automatic-ripping-machine/automatic-ripping-machine/discussions)
- [ARM Wiki](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki)
- [Join the ARM Discord](https://discord.gg/FUSrn8jUcR)
