### ISSUE TITLE
Can't ripping a DVD with ARM on Unraid-Server

### ISSUE THREAD

**Issue by phillipunzen** [automatic-ripping-machine/automatic-ripping-machine#1193]
Hello!
I have installed the AMR as a Docker container on my Unraid server (latest version).
The CD drive (Apple SuperDrive) is also passed through and recognized. The DVDs are recognized by the ARM, but unfortunately it cannot copy the DVDs.

What can I do?

Error:

> [09-07-2024 13:58:10] INFO ARM: ARM version: 2.6.67
> [09-07-2024 13:58:10] INFO ARM: Python version: 3.8.10 (default, Nov 22 2023, 10:22:35) 
> [GCC 9.4.0]
> [09-07-2024 13:58:10] INFO ARM: User is: arm
> [09-07-2024 13:58:10] INFO ARM: Alembic head is: 469d88477c13
> [09-07-2024 13:58:10] INFO ARM: Database version is: 469d88477c13
> [09-07-2024 13:58:10] INFO ARM: ************* Starting ARM processing at 2024-09-07 13:58:10.133061 *************
> [09-07-2024 13:58:11] INFO ARM: Looking for log files older than 1 days old.
> [09-07-2024 13:58:11] INFO ARM: Checking path /home/arm/logs/ for old log files...
> [09-07-2024 13:58:11] INFO ARM: Checking path /home/arm/logs/progress for old log files...
> [09-07-2024 13:58:11] INFO ARM: Job: HOT_SHOTS_PART_DEUX
> [09-07-2024 13:58:11] INFO ARM: Job #1 with PID 219 is currently running.
> [09-07-2024 13:58:11] INFO ARM: Starting Disc identification
> [09-07-2024 13:58:11] INFO ARM: Mounting disc to: /mnt/dev/sr0
> [09-07-2024 13:58:11] INFO ARM: Mounting disc was successful
> [09-07-2024 13:58:11] INFO ARM: Disc identified as video
> [09-07-2024 13:58:12] INFO ARM: DVD CRC64 hash is: a51419db7541e774
> [09-07-2024 13:58:24] INFO ARM: Disc title Post ident -  title:HOT_SHOTS_PART_DEUX year:None video_type:unknown disctype: dvd
> [09-07-2024 13:58:24] INFO ARM: We have no previous rips/jobs matching this label
> [09-07-2024 13:58:25] INFO ARM: Waiting 60 seconds for manual override.
> [09-07-2024 13:59:25] INFO ARM: Manual override found.  Overriding auto identification values.
> [09-07-2024 13:59:25] INFO ARM: ******************* Logging ARM variables *******************
> [09-07-2024 13:59:25] INFO ARM: devpath: /dev/sr0
> [09-07-2024 13:59:25] INFO ARM: mountpoint: /mnt/dev/sr0
> [09-07-2024 13:59:25] INFO ARM: title: Hot Shots! Part Two
> [09-07-2024 13:59:25] INFO ARM: year: None
> [09-07-2024 13:59:25] INFO ARM: video_type: unknown
> [09-07-2024 13:59:25] INFO ARM: hasnicetitle: True
> [09-07-2024 13:59:25] INFO ARM: label: HOT_SHOTS_PART_DEUX
> [09-07-2024 13:59:25] INFO ARM: disctype: dvd
> [09-07-2024 13:59:25] INFO ARM: ******************* End of ARM variables *******************
> [09-07-2024 13:59:25] INFO ARM: ******************* Logging config parameters *******************
> [09-07-2024 13:59:25] INFO ARM: skip_transcode: False
> [09-07-2024 13:59:25] INFO ARM: mainfeature: False
> [09-07-2024 13:59:25] INFO ARM: minlength: 600
> [09-07-2024 13:59:25] INFO ARM: maxlength: 99999
> [09-07-2024 13:59:25] INFO ARM: videotype: auto
> [09-07-2024 13:59:25] INFO ARM: manual_wait: True
> [09-07-2024 13:59:25] INFO ARM: manual_wait_time: 60
> [09-07-2024 13:59:25] INFO ARM: ripmethod: mkv
> [09-07-2024 13:59:25] INFO ARM: mkv_args: 
> [09-07-2024 13:59:25] INFO ARM: delrawfiles: True
> [09-07-2024 13:59:25] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
> [09-07-2024 13:59:25] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
> [09-07-2024 13:59:25] INFO ARM: hb_args_dvd: --subtitle scan -F
> [09-07-2024 13:59:25] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
> [09-07-2024 13:59:25] INFO ARM: raw_path: /home/arm/media/raw/
> [09-07-2024 13:59:25] INFO ARM: transcode_path: /home/arm/media/transcode/
> [09-07-2024 13:59:25] INFO ARM: completed_path: /home/arm/media/completed/
> [09-07-2024 13:59:25] INFO ARM: extras_sub: extras
> [09-07-2024 13:59:25] INFO ARM: emby_refresh: False
> [09-07-2024 13:59:25] INFO ARM: emby_server: 
> [09-07-2024 13:59:25] INFO ARM: emby_port: 8096
> [09-07-2024 13:59:25] INFO ARM: notify_rip: True
> [09-07-2024 13:59:25] INFO ARM: notify_transcode: True
> [09-07-2024 13:59:25] INFO ARM: max_concurrent_transcodes: 0
> [09-07-2024 13:59:25] INFO ARM: ******************* End of config parameters *******************
> [09-07-2024 13:59:25] INFO ARM: Checking for fstab entry.
> [09-07-2024 13:59:25] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
> [09-07-2024 13:59:25] INFO ARM: Final Output directory "/home/arm/media/transcode/unidentified/Hot Shots! Part Two (None)"
> [09-07-2024 13:59:25] INFO ARM: Final Output directory "/home/arm/media/completed/unidentified/Hot Shots! Part Two (None)"
> [09-07-2024 13:59:25] INFO ARM: Processing files to: /home/arm/media/transcode/unidentified/Hot Shots! Part Two (None)
> [09-07-2024 13:59:25] INFO ARM: ************* Ripping disc with MakeMKV *************
> [09-07-2024 13:59:25] INFO ARM: Updating MakeMKV key...
> MakeMKV beta key for this month: T-NDgYjBUFx5ju1nKbVMthSGSURiL0kEAnjOXD3MudnHtk5OPhXzuSjWbPEKFeBDA7C1
> Either /home/arm/.MakeMKV/settings.conf doesn't exist, or app_Key is not inside it
> [09-07-2024 13:59:26] INFO ARM: Starting MakeMKV rip. Method is mkv
> [09-07-2024 13:59:35] INFO ARM: MakeMKV disc number: 0
> [09-07-2024 13:59:35] INFO ARM: Destination is /home/arm/media/raw/Hot Shots! Part Two
> [09-07-2024 13:59:35] INFO ARM: Processing files to: /home/arm/media/raw/Hot Shots! Part Two
> [09-07-2024 13:59:35] INFO ARM: Using MakeMKV to get information on all the tracks on the disc. This will take a few minutes...
> [09-07-2024 13:59:38] ERROR ARM: Call to MakeMKV failed with code: 139 (b'MSG:1005,0,1,"MakeMKV v1.17.6 linux(x64-release) started","%1 started","MakeMKV v1.17.6 linux(x64-release)"\nMSG:3338,0,2,"Downloading latest SDF to /home/arm/.MakeMKV ...","Downloading latest %1 to %2 ...","SDF","/home/arm/.MakeMKV"\nSegmentation fault\n')
> [09-07-2024 13:59:38] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
> [09-07-2024 13:59:38] ERROR ARM: 
> Traceback (most recent call last):
>   File "/opt/arm/arm/ripper/makemkv.py", line 214, in get_track_info
>     mkv = subprocess.check_output(
>   File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.8/subprocess.py", line 516, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'makemkvcon -r --progress=/home/arm/logs/progress/1.log --messages=-stdout --minlength=600 --cache=1 info disc:0
> ' returned non-zero exit status 139.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
>     makemkv_out_path = makemkv.makemkv(logfile, job)
>   File "/opt/arm/arm/ripper/makemkv.py", line 69, in makemkv
>     get_track_info(mdisc, job)
>   File "/opt/arm/arm/ripper/makemkv.py", line 220, in get_track_info
>     raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
>   File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
>     raise super().__init__(self.message)
> TypeError: exceptions must derive from BaseException
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/arm/arm/ripper/main.py", line 203, in <module>
>     main(log_file, job, args.protection)
>   File "/opt/arm/arm/ripper/main.py", line 110, in main
>     arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
>   File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
>     raise ValueError from mkv_error
> ValueError
> [09-07-2024 13:59:38] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.

![Docker-Unraid Config](https://github.com/user-attachments/assets/4eb79bdf-f2c0-4e36-8d88-f780a8d69d07)

**Comment by J-Nistler** [comment]
I'm having a similar issue. I'm guessing it has to do with MakeMKV's licensing? The [current beta key](https://forum.makemkv.com/forum/viewtopic.php?f=5&t=1053) expired at the end of August and the author hasn't announced a new one for Sep/Oct. I think our options are to purchase a license, wait and hope for a new beta key (which should automatically be updated by ARM's beta key updater), or find some way for ARM to think that it is still August 2024. You can read more about the licensing in the [wiki ](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/MakeMKV-Info).

**Comment by phillipunzen** [comment]
I have buy a license, and it works!
Thanks!
