### ISSUE TITLE
🐛 A.R.M. didnt send a Notification

### ISSUE THREAD

**Issue by phillipunzen** [automatic-ripping-machine/automatic-ripping-machine#1196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

If i configure the apprise over the WebUI and click of "Test Notifications" i didnt receive a notification on Discord, Telegram or Gotify. 

### To Reproduce

1. Create the Container in Unraid
2. Setup the Apprise config
3. Click "Send Notification"

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

Arm: 2.6.67

### Expected behavior?

I want to receive a message

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Under ripper settings, did you configure the apprise config?

APPRISE: /etc/arm/config/apprise.yaml

**Comment by MBerantzino** [comment]
I have the same issue. 

When clicking the "Send test notification"-button, the following is logged:

DEBUG ARM: utils.notify apprise message, title: ARM notification body: This is a notification by the ARM-Notification Test!
DEBUG ARM: utils.database_adder Trying to add Notifications
DEBUG ARM: utils.database_adder successfully written Notifications to the database
fatal: could not read Username for 'https://github.com': No such device or address

**Comment by phillipunzen** [comment]
Where you find the log? 
I only find Logs for the rips...

> To get notifications to work with Discord you need
> 
> Settings / Apprise Config
> 
> * DISCORD_WEBHOOK_ID:
> * DISCORD_TOKEN:
> 
> Settings / Ripper
> 
> * APPRISE: set to '/etc/arm/config/apprise.yaml'
> 
> When running inside a docker container the IP address of the host is always 0.0.0.0, which isn't usefull when clicking a link. So need to set
> 
> * UI_BASE_URL:
> * WEBSERVER_PORT:
> 
> When running it with those settings configured, I get the following
> 
> ```shell
> [2024-09-16 10:26:46,971] DEBUG ARM: notifications.arm_nav_notify 0
> [2024-09-16 10:26:52,787] DEBUG ARM: utils.notify apprise message, title: [The ARM Master] - ARM notification body: This is a notification by the ARM-Notification Test! Server URL: http://ipaddress:8080
> [2024-09-16 10:26:52,787] DEBUG ARM: utils.database_adder Trying to add Notifications
> [2024-09-16 10:26:52,795] DEBUG ARM: utils.database_adder successfully written Notifications to the database
> [2024-09-16 10:26:53,226] DEBUG ARM: apprise_bulk.apprise_notify Sent apprise to DISCORD_WEBHOOK_ID was successful
> [2024-09-16 10:26:53,227] DEBUG ARM: utils.notify apprise-config: /etc/arm/config/apprise.yaml
> ```
> 
> This also creates an entry into the Notifications page, so you will see a notification appear next to the bell if it is working.
> 
> Check those values are set, and try again. If it doesn't work, post the output following the setting update, and what fields you have set so I can try and replicate.

**Comment by microtechno9000** [comment]
When using docker the main ARM application logs are dumped to docker. The below will output the logs and continue in a live view, so as you use the webpage it will continue to generate output. 

Note: need to use the docker ARM name configured in the start script

`docker logs -f automaticrippingmachine`

**Comment by phillipunzen** [comment]
My Output:
[17.09.2024 - 04:39:03] DEBUG ARM: utils.database_adder Trying to add Notifications
[17.09.2024 - 04:39:03] DEBUG ARM: utils.database_adder successfully written Notifications to the database
[17.09.2024 - 04:39:03] DEBUG ARM: apprise_bulk.apprise_notify Sent apprise to DISCORD_WEBHOOK_ID was successful
[17.09.2024 - 04:39:03] DEBUG ARM: apprise_bulk.apprise_notify Sent apprise to GOTIFY_TOKEN was successful
[17.09.2024 - 04:39:03] DEBUG ARM: apprise_bulk.apprise_notify Sent apprise to TELEGRAM_BOT_TOKEN was successful
[17.09.2024 - 04:39:03] DEBUG ARM: utils.notify apprise-config: /etc/arm/config/apprise.yaml
[17.09.2024 - 04:39:03] INFO ARM: arm_ripper.rip_visual_media ************* ARM processing complete *************

I get not message on all platforms...

**Comment by microtechno9000** [comment]
Odd, I will check the code and see what's happening. There are a few config fields needed, it is possible one is not set.

Did you set the server address and other fields mentioned?

**Comment by phillipunzen** [comment]
Okay thank you!
I added the Serveraddress, Port, Discord WebhookID (URL from Webhook) and the discord account id.

**Comment by microtechno9000** [comment]
That worked?

**Comment by phillipunzen** [comment]
No, it didn‘t work

**Comment by microtechno9000** [comment]
> No, it doesn’t work

With those values set does it generate any specific logs? With logging set to DEBUG

**Comment by phillipunzen** [comment]
Since I'm not at home, I'm speaking from memory. The server logs in the job logs that the apprise.yml was found and the settings could be read. The output is that a notification is sent via Discord, but it doesn't arrive. When I included Telegram as a test, I got the same result, but with Telegram.

**Comment by microtechno9000** [comment]
Noted in your description you are using unraid. A [quick look at the docs](https://docs.unraid.net/unraid-os/manual/docker-management/), I saw that 'Bridge' is given limited access to the web, but host is [config - network](https://docs.unraid.net/unraid-os/manual/docker-management/#network-type)

Check that, and modify if required.

**Comment by phillipunzen** [comment]
I used here a dedicated IP-Address. I didnt use the Bridge.

**Comment by microtechno9000** [comment]
Ok, so I am rather puzzled then.

If you do a tcpdump of the docker container when running the apprise test, do you see any data to Discord?

**Comment by phillipunzen** [comment]
Hey, i track the connection with my firewall.
It is no outgoing connection from the A.R.M. Server.

I think it is no problem with discord. The App also send no notifcation to telegram or another service. I try discord, gotify, and telegram.

**Comment by microtechno9000** [comment]
Thanks for confirming

so seems there is something with your install or config then that isn't working. Once I am back home will post some commands to try so we can check what is and isn't working.

**Comment by microtechno9000** [comment]
To eliminate a few things, lets test with just discord using the following config. Paste the results below and let me know what responses you get.

Confirming on ARM 2.9.0

Ripper config
- **UI_BASE_URL** "ip address or domain"
- **WEBSERVER_PORT** "8080"
- **ARM_NAME** "your servers name or reference"
- **NOTIFY_RIP** "True"
- **NOTIFY_TRANSCODE** "True"
- **NOTIFY_JOBID** "True"
- **APPRISE** "/etc/arm/config/apprise.yaml"

Apprise Config
- **DISCORD_WEBHOOK_ID** "your id"
- **DISCORD_TOKEN** "your token"
all other fields blank, save that config

From your machine, confirm that the apprise.yaml config only has the Discord details (and Kodi for some reason). The default location for this is within the config folder

```bash
mtech@server:/home/arm/config$ ls -la
total 48
drwxr-xr-x  2 arm arm  4096 Dec 29  2023 .
drwxr-xr-x 17 arm arm  4096 Oct 14 20:20 ..
-rwxr-xr-x  1 arm arm 21624 Oct 14 19:55 abcde.conf
-rwxr-xr-x  1 arm arm  1819 Oct 17 22:56 apprise.yaml
-rwxr-xr-x  1 arm arm 11899 Oct 17 20:27 arm.yaml
```

Bring up your server/machine running arm and run (replace automaticrippingmachine with what ever you named your ARM docker image)
```bash
docker logs -f automaticrippingmachine
```

On pressing "Send Test Notification" you should get
1. Green banner stating "Test notification sent"
2. Notifications 'bell' show a new notification

    [The ARM Master] - ARM notification
    0:03:03.588840 (17-Oct-24 12:29)
    This is a notification by the ARM-Notification Test! Server URL: http://ipaddress:8080

4. Docker logs show message was sent

```
...
[2024-10-17 12:29:04,411] DEBUG ARM: utils.notify apprise message, title: [The ARM Master] - ARM notification body: This is a notification by the ARM-Notification Test! Server URL: http://ipaddress:8080
[2024-10-17 12:29:04,411] DEBUG ARM: utils.database_adder Trying to add Notifications
[2024-10-17 12:29:04,419] DEBUG ARM: utils.database_adder successfully written Notifications to the database
[2024-10-17 12:29:04,916] DEBUG ARM: apprise_bulk.apprise_notify Sent apprise to DISCORD_WEBHOOK_ID was successful
[2024-10-17 12:29:04,916] DEBUG ARM: utils.notify apprise-config: /etc/arm/config/apprise.yaml
...
```

6. Received something on discord

**Comment by microtechno9000** [comment]
Okay, think I see the error, you just need the ID and Token in the config

Apprise Config (examble jibberish string)

-     **DISCORD_WEBHOOK_ID** 123456719210740172 (some number)
-     **DISCORD_TOKEN** JSHDANSDFL1AJHFD_ANS5DFJHENH (some string)

**Comment by phillipunzen** [comment]
Okay wow... This was the problem... I'm sorry...

**Comment by microtechno9000** [comment]
> Okay wow... This was the problem... I'm sorry... 

no worries
