### ISSUE TITLE
🐋 ARM Docker Image - AttributeError: 'NoneType' object has no attribute 'version_num' when trying to start Web UI

### ISSUE THREAD

**Issue by bigdogdylan00** [automatic-ripping-machine/automatic-ripping-machine#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have used the setup script on a Debian 12 LXC container (privileged) in Proxmox. The Docker image pulls just fine, and the docker image builds and starts. However, the Web UI fails to start, complaining that `AttributeError: 'NoneType' object has no attribute 'version_num'`.

### To Reproduce

1. Create LXC container in Proxmox (privileged)
2. Install Debian 12
3. Pass a Proxmox storage device through as a mountpoint
4. Install Docker
5. Run Docker install script
6. Check Docker logs for the container, find that the Web UI is not starting

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

The Web UI should start up

### Relevant log output

```shell
Starting web ui
[2024-11-08 20:46:15,556] INFO ARM: __init__.<module> Setting log level to: INFO
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, ARMInfo # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import db  # needs to be imported before models
  File "/opt/arm/arm/../arm/ui/__init__.py", line 72, in <module>
    from arm.ui.database.database import route_database  # noqa: E402,F811
  File "/opt/arm/arm/../arm/ui/database/database.py", line 28, in <module>
    armui_cfg = ui_utils.arm_db_cfg()
  File "/opt/arm/arm/../arm/ui/utils.py", line 204, in arm_db_cfg
    db_update = arm_db_check()
  File "/opt/arm/arm/../arm/ui/utils.py", line 172, in arm_db_check
    db_revision = arm_db_get()
  File "/opt/arm/arm/../arm/ui/utils.py", line 152, in arm_db_get
    app.logger.debug(f"Database Head is: {db_revision.version_num}")
AttributeError: 'NoneType' object has no attribute 'version_num'
```

### Anything else?

The LXC configuration file is as follows:

`arch: amd64
cores: 2
features: nesting=1
hostname: ARM-12
memory: 2048
mp0: /mnt/pve/media/,mp=/mount/Media
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=BC:24:11:F6:B5:59,ip=dhcp,type=veth
ostype: debian
rootfs: RAIDZ1:subvol-107-disk-0,size=64G
swap: 2048
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
lxc.apparmor.profile: unconfined
lxc.cap.drop:
lxc.autodev: 1
lxc.mount.auto: sys:rw`

I have confirmed that lsscsi -g shows my USB DVD drive. I have also confirmed that all relevant directories (passed through from Proxmox to /mount/Media within the LXC container) are visible and writeable. I am very very new to Docker, so I apologize if there is something obvious that I'm missing. Is there something I'm doing wrong?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
It looks like ARM is trying to get some version information on the database but is getting no valid data back.

Can you please check and confirm the below.
1. Your arm start script doesn't have any typos or missing folders
2. ARM has ownership of the database folder and can read/write to the directory
3. In your arm.yaml file, set logging to DEBUG and restart the container

**Comment by bigdogdylan00** [comment]
I can check all of that today. Which folder does it use for the database, the config folder?

**Comment by microtechno9000** [comment]
The database is in `/home/arm/db`

**Comment by microtechno9000** [comment]
Closing issue as not an ARM bug, but permissions and config of the setup
