### ISSUE TITLE
Log-Spam and Container stuck disc init

### ISSUE THREAD

**Issue by Waschke1994** [automatic-ripping-machine/automatic-ripping-machine#1246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The Container stucks at the Job initialisation and fills the logfiles of my drive extremely fast with this 4 lines again and again:
```
[2024-11-21 18:57:20,688] DEBUG ARM: json_api.process_logfile active
[2024-11-21 18:57:20,688] DEBUG ARM: json_api.process_logfile using handbrake
[2024-11-21 18:57:20,693] DEBUG ARM: json_api.process_handbrake_logfile Cant find index
[2024-11-21 18:57:20,695] DEBUG ARM: json_api.get_x_jobs jobs  - we have 1 jobs`
```
The  BluRay.log stuck at this point:
```
[2024-11-21 18:31:46] INFO ARM: ARM version: 2.6.60
[2024-11-21 18:31:46] INFO ARM: Python version: 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]
[2024-11-21 18:31:46] INFO ARM: User is: arm
[2024-11-21 18:31:46] INFO ARM: Alembic head is: 2e0dc31fcb2e
[2024-11-21 18:31:46] INFO ARM: Database version is: 2e0dc31fcb2e
[2024-11-21 18:31:46] INFO ARM: ************* Starting ARM processing at 2024-11-21 18:31:46.475901 *************
[2024-11-21 18:31:47] INFO ARM: loglife is set to 0. Removal of logs is disabled
[2024-11-21 18:31:47] INFO ARM: Job: FROSTBITE_EU
[2024-11-21 18:31:47] INFO ARM: Job #1 with PID 314 is currently running.
[2024-11-21 18:31:47] INFO ARM: Starting Disc identification
[2024-11-21 18:31:47] INFO ARM: Mounting disc to: /mnt/dev/sr0
[2024-11-21 18:31:47] INFO ARM: Mounting disc was successful
```
and the webinterface is showing this job
![webinterface](https://github.com/user-attachments/assets/f7445c33-f01e-4219-a47f-7493acd127b2)

### To Reproduce

1. Docker on OpenMediaVault 7.4.13-1 (Sandworm)
2. Compose.yml:
```
# Automatic Ripping Machine
# Dockerbased DVD, CD, BluRay Ripper
networks:
  servers:
    external: true
services:
  app:
    deploy:
      resources:
        limits:
          cpus: '8.0'
    container_name: arm-rippers
    privileged: true
    image: 1337server/automatic-ripping-machine:2.6.60
    hostname: arm-rippers
    networks:
      - servers
    environment:
      # Guppen und User-ID des Freigegebenen Ordners
      ARM_UID: 1000
      ARM_GID: 1000
    ports:
      - "9090:8080"
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sr1:/dev/sr1
      - /dev/sr2:/dev/sr2
      - /dev/sr3:/dev/sr3
#      - /dev/dri/card0:/dev/dri/card0
#      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/sg1:/dev/sg1
    volumes:
      - ${FS}/arm/:/home/arm
      - ${FS}/arm/Music:/home/arm/Music
      - ${FS}/arm/logs:/home/arm/logs
      - ${FS}/arm/media:/home/arm/media
      - ${FS}/arm/config:/etc/arm/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    stdin_open: true
    tty: true
    restart: unless-stopped
```
3. the config is completely standard i only added a makeMKV licence

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

I think its a permission problem, but the UID and GID are set to the docker user and the directory settings are 777

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
You are not using the official ARM image, but a fork from 1337. So I am unable to help, 1337server may have added a bug or be working on something that breaks ARM

As for the spamming of the Docker logs, change your UI config 'index_refresh' to something larger, say 5000 (5 seconds)

**Comment by Waschke1994** [comment]
Omg I'm so sorry didn't realised that ... Thx for your notice with the logs, I will Change that and in this move I will Change the Image to yours maybe this will bring a fix

**Comment by Waschke1994** [comment]
unfortunately the only thing that disapeared after i switched to your image is the log-spam...
the container still stuck at the mountingpoint 
`[2024-11-22 18:12:43,050] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
Nov 22 18:13:05 arm-rippers ARM: [ARM] Entering docker wrapper
Nov 22 18:13:05 arm-rippers ARM: Fri Nov 22 18:13:05 CET 2024 [[ARM] Starting ARM for Bluray on sr0
Nov 22 18:13:05 arm-rippers ARM: TARGET       SOURCE   FSTYPE OPTIONS
Nov 22 18:13:08 arm-rippers ARM: /mnt/dev/sr0 /dev/sr0 udf    ro,nosuid,nodev,relatime,iocharset=utf8`

**Comment by microtechno9000** [comment]
At this point all the logs are now in a job log, there should be a log in the arm/logs folder

**Comment by Waschke1994** [comment]
ive done a litte research... 
so the job log says 
`[11-23-2024 10:40:40] INFO ARM: ARM version: 2.9.1
[11-23-2024 10:40:40] INFO ARM: Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
[11-23-2024 10:40:40] INFO ARM: User is: arm
[11-23-2024 10:40:40] INFO ARM: Alembic head is: b326a3663939
[11-23-2024 10:40:40] INFO ARM: Database version is: b326a3663939
[11-23-2024 10:40:40] INFO ARM: ************* Starting ARM processing at 2024-11-23 10:40:40.380569 *************
[11-23-2024 10:40:41] INFO ARM: Looking for log files older than 1 days old.
[11-23-2024 10:40:41] INFO ARM: Checking path /home/arm/logs/ for old log files...
[11-23-2024 10:40:41] INFO ARM: Checking path /home/arm/logs/progress for old log files...
[11-23-2024 10:40:41] INFO ARM: Job: FROSTBITE_EU
[11-23-2024 10:40:41] INFO ARM: Job #1 with PID 238 is currently running.
[11-23-2024 10:40:41] INFO ARM: Starting Disc identification
[11-23-2024 10:40:41] INFO ARM: Mounting disc to: /mnt/dev/sr0
[11-23-2024 10:40:43] INFO ARM: Mounting disc was successful`

The job createted and shows up on webinterface like I already showed in my first post.
But.. I checked the syslog on the host (/var/log/syslog) here i got this error:

`2024-11-23T10:55:07.417649+01:00 server kernel: [  216.514751] UDF-fs: error (device sr0): udf_fiiter_advance_blk: extent after position 2016 not allocated in directory (ino 327)
2024-11-23T10:55:07.417651+01:00 server kernel: [  216.514757] UDF-fs: error (device sr0): udf_verify_fi: directory (ino 327) has entry where CRC length (36) does not match entry length (112)
`
I've already reinstalled the udftools but nothing changed :(

**Comment by steveopolois** [comment]
I think what we see here is related to an underlying kernel issue. I am running docker on Debian 12 with kernel 6.1.119-1 and also seeing this issue.  I have found that some disks work fine but others do not. So far I have one DVD that worked, one DVD that didn't work, and one Blu-ray that didn't work.

After inserting a disk and seeing the same results as @Waschke1994 in ARM I ran `sudo journalctl --since "10 minutes ago"` and that outputs the below two lines repeating.
`kernel: UDF-fs: error (device sr0): udf_verify_fi: directory (ino 327) has entry where CRC length (36) does not match entry length (112)`
`kernel: UDF-fs: error (device sr0): udf_fiiter_advance_blk: extent after position 2016 not allocated in directory (ino 327)`

After some searching, I found references to the same errors in [this post](https://linux.debian.bugs.dist.narkive.com/pRJjjrie/bug-1089698-linux-loop-mounted-udf-isos-no-longer-readable). That indicates that this is a bug in the Linux kernel that was introduced sometime after version 6.1.114, as the UDF code was refactored.

I believe this same bug is also what is causing the issue in #1267

**Comment by steveopolois** [comment]
I have worked around this by downgrading the kernel on my Debian VM. I will add some additional information here if it is helpful to anyone else. Note that this VM was running in VMware workstation 17.6.2 build-24409262 on Windows 10. This fix may not work depending on the hypervisor you are using.

I was originally running vmlinuz-6.1.0-28-amd64 (6.1.119-1) and downgraded to linux-image-6.1.0-12-amd64 (6.1.52-1). The steps below were taken from [this post on Reddit](https://www.reddit.com/r/debian/comments/18h3fxt/downgrading_kernel/).

1. Find available packages. 
```
apt-cache search linux | grep -P "^linux-image[^ ]*[0-9]\-amd64 "
linux-image-6.1.0-25-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-27-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-11-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-12-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-17-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-20-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-21-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-23-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-26-amd64 - Linux 6.1 for 64-bit PCs (signed)
linux-image-6.1.0-28-amd64 - Linux 6.1 for 64-bit PCs (signed)
```
2. Confirm what is installed on your system.
```
ls -1 /boot/vmlinuz-*
/boot/vmlinuz-6.1.0-27-amd64
/boot/vmlinuz-6.1.0-28-amd64
```
3. Install the version you wish to run. I will choose 6.1.0-12.
```
sudo  apt install linux-image-6.1.0-12-amd64
```
5. Confirm the file is installed.
```
ls -1 /boot/vmlinuz-*
/boot/vmlinuz-6.1.0-12-amd64
/boot/vmlinuz-6.1.0-27-amd64
/boot/vmlinuz-6.1.0-28-amd64
```
6. Reboot the system and choose the correct kernel in advanced options on the grub screen.

**Comment by dbuttric** [comment]
I retrograded my kernel to 6.1.0-12-amd64. I'm re-ripping all the BluRays that have failed since I did the kernel upgrade.

Will report back on Monday, but I'm feeling confident.

Thank you all for the work figuring this out!

**Comment by Waschke1994** [comment]
First Off all thx for your research and Tips at hat e moment I do not have the time to check these solutions and workarounds. I will doch this asap I have time :)

**Comment by dingwap** [comment]
I've had the same problem on Debian 12, tried kicking off the script manually within the container and it worked sometimes but not consistently. I've just retrograded my kernel back to 6.10-12-amd64 as per @steveopolois post and it's now working as expected. First disc I inserted kicked off immediately without issue.

Thanks for the help!

**Comment by Sono-Gomorrha** [comment]
I can confirm what @steveopolois wrote. Had the same issue with a DVD stuck at 'Mounting disc was successful'. After downgrading the kernel ARM does now proceed to rip the disc.
