### ISSUE TITLE
🐛 Script Installation Isn't Working

### ISSUE THREAD

**Issue by 641i130** [automatic-ripping-machine/automatic-ripping-machine#1256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Running Ubuntu 20.04.6 LTS and attempting to install this tool using the script results in the tool not starting correctly.

### To Reproduce

1. Install Ubuntu 20.04.6 LTS
2. Follow the wiki to run the script to install the tool
3. Watch it fail

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

Not accessible, it doesn't start!

### Expected behavior?

Should start after a reboot!

### Relevant log output

```shell
root@ripper:/home/asdf# sudo systemctl status armui
● armui.service - Arm service
     Loaded: loaded (/etc/systemd/system/armui.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-12-08 17:12:30 CST; 2s ago
    Process: 31083 ExecStartPre=/bin/bash -xc /usr/bin/systemctl is-active --quiet armui.service && exit >
    Process: 31085 ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py (code=exited, status=1/FAILURE)
   Main PID: 31085 (code=exited, status=1/FAILURE)
root@ripper:/home/asdf# tail /home/arm/logs/WebUI.log 
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, ARMInfo # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 18, in <module>
    import apprise
ModuleNotFoundError: No module named 'apprise'
root@ripper:/home/asdf#
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 641i130** [comment]
Looking into it, I was able to fix this issue by simply doing:
```
pip3 install -r /opt/arm/requirements.txt
```
Should this be part of the script or guide?

**Comment by microtechno9000** [comment]
You will need to install the requirements yes, otherwise ARM will be missing the required python packages.

The Ubuntu install script hasn't been maintained or tested since moving to docker, see [Ubuntu Install](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Alternate-Install-Ubuntu)

The script was left as some users have found it useful. If there is an issue with the script, you are welcome to raise a PR and we can merge it in. [Contribute to ARM](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Contribute)
