### ISSUE TITLE
🐛 <title>No start_arm_container.sh File

### ISSUE THREAD

**Issue by KageShiroe** [automatic-ripping-machine/automatic-ripping-machine#1257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

After i run the command: sudo ./docker-setup.sh -f automaticrippingmachine -t dev_build i do not have a file called start_arm_container.sh to edit

### To Reproduce

on ubuntu 20.04.6 run command sudo ./docker-setup.sh -f automaticrippingmachine -t dev_build

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.10.1

### Expected behavior?

a program called start_arm_container.sh that i can edit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Are you following the install guide for [Docker Installs](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker)

You need to download the script first

**Comment by untoasted-glamor** [comment]
In case anyone else comes across this like I did, I needed to log into the new arm user first:

```
su --login arm
# then type whatever password you configured earlier
ls -la
# should list start_arm_container.sh
```

If start_arm_container isn't there then I manually downloaded the file:
```
wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/main/scripts/docker/start_arm_container.sh
nano start_arm_container.sh
```
