### ISSUE TITLE
🐛 Disc not ejecting

### ISSUE THREAD

**Issue by 4MAZ** [automatic-ripping-machine/automatic-ripping-machine#1260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Disk is not auto ejecting after job is complete

### To Reproduce

Ubuntu 20.04 with the newest docker container. 
Install script 
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -v "/home/arm:/home/arm" \
    -v "/home/arm/music:/home/arm/music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/home/arm/media:/home/arm/media" \
    -v "/home/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --device="/dev/sr4:/dev/sr4" \
    --device="/dev/sr5:/dev/sr5" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='2,3,4,5,6,7,8,9,10,11,12,13,14,15' \
    automaticrippingmachine/automatic-ripping-machine:latest

all other settings default.

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

2.10.1

### Expected behavior?

I expected the the disk to auto eject after the job was complete

### Relevant log output

```shell
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:3032,0,2,"Region setting of drive TSSTcorp:CDDVDW SH-224DB does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","TSSTcorp","CDDVDW SH-224DB"
MSG:5011,0,0,"Operation successfully completed","Operation successfully completed"
DRV:1,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E6YBF4009KR","","/dev/sr1"
DRV:2,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E6YBF4009KT","","/dev/sr5"
DRV:3,0,999,0,"DVD+R-DL TSSTcorp CDDVDW SH-224DB SB01 R93E6YBF4009KV","","/dev/sr2"
MSG:5014,131072,2,"Saving 1 titles into directory file:///home/arm/media/raw/SICARIO","Saving %1 titles into directory %2","1","file:///home/arm/media/raw/SICARIO"
MSG:5005,128,1,"1 titles saved","%1 titles saved","1"
MSG:5036,260,1,"Copy complete. 1 titles saved.","Copy complete. %1 titles saved.","1"
[12-08-2024 17:55:18] DEBUG ARM: job.eject Unmounted disc /dev/sr3
[12-08-2024 17:55:18] DEBUG ARM: job.eject Ejected disc /dev/sr3
[12-08-2024 17:55:18] INFO ARM: makemkv.makemkv Exiting MakeMKV processing with return value of: /home/arm/media/raw/SICARIO
[12-08-2024 17:55:18] DEBUG ARM: utils.notify apprise message, title: ARM notification body: SICARIO rip complete. Starting transcode. 
[12-08-2024 17:55:18] DEBUG ARM: utils.database_adder Trying to add Notifications
[12-08-2024 17:55:18] DEBUG ARM: utils.database_adder successfully written Notifications to the database
[12-08-2024 17:55:18] INFO ARM: arm_ripper.rip_visual_media ************* Ripping with MakeMKV completed *************
[12-08-2024 17:55:18] DEBUG ARM: utils.database_updater ID:1 status=transcoding:<class 'str'>
[12-08-2024 17:55:18] DEBUG ARM: utils.database_updater successfully written to the database
[12-08-2024 17:55:18] INFO ARM: arm_ripper.start_transcode ************* Starting Transcode With HandBrake *************
[12-08-2024 17:55:18] DEBUG ARM: arm_ripper.start_transcode handbrake_mkv: /home/arm/media/raw/SICARIO, /home/arm/media/transcode/unidentified/SICARIO, /home/arm/logs/SICARIO.log
[12-08-2024 17:55:18] INFO ARM: utils.sleep_check_process Transcode limit is disabled
[12-08-2024 17:55:18] DEBUG ARM: handbrake.handbrake_mkv B1_t00.mkv
[12-08-2024 17:55:18] DEBUG ARM: handbrake.handbrake_mkv filename: B1_t00.mkv
[12-08-2024 17:55:18] DEBUG ARM: handbrake.handbrake_mkv UPDATED filename: B1_t00.mkv
[12-08-2024 17:55:18] INFO ARM: handbrake.handbrake_mkv Transcoding file B1_t00.mkv to /home/arm/media/transcode/unidentified/SICARIO/B1_t00.mkv
[12-08-2024 17:55:18] DEBUG ARM: handbrake.handbrake_mkv Sending command: nice HandBrakeCLI -i /home/arm/media/raw/SICARIO/B1_t00.mkv -o /home/arm/media/transcode/unidentified/SICARIO/B1_t




Full log attached below
```

### Anything else?

[log (1).txt](https://github.com/user-attachments/files/18087473/log.1.txt)

I had this working on an older docker image. I decided to update and started with fresh install of Ubuntu 20.04.

The job still completes and the rips look good, just not ejecting at the end.

Just want to add, I love this project and I think its awesome. I appreciate all the hardwork the contributors have put into it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Thanks, it's a fun project to work on

Looking at the logs, the system is trying to eject, it is executing the eject [job.eject](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/f3689c124b4ee2a3ff3077a95827a0d1d7f322d9/arm/models/job.py#L207) just nothing happens.

Can run the below and provide the results
1. stop the ARM container, insert a disk then try `eject -sv /dev/sr1`
2. If that works, restart the arm container, wait for it to come up.
3. Insert a disk, a job will start but just ignore that.
4. Enter the docker container docker `exec -it <<container name>> /bin/bash`
5. From within the container, then run the same eject command `eject -sv /dev/sr1`

**Comment by 4MAZ** [comment]
I used eject -sv /dev/sr3 becuase thats what drive was being used in the log above. Here is the output from the commands you asked me to run:

arm@arm:~$ eject -sv /dev/sr3
eject: device name is `/dev/sr3'
eject: expanded name is `/dev/sr3'
eject: `/dev/sr3' is not mounted
eject: `/dev/sr3' is not a mount point
eject: `/dev/sr3' is not a multipartition device
eject: trying to eject `/dev/sr3' using SCSI commands
eject: SCSI eject succeeded
arm@arm:~$ sudo docker start arm-rippers
[sudo] password for arm:
arm-rippers
arm@arm:~$ exec -it arm-rippers /bin/bash
-bash: exec: -i: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
arm@arm:~$ sudo exec -it arm-rippers /bin/bash
sudo: exec: command not found
arm@arm:~$ sudo docker exec -it arm-rippers /bin/bash
root@81c41013cc1f:/home/arm# eject -sv /dev/sr1
eject: device name is `/dev/sr1'
eject: /dev/sr1: not mounted
eject: /dev/sr1: is whole-disk device
eject: /dev/sr1: trying to eject using SCSI commands
eject: SCSI eject succeeded
root@81c41013cc1f:/home/arm#


Both times the drive ejected as it should.

**Comment by 4MAZ** [comment]
I did some more trouble shooting with all my drives. Everything seemed to work as it should other then sr1 would not eject when the docker container was stopped. After starting the container they all acted as expected.


`root@81c41013cc1f:/home/arm#arm@arm:~$ sudo docker stop arm-rippers
arm-rippers
arm@arm:~$ lsscsi -g
[0:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr0   /dev/sg0
[1:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr1   /dev/sg1
[2:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr2   /dev/sg2
[3:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr3   /dev/sg3
[4:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr4   /dev/sg4
[5:0:0:0]    cd/dvd  TSSTcorp CDDVDW SH-224DB  SB01  /dev/sr5   /dev/sg5
[40:0:0:0]   disk    ATA      PNY CS900 500GB  0LA5  /dev/sda   /dev/sg6
arm@arm:~$ eject -sv /dev/sr0
eject: device name is `/dev/sr0'
eject: expanded name is `/dev/sr0'
eject: `/dev/sr0' is not mounted
eject: `/dev/sr0' is not a mount point
eject: `/dev/sr0' is not a multipartition device
eject: trying to eject `/dev/sr0' using SCSI commands
^[[Aeject: SCSI eject succeeded
arm@arm:~$ eject -sv /dev/sr1
eject: device name is `/dev/sr1'
eject: expanded name is `/dev/sr1'
eject: `/dev/sr1' is not mounted
eject: `/dev/sr1' is not a mount point
eject: `/dev/sr1' is not a multipartition device
eject: trying to eject `/dev/sr1' using SCSI commands
eject: SCSI eject failed
eject: unable to eject, last error: Success
arm@arm:~$ eject -sv /dev/sr2
eject: device name is `/dev/sr2'
eject: expanded name is `/dev/sr2'
eject: `/dev/sr2' is not mounted
eject: `/dev/sr2' is not a mount point
eject: `/dev/sr2' is not a multipartition device
eject: trying to eject `/dev/sr2' using SCSI commands
eject: SCSI eject succeeded
arm@arm:~$ eject -sv /dev/sr3
eject: device name is `/dev/sr3'
eject: expanded name is `/dev/sr3'
eject: `/dev/sr3' is not mounted
eject: `/dev/sr3' is not a mount point
eject: `/dev/sr3' is not a multipartition device
eject: trying to eject `/dev/sr3' using SCSI commands
eject: SCSI eject succeeded
arm@arm:~$ eject -sv /dev/sr4
eject: device name is `/dev/sr4'
eject: expanded name is `/dev/sr4'
eject: `/dev/sr4' is not mounted
eject: `/dev/sr4' is not a mount point
eject: `/dev/sr4' is not a multipartition device
eject: trying to eject `/dev/sr4' using SCSI commands
eject: SCSI eject succeeded
arm@arm:~$ eject -sv /dev/sr5
eject: device name is `/dev/sr5'
eject: expanded name is `/dev/sr5'
eject: `/dev/sr5' is not mounted
eject: `/dev/sr5' is not a mount point
eject: `/dev/sr5' is not a multipartition device
eject: trying to eject `/dev/sr5' using SCSI commands
eject: SCSI eject succeeded
arm@arm:~$ sudo docker start arm-rippers
arm-rippers
arm@arm:~$ sudo docker exec -it arm-rippers /bin/bash
root@81c41013cc1f:/home/arm# eject -sv /dev/sr0
eject: device name is `/dev/sr0'
eject: /dev/sr0: not mounted
eject: /dev/sr0: is whole-disk device
eject: /dev/sr0: trying to eject using SCSI commands
eject: SCSI eject succeeded
root@81c41013cc1f:/home/arm# eject -sv /dev/sr0
eject: device name is `/dev/sr0'
eject: /dev/sr0: not mounted
eject: /dev/sr0: is whole-disk device
eject: /dev/sr0: trying to eject using SCSI commands
^[eject: SCSI eject succeeded
root@81c41013cc1f:/home/arm# eject -sv /dev/sr1
eject: device name is `/dev/sr1'
eject: /dev/sr1: not mounted
eject: /dev/sr1: is whole-disk device
eject: /dev/sr1: trying to eject using SCSI commands
eject: SCSI eject succeeded
root@81c41013cc1f:/home/arm# eject -sv /dev/sr2
eject: device name is `/dev/sr2'
eject: /dev/sr2: not mounted
eject: /dev/sr2: is whole-disk device
eject: /dev/sr2: trying to eject using SCSI commands
eject: SCSI eject succeeded
root@81c41013cc1f:/home/arm# eject -sv /dev/sr3
eject: device name is `/dev/sr3'
eject: /dev/sr3: not mounted
eject: /dev/sr3: is whole-disk device
eject: /dev/sr3: trying to eject using SCSI commands
eject: SCSI eject succeeded
root@81c41013cc1f:/home/arm# eject -sv /dev/sr4
eject: device name is `/dev/sr4'
eject: /dev/sr4: not mounted
eject: /dev/sr4: is whole-disk device
eject: /dev/sr4: trying to eject using SCSI commands
eject: SCSI eject succeeded
root@81c41013cc1f:/home/arm# eject -sv /dev/sr5
eject: device name is `/dev/sr5'
eject: /dev/sr5: not mounted
eject: /dev/sr5: is whole-disk device
eject: /dev/sr5: trying to eject using SCSI commands
eject: SCSI eject succeeded
root@81c41013cc1f:/home/arm#`

**Comment by 4MAZ** [comment]
So Ive been ripping just Sicario in different drives and it thats the only thing the pc is doing it seems to work fine. If I start to put in multiple movies in multiple drives issue start to occur.

**Comment by microtechno9000** [comment]
Odd, doesn't look like there is a config or docker issue.

The multiple jobs shouldn't cause an issue with something like this, as ARM will just eject the drive for that job.

Do you have logs from both jobs that the issue occured?
If not, can you run two jobs and post them here. With debug logging on

**Comment by 4MAZ** [comment]
I will run some tonight and document what happens with each job and upload the logs.

I think I have mentioned it before but I am no linux expert by any means but I started digging around in logs and may have discovered the underlying issues. Attached is a txt file of the output from running dmesg and I am seeing alot of IO errors relating to the my disk drives.
[dmesg.txt](https://github.com/user-attachments/files/18112682/dmesg.txt)

**Comment by 4MAZ** [comment]
So I am getting really mixed results heres one that failed and did not eject.
[BE_COOL_WS.log](https://github.com/user-attachments/files/18132776/BE_COOL_WS.log)

**Comment by 4MAZ** [comment]
Two more that didnt eject.

[BANDIDAS_SIDEB.log](https://github.com/user-attachments/files/18132833/BANDIDAS_SIDEB.log)
[BLACK_CAULDRON.log](https://github.com/user-attachments/files/18132834/BLACK_CAULDRON.log)

**Comment by 4MAZ** [comment]
[3MUSKETEERS.log](https://github.com/user-attachments/files/18132854/3MUSKETEERS.log)
Another one that did not eject.

**Comment by 4MAZ** [comment]
[MASTER_AND_COMMANDER_D1.log](https://github.com/user-attachments/files/18132937/MASTER_AND_COMMANDER_D1.log)
Its not going well lol. this one did not eject either.

**Comment by microtechno9000** [comment]
> I will run some tonight and document what happens with each job and upload the logs.
> 
> I think I have mentioned it before but I am no linux expert by any means but I started digging around in logs and may have discovered the underlying issues. Attached is a txt file of the output from running dmesg and I am seeing alot of IO errors relating to my disk drives.
> [dmesg.txt](https://github.com/user-attachments/files/18112682/dmesg.txt)
> 

Looking at these logs looks like it might be a hardware issue.

https://forums.debian.net/viewtopic.php?t=135019

**Comment by 1337-server** [comment]
https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Docker-Troubleshooting#makemkv-cant-find-drives

Try using the recommended steps, as you currently aren't passing in both identifiers to MakeMKV

**Comment by 4MAZ** [comment]
Doesnt seem to be a hardware issue changed psu and sata cables still running into the issue.

So my devices in the starter script should look like this:
`--device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --device="/dev/sr0:/dev/sg0" \
    --device="/dev/sr1:/dev/sg1" \
    --device="/dev/sr2:/dev/sg2" \
    --device="/dev/sr3:/dev/sg3" \`

**Comment by 4MAZ** [comment]
Not sure if the above was correct but after adding it it seemed to work as intended. I did reinstall and use the older image i was originally using. 2.6.72 and I did not need to add those for auto eject to work.

**Comment by 1337-server** [comment]
Glad you got it sorted.

**Comment by microtechno9000** [comment]
When you run eject via ssh, are you doing that from the host or inside the docker image?

Try again from within the image using the below and use `eject -v`

```bash
docker exec -it automatic-ripping-machine /bin/bash
```

**Comment by heatvent** [comment]
Hi, I am having issues as well with auto_eject not working. I am using a VM in VMWare Workstation Pro 17. Ripping works fine but the auto eject is not working.

I entered the container with the following command:

docker exec -it 449b78cd3402 /bin/bash

Then, I tried the eject command:

eject -sv /dev/sr0

Below is the result I got back:

arm@ARM:~$ docker exec -it 449b78cd3402 /bin/bash
root@449b78cd3402:/home/arm# eject -sv /dev/sr0
eject: device name is `/dev/sr0'
eject: /dev/sr0: not mounted
eject: /dev/sr0: is whole-disk device
eject: cannot open /dev/sr0: Device or resource busy
root@449b78cd3402:/home/arm# 

Next I tried from the VM itself and it worked:

arm@ARM:~$ eject -sv /dev/sr0
eject: device name is `/dev/sr0'
eject: /dev/sr0: mounted on /media/arm/PASSENGERS_2016
eject: /dev/sr0: is whole-disk device
eject: /media/arm/PASSENGERS_2016: unmounting
eject: /dev/sr0: trying to eject using SCSI commands
eject: SCSI eject succeeded

Not sure if this is a limitation with VMWare Workstation since I can eject from the VM itself. Any thoughts would be appreciated. Not sure what the potential issues are if you can eject from the docker host OS but not from within the docker container.
