### ISSUE TITLE
🐛 https://1337server.pythonanywhere.com/request/key Internal Server Error

### ISSUE THREAD

**Issue by ToasterUwU** [automatic-ripping-machine/automatic-ripping-machine#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [ ] I'm using the latest release

### Describe the bug?

https://1337server.pythonanywhere.com/request/key is down or broken it seems. So noone can request a API key for submitting the identification of Discs.

### To Reproduce

1. Go to https://1337server.pythonanywhere.com/request/key
2. Witness the Error

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.8.0

But this doesnt matter for obvious reasons.

### Expected behavior?

HTTP Code 200

### Anything else?

I looked for issues about this but couldnt find anything. Seems odd since this is a big part of the programs function, hope i didnt miss it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Thank you for letting us know

Fixed!
