### ISSUE TITLE
V2 - Interactive Install Script

### ISSUE THREAD

**Issue by MrTechGadget** [automatic-ripping-machine/automatic-ripping-machine#136]
I've spent some time today turning the install instructions in the v2 readme into an interactive install script.
It incorporates the PR #132 missing dependencies 

[install ARM v2 script](https://gist.github.com/audioeng/65d753fb9cae7cce2e5a9a81263f4a42)

You can install this directly from the command-line by running:
`bash <(wget -qO- https://gist.githubusercontent.com/audioeng/65d753fb9cae7cce2e5a9a81263f4a42/raw/a5550343c30de6e14854e950a4a175231b9d70b9/installARM.sh)`
Or, if you don't trust me (which while I will tell you I am a nice guy, you shouldn't really trust me on that...) just download it/copy & paste/manually type it in and run it
`bash installARM.sh`

**Comment by muckngrind4** [comment]
Looks cool.  I'm going to try it out on my next install...

**Comment by audioeng** [comment]
I've reverted my VM several times, it is working consistently for me installing everything error free.
You still have to set the drive permissions in fstab and edit your config but it saves a lot of cut & paste... :)

That said, I'm still seeing issues with the arm account having enough permissions to run the script, is that expected at this point? we might need to add some chmod can chown commands in somewhere.

**Comment by jeroentheuns** [comment]
Thanks! I'm seeing errors in the end:
...
Adding debian:GlobalSign_Root_CA_-_R2.pem
Adding debian:Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem
done.
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for ca-certificates (20170717~16.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
sudo: git: command not found
/dev/fd/63: line 20: cd: arm: No such file or directory
sudo: git: command not found
The directory '/home/jeroen/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jeroen/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 373kB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-10.0.1
The directory '/home/jeroen/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jeroen/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
cp: cannot stat '/opt/arm/setup/arm@.service': No such file or directory
cp: cannot stat 'docs/arm.conf.sample': No such file or directory
Don't forget to edit the /opt/arm/arm.conf configuration file, setup any /mnt paths, and reboot!
jeroen@jeroen-Standard-PC-i440FX-PIIX-1996:~$

**Comment by emmakat** [comment]
any update on this script? I'd like to use it. I too get this error
cp: cannot stat 'docs/arm.conf.sample': No such file or directory
Don't forget to edit the /opt/arm/arm.conf configuration file, setup any /mnt paths, and reboot!

probably user error but curious if the steps docs/arm.conf.sample at the end are correct since v2 seems to use this:  
cp /opt/arm/setup/arm@.service /etc/systemd/system/
cp --backup=numbered docs/arm.conf.yaml.sample arm.conf.yaml
cp docs/arm.yaml.sample arm.yaml
mkdir /etc/arm/
ln -s /opt/arm/arm.yaml /etc/arm/

**Comment by emmakat** [comment]
thanks for this. am I supposed to login as arm user after rebooting?
