### ISSUE TITLE
v2 yaml config?

### ISSUE THREAD

**Issue by audioeng** [automatic-ripping-machine/automatic-ripping-machine#139]
I noticed that in v2 you are parsing the config file and building a temporary yaml file from it. 
The config file itself is so close to being yaml compliant all by itself, would it make more sense to just do that instead? I have a yaml compliant version ready to go, say the word and I will edit the config.py to take advantage of that instead of making a temp file. 

Am I missing another reason for the temp yaml config?

**Comment by ahnooie** [comment]
No, the original thought was to keep compatibility with the old config, but in hindsight we're making enough changes with V2 we probably shouldn't worry about the old config files working and just switch over to yaml.  I saw make your change.

**Comment by muckngrind4** [comment]
I agree.  Let's move to a pure yaml config...

**Comment by audioeng** [comment]
#146 'might' accomplish this, pending testing and review.

**Comment by muckngrind4** [comment]
Added in #142
