### ISSUE TITLE
Suggestion for default config file for additional perimeters for Handbreake for English speaking users.

### ISSUE THREAD

**Issue by Plexen85** [automatic-ripping-machine/automatic-ripping-machine#145]
Suggestion for default config file for additional perimeters for Handbreake for English speaking users.

# Additional HandBrake arguments.  
HB_ARGS="--subtitle-lang-list eng --all-subtitles --native-language eng --subtitle-default=scan"

This will give you default to show foreign languages as default subtitle file and give you an additional subtitle file if you want all subtitles for the movie 

Folks might already be doing this but figured it might be worth posting to help someone.

**Comment by muckngrind4** [comment]
Thanks @Plexen85.  I love seeing what others are doing so I can learn from them!  I'm thinking maybe we'll put a section in the wiki where people can share their hb_args.  I use something similar except I burn in the forced audio subtitles...  I'm not sure it's the best, but it's pretty bomb proof to work with any player...

**Comment by Plexen85** [comment]
Yeah, I have always been a fan of soft subtitles directly from source media 

When I scripted handbrake automation in vb a few years back they didn’t have as many options in handbrake Cli 

If you guys wanted exposure for your project you should reach out to byte my bits on YouTube. He a plex YouTuber and could get more people using the tool.

**Comment by audioeng** [comment]
Good idea, maybe once we get the move to python done would be good timing..

**Comment by muckngrind4** [comment]
Agreed.  Great suggestion, but we should wait for the python rewrite first...

**Comment by Plexen85** [comment]
Is that the V2 you guys have been talking about ?
