### ISSUE TITLE
Some config settings appear to be hardcoded.

### ISSUE THREAD

**Issue by Plexen85** [automatic-ripping-machine/automatic-ripping-machine#153]
I found 3 issues. Unless the default folders are left in config file provided at installation 
1. PLEX_SUPPORT=true will not trigger 
2. OMDB name will not make it to the mkv file only the folder i.e. Downsizing (2017) will be the folder name but not the file name. 
3. File permissions of 777 will not be applied 
SET_MEDIA_PERMISSIONS=true
CHMOD_VALUE=777

### Environment
Umbutu 16.04 fresh install

**Comment by muckngrind4** [comment]
Hi @Plexen85, Thanks for submitting this.  Can you tell me what version your running?

**Comment by Plexen85** [comment]
Is that listed at top of a .py files someplace? Have to be honest. I haven’t looked at the code. I installed by the readme instructions. 

I can post log files. I am running two different configurations on two old dell 3010s. How do you want me to post them so all the text doesn’t make this thread confusing.

**Comment by muckngrind4** [comment]
In v2 it's in a file but not in v1.x. v2 is still beta, so you would have downloaded it from the v2_master branch.  If you downloaded from master the you're on v1.x.

**Comment by muckngrind4** [comment]
Also, a log file would help if you have one.

**Comment by Plexen85** [comment]
Yeah I’m on master branch so v1. Yes I can post log files from the system working correctly and one not this weekend

**Comment by Plexen85** [comment]
Found my issue. My final destination folder setting was same as unidentified location. While watching the default machine,I saw arm does the rename, file move, and plex settings from there and ends up in my final destination folder. 

Very clever of the devs and I see why it’s done that way. 

I will stick to my day job and stay in the world of sql.
