### ISSUE TITLE
Not naming movies with OMDB

### ISSUE THREAD

**Issue by Yokopops** [automatic-ripping-machine/automatic-ripping-machine#164]
Hi, I have set up an ARM and set the configs correct as far as i'm aware even including my API key however, movies are still not naming. I have attached a snip from one of my logs to show the error, I am still learning so go easy on me :D If you need any more information please let me know but I assumed you may be able to help by the error listed in this log. I am using the default branch as for some reason the V2 will not work at all (not even attempt to rip or generate log files) so if you can help with that as well I would appreciate it.

Regards.

Linux version:
VERSION="16.04.4 LTS (Xenial Xerus)"
*** Start config parameters ****
	Timestamp: Fri, 18 May 2018 01:27:54 +0100
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
RAWPATH="/mnt/media/ARM/raw/"
MEDIA_DIR="/mnt/media/ARM/Media/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
LOG_SINGLE_FILE=false 
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
SET_MEDIA_OWNER=false
CHOWN_USER=
CHOWN_GROUP=
MINLENGTH="600"
RIPMETHOD="mkv" 
MKV_ARGS=""
HB_PRESET="High Profile" 
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--subtitle scan -F"
PLEX_SUPPORT=false
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
NOTIFY_RIP=true
NOTIFY_TRANSCODE=true
IFTTT_EVENT="arm_event"
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files: 
DEVLINKS=/dev/disk/by-id/ata-ATAPI_iHOS104_5504068_306111500214 /dev/disk/by-uuid/2011-07-19-20-05-58-00 /dev/disk/by-label/THOR /dev/cdrom /dev/disk/by-path/pci-0000:00:13.0-ata-2 /dev/dvd
DEVNAME=/dev/sr0
DEVPATH=/devices/pci0000:00/0000:00:13.0/ata2/host1/target1:0:0/1:0:0:0/block/sr0
DEVTYPE=disk
ID_ATA=1
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_BUS=ata
ID_CDROM=1
ID_CDROM_BD=1
ID_CDROM_CD=1
ID_CDROM_DVD=1
ID_CDROM_MEDIA=1
ID_CDROM_MEDIA_DVD=1
ID_CDROM_MEDIA_SESSION_COUNT=1
ID_CDROM_MEDIA_STATE=complete
ID_CDROM_MEDIA_TRACK_COUNT=1
ID_CDROM_MEDIA_TRACK_COUNT_DATA=1
ID_FOR_SEAT=block-pci-0000_00_13_0-ata-2
ID_FS_LABEL=THOR
ID_FS_LABEL_ENC=THOR
ID_FS_TYPE=udf
ID_FS_USAGE=filesystem
ID_FS_UUID=2011-07-19-20-05-58-00
ID_FS_UUID_ENC=2011-07-19-20-05-58-00
ID_MODEL=ATAPI_iHOS104
ID_MODEL_ENC=ATAPI\x20\x20\x20iHOS104\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_PATH=pci-0000:00:13.0-ata-2
ID_PATH_TAG=pci-0000_00_13_0-ata-2
ID_REVISION=WL0F
ID_SERIAL=ATAPI_iHOS104_5504068_306111500214
ID_SERIAL_SHORT=5504068_306111500214
ID_TYPE=cd
MAJOR=11
MINOR=0
SUBSYSTEM=block
TAGS=:systemd:seat:uaccess:
USEC_INITIALIZED=2891968
identified udf
found THOR on /dev/sr0
identified udf as video
failed to get title Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 69, in <module>
    disc_title = clean_for_filename(getdvdtitle())
  File "/opt/arm/getmovietitle.py", line 31, in getdvdtitle
    dvd_title = doc['METADATA']['MDR-DVD']['dvdTitle']
KeyError: 'dvdTitle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 71, in <module>
    disc_title = clean_for_filename(getbluraytitle())
  File "/opt/arm/getmovietitle.py", line 39, in getbluraytitle
    with open(args.path + '/BDMV/META/DL/bdmt_eng.xml', "rb") as xml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dev/sr0/BDMV/META/DL/bdmt_eng.xml'
got to here
HAS_NICE_TITLE is false
video title is now THOR
video type is unknown
Starting video_rip.sh
Video Title is THOR
Ripping video THOR from /dev/sr0
Using mkv method of ripping.
MSG:1005,0,1,"MakeMKV v1.12.2 linux(x64-release) started","%1 started","MakeMKV v1.12.2 linux(x64-release)"
DRV:0,2,999,1,"BD-ROM ATAPI iHOS104 WL0F","THOR","/dev/sr0"

**Comment by Yokopops** [comment]
Just noted some DVDs are finding names and naming the folder but file name stays like title00 is this how it is suppose to work?

Regards.

**Comment by Yokopops** [comment]
Fixed my issue, however, I cannot get V2 To work at all, it does not seem to run for some reason so any advice is appreciated.

Regards

**Comment by muckngrind4** [comment]
I can try to help you on v2. Are you still on 16.04?  Any issues during installation?

**Comment by Yokopops** [comment]
Thanks. I will attempt to reinstall V2 when my current queue has processed on the main branch. When I attempted to install V2 before I had no error codes, but whenever I inserted a DVD it never ripped, I checked processes with Htop and it seemed nothing was going on? Do I have to log into the arm user or anything to activate it? The linux version is 16.04.

Kind regards.

**Comment by muckngrind4** [comment]
A couple things to check:
Did you get an arm log when you tried ripping?  If you installed to /opt it should be in /opt/arm/log/
Also, try running it from the command line by calling "main.py -d <devname>" where the devname is the name (not path) of the optical drive.  So something like '/opt/arm/arm/main.py -d sr0'.  If it doesn't work as the arm user, try running as root.  If neither works, then check that all udev and service links are in place (the 'ln' and 'cp' commands near the end of the install guide).  

Let me know how it goes.

**Comment by Yokopops** [comment]
Thanks a lot. Will update you in a couple of days.

Kind regards.

**Comment by mattphat** [comment]
How did you get the naming to work?  I'm getting the same error in my logs
  
> identified udf as video
> failed to get title Traceback (most recent call last):
>   File "/opt/arm/getmovietitle.py", line 69, in <module>
>     disc_title = clean_for_filename(getdvdtitle())
>   File "/opt/arm/getmovietitle.py", line 31, in getdvdtitle
>     dvd_title = doc['METADATA']['MDR-DVD']['dvdTitle']
> KeyError: 'dvdTitle'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/arm/getmovietitle.py", line 71, in <module>
>     disc_title = clean_for_filename(getbluraytitle())
>   File "/opt/arm/getmovietitle.py", line 39, in getbluraytitle
>     with open(args.path + '/BDMV/META/DL/bdmt_eng.xml', "rb") as xml_file:
> FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dev/sr0/BDMV/META/DL/bdmt_eng.xml'
> got to here
> HAS_NICE_TITLE is false

**Comment by muckngrind4** [comment]
Likely the call to the windows media metaservice is failing.  You can try running it manually to see what it returns.
- Uncomment line #25 in getmovietitle.py 
- Run getmovietitle.py -p <mountpath> where <mountpath> is the full path to where your DVD is mounted.  You should get a hash printed to stdout.
- In a web browser, type this url: http://metaservices.windowsmedia.com/pas_dvd_B/template/GetMDRDVDByCRC.xml?CRC= and paste the hash you received above after the equal sign in the url.
- hit enter and you should get some xml back.  

Post the xml you received and I'll try to help after that.

**Comment by mattphat** [comment]
Sigh, I don’t know how to see sdtout.

**Comment by mattphat** [comment]
I never learnt any tricks - any tips to decipher this?

**Comment by muckngrind4** [comment]
Stdout is just the output from the program to the command line. Run the 'getmovietitle.py -p sr0' (or whatever the name of your device is) command and post what is spit back at you and I'll help decipher it.

**Comment by muckngrind4** [comment]
Drop the 'dev' part of the path. Just 'getmovietitle.py -p sr0'.   Post the output you get.

**Comment by mattphat** [comment]
Thanks - I've tunnelled home, but I can't confirm there is actually a disc in the tray, so if you're rolling your eyes, it's on me :)

This is the result : 

> Traceback (most recent call last):
>   File "getmovietitle.py", line 71, in <module>
>     disc_title = clean_for_filename(getbluraytitle())
>   File "getmovietitle.py", line 39, in getbluraytitle
>     with open(args.path + '/BDMV/META/DL/bdmt_eng.xml', "rb") as xml_file:
> IOError: [Errno 2] No such file or directory: 'sr0/BDMV/META/DL/bdmt_eng.xml'

**Comment by mattphat** [comment]
Yeah I’m sorry but there is nothing else before that output. Tried sudo in front, trying doing it after a sudo su (as root).

**Comment by mattphat** [comment]
Ok, I tried another commercial DVD and this gave me a hash code, still not printed out to the console, but in the log while it was busy running through the motions.   The other disc I knew wouldn't get the name posted a hash code that can't be found.  Guess it's just not in the database.  It's not such a big concern, I do know what the disc is called when I put it in... and the auto created media folders give it the disc name, close enough.

I'll undo the un-comment of line # 25 and see how we go from there.  Noticed that with a known disc it still hasn't actually named the file or moved it to the movies folder.  (well, it has named it - the same as the hash code).

Thanks so much for your patience!

**Comment by muckngrind4** [comment]
Ok. Thanks for the update.
