### ISSUE TITLE
V2 issues

### ISSUE THREAD

**Issue by emmakat** [automatic-ripping-machine/automatic-ripping-machine#165]
### Description
[V2 just doesn't work for me. I've installed it line by line with no errors on a fresh 16.04 ubuntu server. the instructions are missing verbose instructions, such as whether to login as arm, etc, what to do after reboot, etc,. there is no /opt/arm/log/ at all  and nothing happens when i put in a disk. It would be helpful to have a rollback method, or a way to get my system to v1 without formatting and starting over. Any advice is appreciated}

### Log file
[Contents of log files under /opt/arm/logs]

### Config file
[Contents of your /opt/arm/config file]

### Environment
[Ubuntu 16.04 xenial")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

**Comment by muckngrind4** [comment]
Hi @emmakat.  I'm running a full install and will update the instructions and get back to you with what I find.

**Comment by muckngrind4** [comment]
I've just completed an 18.04 install and updated the README.  You can find it under the v2_18.04 branch.  It should work for 16.04 also.  For changes check out the diff here: 
https://github.com/automatic-ripping-machine/automatic-ripping-machine/commit/11909c5efc7d6d71c5775d3b8e122b2d9ea7f2ea#diff-04c6e90faac2675aa89e2176d2eec7d8 
I still need to refine it, but there were a few steps missing that are now included.  I will test it on 16.04 in the next few days.

**Comment by muckngrind4** [comment]
I've updated the README here: [https://github.com/automatic-ripping-machine/automatic-ripping-machine/tree/v2_master](url) Take a look at it and see if it helps.

**Comment by Yokopops** [comment]
Link returns a 404 error. however, I just went into the v2 build the normal way. Posting corrected link for reference if anyone needs it: [](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/v2_master/README.md) Going to attempt to reinstall v2 and will let you know how I get on.

Kind regards

**Comment by muckngrind4** [comment]
Thanks @Yokopops! I've updated the link in my comment also...

**Comment by Yokopops** [comment]
No problem just trying to help! By the way, should I attempt a full fresh install or swap from v1?
