### ISSUE TITLE
Install directions incorrectly id /root/.MakeMKV as settings dir

### ISSUE THREAD

**Issue by Spinningbull** [automatic-ripping-machine/automatic-ripping-machine#179]
### Description
[Description of Bug, Feature, Question, etc.]
In the new version - the settings.conf file and key_hashed.txt file need to be placed in /home/arm/.MakeMKV/ not /root/.MakeMKV

took me awhile to figure out what was going on.

### Log file
[Contents of log files under /opt/arm/logs]

### Config file
[Contents of your /opt/arm/config file]

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

**Comment by muckngrind4** [comment]
Thanks @Spinningbull.  Good catch.  I've updated the instructions.

**Comment by muckngrind4** [comment]
Fixed in #181
