### ISSUE TITLE
Duplicate kernel events when inserting disc causing ARM to run twice

### ISSUE THREAD

**Issue by jaffee** [automatic-ripping-machine/automatic-ripping-machine#202]
### Description
I got ARM working after a bit of difficulty, was able to rip a few discs, then they stopped working properly. Long story short, the kernel seems to be firing two events when I insert a DVD which is causing two ARM jobs to get fired for the same device which causes a variety of havoc.

Here is udevadm monitor showing the duplicated events.
```
# udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[18803.960118] change   /devices/pci0000:00/0000:00:01.1/ata1/host0/target0:0:0/0:0:0:0/block/sr0 (block)
KERNEL[18804.070848] change   /devices/pci0000:00/0000:00:01.1/ata1/host0/target0:0:0/0:0:0:0/block/sr0 (block)
UDEV  [18805.041536] change   /devices/pci0000:00/0000:00:01.1/ata1/host0/target0:0:0/0:0:0:0/block/sr0 (block)
UDEV  [18805.690674] change   /devices/pci0000:00/0000:00:01.1/ata1/host0/target0:0:0/0:0:0:0/block/sr0 (block)
```

I'm running Ubuntu 16.04 in VirtualBox on Windows Server 2016 Essentials.

I realize this probably isn't directly related to ARM, but I think ARM can probably work around it and I may try to submit a patch. What's odd to me is that the problem occurred several times, then stopped for a few discs, and now is occurring again.

### Log file
Here is a snippet - you can see how lots of lines are duplicated:

```
identified udf
found O200NNW1 on /dev/sr0
identified udf as video
identified udf as video
Obtained Title Oliver and Company (2009)
Obtained Title Oliver and Company (2009)
got to here
HAS_NICE_TITLE is true
video title is now Oliver and Company (2009)
video type is movie
got to here
HAS_NICE_TITLE is true
video title is now Oliver and Company (2009)
video type is movie
Starting video_rip.sh
Video Title is Oliver and Company (2009)
Ripping video O200NNW1 from /dev/sr0
Using mkv method of ripping.
Starting video_rip.sh
Video Title is Oliver and Company (2009)
Ripping video O200NNW1 from /dev/sr0
Using mkv method of ripping.
MSG:1005,0,1,"MakeMKV v1.12.2 linux(x64-release) started","%1 started","MakeMKV v1.12.2 linux(x64-release)"
MSG:1005,0,1,"MakeMKV v1.12.2 linux(x64-release) started","%1 started","MakeMKV v1.12.2 linux(x64-release)"
DRV:0,2,999,1,"DVD+R-DL VBOX CD-ROM 1.0","O200NNW1","/dev/sr0"
DRV:1,256,999,0,"","",""
```

It's the same with systemd events in syslog.

### Config file

Not relevant I don't think given that the issue is with the kernel firing multiple events for a single change.

### Environment
I'm running Ubuntu 16.04 in VirtualBox on Windows Server 2016 Essentials.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

ARM: master a3da71279b8c438b451619f4470557d77d16506f

P.S. thanks for ARM - it's awesome!

**Comment by muckngrind4** [comment]
Are the two events simultaneous?  Or is one firing after a long time out?  If you're feeling up to it. You can try the v2_master branch. It's a rewrite and uses udev differently. I don't know if it would fix the problem but might be worth a try.  If you'd like to submit a patch (and feel free to do so) I'd suggest doing it against the v2 codebase. That is the codebase we will be developing going forward.

**Comment by jaffee** [comment]
The two events are simultaneous, there is no perceptible delay between them. As you can see from `udevadm monitor` output, the two kernel events fire right in a row before udev has a chance to respond to either of them, then the two udev events fire. On eject, only one kernel and one udev event fire.

I have a fairly strong hunch that this is a hardware or virtualization issue, so I'm going to try patching what I've got first. I realized last night that there was a v2 branch ahead of master, but the setup process looked a bit more burdensome (albeit more correct, not running under root is nice). If I get a chance this weekend, I'll spin up a fresh VM and give that a shot too. 

Thanks!
