### ISSUE TITLE
Optical Drive IO issues

### ISSUE THREAD

**Issue by fabltd** [automatic-ripping-machine/automatic-ripping-machine#211]
Hi All

The main console out is displaying:

print_req_error: I/O error, dev sr0, sector 14293504
Buffer I/O error pm dev sr0, logical block 3573376, async page read

When disc is first inserted.

Thanks

**Comment by muckngrind4** [comment]
Does it still run ARM? These tend to be disc or drive issues. I'm curious to know if ARM was still launched and ran.

**Comment by fabltd** [comment]
yes ARM still launched and ran. Happens with all discs. Any idea how to mute these?

**Comment by Plexen85** [comment]
I had a similar issue with arm when make mkv was was outdated and needed to be upgraded to the latest version. Arm would just take disc create and empty folder for all discs. I didn’t realize the problem was that until my windows pc prompted me to upgrade its version.

**Comment by muckngrind4** [comment]
I don't know how to mute these.  It's not coming from ARM, so I'd guess it's function of the kernel/OS, or as @Plexen85 says, from MakeMKV.  If ARM is running OK then the only option might be to ignore them...

**Comment by fabltd** [comment]
Hi

@Plexen85  Checked have the latest version 1.12.2-1

Will try the disable.

JT
