### ISSUE TITLE
Ripped and trans coded media not moving

### ISSUE THREAD

**Issue by lohannes** [automatic-ripping-machine/automatic-ripping-machine#216]
### Description
I have an issue where all of my media goes to /home/arm/abcde.**** instead of /mnt/WindowsShare/Final like specified in the config file. 

### Environment
Ubuntu Server 16.04 LTS

### Log file
Logs show everything ripping and trans coding successfully. Is there a simple config change I made that messed everything up?

**Comment by muckngrind4** [comment]
Hi @lohannes Do you have Mainfeature=True in your config?  Also, if you can drag and drop a log file I can look through it to understand what path ARM took and determine if there is a config entry that needs to be changed or if there is a bug in the logic.

**Comment by lohannes** [comment]
Mainfeature is true, I scrubbed through the logs and this seems to be the issue. Is there something wrong with my mount? If so, how do I fix it?
**mkdir: cannot create directory ‘/mnt/media’: Permission denied
touch: cannot touch '/mnt/media/ARM/emby/music//flac/Various Artists/Living In $
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$
/usr/bin/abcde: line 1727: /mnt/media/ARM/emby/music//flac/Various Artists/Livi$**

**Comment by lohannes** [comment]
I solved it, I had SMB version 1.1 instead of SMB 3.0
