### ISSUE TITLE
Is there a way to keep raw DVD (and blu-ray) files after transcoding?

### ISSUE THREAD

**Issue by ThisGuyYouKnow** [automatic-ripping-machine/automatic-ripping-machine#222]
### Description
I'm trying to find a way to keep the raw DVD and Blu-ray ripped files after transcoding.  I've gone through most of the scripts, but it is eluding me what may be commented out to do so.  Am I missing something obvious?  My backup plan is just to change SKIP_TRANSCODE=false to "true" and run handbrake manually, but it sure is easier to just delete the few raw (and occasionally just the transcoded) files as preferred.

### Environment
Ubuntu 16.04.05
arm v1.3.0

### Log file
N/A

**Comment by ThisGuyYouKnow** [comment]
Okay, so this appears to be a duplicate of issue #99 ( https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/99 ).  I'm going to try the suggested commenting outs.  Maybe make this a feature request?

**Comment by ThisGuyYouKnow** [comment]
Accidentally closed.  Commented out six lines starting with either "rm" or "rmdir" in video_transcode.sh .

**Comment by muckngrind4** [comment]
Thanks for updating the issue @ThisGuyYouKnow, For others on v2, there is a config (DELRAWFILES) that will accomplish this.
