### ISSUE TITLE
V2_master cannot rip music cds

### ISSUE THREAD

**Issue by Yokopops** [automatic-ripping-machine/automatic-ripping-machine#225]
Hi, Just attempted to rip a music cd (Never tried before) and it just ejects it after a few moments, probably overlooking some setting or something. Log attached

[music_cd.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2250868/music_cd.log)

**Comment by emmakat** [comment]
Looks like permissions issue: “mkdir: cannot create directory â€˜/mnt/media/ARMâ€™: Permission denied  “

**Comment by muckngrind4** [comment]
Check and make sure your arm user has write permissions to /mnt/media/ARM.  I think abcde is trying to make a subdirectory in /mnt/media/ARM based on your settings in your .abcde config file.

**Comment by Yokopops** [comment]
All sorted just manually made the folder required. Cheers peeps.
