### ISSUE TITLE
Media depositing to /Emby/Media instead of the specified completed folder

### ISSUE THREAD

**Issue by lohannes** [automatic-ripping-machine/automatic-ripping-machine#228]
### Description
Automatic Ripping Machine is depositing the completed, encoded flac files to /mnt/media/ARM/emby/music/flac instead of /mnt/media/ARM/Completed, as specified in the config file. Did I miss a simple config change?

### Environment
Ubuntu Server 18.04

I can post logs if needed, but I assume its a config change I missed?

**Comment by emmakat** [comment]
checking you Edited the music config file (located at /home/arm/.abcde.conf)?
