### ISSUE TITLE
abcde: cannot create Temp directory

### ISSUE THREAD

**Issue by robertoweij** [automatic-ripping-machine/automatic-ripping-machine#237]
Hi There,

### Description
abcde logs in /home/arm/logs/music_cd.log:
mkdir: cannot create directory `//abcde.xxxx` : Permission denied

running abcde in the shell as user arm from /home/arm performs as expected.

### Environment
Ubuntu 16.04.5 LTS
latest release

### Log file
Executing customizable pre-read function... done.
Getting CD track info... Querying the CD for audio tracks...
Grabbing entire CD - tracks: 01 02 03 04 05 06 07 08 09 10 11 12 13
mkdir: cannot create directory ‘//abcde.d310b50d’: Permission denied
abcde: Temp directory //abcde.d310b50d could not be created.
[2018-08-11 21:09:06] ERROR ARM: Call to abcde failed with code: 1(b'')
[2018-08-11 21:09:06] INFO ARM: Music rip failed.  See previous errors.  Exiting

**Comment by muckngrind4** [comment]
Hi @robertoweij. Can you drag and drop your full music_cd.log file here?  Also the 
.abcde.conf file in the /home/arm/ path?

**Comment by robertoweij** [comment]
Hi Derek,

Here are the files.

[music_cd.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2280829/music_cd.log)

[_abcde.conf.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2280833/_abcde.conf.txt)

**Comment by muckngrind4** [comment]
Thanks guys. I'll do some testing and see what I find.

**Comment by muckngrind4** [comment]
FYI  I've found the issue and should have a fix up in a day or two.
