### ISSUE TITLE
Problems with install @: cp /opt/arm/arm@.service /etc/systemd/system/

### ISSUE THREAD

**Issue by Spartan-Sec** [automatic-ripping-machine/automatic-ripping-machine#239]
### Description
Running: 
**cp /opt/arm/arm@.service /etc/systemd/system/**

yields:
**cp: cannot stat '/opt/arm/arm@.service': No such file or directory**

ls on /opt/arm yields:
**root@ubuntu:/opt/arm# ls
arm          CONTRIBUTING.md          LICENSE          scripts
armui         db         README.md          setup 
build         docs          requirements.txt          setup.cfg 
CHANGELOG.md          ISSUE_TEMPLATE.md          runui.py          VERSION **

It appears that the file arm@.service is not in the path /opt/arm/ according to both the error and the results of ls.

The only other error I am getting during the install process is: 
**Err:8 http://ppa.launchpad.net/mc3man/xerus-media/ubuntu bionic Release       
  404  Not Found [IP: 91.189.95.83 80]**
as a result of:
**sudo apt update** 
and
**sudo add-apt-repository ppa:mc3man/xerus-media**

The only deviations from the instructions listed here:
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/master/README.md

are 2 additional commands that I found in another issue thread:
https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/156

Here are the commands I have entered (note: modifications mentioned above are in bold):

sudo   apt-get install git
sudo add-apt-repository   ppa:heyarje/makemkv-beta
sudo add-apt-repository   ppa:stebbins/handbrake-releases
sudo add-apt-repository   ppa:mc3man/xerus-media
sudo apt update
sudo apt install makemkv-bin   makemkv-oss
sudo apt install handbrake-cli   libavcodec-extra
sudo apt install abcde flac   imagemagick glyrc cdparanoia
sudo apt install at
sudo apt install python3   python3-pip
sudo apt-get install   libdvd-pkg
sudo dpkg-reconfigure   libdvd-pkg
sudo su
cd /opt
git clone   https://github.com/automatic-ripping-machine/automatic-ripping-machine.git   arm
cd arm
**sudo apt-get install libcurl4-openssl-dev**
**sudo apt-get install libssl-dev**
pip3 install -r   requirements.txt
ln -s   /opt/arm/51-automedia.rules /lib/udev/rules.d/
ln -s /opt/arm/.abcde.conf   /root/
cp /opt/arm/arm@.service   /etc/systemd/system/ *(error occurs following this command)*
cp config.sample config

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Ubuntu 18.04.1 LTS

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
v2_master

commit 8190e8d1ff8ccb5e26b7d418c66e4597faeef6f9 (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: b6a0228 3cb5b6f
Author: Derek <22111345+muckngrind4@users.noreply.github.com>
Date:   Sat Aug 11 10:03:24 2018 -0700

    Merge branch 'v2.1_dev' into v2_master

### Log file
N/A

**Comment by muckngrind4** [comment]
Hi @Spartan-Sec, A couple of notes.  The readme you are looking at is not for the current branch.  Additionally, we just fixed an issue with v2_master (the current master), so you'll want to update your v2_master branch and then check out the current readme.  Here are the steps I'd recommend:

`git checkout v2_master` (probably not needed but can't hurt)
`git pull`

Follow the readme located [here](https://github.com/automatic-ripping-machine/automatic-ripping-machine)

You'll be repeating parts of the install, but it won't hurt anything.  Post back if you have any issues.

**Comment by Spartan-Sec** [comment]
@muckngrind4  - thanks for the reply!  I'll poke at this later tonight (or maybe earlier, if I'm sneaky).

Will update w/ results.

**Comment by Spartan-Sec** [comment]
@muckngrind4 
That seems to have worked.  Thanks.  

I'm assuming at this point that the install has completed successfully.  I modified arm.yaml to my preferred output.  Dropped a disc in, but it doesn't appear to be doing anything.  Research continues.
