### ISSUE TITLE
Using title for TV shows is bad

### ISSUE THREAD

**Issue by altano** [automatic-ripping-machine/automatic-ripping-machine#243]
Using the title for folder/file naming might work for movies, but for TV shows it is a mess. For example, if I rip 4 discs of Cosmos and they are all named Cosmos, I have no way of organizing the resulting files. The disc names (e.g. COSMOS_DISC1, COSMOS_DISC2) are actually a much better starting point.

I've actually edited identify.sh to change `VIDEO_TITLE=${GET_TITLE_OUTPUT}` to `VIDEO_TITLE="${GET_TITLE_OUTPUT}_${ID_FS_LABEL}"`. This works just fine for movies (you get the nice title in the resulting file name) but it works for TV shows too (you can easily identify each part of the season).

Shall I submit this as a PR?

**Comment by muckngrind4** [comment]
Hmm...  I've had some tv shows where every disc is named the exact same thing--and some where every disc is named "dvd-video".  I think using the disc lable would cause naming conflicts in those cases.  What we've tried to implement is a timestamp to ensure uniqueness between discs as it seems to be the only sure way to handle it...

TV shows are a pain in the neck, that is for sure...

**Comment by altano** [comment]
Right, that’s why combining the title and the disc label works well. One of the two is usually descriptive enough. And the timestamps in case of conflict are great but since I rip multiple discs at once, I can’t use the time stamp to figure out disc number/order.

The change I mentioned above works really well for me in all cases I’ve seen.

**Comment by RickB1974** [comment]
Where can i find the Identify.sh file? I would like to try this change. I have a lot of TV series to rip and the current naming convention is very confusing.

**Comment by altano** [comment]
It looks like there is a new v2 that has been released and represents master. If I switch to the v1.4.0 tag I can see identify.sh in the root dir: https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/v1.4.0/identify.sh

I don’t know where the analogous logic is in the v2 branch but hopefully that can give you a lead for investigating.

good luck!
