### ISSUE TITLE
Upgraded to v2 and I am having noob issues with permissions denied

### ISSUE THREAD

**Issue by Plexen85** [automatic-ripping-machine/automatic-ripping-machine#244]
### Description
Upgraded to v2 and I am having noob issues with permissions denied I granted arm rights to the folder and all users with cmod but I'm obviously missing something

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[2018-08-14 20:08:41] ERROR ARM: Couldn't create a directory at path: /media/<user>/Raw/unidentified/Ronin/ Probably a permissions error.  Exiting

**Comment by Plexen85** [comment]
Ubuntu 18.04, sorry left that off.

**Comment by Plexen85** [comment]
I just confirmed that if I move back to the folders in the default conf file I have no issues with permissions. the folders I am trying to use are not on the os drive but a secondary drive. do I need to add an ftab entry? I dont see any other way to open the folders up in regards to cmod or gui edits to permissions.

**Comment by muckngrind4** [comment]
I don't know your situation exactly, but I'm writing to an external NAS and I do need an entry in my fstab.

Did it work on v1 but not v2?  If it worked on v1 but not v2, then it may be that you need to grant the 'arm' user write access to the directory.

**Comment by Plexen85** [comment]
It did work in v1. I’m most likely doing something wrong on my end. I will look into adding arm to the user group that owns
The folder. Not sure why adding cmon and granting read write permissions to all users didn’t do the trick.

**Comment by Plexen85** [comment]
I’m going to do a freash install with one hard disk with default config. Think that will resolve my permissions issue. And then I can research the logs as to why when doing DVDs eject is not working but cds are. I’m sure it will be great upgrade once I figure it out. What is the default web address for the queue?

**Comment by Plexen85** [comment]
Well think I am beyond my noob issue here on permissions denied. sorry to have bothered. Fixed a majority of my issues by running the following commands: 

sudo mkdir /mnt/media/
sudo chown arm:arm /mnt/media/

Arm was working but it kept erroring on permissions for Umbutu  18.04

**Comment by Plexen85** [comment]
last issue is when after dvd is complete it is not ejecting. But cds are. What could be the cause of this?
