### ISSUE TITLE
DVD won't mount, ripping aborted - see issue #235

### ISSUE THREAD

**Issue by mg-man** [automatic-ripping-machine/automatic-ripping-machine#246]
Sorry for opening another issue, but I don't seem to be able to re-open the original.  I've tried the suggested 'fix' - which didn't work.  See comments I've added to the Closed Issue.  Thx.

**Comment by muckngrind4** [comment]
Hi @mg-man, I've reopend #235.  I'm going to close this one so that all comments stay with the original issue.
