### ISSUE TITLE
EMail Notification Support Removed in v2?

### ISSUE THREAD

**Issue by JSylvia007** [automatic-ripping-machine/automatic-ripping-machine#247]
### Description
I wrote some things for v1 and got email notifications encorporated, but it looks like these were removed in v2.  Was there a specific reason for this?  Are there plans to add it back in?

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
v2_master
commit 3f40908a32c265d548857cc7d9eb4f0d72f2099b (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: 1ed41eb b64bbf0
Author: Derek <22111345+muckngrind4@users.noreply.github.com>
Date:   Mon Aug 13 23:54:26 2018 -0700

    Merge pull request #241 from automatic-ripping-machine/v2_fixes

    Added -l option to su in arm_wrapper.  Fixes #237

### Log file
Not needed...

**Comment by JSylvia007** [comment]
@muckngrind4 this is good news!  If you look at some of my pull requests from v1, you can see how we did it back then.

**Comment by 1337-server** [comment]
Feature is in V2 via apprise/postfix
