### ISSUE TITLE
ARM stops itselve

### ISSUE THREAD

**Issue by cyni0s** [automatic-ripping-machine/automatic-ripping-machine#254]
### Description
When CD is inserted. ABCDE doesn't start. Instead it stops turning in the drive and does nothing.

### Environment
- Ubuntu 18.04.1 LTS
- v2_master
(Merge pull request #241 from automatic-ripping-machine/v2_fixes, Added -l option to su in arm_wrapper.  Fixes #237)

### Log file

- no logfile created by this

- Syslog:
   Oct  6 19:06:05 arm ARM: Starting ARM on sr0
   Oct  6 19:06:05 arm systemd[1]: Created slice User Slice of arm.
Oct  6 19:06:05 arm systemd[1]: Starting User Manager for UID 1001...
Oct  6 19:06:05 arm systemd[1]: Started Session c50 of user arm.
Oct  6 19:06:05 arm systemd[24413]: Reached target Timers.
Oct  6 19:06:05 arm systemd[24413]: Listening on GnuPG cryptographic agent and passphrase cache.
Oct  6 19:06:05 arm systemd[24413]: Listening on GnuPG network certificate management daemon.
Oct  6 19:06:05 arm systemd[24413]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Oct  6 19:06:05 arm systemd[24413]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Oct  6 19:06:05 arm systemd[24413]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Oct  6 19:06:05 arm systemd[24413]: Reached target Sockets.
Oct  6 19:06:05 arm systemd[24413]: Reached target Paths.
Oct  6 19:06:05 arm systemd[24413]: Reached target Basic System.
Oct  6 19:06:05 arm systemd[24413]: Reached target Default.
Oct  6 19:06:05 arm systemd[24413]: Startup finished in 79ms.
Oct  6 19:06:05 arm systemd[1]: Started User Manager for UID 1001.
Oct  6 19:06:05 arm systemd[1]: Stopping User Manager for UID 1001...
Oct  6 19:06:05 arm systemd[24413]: Stopped target Default.
Oct  6 19:06:05 arm systemd[24413]: Stopped target Basic System.
Oct  6 19:06:05 arm systemd[24413]: Stopped target Timers.
Oct  6 19:06:05 arm systemd[24413]: Stopped target Sockets.
Oct  6 19:06:05 arm systemd[24413]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Oct  6 19:06:05 arm systemd[24413]: Closed GnuPG network certificate management daemon.
Oct  6 19:06:05 arm systemd[24413]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Oct  6 19:06:05 arm systemd[24413]: Closed GnuPG cryptographic agent and passphrase cache.
Oct  6 19:06:05 arm systemd[24413]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Oct  6 19:06:05 arm systemd[24413]: Stopped target Paths.
Oct  6 19:06:05 arm systemd[24413]: Reached target Shutdown.
Oct  6 19:06:05 arm systemd[24413]: Starting Exit the Session...
Oct  6 19:06:05 arm systemd[24413]: Received SIGRTMIN+24 from PID 24432 (kill).
Oct  6 19:06:05 arm systemd[1]: Stopped User Manager for UID 1001.
Oct  6 19:06:05 arm systemd[1]: Removed slice User Slice of arm.

**Comment by muckngrind4** [comment]
Hi @cyni0s. Try executing the arm_wrapper.sh script using `python3 /opt/arm/scripts/arm_wrapper.sh sr0`

**Comment by cyni0s** [comment]
Hi muckngrind4. 
When I execute this command using bash I get no output.

Syslog just says:
- arm ARM: Starting ARM on sr1
