### ISSUE TITLE
Encoding issue.

### ISSUE THREAD

**Issue by Yokopops** [automatic-ripping-machine/automatic-ripping-machine#255]
Opened new issue as requested. The extras seem to encode correctly however the main movie is just a 3kb file. Before your last fix it worked without issue?

**Comment by muckngrind4** [comment]
Hi @Yokopops.  Does this happen on all dvd's?  Can you provide a log for a different dvd?

**Comment by Yokopops** [comment]
Seem to only do it on that DVD. The other one worked after a second try, will open another issue if I come across it again. Strange how this DVD ripped fine before but now it puts it into the right folder it wont work. Another quick question before I close the case, will this system name episodes in a series or not?

**Comment by muckngrind4** [comment]
No it won't. Unfortunately there isn't a CDDB type data source that maps series episodes to tracks on the DVD, so there is no way to do it without human intervention. I'm working on a UI that will allow you to interact with arm so you can do these types of things. The first iteration will be aimed at renaming unidentifiable/misidentified movie.  Hopefully I'll have this ready in the next couple of months.  After that will be a feature to will walk a user through identifying series episodes.
