### ISSUE TITLE
Strange issues with encoding?

### ISSUE THREAD

**Issue by Yokopops** [automatic-ripping-machine/automatic-ripping-machine#256]
Every time I put a DVD into the drive it appears to encode from the DVD as it is not ejecting from the drive untill it has finished, the other issue is it is placing the main movie file into the Extras folder and naming it "Title_01.mkv". Any help would be appreciated! 
[SPIDERMAN.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2475917/SPIDERMAN.log)

**Comment by Yokopops** [comment]
[STAR_TREK__INTO_DARKNESS.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2475919/STAR_TREK__INTO_DARKNESS.log)

Another log. This one is strange it appears to have encoded the movie 3 times (Into the extras folder again) they are all the same play length, however, they have slight file size diffrences 1,349,202, 1,349,217 and 1,349,218

**Comment by muckngrind4** [comment]
Hi @Yokopops.  You have Main feature = false in your config. Change it to true and give it a run.

**Comment by Yokopops** [comment]
Ah will give it a shot, don't know how that got changed! Will get back to you.

**Comment by Yokopops** [comment]
Just tried a rip and it is still encoding from the disc rather than eject to make a queue?

**Comment by Yokopops** [comment]
@muckngrind4 I have gone over the config files and unless I missed something, there is a problem someplace? it was working before with Main feature = false also.

**Comment by mg-man** [comment]
I've been using ARM since 1.x and have recently started playing with v2 and now v2.1_dev... in both v2 and v2.1_dev, I have the same behaviour.  The process seems to run in two passes, but the first pass doesn't seem to create a 'raw' file... and then [like the OP] the second pass (encode) runs from the DVD... I've tried Main Feature = true and false, and have even reinstalled fresh...

**Comment by mg-man** [comment]
OK... I've experimented some more, and had a look at the code... the '2 passes' I see appear to both come from handbrake - I'm guessing the default is a two-pass encode?  If so, there doesn't seem to be any combination of 'backup' / 'mkv' and Main feature = 'true' / 'false' that will result in a 'rip' of the DVD to the ../raw directory - and for handbrake to pick that up and encode from that (thereby releasing the DVD drive for another rip while the encoding happens)?
