### ISSUE TITLE
Failed to load JVM library

### ISSUE THREAD

**Issue by thri1hous** [automatic-ripping-machine/automatic-ripping-machine#259]
### Description
[Description of Bug, Feature, Question, etc.]
it seems like most blue rays and dvd movies dont get IDed and stay in the unidentified folder
looking at the logs for blue ray movies i found this line 
bdj.c:689: BD-J check: Failed to load JVM library
maybe this is a different issue entirely but i thought it was something we could look into. 
i have the default-jre-headless installed so im not sure what would be causing this.
ill keep eye on other blue ray logs and update this with new information 

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
`bdj.c:689: BD-J check: Failed to load JVM library`
This is now a standard message/soft error that MakeMKV always outputs according to the MakeMKV forums
