### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by WTaylorA** [automatic-ripping-machine/automatic-ripping-machine#263]
### Description
atp install dependencies broken

### Environment
Ubuntu 18.x (headless)

Not even making it as far as pulling the files from GIT.  Most of the "apt install" lines produce broken dependency issues.

* sudo apt install makemkv-bin makemkv-oss
* sudo apt install handbrake-cli libavcodec-extra
* sudo apt install abcde flac imagemagick glyrc cdparanoia
sudo apt install at
sudo apt install python3 python3-pip
* sudo apt-get install libcurl4-openssl-dev libssl-dev
* sudo apt-get install libdvd-pkg
* sudo dpkg-reconfigure libdvd-pkg
sudo apt install default-jre-headless

All marked with a "*" were broken on a clean, fresh 18.03 server build last night.  Can attach exact errors if needed when I'm at home.  Have any of the required packages changed recently?

**Comment by akasoggybunz** [comment]
Is there a fix or work around for this? I am also experiencing this.

**Comment by cclarke591** [comment]
Same here.

**Comment by burkeyc** [comment]
same: 
The following packages have unmet dependencies:
 makemkv-oss : Depends: libavcodec57 (>= 7:3.4.4) but it is not going to be installed or
                        libavcodec-extra57 (>= 7:3.4.4) but it is not going to be installed
               Depends: libavutil55 (>= 7:3.4.4) but it is not going to be installed
               Depends: libqt4-dbus (>= 4:4.5.3) but it is not installable
               Depends: libqtcore4 (>= 4:4.8.0) but it is not installable
               Depends: libqtgui4 (>= 4:4.5.3) but it is not installable
E: Unable to correct problems, you have held broken packages.

The following packages have unmet dependencies:
 makemkv-oss : Depends: libavcodec57 (>= 7:3.4.4) but it is not going to be installed or
                        libavcodec-extra57 (>= 7:3.4.4) but it is not going to be installed
               Depends: libavutil55 (>= 7:3.4.4) but it is not going to be installed
               Depends: libqt4-dbus (>= 4:4.5.3) but it is not installable
               Depends: libqtcore4 (>= 4:4.8.0) but it is not installable
               Depends: libqtgui4 (>= 4:4.5.3) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jobridts** [comment]
I solved this by adding this to /etc/apt/sources.list

deb http://archive.ubuntu.com/ubuntu bionic universe multiverse
deb-src http://archive.ubuntu.com/ubuntu bionic universe multiverse

deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
deb-src http://us.archive.ubuntu.com/ubuntu/ bionic universe
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe
deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe

deb http://us.archive.ubuntu.com/ubuntu/ bionic multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates multiverse

deb http://security.ubuntu.com/ubuntu bionic-security universe
deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse

**Comment by cclarke591** [comment]
Can confirm, @jobridts solution works for this issue.

**Comment by 1337-server** [comment]
Assuming this is now resolved
