### ISSUE TITLE
V2.0.1 stable: abcde doesn't rip -permission issue

### ISSUE THREAD

**Issue by keiem** [automatic-ripping-machine/automatic-ripping-machine#266]
### Description
When you insert a music cd it detects the cd but abcde can't rip because it can't create a temp directory.  It's just a permission issue but I don't know where abcde wants to make the temp directory.

### Environment
Ubuntu 18.04.1
ARM V2.0.1 stable

### Log file
[music_cd.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2634847/music_cd.log)

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by blahdidbert** [comment]
Wanted to leave a comment and confirm I am now experiencing the same thing. Here is a snippet of my logs as well:

-----

    [2019-01-12 21:24:30] INFO ARM: utils.rip_music Disc identified as music
    [2019-01-12 21:24:30] DEBUG ARM: utils.rip_music Sending command: abcde -d "/dev/sr0" >>     "/home/arm/logs/music_cd.log" 2>&1
    CDDB method 0: cddb
    Executing customizable pre-read function... done.
    Getting CD track info... Querying the CD for audio tracks...
    Grabbing entire CD - tracks: 01 02 03 04 05 06 07 08 09 10 11 12
    Trying CDDB method cddb.
    Checking CDDB server status...
    Querying the CDDB server...
    Obtaining CDDB results...
    Retrieving 1 CDDB match...done.
    ---- Avenged Sevenfold / Waking The Fallen ----
    1: Waking The Fallen
    2: Unholy Confessions
    3: Chapter Four
    4: Remenissions
    5: Desecrate Through Reverance
    6: Eternal Rest
    7: Second Heartbeat
    8: Radiant Eclipse
    9: I Won't See You Tonight (Part 1)
    10: I Won't See You Tonight (Part 2)
    11: Clairvoyant Disease
    12: And All Things Will End
    
    Selected: #1 (Avenged Sevenfold / Waking The Fallen)
    Edit selected CDDB data [y/N]? 
    Is the CD multi-artist [y/N]? n
    Creating playlist...
    mkdir: cannot create directory ‘/mnt/media’: Permission denied
    touch: cannot touch '/mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u': No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The     Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    /usr/bin/abcde: line 1771: /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/Waking The Fallen.m3u: No such file or directory
    trying to get cover with glyrc for Avenged Sevenfold / Waking The Fallen
    - Artist   : avenged sevenfold
    - Album    : waking the fallen
    - Language : us
    - Type     : cover
    
    ---- Triggering: musictree local coverartarchive 
    #[00/01] Checking image-types: [- DLError: Couldn't resolve host name [6]
    - DLError: Couldn't resolve host name [6]
    !- DLError: Couldn't resolve host name [6]
    !!] (-3 item(s) less)
    ---- Triggering: lastfm jamendo musicbrainz 
    #[00/01] Checking image-types: [.] (-0 item(s) less)
    ---- 
    [0;34m
    ///// ITEM #1 /////
    [0mWRITE to '/home/arm/abcde.a610170c/cover.jpg'
    FROM: <https://lastfm-img2.akamaized.net/i/u/300x300/9c152f2f534b449388423c6383f9492d.png>
    PROV: lastfm
    SIZE: 49134 Bytes
    MSUM: aba4bee6327f5727656931de97356b7f
    TYPE: cover
    SAFE: No
    RATE: 0
    STMP: 0.000000
    FRMT: png
    DATA: <not printable>
    [0;34m
    ////////////////////
    [0m[0;33m# => 1 item in total.
    [0mcopying cover to target directory /mnt/media/ARM/emby/music//flac/Avenged     Sevenfold/Waking The Fallen
    mkdir: cannot create directory ‘/mnt/media’: Permission denied
    cp: cannot create regular file '/mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The     Fallen': No such file or directory
    Grabbing track 01: Waking The Fallen...
    cdparanoia III release 10.2 (September 11, 2008)
        
    Ripping from sector       0 (track  1 [0:00.00])
    	  to sector    7674 (track  1 [1:42.24])

    outputting to /home/arm/abcde.a610170c/track01.wav



    Done.


    echo Encoding track 01 of 12: Waking The Fallen...
    Encoding track 01 of 12: Waking The Fallen...
    encodetrack-flac-01 nice -n 10 flac -f -s -e -V -8 --replay-gain -o /home/arm/abcde.a610170c/track01.flac /home/arm/abcde.a610170c/track01.wav
    encodetrack-01 true
     echo Tagging track 01 of 12: Waking The Fallen...
    Tagging track 01 of 12: Waking The Fallen...
    tagtrack-flac-01 nice -n 10 metaflac --no-utf8-convert --import-tags-from=- /home/arm/abcde.a610170c/track01.flac
    tagtrack-01 true
    mkdir: cannot create directory ‘/mnt/media’: Permission denied
    movetrack-01 mv /home/arm/abcde.a610170c/track01.flac /mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/01.Waking The Fallen.flac
    mv: cannot move '/home/arm/abcde.a610170c/track01.flac' to '/mnt/media/ARM/emby/music//flac/Avenged Sevenfold/Waking The Fallen/01.Waking The Fallen.flac': No such file or directory
    movetrack-output-flac true

-----

As a stop gap for the error at hand (still not sure if this really fixed the issue (will know more tomorrow), I created a directory in the path it was wanting and assigned it ownership and modifiers.   
In my case above, it could not create folders in /mnt/media/, so I created that directory:  
    sudo mkdir /mnt/media/
Assigned it to the arm group:  
    sudo chown arm:arm /mnt/media/
And then gave it the same modifiers from the initial install:  
    sudo chmod 775 /mnt/media/

This had no effect.

**Comment by blahdidbert** [comment]
I **think** I figured out this issue. The problem lies in that the base configuration and the base directions do not specify any particular modifications that need to occur in the `/opt/arm/setup/.abcde.conf` file (or the symlinked on in `/home/arm/`). 

On line 66, the user needs to place this final output directory as a location that ARM has permissions to read and write too (775) for **music media** as it is not defined in the `arm.yaml` file. Due to some reason, this directory structure can only be two directories deep before needing that permission granted. For example, `/home/arm/Music` should be the default directory in this file, but if a user wants to have the final output on another drive or SMB share, then ARM needs permissions to that directory two levels down (`/media/externaldrive/` and all child folders will work but `/media/externaldrive/some/folder/` will not work). 

When I get more free time I will create a pull request but I am pretty confident this is the fix.

**Comment by 1337-server** [comment]
Closed as stale and no longer current with latest versions
