### ISSUE TITLE
Bluray does not complete MakeMKV Exit Code 139

### ISSUE THREAD

**Issue by nivinm** [automatic-ripping-machine/automatic-ripping-machine#268]
### Description
Hello, 

I've noticed that many of my Sony blu rays are not completing successfully. They get ejected within seconds. The exit code for MakeMKV is: 139

I did see this in syslog. 
Dec 18 18:55:38 arm udisksd[1897]: Error probing device: Error sending ATA command IDENTIFY PACKET DEVICE to /dev/sr0: ATA command failed: error=0x01 count=0x02 status=0x50 (g-io-error-quark, 0)

### Environment
Description:    Ubuntu 16.04.5 LTS
Release:        16.04

v2_master
Merge pull request #241 from automatic-ripping-machine/v2_fixes

### Log file
[VENOM_2018.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2692859/VENOM_2018.log)

**Comment by nivinm** [comment]
It works if I rip the movie manually through the MakeMKV gui.

**Comment by ahnooie** [comment]
What happens if you rip manually using CLI?
