### ISSUE TITLE
duel process when disc insert

### ISSUE THREAD

**Issue by caej** [automatic-ripping-machine/automatic-ripping-machine#269]
### Description
after disc insert the main.py is run twice

![skaermbillede 2018-12-27 kl 17 58 36](https://user-images.githubusercontent.com/2050066/50488182-783cb400-0a01-11e9-9ca3-3142cdfaf504.png)

### Environment
Ubuntu Server 18.04

**Comment by projektdotnet** [comment]
This is actually normal, what you're seeing is multiple sub-processes that Handbrake spawns, sort your htop by tree and you'll see that they're part of the same process.

![screenshot from 2019-02-24 10-32-14](https://user-images.githubusercontent.com/66758/53303505-d3cbc800-381f-11e9-85c1-ac82f5eb7a10.png)

**Comment by 1337-server** [comment]
Bug fixed in later versions
