### ISSUE TITLE
Emby scan doesn't run if main feature is false

### ISSUE THREAD

**Issue by ahnooie** [automatic-ripping-machine/automatic-ripping-machine#27]
Maybe emby refresh should be a function so it can be called from multiple locations? @muckngrind4

**Comment by muckngrind4** [comment]
I agree that the refresh should be a function.  But I don't know how it would work if main feature is disabled.  In that case, many files would be ripped/transcoded and manual interaction would be needed to name the files correctly negating the need for the automated library scan.

**Comment by muckngrind4** [comment]
Actually, I was just looking and a HandBrake scan will identify the main feature, so I think we can handle this...

**Comment by muckngrind4** [comment]
Added logic to do this for blurays.  Can't do this for dvd's yet.

**Comment by muckngrind4** [comment]
Adding for dvd's next...
