### ISSUE TITLE
Handbrake "High Profile" deprecated

### ISSUE THREAD

**Issue by skitzo2000** [automatic-ripping-machine/automatic-ripping-machine#271]
### Description
Handbrake "High Profile" is deprecated in the latest version of handbrake, so transcoding fails if you use the default arm.yaml

Ref:  https://handbrake.fr/docs/en/latest/technical/official-presets.html

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
V2_master

Sorry Deleted the original log:

Per above reference
HQ 1080p30 Surround <use this as the replacement for High Profile.

**Comment by ahnooie** [comment]
Confirmed, ran into this today after upgrading Handbrake

**Comment by 1337-server** [comment]
New profile was added a long time ago
