### ISSUE TITLE
Add instructions for installing ccextrator

### ISSUE THREAD

**Issue by ahnooie** [automatic-ripping-machine/automatic-ripping-machine#273]
### Description
MakeMKV 1.14.1 and later now requires ccextrator when extracting subtitles, which should be added to the readme

### Environment
ISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

v2_master
commit 3f40908a32c265d548857cc7d9eb4f0d72f2099b (HEAD -> v2_master, origin/v2_master)

### Log file
MSG:4040,0,1,"Unable to execute external program 'ccextractor' as its path is not set in preferences","Unable to execute external program '%1' as its path is not set in preferences","ccextractor"
MSG:4041,0,2,"Failed to execute external program 'ccextractor' from location '/usr/bin/mmccextr'","Failed to execute external program '%1' from location '%2'","ccextractor","/usr/bin/mmccextr"

**Comment by ahnooie** [comment]
```
apt install gcc
apt install libcurl4-gnutls-dev
apt install libtesseract-dev
git clone https://github.com/CCExtractor/ccextractor
cd ccextractor/linux
./autogen.sh
make
make install
cd /usr/bin/
ln -s /usr/local/bin/ccextractor mmccextr
```

**Comment by ahnooie** [comment]
To suppress the MSG:4040 warning in /home/arm/.MakeMKV/settings.conf add:

app_ccextractor = "/usr/local/bin/ccextractor"

**Comment by lignumaqua** [comment]
Just found this. Thank you! Without it ARM runs agonizingly slowly...
Note that you also need 
`./configure`
after the 
`./autogen.sh`

**Comment by cpaucar3** [comment]
No sym link is needed if the /usr/local/bin/ path is added to the settings.conf as mentioned above. All warnings will go away with just that one change.

**Comment by sjbrownie** [comment]
You will need this or make will fail

**Comment by 1337-server** [comment]
Closing as stale, this also shouldn't be needed as it should come with most installs of MakeMKV
