### ISSUE TITLE
No module named 'arm.config' in dev2.1 branch

### ISSUE THREAD

**Issue by ahnooie** [automatic-ripping-machine/automatic-ripping-machine#278]
### Description

@muckngrind4 

No module named 'arm.config'
Testing a fresh install on the dev2.1 branch

### Environment
Ubuntu 18.04.1
commit 2f8b861f5d93198cbe0ba31e4bc608e7e81e8e59 (HEAD -> v2.1_dev, origin/v2.1_dev)

arm@arm3:/opt/arm/scripts$ /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 17, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa: E402
  File "/opt/arm/arm/ripper/__init__.py", line 1, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, getkeys  # noqa F401
  File "/opt/arm/arm/ripper/logger.py", line 8, in <module>
    from arm.config.config import cfg
ModuleNotFoundError: No module named 'arm.config'

**Comment by muckngrind4** [comment]
Config.py was missing from the repo. Pushed and fixed.
