### ISSUE TITLE
Legacy Handbrake Profile

### ISSUE THREAD

**Issue by chaircommander** [automatic-ripping-machine/automatic-ripping-machine#282]
### Description
Within the arm.yaml config file, it still has "High Profile" as the default profile for HandBrake which is no longer supported. HandBrake.fr suggests to use the comparable "HQ 1080p30 Surround" instead. This fixed handbrake reporting invalid profile in the error logs.

**Comment by ahnooie** [comment]
Thanks, this is a duplicate of #271 and will be fixed in the next release.
