### ISSUE TITLE
Dev 2.1 Move to final destination is failing because source mkv file does not exist

### ISSUE THREAD

**Issue by ahnooie** [automatic-ripping-machine/automatic-ripping-machine#283]
### Description
On both BluRays and DVD At end of rip when moving from the unidentified folder to the movie destination the move is failing with: 

No such file or directory: '/mnt/media/unidentified/The Hobbit - The Battle of the Five Armies/The Hobbit - The Battle of the Five Armies.mkv'

In /mnt/media/unidentified/The Hobbit - The Battle of the Five Armies/

The file "The Hobbit - The Battle of the Five Armies.mkv" does not exist.  The files are actually like title_21.mkv, etc.

### Environment
Ubuntu 18.04.1
commit 0e49895451243e6469ed6b040e99e37d031050d7 (HEAD -> v2.1_dev_fix_yamlfilepath, origin/v2.1_dev_fix_yamlfilepath)

### Log file
[HOBBIT_DESOLATION_OF_SMAUG_EE.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2799203/HOBBIT_DESOLATION_OF_SMAUG_EE.log)

**Comment by muckngrind4** [comment]
Fixed in 2.1_dev.
