### ISSUE TITLE
issues with more than 10 DVD drives

### ISSUE THREAD

**Issue by evilone4fun** [automatic-ripping-machine/automatic-ripping-machine#286]
### Description
I am building out a large rig for ripping a giant collection.  The system currently sits at 12 DVD drives.  Drives 11 and 12 are not being picked up by ARM.

/dev/sr10 and /dev/sr11

I suspect it is due to the double digit dev/sr number.  Unfortunately I am not skilled enough to figure it out myself.

### Environment
root@mediripper:/etc/cron.hourly# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
root@mediripper:/etc/cron.hourly#

### Log file

not being picked up in empty.log.

**Comment by muckngrind4** [comment]
Yep, you're right.  It's the extra character and it's a bug.  The quick fix is to comment out line 267 in arm/main.py.  It should read:
`args.devpath = args.devpath[:3]`
Just put a '#' in front of it to comment it out.
`# args.devpath = args.devpath[:3]`

Let me know how it goes.  I think you might be the first to have that many drives.  I'd love to hear how goes and the specs of your machine...

**Comment by evilone4fun** [comment]
Thanks, After commenting out line 267 it picked up all drives when I loaded all 12 with Futurama.  Hopefully it rips cleanly.

My personal DVD\Bluray collection is over 1200 titles at the moment.  I am currently focusing on TV show DVDs.  Once I get done with that then I will go to the Movies.  

Currently I am only using ARM to rip MKVs  I have the Transcoding turned off in ARM and I am doing that across 4 old Mac Minis since they have QuickSync.  

I run a data center as my day job so I have access to a lot of hardware.  Also I have a tendancy to push the limits with builds like this.  I picked up 8 of my DVD drives at the local salvage house for $3 each.  The system is a work in progress.  I will probably be changing it out for a less powerful system since MakeMKV doesn't take too much resources by itself.  12 drives running at once right now is only using half the procs.  The ARM box is my old desktop but modified.  

Main Case
AMD FX-8150 8 core proc
ASUS motherboard
16GB of DDR3
700 Watt Corsair power supply
CoolerMaster case (don't know the model)
100GB HP Enterprise grade SSD boot (it is what I had laying around)
3TB WD Red for the rip target.
2 Bluray readers
2 DVD burners
8 drive SAS card. (being replaced with a better one eventually)

Secondary case
9 bay Bestduplicator CD Duplicator enclosure from Amazon.
8 DVD burners
2 SAS breakout cables.

Storage array
Synology DS1517+ with 5 8TB WD Red drives.

The final build will probably end up with 16+ Optical drives.  2 of the 8 bay enclosures and then however many bays the system case has in it.  I will probably be setting up an old LTO3 tape drive I have and backing up the RAW MKV files to tape so I won't have to rip them again.

I will post more info as it grows.  

By the time i finished typing this up I ripped 13 discs of Futurama.

**Comment by muckngrind4** [comment]
Glad the fix worked.  I've put the fix in dev branch already which I'm hoping to release it in a month or so.

Cool setup.  Thanks for sharing.  I'm guessing it's the biggest setup so far for ARM (since you found the bug).  I was wondering what kind of horsepower you needed to drive 12 simultaneous rips, but if you're not transcoding, it should be a pretty light load.  IO might be your bottleneck....

**Comment by evilone4fun** [comment]
SO I may be submitting a few suggestions for the install instructions.  I have now built my ARM install about 12 times.  As I was playing with different hardware incarnations.  Tuning the scripts I use to do the install.
I am thinking the current build amy be the final one for a while.   Ill post specs, pics, and videos soon.

**Comment by muckngrind4** [comment]
That would be great. Suggestions are always welcome!  The install process could certainly use some help....

**Comment by NiklasWilson** [comment]
This will need to commented out on any machine with 10+ drives? I just set this up with 5 DVD drives and am adding 5 bluray drives next week. for a total of 10 drives.

**Comment by evilone4fun** [comment]
It is only needed if you go above 10 drives.  once /dev/sr becomes a double digit number since it starts at 0 you don't have to go to a 2 digit number till you hit the 11th drive.  Personally I have run into some stability issues on my 24 drive ripping machine and eventually trimmed it back to 2 machines each running 10 drives.

**Comment by NiklasWilson** [comment]
Guess I got lucky having exactly 10 drives. thanks for the quick response.
Out of curiosity how are you connecting your drives? I am using 10 SATA to USB dongles/converters with 2 powered USB3 hubs.
