### ISSUE TITLE
[Feature Request] Post-Processing Command

### ISSUE THREAD

**Issue by projektdotnet** [automatic-ripping-machine/automatic-ripping-machine#287]
Feature Request

My ripping machine and my plex server are two completely different machines in two different locations. It would be awesome if there was a way that after the rip and encode ran, that another command could be executed automatically that allowed you to execute a custom command (like SFTP or SCP to copy the file in my case).

**Comment by accountnumber3** [comment]
I agree, but there's dozens of ways to do this.
* Edit the yaml file, set MEDIA_DIR to an sshfs mount
* Edit the yaml file, set up Pushbullet or IFTTT to run rsync
* Set up syncthing between the two boxes
* Add a cron job to `rsync -az --remove-source-files $MEDIA_DIR Plex:/path/to/files`

**Comment by jeffeb3** [comment]
The rsync command won't know if the handbrake or other processing is finished, right? I don't want it to clobber a process as it's working. Otherwise, that's a great solution for me (intermittent network here, and ripping directly to the network isn't a great choice).

**Comment by jeffeb3** [comment]
I actually think a post processing script would be pretty useful. Something that would call a script in a shell after setting some environment variables like:

ARM_OUTPUT_FOLDER
ARM_DISC_TYPE
ARM_TITLE
ARM_TOTAL_TIME_SECONDS
ARM_ALBUM_COVER_FILENAME
etc...

I could use that to send a message to slack (which is my preferred notification system), kick off an rsync, or run some sort of verification, etc. It would allow a lot of generic utilities. The pushbullet and IFTTT integration could be pushed out there too.

If you added some sort of step or state too, you could call it when it starts, moves to a new step, etc.

**Comment by bhuebschen** [comment]
commands before and after every processing step where not bad.

**Comment by AntaeusNar** [comment]
As there are open issues with identifying the ripped film, an option would be to use an after action script like [OrgNoMore](https://github.com/travman1900/OrgNoMore).  This script matches and moves the ripped title into a folder formatted for Plex/Embly using a TVDB api request for id.
