### ISSUE TITLE
Documentation Clarification: How to assign mounts to optical drives?

### ISSUE THREAD

**Issue by hiroo916** [automatic-ripping-machine/automatic-ripping-machine#288]
### Description
Although I have some UNIX experience from CS back in college, I'm a noob to Linux as a desktop.  I got through most of the steps to install ARM but am stuck at the mounting of optical drives:

> Create mount point for each dvd drive. If you don't know the device name try running 'dmesg | grep -i dvd'. The mountpoint needs to be /mnt/dev/. So if your device name is sr0, set the mountpoint with this command:
> 
> sudo mkdir -p /mnt/dev/sr0

This is what the dmesg outputs on my system:
```
[    3.469229] ata8.00: ATAPI: HL-DT-ST DVD+/-RW GTA0N, A100, max UDMA/100
[    3.547808] sr 7:0:0:0: [sr0] scsi3-mmc drive: 48x/48x writer dvd-ram cd/rw xa/form2 cdda tray
[    3.549927] scsi 8:0:0:0: CD-ROM            HL-DT-ST DVD+-RW GTA0N    A100 PQ: 0 ANSI: 5
[    3.623532] sr 8:0:0:0: [sr1] scsi3-mmc drive: 24x/62x writer dvd-ram cd/rw xa/form2 cdda tray
[    4.140479] sr 2:0:0:0: [sr2] scsi3-mmc drive: 24x/24x writer dvd-ram cd/rw xa/form2 cdda tray
[    4.189513] scsi 9:0:0:0: CD-ROM            MAD DOG  MD-16XDVD9       2.F6 PQ: 0 ANSI: 0
[    5.048192] sr 10:0:0:0: [sr4] scsi3-mmc drive: 125x/125x writer dvd-ram cd/rw xa/form2 cdda tray
[    5.327663] sr 11:0:0:0: [sr5] scsi3-mmc drive: 62x/62x writer dvd-ram cd/rw xa/form2 cdda tray
[    7.160831] sr 13:0:0:0: [sr6] scsi3-mmc drive: 125x/125x writer dvd-ram cd/rw xa/form2 cdda tray
```
I have a bunch of drives hooked up to this system so it's kind of confusing which is which, but it looks like the USB connected ones are getting a "sr#" name but the internal ones aren't (1, 3) and then #5 MAD DOG is also another USB connected one but it also doesn't get a "sr#".

Can anybody clue me in on how exactly to set mount points for all of these?  Thanks.

Also some examples for the next step would help.

> Create entries in /etc/fstab to allow non-root to mount dvd-roms Example (create for each optical drive you plan on using for ARM):
> 
> /dev/sr0  /mnt/dev/sr0  udf,iso9660  user,noauto,exec,utf8  0  0

### Environment
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.1
DISTRIB_CODENAME=tessa
DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"

* v2_master

commit 3f40908a32c265d548857cc7d9eb4f0d72f2099b (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: 1ed41eb b64bbf0
Author: Derek <22111345+muckngrind4@users.noreply.github.com>
Date:   Mon Aug 13 23:54:26 2018 -0700

    Merge pull request #241 from automatic-ripping-machine/v2_fixes
    
    Added -l option to su in arm_wrapper.  Fixes #237

**Comment by muckngrind4** [comment]
I'm not sure about why some of your drives aren't being assigned--hopefully some one else can be of assistance--but as for the fstab entries you just need to create one entry for each drive you have by replacing the actual drive mount point (sr0, sr1, etc) for the sr0 in the example.  So if you had two drives (sr0 and sr1) your fstab would have two entries like this:

`/dev/sr0 /mnt/dev/sr0 udf,iso9660 user,noauto,exec,utf8 0 0`
`/dev/sr1 /mnt/dev/sr1 udf,iso9660 user,noauto,exec,utf8 0 0`

I hope that helps...
