### ISSUE TITLE
Music CDs not being identified correctly

### ISSUE THREAD

**Issue by Sono-Gomorrha** [automatic-ripping-machine/automatic-ripping-machine#289]
### Description
Some of my music CDs are being identified not correctly. What I mean is that I have a CD which is e.g. from [Moix Dix Mois](https://www.discogs.com/Moi-dix-Mois-Vain/release/4517935), but ARM identifies this as David Clayton-Thomas / The Christmas Song (Promo CD Single); most likely [this one](https://www.discogs.com/David-Clayton-Thomas-The-Christmas-Song/release/13156241).  

### Environment
OS
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

ARM v2_master branch

### Log file
[music_cd.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/2919981/music_cd.log)

**Comment by Sono-Gomorrha** [comment]
In general the recognition works fine for me. It just occurs with some rarer items like these obsucre promo CDs from quite unknown bands

**Comment by 1337-server** [comment]
This is most likely an issue with upstream (Musicbrainz) not being able to find the track.

If you want to help out and contribute, you can create an account  with Musicbrainz and submit the info for the disc. It will help others in future.

https://musicbrainz.org/doc/How_to_Contribute
