### ISSUE TITLE
ARM fails on trying to open DVD Drive

### ISSUE THREAD

**Issue by andymelichar** [automatic-ripping-machine/automatic-ripping-machine#290]
### Description
I'm getting errors on "Failed to open device" - but what's weird is ARM can read the name of the DVD. If I put the DVD in and kick off arm, it detects the name and creates a log file with the name of the DVD, but then errors out.

### Environment
CentOS Linux release 7.6.1810 (Core)
v2_master

### Log file
utils.get_cdrom_status Failed to open device /dev/sr0 to check status

### fstab entry
/dev/sr0     /mnt/dev/sr0            udf,iso9660     user,noauto,exec,utf8   0 0

**Comment by andymelichar** [comment]
The only way I was able to get this to work was to change
`/bin/su -l -c "echo /usr/bin/python3 /opt/arm/arm/main.py -d ${DEVNAME} | at now" -s /bin/bash arm`
to
`/bin/su root -l -c "echo /usr/bin/python3 /opt/arm/arm/main.py -d ${DEVNAME} | at now" -s /bin/bash arm`

Probably not the best fix, if anyone else knows a better way let me know!

**Comment by muckngrind4** [comment]
Getting ARM to run as the arm user is a little tricky. I've tested the current method on Ubuntu bit not any other flavors. I suspect the might be a subtle difference between Ubuntu and CentOS. Glad you got to working. I'd be curious if this command works on your system:
`/bin/su arm -l -c "echo /usr/bin/python3 /opt/arm/arm/main.py -d ${DEVNAME} | at now" -s /bin/bash`
