### ISSUE TITLE
ARM crashes when attempting to rip audio CD

### ISSUE THREAD

**Issue by mg-man** [automatic-ripping-machine/automatic-ripping-machine#292]
### Description
When attempting to rip audio CD, ARM crashes.  This is due to 2 errors in main.py.

line 110 should be... 
`utils.notify(job, "ARM notification", "Found music CD: " + str(job.label) + ". Ripping all tracks")`  

...and, line 323 should be...
`utils.notify(job, "ARM notification", "Music CD: " + str(job.label) + " processing complete.")`

BTW, for audio CDs, job.label is blank... is there a way to populate this with something meaningful?  

### Environment
Unubtu 18.04 LTS, ARM v2.1_dev

**Comment by DrEVILish** [comment]
I'm having the same issue on Ubuntu 18.04LTS, using the latest build was only installed last month.

Inserting CDs crashes ARM, has worked perfectly for BDs

**Comment by mg-man** [comment]
I should have been a little more clear... the existing main.py has...

`...music CD: " + job.label + ". Ripping...`

...it needs to be changed (in both places) to...

`...music CD: " + str(job.label) + ". Ripping...`

job.label is blank (see my other comment above), but at least this gets the CD rip running...

**Comment by DrEVILish** [comment]
Mine was still causing a problem with str(job.label) so I removed it completely and just had 
`...music CD, Ripping...` in both places.
