### ISSUE TITLE
Upgraded to Ubuntu 19.04 from 18.04 then -- ARM stopped working

### ISSUE THREAD

**Issue by eplummer13** [automatic-ripping-machine/automatic-ripping-machine#293]
### Description
ARM does not seem to even run after disk is inserted

### Environment
Ubuntu 19.04
V2

### Log file
Doesn't run, however will test more

**Comment by insanity54** [comment]
The issue title is not describing the issue. I think you mean, "ARM does not run on Ubuntu 19.04"

**Comment by eplummer13** [comment]
After walking away for a bit, i decided to run through the installation steps post upgrade. Some didn't run as they are written for 18.04 however the ones that did work were enough to fix the process after reboot. I suppose the real issue here is why did it break from the update? to help others maybe the process to install on 19.04 could be added.

**Comment by eplummer13** [comment]
thank you for the fast initial response

**Comment by pltaylor** [comment]
I installed in on 19.04 fresh and am getting a 
`PermissionError: [Errno 13] Permission denied: '/mnt/dev'`
error on reading the disk.  Any thoughts on how to fix it?
