### ISSUE TITLE
DVD lookup service (windowsmedia) down? 

### ISSUE THREAD

**Issue by mg-man** [automatic-ripping-machine/automatic-ripping-machine#295]
INFO ARM: DVD CRC64 hash is: f8f9d45140065acc
ERROR ARM: Failed to reach windowsmedia web service.  Error number is: 104

When I manually send a query using...
`http://metaservices.windowsmedia.com/pas_dvd_B/template/GetMDRDVDByCRC.xml?CRC=f8f9d45140065acc`

I get a "connection was reset" error...  Is anyone else seeing this?

**Comment by muckngrind4** [comment]
Yep. I'm seeing this too. I wonder if MS has turned this off. I've noticed over the last few months a number of the newer DVDs I've bought weren't in the database and was wondering if they were abandoning the service. Hopefully it will come back up....

**Comment by mg-man** [comment]
Yeah, I was wondering the same...
As a workaround [I'm running v2.1_dev], I uncommented the `# return False` at line 113 in identify.py so that it drops through.  I'm running the webserver, so I can manually look up each DVD.  Not ideal, but at least it sort-of gets around this.

**Comment by muckngrind4** [comment]
If your on v2.1_dev I just pushed a fix. It is similar to yours but allows the DB to be populated correctly.

**Comment by mg-man** [comment]
OK, thanks... am travelling for the next couple of days, but will check it out and report back.  

windowsmedia.com still seems to be un-responsive...

**Comment by martinzirkle** [comment]
Checked out lastest v2.1_dev and it appears to be working. Thanks! Hopefully windowsmedia will be back up soon...

**Comment by muckngrind4** [comment]
Looks like it's not getting fixed...
https://support.microsoft.com/en-us/help/4488539/changes-metadata-services-windows-media-center-media-player

**Comment by TheOddball** [comment]
Hopefully there will be a fix for this soon.. Another project maybe

**Comment by obsidiangroup** [comment]
I have been searching and looking for other ways to accomplish this, and have come up empty.  Does ARM keep a track of movies it has ripped, and a mapping of the hash to title?  If so, my company may be able to come up with a solution but I would have to set up a gofundme page or something similar to fund the project.

If we were to create a service similar to the windowsmetadata service, that maintains a database of hashes, title, imdb id, omdb id, etc and expose it via an API, it would help not only ARM, but any other projects / programs that rely on the hash value of the disc.

If ARM kept a database of everything each user has ripped, with the crc64 -> title mapping, and we could get the community to submit their databases, we would have a starting point.  From there, we could obtain the imdb id, etc and populate the database with that information.  This would be helpful for scrapers to obtain other metadata.  The API would also allow users to submit new information, and in the case of the ARM, when a title is not in this database and the user puts the correct information, it would update the database.

I wonder if Microsoft would be willing to provide a database dump of their metadata information -- they wouldn't have to include artwork, etc, but just general information including the hash values?  I am seeing what type of interest of possibly funding this would be.  I will also come up with a rough draft of what it would take to implement this.

**Comment by KlfJoat** [comment]
There are a few models for this situation in the CD-DA (audio CD) world...  One is CDDB and the other is MusicBrainz.

CDDB can be either or both local and distributed contribution.  But it's limited and crowdsourced information without review or even a standard (such as how to handle titles starting with "the") can be low quality.  It's just a list of track names with no other information--not even track length or type (like music, skit, spoken word).

MusicBrainz is centralized (though a local cache can be used).  However, it has a LOT more information about the works and tracks.  Using the website, you can find with multiple versions of the same work and the same recording of the same work across compilations, etc.  If ambitious enough, this model could be used here to name DVD extra tracks and see if they're the same thing across multiple releases of the same movie.  It would require a central service and a *LOT* of work to manage the standard, changes, etc.  MusicBrainz has information licensing models to help with the costs.  Other, Windows-based metadata information applications have such a "user contributed" model, but they lock it to their own application.  

Whatever is done, I'd want extras to be included because that's an important part of the media experience for me.  Since ARM doesn't handle extras or non-movies very well, I'm creating my own thing in the MusicBrainz style (though local only) to name the tracks on a disc and identify their type (movie, trailer, TV episode, scene, deleted scene, etc), and put them in the right directories according to Plex conventions.  

But if that could be done automatically, I'd like to see that.

**Comment by TomW1605** [comment]
has there been any update on this?

**Comment by 1337-server** [comment]
> has there been any update on this?

Arm now uses OMdb to identify movies, you need an OMdb key for ident to work.
CDs need to use musicbrainz as cddb is dead.

But OMdb has limitations, they don't use crc. This means that we have to rely on the disc label being close to the dvd name. But there is no alternative right now, and it seems unlikely that another service of its type will be created.

**Comment by TomW1605** [comment]
thanks. might be worth closing any issues related to windowsmedia and removing it from the code. there are still errors in the logs because it is trying to access it and these could through people off who are trying to debug movie identification.

**Comment by cmbernard333** [comment]
I'm still seeing this issue with the latest master branch. Is there something I should do different so it uses OMdb correctly? I have the key configured in arm.yaml.

**Comment by 1337-server** [comment]
Can you share your logs ?

Are you using v2_master ?

**Comment by cmbernard333** [comment]
I was using `v2_master`. I deleted all my logs unfortunately because I was trying to debug a separate issue. I am now consistently seeing:

```[ 2826.679424] sr 1:0:0:0: [sr0] tag#3 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=0s
[ 2826.679428] sr 1:0:0:0: [sr0] tag#3 Sense Key : Illegal Request [current]
[ 2826.679431] sr 1:0:0:0: [sr0] tag#3 Add. Sense: Read of scrambled sector without authentication
[ 2826.679434] sr 1:0:0:0: [sr0] tag#3 CDB: Read(10) 28 00 00 3f 1c f8 00 00 02 00
[ 2826.679438] blk_update_request: I/O error, dev sr0, sector 16544736 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[ 2826.679508] Buffer I/O error on dev sr0, logical block 2068092, async page read
```

On ubuntu 20.04. I reinstalled libdvd-pkg several times and handbrake and vlc to no effect.

**Comment by 1337-server** [comment]
Isnt this standard for reading encrypted discs ?

**Comment by cmbernard333** [comment]
My working assumption was `libdvd-pkg` from VLC was supposed to help reading encrypted dvds but it's been a long while since I've done this.

**Comment by 1337-server** [comment]
You would be better to open a new issue. As this isnt related to this issue.

**Comment by cmbernard333** [comment]
I fixed my encrypted read issue. I am still seeing the windowsmediadb error: 104 when running `v2_master`

**Comment by 1337-server** [comment]
Ignore it ?

Windowsmetadata is no longer working and will cause error 104 every time ARM is run. This can be ignored as ARM now uses OMdb as its metadata provider. Its not as good as WMD but there are no alternatives that use dvd crc anymore.

**Comment by cmbernard333** [comment]
Ok. Thanks for the tip. Any indication in the logs if OMdb is collecting information successfully? It doesn't seem to be naming things correctly.

**Comment by 1337-server** [comment]
Did you add your own OMdb api key ? Once that is added to the arm config you should see something like this.

```
[2021-01-01 18:08:07] INFO ARM: identify.identify_dvd DVD CRC64 hash is: 9e1f7fbe8fb51a76
[2021-01-01 18:08:07] DEBUG ARM: identify.identify_dvd http://metaservices.windowsmedia.com/pas_dvd_B/template/GetMDRDVDByCRC.xml?CRC=9e1f7fbe8fb51a76
[2021-01-01 18:08:07] DEBUG ARM: identify.identify_dvd dvd_title_label= BLADE_DVD
[2021-01-01 18:08:07] DEBUG ARM: identify.identify_dvd dvd_title ^a-z= BLADE DVD
[2021-01-01 18:08:07] DEBUG ARM: identify.identify_dvd dvd_title SKU$= BLADE DVD
[2021-01-01 18:08:07] DEBUG ARM: identify.callwebservice http://www.omdbapi.com/?t=BLADE DVD&y=&plot=short&r=json&apikey=key_hidden
[2021-01-01 18:08:07] DEBUG ARM: identify.callwebservice ***Calling webservice with Title: BLADE DVD and Year: 
[2021-01-01 18:08:07] DEBUG ARM: identify.callwebservice Webservice failed
[2021-01-01 18:08:07] DEBUG ARM: identify.identify_dvd DVD_INFO_XML: fail
[2021-01-01 18:08:07] DEBUG ARM: identify.get_video_details Title = BLADE DVD
[2021-01-01 18:08:07] DEBUG ARM: identify.get_video_details Title: BLADE+DVD | Year: 
[2021-01-01 18:08:07] DEBUG ARM: identify.get_video_details Calling webservice with title: BLADE+DVD and year: 
[2021-01-01 18:08:07] DEBUG ARM: identify.callwebservice http://www.omdbapi.com/?t=BLADE+DVD&y=&plot=short&r=json&apikey=key_hidden
[2021-01-01 18:08:07] DEBUG ARM: identify.callwebservice ***Calling webservice with Title: BLADE+DVD and Year: 
[2021-01-01 18:08:08] DEBUG ARM: identify.callwebservice Webservice failed with error: Movie not found!
[2021-01-01 18:08:08] DEBUG ARM: identify.get_video_details response: fail
[2021-01-01 18:08:08] DEBUG ARM: identify.get_video_details Removing year...
[2021-01-01 18:08:08] DEBUG ARM: identify.callwebservice http://www.omdbapi.com/?t=BLADE+DVD&y=&plot=short&r=json&apikey=key_hidden
[2021-01-01 18:08:08] DEBUG ARM: identify.callwebservice ***Calling webservice with Title: BLADE+DVD and Year: 
[2021-01-01 18:08:08] DEBUG ARM: identify.callwebservice Webservice failed with error: Movie not found!
[2021-01-01 18:08:08] DEBUG ARM: identify.get_video_details response: fail
[2021-01-01 18:08:08] DEBUG ARM: identify.get_video_details Trying title: BLADE
[2021-01-01 18:08:08] DEBUG ARM: identify.callwebservice http://www.omdbapi.com/?t=BLADE&y=&plot=short&r=json&apikey=key_hidden
[2021-01-01 18:08:08] DEBUG ARM: identify.callwebservice ***Calling webservice with Title: BLADE and Year: 
[2021-01-01 18:08:08] DEBUG ARM: identify.callwebservice Webservice successful.  New title is Blade.  New Year is: 1998

```

**Comment by jarrodCoombes** [comment]
> I have been searching and looking for other ways to accomplish this, and have come up empty. Does ARM keep a track of movies it has ripped, and a mapping of the hash to title? If so, my company may be able to come up with a solution but I would have to set up a gofundme page or something similar to fund the project.

Personally I'd be happy to kick in to a fund for this, possibly even a monthly amount on patreon.
 
> I wonder if Microsoft would be willing to provide a database dump of their metadata information -- they wouldn't have to include artwork, etc, but just general information including the hash values? I am seeing what type of interest of possibly funding this would be. I will also come up with a rough draft of what it would take to implement this.

If they did I would be very surprised. They probably consider it proprietary data and therefore won't let it go, even if they are not using it.

**Comment by 1337-server** [comment]
> > I have been searching and looking for other ways to accomplish this, and have come up empty. Does ARM keep a track of movies it has ripped, and a mapping of the hash to title? If so, my company may be able to come up with a solution but I would have to set up a gofundme page or something similar to fund the project.
> 
> 
> 
> Personally I'd be happy to kick in to a fund for this, possibly even a monthly amount on patreon.
> 
>  
> 
> > I wonder if Microsoft would be willing to provide a database dump of their metadata information -- they wouldn't have to include artwork, etc, but just general information including the hash values? I am seeing what type of interest of possibly funding this would be. I will also come up with a rough draft of what it would take to implement this.
> 
> 
> 
> If they did I would be very surprised. They probably consider it proprietary data and therefore won't let it go, even if they are not using it.
> 
> 

ARM does still keep track of dvd crc64 idents. But it is only used locally. 

The main issue is that to my knowledge there are no online databases that make use of crc64. So one would need to be created and would rely almost entirely on user submitted data.

The coding isn't the real issue with this, it would be the cost/maintenance to keep the website/database online.

An alternative could be that users submit data (titles,year and crc64) via GitHub or other service and a database file could be updated regularly and included with all ARM installations. This would save on the cost requirement of upkeep, while still giving users and opt-in option of helping with submitting of data. 

But this would need to be approved from @flammableliquids and support from the ARM userbase for this to work.

**Comment by jarrodCoombes** [comment]
> The coding isn't the real issue with this, it would be the cost/maintenance to keep the website/database online.

What kind of cost would this be do you think? I can't imaging the storage cost would be much, it would boil down to the bandwidth/data transfer cost, and I've no idea how to even start to estimate that.

**Comment by 1337-server** [comment]
> > The coding isn't the real issue with this, it would be the cost/maintenance to keep the website/database online.
> 
> What kind of cost would this be do you think? I can't imaging the storage cost would be much, it would boil down to the bandwidth/data transfer cost, and I've no idea how to even start to estimate that.

I think you are correct that the DB size wouldn't be a concern, at least not in the short term.

I think the main concern would be the variance of the usage, some users will use ARM in small burst to go through their entire collection of 1k-2k movies/series in a short period of time. Others will use it to backup only 1 or 2 discs a month. The problem would be accounting for this while also keeping the costs low enough to be sustainable.

But the main problem with estimating the cost would be that we have no data on the number of active users using ARM currently. So there really is no way to know before setting things up.

This is why i suggested the alternative, as it's easier to get started, and in the short term it's very unlikely to go over the 100MB github file limit for the database file. And there are no costs to setup/maintain a website and API.

**Comment by jarrodCoombes** [comment]
Does it have to be in this Git? Could not be it's own separate thing that users can choose to enable or not. I could envision throwing it in a folder, setting an option in the yaml to use it, add to it as needed and then just using Cron to do a git update to sync the thing on some time interval.

But I am also open to spinning up a VPS somewhere and setting up the DB for access and just see how it goes...

**Comment by jarrodCoombes** [comment]
> I think the main concern would be the variance of the usage, some users will use ARM in small burst to go through their entire collection of 1k-2k movies/series in a short period of time. Others will use it to backup only 1 or 2 discs a month. The problem would be accounting for this while also keeping the costs low enough to be sustainable.
> 
> But the main problem with estimating the cost would be that we have no data on the number of active users using ARM currently. So there really is no way to know before setting things up.

*back of the napkin math alert*

I've been thinking about this some more. The exchange between the client and the server would be quite simple. A CRC64 hash is sent, and in return the client gets an IMDB record number, and/or TMDB record number.  That's a total exchange of something like 16 or 32 bytes without the TCP overhead. So I think it would be reasonable to assume, for arguments sake, that each lookup would cost 1Kbyte of transfer. Someone doing 2k movies, would then only use up about ~2Mbyte of data.  

Some of the VPS I was looking at had $20/mo plans that allowed for 2Tbytes of transfer a month. That would be something like 2 billion transfers at 1Kbyte each.  

On top of this a setup like this could easily limit the number of lookups for any one user per month to something that guarantees sustainability. If we limited it to 1k per user per month, then we could service 2 million users a month without the cost going above the VPS monthly.

I guess what I am saying is that the risk here is minimal from a cost stand point, and I am totally willing to donate the VPS monthly for the cause if someone can help me write the database end of it.

**Comment by 1337-server** [comment]
I dont mind helping writing some of the code.

Are you looking to have users add new items from the other service ? Or adding them from a post from ARM github?

**Comment by jarrodCoombes** [comment]
> I dont mind helping writing some of the code.
> 
> Are you looking to have users add new items from the other service ? Or adding them from a post from ARM github?

Other service? I'd not really thought at far ahead tbh.  Something low friction for sure, maybe ARM could update this DB when they user manually enters a title that is not found in this DB or found via the disk name match?

**Comment by 1337-server** [comment]
> 
> 
> > I dont mind helping writing some of the code.
> > Are you looking to have users add new items from the other service ? Or adding them from a post from ARM github?
> 
> Other service?
> 
> I'd not really thought at far ahead tbh. Something low friction for sure, maybe ARM could update this DB when they user manually enters a title that is not found in this DB or found via the disk name match? But that maybe something done once the concept is proven. Totally open to suggestions for initially populating the DB though.

That's the hard part of this. You would need users to submit their data, and its not really possible to ask them to submit their database file as it contains all their api/secret keys.

So the option only really comes down to creating an extra part of the ARMui that would allow submitting of data. Because im not sure if users would be happy if ARM suddenly started reporting all of their rips to an external source.

**Comment by jarrodCoombes** [comment]
What about a seperate script that goes through their DB, pulls out the CRC64 disk hash and the name of the disk (movies only) shows that to the user and asks them if they want to submit it all? Users can just run that (if they choose to) without anyone having to mod ARM for now. Throw in a `--alwaysallow` type switch and some sort of way to track what has already been uploaded and they could then make a cron job to run it at whatever interval they want.

This makes it completely voluntary, does not change ARM in any way, and could kick us off to start with.

I should note that I am brand new to most of this, and while I have some programming skills, I'll definitely need help bringing them up to speed on this...

**Comment by 1337-server** [comment]
If you have a look at https://github.com/1337-server/dvd-crc64-database its a very basic beginning of an api that could be used.

It doesnt have any way to add new entries, it only outputs entries it already has. It really just to show how easy the api is to setup. The much harder part is coding a way to allow users to add their own enties, but its a start.

**Comment by jarrodCoombes** [comment]
> If you have a look at https://github.com/1337-server/dvd-crc64-database its a very basic beginning of an api that could be used.
> 
> It doesnt have any way to add new entries, it only outputs entries it already has. It really just to show how easy the api is to setup. The much harder part is coding a way to allow users to add their own enties, but its a start.

I just need to work out what to do with all of that ot make it work.... lol.

But poking at the DB it looks like it has way more in it than I was thinking, things like the poster URL among other. I was literally thinking a DB that has 2 tables in it, CRC-64 hash table and an info table with: Movie Name/Year, IMDB record number and OMDB record number. All the meta data can be retrieved and stored else where. Or am I missing something here?

**Comment by 1337-server** [comment]
Yes its a little overpopulated. 
Personally I would prefer to keep the number of requests down rather than forcing the users to add an external source if they dont have need it. By adding the poster data you can remove the need to add an omdb api key and still get all the info required for arm to work and the ui to look good.

But I think the only needed items are 
```
    crc_id = db.Column(db.String(63), unique=True, nullable=False)
    user_id = db.Column(db.String(63))
    date_added = db.Column(db.DateTime)

    no_of_titles = db.Column(db.Integer)
    title = db.Column(db.String(256))
    year = db.Column(db.String(4))
    video_type = db.Column(db.String(20))

    imdb_id = db.Column(db.String(15))
    tmdb_id = db.Column(db.String(15))
    omdb_id = db.Column(db.String(15))

    hasnicetitle = db.Column(db.Boolean)
    disctype = db.Column(db.String(20))
    label = db.Column(db.String(256))
    validated = db.Column(db.Boolean)
```

Possibly even less.

**Comment by jarrodCoombes** [comment]
Just to make sure I am thinking of this correct. 

The desired result here is that ARM sends over the disc's CRC-64 hashed id, along with another CRC-64 hashed user id. The server then locates the disc by that ID and send backs the disk's title, year, poster URL and label (identified or not). And this is what the example code you threw together does right? This then allows ARM to name the folder/file correctly so that the user can dump that into their media platform of choice and get the meta data via that platform.

I am wondering why the DB would need to log the disc type, video type or IMDB/tmdb/omdb ids?

**Comment by 1337-server** [comment]
The video_type arm uses this after transcoding to move the files correctly.
The disc_type isnt required.
Attaching the external id's makes things easier, should you need to lookup more info (plot, ratings, cast, etc)

**Comment by jarrodCoombes** [comment]
> The code i linked is the API only, ARM would need to be modified to ping the api with the crc just as it does currently with omdb.

Yep, that much I gathered. What I am not sure about is how to implement this API on a server. I setup an Ubuntu 20.04LTS server @ arm-db.zatek.net with nginx, but need to work out how to use your code on there.

**Comment by 1337-server** [comment]
Did you make sure it was running ? It should look like http://1337server.pythonanywhere.com/index.html

Once you have confirmed it is setup you can request a API key that will be sent to your email, then you will need to modify [/arm/ripper/identify.py](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/v2_master/arm/ripper/identify.py) to check the api first for crc64 of the dvd.
At the moment the api is coded to allow searches without any api key. Only adding new entries requires a key.
And the api tracks the api key of all submitions so if there are a bunch of bad submittions from one user these can easily be removed.

For searching the url would be 
[/api/v1/?mode=s&crc64={dvd crcr64 here}](#)

The api's end is coded and can recieve new entries but ARM needs to be modified in a way to allow users to send new entries to the api.
For adding the url would be 
[/api/v1/?mode=p&api_key={apikey}&crc64={dvd crcr64 here}&t={title}&y={year}&etc=&etc=](#)

[THIS](https://github.com/1337-server/dvd-crc64-database/blob/ddf2bc058b484b9ba636e498700e4860b8b71f92/ui/routes.py#L25)
and
[THIS](https://github.com/1337-server/dvd-crc64-database/blob/ddf2bc058b484b9ba636e498700e4860b8b71f92/ui/utils.py#L34) will show you the details you need to send to the api when adding

Let me know if you need anymore info

**Comment by jarrodCoombes** [comment]
> Did you make sure it was running ?

What I meant to say is I am not sure how to install it. This is all very new to me (though once it's up and running, futzing with the python code should be easy enough).

**Comment by 1337-server** [comment]
Cant you just run runui.py from a python terminal (or regular terminal in linux) ?

**Comment by jarrodCoombes** [comment]
> Cant you just run runui.py from a python terminal (or regular terminal in linux) ?

You underestimate how new I am to this kind of python project..

So I am inferring that the process is git clone the repo, then just run the `runui.py` command? So I don't actually need nginx... I'll try this as soon as I can.

**Comment by 1337-server** [comment]
> 
> 
> > Cant you just run runui.py from a python terminal (or regular terminal in linux) ?
> 
> You underestimate how new I am to this kind of python project..
> 
> So I am inferring that the process is git clone the repo, then just run the `runui.py` command? So I don't actually need nginx... I'll try this as soon as I can.

Yes, however you will need to edit runui.py 
`app.run(host="127.0.0.1", port="9999", debug=True)`
and set this to your own preference.

**Comment by Coloradohusky** [comment]
It doesn't appear as if the API is currently working? Requests are returning `"success": false` (see http://1337server.pythonanywhere.com/api/v1/?mode=s&crc64=5cd73d310021b6fa478fed685c112199 for an example)

**Comment by obsidiangroup** [comment]
I'm more than happy to spin up a vm instance to assist with this or lend a
hand running this. I would just need to know what type of database you're
using and either a dump of the db, or we can setup replication. Either way,
if you need help let me know.

**Comment by 1337-server** [comment]
ARM now uses omdb, and in the latest version tmdb is also an option.

**Comment by n8henrie** [comment]
I see this and <https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/312> were closed (and https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/312 marked as `Fixed`) -- I've been watching this issue for while to see what solution you come up with as I have a similar toy project that I'm slowly rewriting: (<https://github.com/n8henrie/dvdrip>).

It looks like the key logic is here:

- https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/cef9ef40d7a60dae173804cf64d562995f89b4d5/arm/ripper/identify.py#L115
- https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/cef9ef40d7a60dae173804cf64d562995f89b4d5/arm/ui/utils.py#L709

where it tries to use the CRC64 to query `http://1337server.pythonanywhere.com/api/v1/?mode=s&crc64=CRCHERE`. 

If not found, it uses a regex on the DVD label: `dvd_title = re.sub(r"[^a-zA-Z _-]", "", dvd_title)` and ships that off to `metadata_selector`, which queries either `tmdb` or `omdb` based on the "best guess" at title and year (which may not be provided).

It looks like metadata can then be optionally sent back to the ARM API endpoint: https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/cef9ef40d7a60dae173804cf64d562995f89b4d5/arm/ui/routes.py#L883

(As a site note, it [looks like](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/f4496dab18181171eb072e35787b1031185d4af5/requirements.txt#L9) you are depending on `flask>=1.0.2`; updating to 2.0 would enable async routes, which I'm betting would drastically speed up sending that batch of async requests).

Thanks for your hard work on this!

**Comment by n8henrie** [comment]
(Ping @obsidiangroup from https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/312#issuecomment-701116815)

**Comment by 1337-server** [comment]
> (As a site note, it [looks like](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/f4496dab18181171eb072e35787b1031185d4af5/requirements.txt#L9) you are depending on flask>=1.0.2; updating to 2.0 would enable async route

I'll look into this, but it was already re-written, It's now mostly client side. It now throws a list out to JavaScript and lets the client go through it so that progress can be shown.
If you have a look at the v2_devel branch, it's much more updated.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/d096a2794b5280b1315001926b840ce305934415/arm/ui/routes.py#L716

**Comment by z4ch523** [comment]
Hi, I was wondering what the status of the online DB was?
I uploaded my local jobs today via the arm UI but when I inserted a DVD for the second time the identification failed (wrong result).

**Comment by 1337-server** [comment]
https://1337server.pythonanywhere.com/api/v1/?mode=latest

Should give you the last 5 discs/crcr64 added to the database

This is how you would find that crcr64 ID 
https://1337server.pythonanywhere.com/api/v1/?mode=s&crc64=CRC64-IDNUMBER-HERE

Like this https://1337server.pythonanywhere.com/api/v1/?mode=s&crc64=1f4c3610598f8588

But it seems like that ID wasn't added

**Comment by z4ch523** [comment]
Ah, that means uploading my jobs is the issue.
So I should create another issue then?
