### ISSUE TITLE
install script

### ISSUE THREAD

**Issue by drewwells** [automatic-ripping-machine/automatic-ripping-machine#300]
### Description
Installation script/apt package that handles the install and uninstallation of ARM. It installs all required dependencies, sets up scripts, and/or give instructions for modifying cdrom insert.

### Environment
Small list of supported environments

**Comment by jswetzen** [comment]
I made an Ansible role a while back for this, and a Vagrantfile for automatically setting up a virtual machine (the recommended way of installing anyway). It worked quite well! ...a few years ago. I haven’t had time to update it, but it shouldn’t be that difficult. Feel free to submit a PR or come with suggestions.

https://github.com/jswetzen/automatic-ripping-machine-setup
