### ISSUE TITLE
Movie titles not being matched automatically

### ISSUE THREAD

**Issue by cr45hmurphy** [automatic-ripping-machine/automatic-ripping-machine#310]
### Description

I realize that this was somewhat covered in Issue #295, but is there any way to switch the internet search database from Windows Media Servers to OMDB or something similar? This being due to the Windows Media Servers being down indefinitely. I also know that the developer build allows for users to search for a title and match it up manually. I'm mainly just asking out of the desire for convenience and laziness. I'm willing to help figure this out, but want to know if anyone else has had experience or matching DVD/BluRay data with other internet movie/TV show databases.

### Environment

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

**Comment by mpompey** [comment]
I'm not sure how active folks are on this. Did you ever figure this out? I guess we would need some db of DVD movies and their serial numbers as that is what Windows MEdia Service was matching on. I'm not sure how tmdb works, maybe we could do a match on disc name? But the disc name isn't an exact match to movie title.

I'd be willing to help too. But I'm a BI guy by trade, not a developer per se. But whatever I can do, you guys got it.

I'm personally to find a way to get my rip time for DVDs down from 7 hours.

**Comment by junebug217** [comment]
I haven't had a chance to look at it very thoroughly yet. I'm thinking the same thing as you, with regards to the serial number. I know that OMDB has an API which might be leveraged to lookup movie titles. I'm also not much of a developer; more of a tinkerer.

**Comment by mpompey** [comment]
I guess it's time to start learning Python so we can see what is going on. :)

**Comment by drmikecrowe** [comment]
I spent quite a while researching API's looking for something that could help.  I can't find any alternative.  For instance, [RapidAPI](https://rapidapi.com) has thousands of commercial API's, and none fit the bill (nor any other that I found while googling around)

Unfortunately, a lot of my old disks just don't have nice titles.  I continually see this in my logs:

```
[2019-12-31 20:42:39] INFO ARM: identify.identify Disc does not have a nice title.  Skipping video type identification and setting title=title_unkonwn
```

so OMDB is never called.

I created a very manual option for those who aren't faint of heart.  Basically, it's a command line program which searches IMDB and renames the files appropriately:

[searchImdb.py](https://gist.github.com/drmikecrowe/1f30f8f655661ae508709f0cf505a1a0)

**NOTE**: You will need to tweak this, it assumes you're comfortable with python, etc.

I have it play the movie in `totem`, then it searches:

```
Search Directory: title_unknown_157805540893
Running command: totem "/home/mcrowe/NAS/Movies/Ripped/title_unknown_157805540893/title_t00.mkv"

Movie Search []: frost nixon
-1: New Search
0: Skip
1: David Frost Interviews Richard Nixon (1977) David Frost,Richard Nixon
2: Frost-Nixon (2008) Frank Langella,Michael Sheen,Sam Rockwell
3: Frost-Nixon (2008) 
4: Frosting-Nixon (2013) 
5: Frost on Nixon (2011) 
6: Case Study: Frost Nixon (2017) 
7: The Making of Frost-Nixon (2009) 
8: Twilight-Frost-Nixon-Bolt (2008) 
9: Frost Nixin (2013) 
10: The Nixon Library (2009) 
11: Nixon in Chicago (1973) 
12: The Real Interview (2009) 
13: Discovering Secrets (2009) 
Select: 2
rename title_unknown_157805540893 -> Frost-Nixon (2008)
rename Frost-Nixon (2008)/title_t00.mkv -> Frost-Nixon (2008)/Frost-Nixon (2008).mkv
rename Frost-Nixon (2008)/title_t02.mkv -> Frost-Nixon (2008)/Frost-Nixon (2008) - Extra #1.mkv
rename Frost-Nixon (2008)/title_t01.mkv -> Frost-Nixon (2008)/Frost-Nixon (2008) - Extra #2.mkv
```

**Comment by 1337-server** [comment]
I used this getmovietitle.py to fix some of the file names but its not perfect. And im currently trying to add Trakt.tv or TMBD instead of  the windows media service.

`#!/usr/bin/python3

import argparse
import urllib
import datetime
import pydvdid  # dead
import unicodedata
import sys  # noqa # pylint: disable=unused-import
import re
import logging
import json
import os  # noqa # pylint: disable=unused-import
import xmltodict  # noqa # pylint: disable=unused-import

from config import cfg

import logger  # noqa # pylint: disable=unused-import
import classes  # noqa # pylint: disable=unused-import


def entry():
    """ Entry to program, parses arguments"""
    parser = argparse.ArgumentParser(description='Get Movie Title from DVD or Blu-Ray')
    parser.add_argument('-p', '--path', help='Mount path to disc', required=True)

    return parser.parse_args()


def getdvdtitle(disc):
    """ Calculates CRC64 for the DVD and calls Windows Media
        Metaservices and returns the Title and year of DVD """
    global hasnicetitle
    dvd_title = disc.label
    year = disc.videoyear
    omdb_api_key = cfg['OMDB_API_KEY']
    dvd_title_clean = cleanupstring2(dvd_title)
    logging.info("DVD title: " + str(dvd_title))

    # try to contact omdb
    try:
        dvd_info_xml = callwebservice2(omdb_api_key, dvd_title_clean, year)
        logging.debug("DVD_INFO_XML: " + str(dvd_info_xml))
    except OSError:
        # we couldnt reach omdb
        logging.error("Failed to reach OMDB")
        return [None, None]
    # couldnt be found
    if dvd_info_xml == "fail":
        logging.debug("We found ERROR IN DVD_INFO_XML")
        # see if there is a hyphen and split it
        if dvd_title.find("-") > -1:
            dvd_title_slice = dvd_title[:dvd_title.find("-")]
            dvd_title_slice = cleanupstring2(dvd_title_slice)
            logging.debug("Trying title: " + dvd_title_slice)
            dvd_info_xml = callwebservice2(omdb_api_key, dvd_title_slice, year)
            logging.debug("DVD STUFF: " + str(dvd_info_xml))
            # if still fail, then try slicing off the last word in a loop
        while dvd_info_xml == "fail" and dvd_title_clean.count('+') > 0:
            dvd_title_clean = dvd_title_clean.rsplit('+', 1)[0]
            logging.debug("Trying title: " + dvd_title_clean)
            dvd_info_xml = callwebservice2(omdb_api_key, dvd_title_clean, year)
    ##try to set our new title
    try:
        dvd_title2 = dvd_info_xml['Title']
        dvd_release_date = dvd_info_xml['Year']
        disc.hasnicetitle = True
    except KeyError as a:
        # couldnt get our title
        logging.error("key Error" + str(a))
        return [None, None]
    return [dvd_title2, dvd_release_date]


def getbluraytitle(disc):
    """ Get's Blu-Ray title by parsing XML in bdmt_eng.xml """
    try:
        with open(disc.mountpoint + '/BDMV/META/DL/bdmt_eng.xml', "rb") as xml_file:
            doc = xmltodict.parse(xml_file.read())
    except OSError:
        logging.error("Disc is a bluray, but bdmt_eng.xml could not be found.  Disc cannot be identified.")
        return [None, None]

    try:
        bluray_title = doc['disclib']['di:discinfo']['di:title']['di:name']
    except KeyError:
        logging.error("Could not parse title from bdmt_eng.xml file.  Disc cannot be identified.")
        return [None, None]

    bluray_modified_timestamp = os.path.getmtime(disc.mountpoint + '/BDMV/META/DL/bdmt_eng.xml')
    bluray_year = (datetime.datetime.fromtimestamp(bluray_modified_timestamp).strftime('%Y'))

    bluray_title = unicodedata.normalize('NFKD', bluray_title).encode('ascii', 'ignore').decode()

    bluray_title = bluray_title.replace(' - Blu-rayTM', '')
    bluray_title = bluray_title.replace(' Blu-rayTM', '')
    bluray_title = bluray_title.replace(' - BLU-RAYTM', '')
    bluray_title = bluray_title.replace(' - BLU-RAY', '')
    bluray_title = bluray_title.replace(' - Blu-ray', '')
    return bluray_title, bluray_year


def clean_for_filename(string):
    """ Cleans up string for use in filename """
    string = re.sub('\[(.*?)\]', '', string)
    string = re.sub('\s+', ' ', string)
    string = string.replace(' : ', ' - ')
    string = string.replace(': ', ' - ')
    string = string.strip()
    return re.sub('[^\w\-_\.\(\) ]', '', string)


# pylint: disable=C0103


def main(disc):
    # args = entry()

    disc.hasnicetitle = False
    try:
        disc_title, disc_year = getdvdtitle(disc)
        # logging.info("INFO: "+str(disc_title)+" : "+str(disc_year))
        if disc_title:
            disc_title = clean_for_filename(disc_title)
            logging.info("getmovietitle dvd title found: " + disc_title + " : " + disc_year)
        else:
            logging.warning("DVD title not found")
            disc_title = disc.label
            disc_year = ""
    except Exception:
        disc_title, disc_year = getbluraytitle(disc)
        if disc_title:
            disc_title = clean_for_filename(disc_title)
            logging.info("getmovietitle bluray title found: " + disc_title + " : " + disc_year)
            disc.hasnicetitle = True
        return (disc_title, disc_year)
    else:
        logging.info(str(disc_title) + " : " + str(disc_year))
        if disc_title:
            disc.hasnicetitle = True
        logging.info("Returning: " + str(disc_title) + ", " + str(disc_year))
        return (disc_title, disc_year)


def callwebservice2(omdb_api_key, dvd_title, year=""):
    """ Queries OMDbapi.org for title information and parses if it's a movie
        or a tv series """

    logging.debug("***Calling webservice with Title: " + dvd_title + " and Year: " + year)
    try:
        strurl = "http://www.omdbapi.com/?t={1}&y={2}&plot=short&r=json&apikey={0}".format(omdb_api_key, dvd_title,
                                                                                           year)
        logging.debug(
            "http://www.omdbapi.com/?t={1}&y={2}&plot=short&r=json&apikey={0}".format("key_hidden", dvd_title, year))
        dvd_title_info_json = urllib.request.urlopen(strurl).read()
        logging.debug("Webservice works")
    except Exception as w:
        logging.debug("Webservice failed" + str(w))
        return "fail"
    else:
        doc = json.loads(dvd_title_info_json.decode())
        logging.debug(str(doc))
        if doc['Response'] == "False":
            logging.debug("Webservice failed with error: " + doc['Error'])
            return "fail"
        else:
            new_year = doc['Year']
            new_title = doc['Title']
            logging.debug("Webservice successful.  New Year is: " + new_year)
            logging.debug("Webservice successful.  New Title is: " + new_title)
            return doc


def cleanupstring2(string):
    # clean up title string to pass to OMDbapi.org
    string = string.strip()
    return re.sub('[_ ]', "+", string)
`

**Comment by 1337-server** [comment]
I changed the getmovietitle.py to use omdb instead of windows media, it saves headaches for some, but not all of them.

[getmovietitle.zip](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/4567358/getmovietitle.zip)

**Comment by emmakat** [comment]
@1337-server  I think this functionality is in identify.py which is https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/v2.1_dev/arm/ripper/identify.py

**Comment by 1337-server** [comment]
Sorry i havent really tried 2.1 dev im still running masterv2.
And its doesnt have this funcionality in masterv2
i did take a look at 2.1 dev branch though, and identify_dvd is still calling Windows Media Metaservices Is there any reason its still being left in ?

**Comment by cr45hmurphy** [comment]
I see that this issue was closed. Was a resolution found? It shows that it’s a duplicate, but there isn’t a linked issue to what it’s a duplicate of.
