### ISSUE TITLE
metaservices.windowsmedia.com is no longer valid

### ISSUE THREAD

**Issue by garbled1** [automatic-ripping-machine/automatic-ripping-machine#312]
### Description
metaservices.windowsmedia.com is no longer valid

### Environment
Irrelvant

### Log file

Per the below, I think the actual windows media service is down.  Which explains why none of my rips are getting titles.

https://support.microsoft.com/en-us/help/4488539/changes-metadata-services-windows-media-center-media-player

wget 'http://metaservices.windowsmedia.com/pas_dvd_B/template/GetMDRDVDByCRC.xml?CRC=570eed4da7c52238'
--2019-10-15 17:31:43--  http://metaservices.windowsmedia.com/pas_dvd_B/template/GetMDRDVDByCRC.xml?CRC=570eed4da7c52238
Resolving metaservices.windowsmedia.com (metaservices.windowsmedia.com)... 157.56.59.240
Connecting to metaservices.windowsmedia.com (metaservices.windowsmedia.com)|157.56.59.240|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

**Comment by len0rd** [comment]
See #295 Sounds like the dev branch has a fix

**Comment by garbled1** [comment]
It's not a fatal error for me, it's just that obviously nothing gets titled anymore, which means I need to do it manually.

**Comment by obsidiangroup** [comment]
Just wondering, since I have had no luck and have had other things come up -- has there been any traction with finding a suitable replacement for a way to identify dvd movie names from the crc64 hash?
