### ISSUE TITLE
Cant seem to get handbrake to write a file with DTS as the Default soundtrack

### ISSUE THREAD

**Issue by dbuttric** [automatic-ripping-machine/automatic-ripping-machine#317]
### Description
I think I have my Handbrake presets set up correctly. In the audio section, the first track is set for auto passthrough, and only DTS is checked in the list of Passthrough tracks.
I have english as the language, and have chosen the 'All Audio tracks for the given language' for selection criteria.
I have an AC3 track as fallback.
When HandBrake writes out the file, the DTS track is the last one in the list, and it is not the default.

When I go to play the file, the player choses the default track, which is the AC3 track.

I then used mkvpropedit to set the default to the DTS track, and now my player is using that when i playback, so I have a workaround for this.

I'm not convinced that this is an ARM problem - it seems more like a Handbrake problem. But, I thought I'd post this here, perhaps others have seen this problem?

### Environment
Ubuntu 18.04.3
v2.1_dev
### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[MINORITY_REPORT.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/4002923/MINORITY_REPORT.log)

**Comment by 1337-server** [comment]
Closing as stale
