### ISSUE TITLE
no automatic start after insert cd

### ISSUE THREAD

**Issue by gravidigit** [automatic-ripping-machine/automatic-ripping-machine#322]
### Description
My Arm Maschine dont start automatic after insert a dvd. With this execute command starts manualy as root. Thanks!

/usr/bin/python3 /opt/arm/arm/main.py -d sr0

### Environment
Ubuntu 18.0.4 LTS / VMWARE

### Log file
no Logs found

**Comment by flammableliquids** [comment]
I found a similar problem and could only start manually. Are you seeing anything in the dmesg logs when you insert the dvd?

**Comment by gravidigit** [comment]
Hi, no hit in the dmesg log. Have you any other idea?

**Comment by flammableliquids** [comment]
I had a similar problem, and tried a bunch of things. I'm not sure what was the actual final solution.

Your /etc/fstab must contain all the DVD Drives your trying to use. (Correct spacing, no fullstops instead of comma's)

Also trying something like 

```
udevadm control --reload-rules
```

**Comment by gravidigit** [comment]
Thanks, my fstab is fine. i have found a workaround. is the arm.yaml config file in /opt/arm not present, run the software automaticly.

**Comment by supradj** [comment]
> 
> 
> Thanks, my fstab is fine. i have found a workaround. is the arm.yaml config file in /opt/arm not present, run the software automaticly.

Hi, i have the same issue
my `/etc/fstab`: 
```
/dev/sr0  /mnt/dev/sr0  udf,iso9660  user,noauto,exec,utf8  0  0
/dev/sr1  /mnt/dev/sr1  udf,iso9660  user,noauto,exec,utf8  0  0

UUID=e2d43a53-dea9-485e-a953-06e92846080b /mnt/ext ext4 defaults 0 2
```
Have installed the v2.1 from git.
US 18.04.4 LTS (fresh)

@gravidigit what do you mean? Deleting the arm.yaml file?

Cheers ;)

**Comment by gravidigit** [comment]
yes this did i mean.
