### ISSUE TITLE
DVD Drive to HDD mapping

### ISSUE THREAD

**Issue by flammableliquids** [automatic-ripping-machine/automatic-ripping-machine#323]
### Description
I need to backup all 300~ of my DVD collection. From what I can see in the arm.yaml configuration, it is many DVD Drives to one HDD.
I figured with a multiple DVD drive setup (3 drives in the 1 PC), the best solution would be to have each drive to map to a different HDD. Reducing IO contention.

My question is; is it possible to have multiple installations of the arm script setup (e.g.: /opt/arm , /opt/armsr1, /opt/armsr2 ) with one arm user? That way I can have multiple configurations, pointing to multiple drives, all ripping and encoding at the same time.
Also, if this is possible, would this be possible with 1 installation running v2.0 and another running v2.1_dev

### Environment
[Ubuntu v18]
[ARM Release Version v2]

**Comment by IInvocation** [comment]
Didnt see a posdibility for this. But you could also merge your disks for something close to raid0/raid10. Personally - i'm using 2 drives backing up to a custom nas. My 2 drives together only cause like 350 mbit/s - not even close to maxing out a gigabit connection. Let alone a hdd.

**Comment by shelvacu** [comment]
There is currently no way to run ARM from different directories without modifying the code directly, which also means there's no way to run multiple instances.

I would recommend looking into software raid solutions like mdadm and zfs.
