### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by gravidigit** [automatic-ripping-machine/automatic-ripping-machine#324]
Have any a guide to install the current version on ubuntu or debian? The git guide is not function.

**Comment by flammableliquids** [comment]
[This](https://www.fosslinux.com/6406/how-to-install-ubuntu-server-18-04-lts.htm) is the guide I used.  I found it quite comprehensive.

**Comment by gregs007** [comment]
Followed the guide for ubuntu 18.04 and it _almost_ worked. However I had to change one item to make it work. Calling werkzeug library from robobrowser library seems to have changed syntax/broken in latest versions. This is not an issue with ARM, it's an issue with interoperability of two perl libraries.

In file:
`/usr/local/lib/python3.6/dist-packages/robobrowser/browser.py`

I had to change:
`from werkzeug import cached_property`

to:
`from werkzeug.utils import cached_property`

After I did that, I was able to rip successfully. The error I got was:

```
Traceback (most recent call last):
  File "/opt/arm/arm/main.py", line 19, in <module>
    from getkeys import grabkeys
  File "/opt/arm/arm/getkeys.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'
```
