### ISSUE TITLE
Possibility to rip all DVDs as data

### ISSUE THREAD

**Issue by quizilkend** [automatic-ripping-machine/automatic-ripping-machine#326]
Our movie collection consists of the iso files directly ripped from the DVDs.
Is it possible to configure arm that all DVDs are ripped as isos, independently of their content?
I searched through the issues but found only people who had this behaviour accidentially.

**Comment by Halfang** [comment]
Not being experienced on this, I would think that modifying identify.py would give you an opportunity to change all video types to data, and thus "burn" them as .iso
