### ISSUE TITLE
Problem getting udevadm to execute correctly

### ISSUE THREAD

**Issue by LunarEngineer** [automatic-ripping-machine/automatic-ripping-machine#329]
### Description

I'm running arm in an Ubuntu 18.04 VM being run headlessly on a base Ubuntu machine.

I know that it's using sr0 as the device and I can successfully mount after going through the install process.

I can also run the script manually and it does generate a logfile and kicks off pushbullet but nothing happens save for

"""
[2020-03-14 17:12:23] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.
"""

I'm suspicious that something's wrong with my udev
[51.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/4333088/51.txt)

Also, the mail for arm was getting error "main.py: error: argument -d/--devpath: expected one argument" but now is getting "FileNotFoundError: [Errno 2] No such file or directory: '/dev/loo'

*No* logs are being created without me manually running the script.

### Environment
Ubuntu 18.04.4 LTS
Running V2_master cloned down as of today with commit 3f40908a32c265d548857cc7d9eb4f0d72f2099b

### Log file
[empty.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/4333087/empty.log)

**Comment by crunchymetal** [comment]
Don't have a solution for you, just wanted to let you know I've recently stumbled across this project and have the exact same symptoms.

**Comment by wyattearp** [comment]
FYI - I just managed to get ubuntu 18.04 working with numerous things wrong:
* needing to patch in fix for robobrowser issue with werkzeurg (https://stackoverflow.com/a/60157748/6886)
* needing to manually build (and copy in) `ccextractor` (see #273 and fix is about 1/2 down in config file)

I would attempt to run the command in the arm_warapper by hand with `python3` - I can't find it in my history, but I think I had some other packages that didn't install and it was silently throwing the python error code.

**Comment by hbast** [comment]
@wyattearp was right. I'm also on ubuntu 18.04 an got the werkzeug error. Here is the mail from arm.

`
From arm@arm.fritz.box  Tue Apr 14 15:38:17 2020
X-Original-To: arm
Subject: Output from your job       31
To: arm@arm.fritz.box
Date: Tue, 14 Apr 2020 15:38:17 +0200 (CEST)
From: arm@arm.fritz.box

/opt/arm/arm/config.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(f)
Traceback (most recent call last):
  File "/opt/arm/arm/main.py", line 19, in <module>
    from getkeys import grabkeys
  File "/opt/arm/arm/getkeys.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "/usr/local/lib/python3.7/dist-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.7/dist-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/local/lib/python3.7/dist-packages/werkzeug/__init__.py)
`

**Comment by wndrslope** [comment]
It took me a while to find this thread but I am glad I did. I am also experiencing the exact same thing. I am running Ubuntu 20.04.2 LTS natively on a Dell XPS 13 9360 (075B).
My log files:
The empty.log only wrote the first time I ran it. I'm not sure why it never wrote to it again.
[empty.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5936285/empty.log)

[None_161258666488.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5936284/None_161258666488.log)

[ROBINHOOD_161258758040.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5936287/ROBINHOOD_161258758040.log)

And here is my 51-automedia.rules:

[51-automedia.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5936289/51-automedia.txt)

Thanks for the awesome ripping machine and help with my issue.

**Comment by 1337-server** [comment]
Can you try running `sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0`

**Comment by wndrslope** [comment]
@1337-server 
Thanks for the quick reply. I didn't expect anyone to be online at the moment. Here is the output for the command you gave me:

`/opt/arm/arm/config/config.py:10: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(f)
/dev/sr0
Log: /home/arm/logs/None_161259137477.log
`

Thanks again for your help,
-wndrslope

**Comment by 1337-server** [comment]
There is an error somewhere (probably multiple)

`None_161259137477.log` means it cant get the title from the disc

But can you try the solution from #396 and we can go from there.

Once you have added the fix can you run the command again and then post both the output of the file and the logfile it outputs in the log folder.

**Comment by wndrslope** [comment]
I applied the change and now I have:
`:~$ sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0
/dev/sr0
Log: /home/arm/logs/None_161259294966.log
`
[None_161259294966.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5936370/None_161259294966.log)

Thanks again for your quick responses.

**Comment by 1337-server** [comment]
Does this 

> 
> 
> I applied the change and now I have:
> `:~$ sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0 /dev/sr0 Log: /home/arm/logs/None_161259294966.log `
> [None_161259294966.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5936370/None_161259294966.log)
> 
> Thanks again for your quick responses.

Does this happen with all discs ?

Can you try running as root to see if this is some permission issue ?

**Comment by wndrslope** [comment]
> Does this
> 
> > I applied the change and now I have:
> > `:~$ sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0 /dev/sr0 Log: /home/arm/logs/None_161259294966.log `
> > [None_161259294966.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5936370/None_161259294966.log)
> > Thanks again for your quick responses.
> 
> Does this happen with all discs ?
> 
> Can you try running as root to see if this is some permission issue ?

I can try when I get back from vacation on Saturday.  Thanks again for the help.
