### ISSUE TITLE
TV show episodes are being combined into one large file

### ISSUE THREAD

**Issue by andrewguest** [automatic-ripping-machine/automatic-ripping-machine#330]
### Description
When I use ARM on a disk that contains TV episodes, it first creates one large file containing all of the episodes together and then creates files for the individual episodes.

I just want the individual episodes in individual files. I'm assuming this is a MakeMKV issue, since it's happening when the files are copied from the disk.

-rw-rw-r-- 1 arm arm 1.4G Mar 15 23:05 title_t00.mkv
-rw-rw-r-- 1 arm arm 273M Mar 15 23:38 title_t01.mkv  
-rw-rw-r-- 1 arm arm 226M Mar 16 00:43 title_t02.mkv
-rw-rw-r-- 1 arm arm 216M Mar 15 23:54 title_t03.mkv
-rw-rw-r-- 1 arm arm 229M Mar 16 00:11 title_t04.mkv
-rw-rw-r-- 1 arm arm 216M Mar 15 23:21 title_t05.mkv
-rw-rw-r-- 1 arm arm 242M Mar 16 00:27 title_t06.mkv

In this output I don't want **title_t00.mkv** to  even be created, if possible.

**Comment by rj175** [comment]
Hey @andrewguest i had the same thing happen to me when I first started using arm. I think this is caused by the ‘play all’ option you get on these kind of DVDs. My work around was to adjust the max length to 2400. This means that nothing over 40minutes would be ripped.
