### ISSUE TITLE
This project does not work, is unmaintained, do not use

### ISSUE THREAD

**Issue by emmakat** [automatic-ripping-machine/automatic-ripping-machine#332]
I have followed the steps one by one, on 16.04 and 18.04 and it simply does not work no matter what. I've checked the various issues and associated fixes, to no avail. I wish the owner would take this offline if it will not ever work properly. Wasted another 2 hours tonight trying again.

**Comment by accountnumber3** [comment]
Use the v2.1 dev branch. Post some useful info if you want a useful response.

**Comment by emmakat** [comment]
Thanks! Apologies for the curt message, that was not helpful. I appreciate your response, and will try the 2.1 dev branch. It might be helpful to others to update the readme with that suggestion, in case they can avoid my error.
