### ISSUE TITLE
Unable to get ARM running

### ISSUE THREAD

**Issue by bramdean** [automatic-ripping-machine/automatic-ripping-machine#333]
### Description
ARM doesn't run automatically or even if I run manually.

I can see and play DVD's - /mnt/dev/sr0

I had no errors during the setup or install process

### Environment
OS - new clean and updated install
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

Latest version of ARM 

### Log file
I get no Log file what so ever

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by emmakat** [comment]
did you run the dev 2.1 branch? I was told to try that one because I had the exact same problem. I was about to start a new fresh install to find out.

**Comment by emmakat** [comment]
just verified 2.1 works, with one fix to the requirements.txt file just add this file at the end. It fixes the one major error referenced in issue #327 
Werkzeug==0.16.1

**Comment by bramdean** [comment]
Thank you emmakat...

I got further ... at least I have a log file now, with the following error
"Failed to open device /dev/sda to check status"

**Comment by emmakat** [comment]
ok that sounds like the drives aren't setup right in your fstab. Here's how I got mine working: 
I opened the disks application in ubuntu and for each drive I clicked the gear icon and chose edit mount options. I turned the slider for user session defaults faults off, and here's the image showing what I put in each field: 
[mount options](https://user-images.githubusercontent.com/29872150/79641934-67acd180-814f-11ea-8afe-b54196e1dd2a.JPG)

**Comment by frankcharlton** [comment]
I was just having this same issue and seemed to fix it. I followed emmakat's advice, but was still getting failures. Nothing every fully started, and I wasn't producing logs.

The fix seems to be installing the dev 2.1 version, and then editing these new flags in the config file:
`# Wait for manual identification
MANUAL_WAIT: true

# Wait tie for manual identification (in seconds)
MANUAL_WAIT_TIME: 600`

I set these to be false / 10 seconds. I think what's happening is that the metadata lookup is failing, and so we're waiting around 10 minutes while nothing is happening. Based on the latest comments on the main blog post (https://b3n.org/automatic-ripping-machine/) it sounds like the Microsoft lookup service is dead. Turn off the manual wait, and deal with the metadata yourself after the files are complete. Running my first rip now.

**Comment by emmakat** [comment]
yep, only 2.1 dev version works as far as I can tell. Did you have any luck at all with the web server by chance? I'm happily ripping many cds, but wish I could figure out that part of it all.

**Comment by frankcharlton** [comment]
No :/ But I saw you started up an issue. Hope to figure that out too!

**Comment by bramdean** [comment]
Thanks for your help so far... made huge prgress
thought was all working, took a while t read and process a dvd, was creating .mkv in raw - ejected DVD but no movie....

The following was in the log file....any ideas please?

[2020-04-19 09:57:12] ERROR ARM: Handbrake encoding of file title_t00.mkv failed with code: 2(b'')
[2020-04-19 09:57:12] INFO ARM: Handbrake processing complete
[2020-04-19 09:57:12] INFO ARM: Transcoding completed with errors.  Title(s) title_t00.mkv failed to complete.

**Comment by bramdean** [comment]
If you have a moment would you look at this log file please?
all seems to work, but the film file is never created ...... strange, because it is in the raw dir during processing....

[War_of_the_Wild.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/4499537/War_of_the_Wild.log)

**Comment by frankcharlton** [comment]
```
MSG:5014,0,2,"Saving 1 titles into directory /home/arm/media/raw/War_of_the_Wild","Saving %1 titles into directory %2","1","/home/arm/media/raw/War_of_the_Wild"
MSG:5005,128,1,"1 titles saved","%1 titles saved","1"
MSG:5036,260,1,"Copy complete. 1 titles saved.","Copy complete. %1 titles saved.","1"
[2020-04-19 16:22:06] INFO ARM: Exiting MakeMKV processing with return value of: /home/arm/media/raw/War_of_the_Wild
[2020-04-19 16:22:06] INFO ARM: Transcoding file title_t00.mkv to /home/arm/media/unidentified/War_of_the_Wild/title_t00.mkv
Cannot load libnvidia-encode.so.1
Cannot load libnvidia-encode.so.1
Cannot load libnvidia-encode.so.1
Cannot load libnvidia-encode.so.1
[16:22:06] hb_init: starting libhb thread
[16:22:06] thread 7fdd17074700 started ("libhb")
HandBrake 1.2.1 (2019021900) - Linux x86_64 - https://handbrake.fr
2 CPUs detected
Invalid preset High Profile

```
Pretty new to this, but it looks like for whatever reason your installation of Handbrake doesn't have the High Profile preset. I'd try a few things - reinstall the Handbreak CLI portion, and if that doesn't work, I'd try changing the profiles listed in /opt/arm/arm.yaml.

I'm currently setting these to:
```
##########################
## HandBrake Parameters ##
##########################

# Handbrake preset profile for DVDs
# Execute "HandBrakeCLI -z" to see a list of all presets
HB_PRESET_DVD: "Super HQ 720p30 Surround" 

# Handbrake preset profile for Blurays
# Execute "HandBrakeCLI -z" to see a list of all presets
HB_PRESET_BD: "Super HQ 1080p30 Surround" 
```

**Comment by frankcharlton** [comment]
See here: https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/271

**Comment by bramdean** [comment]
Thanks frankcharlton - that worked ....
now let the fun begin.
Appreciate the help!
