### ISSUE TITLE
Werkzeug => v1.0.0 are incompatible with ARM

### ISSUE THREAD

**Issue by toolstack** [automatic-ripping-machine/automatic-ripping-machine#336]
### Description
The Werkzeug v1 and newer library has known backward compatibility issues and ARM will fail.

Easiest short term solution is to install 0.16.0 via pip3:
```
pip3 uninstall werkzeug
pip3 install werkzeug==0.16.0
```

### Environment
Ubuntu 18.04 Server
v2_fixes

### Log file
```
Traceback (most recent call last):
  File "/opt/arm/arm/main.py", line 20, in <module>
    from getkeys import grabkeys
  File "/opt/arm/arm/getkeys.py", line 2, in <module>
    from robobrowser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.6/dist-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'
```

**Comment by emmakat** [comment]
suggest that v2.1_dev branch be run, as that's the only version that works afaik.
If you edit requirements.txt in /opt/arm and add this to the end 
Werkzeug==0.16.1 
it will fix this issue.

**Comment by tandell** [comment]
Just to confirm this issue and fix.

Was running Ubuntu 18.04 / python 3.7 / unknown v2_master checkout

I did a dist-upgrade to Ubuntu 20.04 / python 3.8. At this point ARM stopped working with some misleading libdvdcss errors. Started troubleshooting and ran across this issue.

At a certain point, I reran `sudo pip3 install -r requirements.txt` and caught that `werkzeug 1.x` was installed. Followed toostack's uninstall and emmakat's suggestion. I then reran the pip3 install. ARM now appears to be working again. (even though `dmesg` is still reporting the libdvdcss errors....)
