### ISSUE TITLE
When one CD has a read_error, all other devices stop.

### ISSUE THREAD

**Issue by speedtoys** [automatic-ripping-machine/automatic-ripping-machine#339]
When there is a read error (a scratched disk is being worked out, etc) all other sr* devices just..stop, and will get to read a tiny amount of data only between retries, every few seconds.

Why?

### Environment

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
v2.1_dev_fix_yamlfilepath

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[scsi_read error: sector=154414 length=27 retry=0
                 Sense key: 3 ASC: 11 ASCQ: 0
                 Transport error: Medium reading data from medium
                 System error: Input/output error
scsi_read error: sector=154143 length=27 retry=0
                 Sense key: 3 ASC: 11 ASCQ: 0
                 Transport error: Medium reading data from medium
                 System error: Input/output error
]

Video..when a retry logs, everyone gets a small IO..then pause.

I have 11 drives in operation, not all seen.

**Comment by flammableliquids** [comment]
I have 3 drives, and I am able to error out 1 disk and continue on with the others.

Have you tried v2.1_dev, or v2.2 ?

Also are the error's your getting, coming from the job log? Dmesg? or Server mail?
