### ISSUE TITLE
Movies are not moved to completed directory, name is not correct

### ISSUE THREAD

**Issue by kiwinv** [automatic-ripping-machine/automatic-ripping-machine#340]
### Description
Hi, I've just moved from the v2 master branch to dev to work around the Windows Media API being down but have been having issues with my DVD rips. 
I have tried manually setting the media type to 'movie', renaming from the ui, using the handbrake.py and identify.py from pull request #338 and using a different API key for OMDb but still receive the error 
>TypeError: move_files() takes from 3 to 4 positional arguments but 5 were given
The folder containing the title remains in the unidentified folder with the name unchanged. An empty folder appears in 'completed' and nothing appears in 'movies'.

Any help is greatly appreciated!

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[HAPPY_FEET_TWO.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/4621842/HAPPY_FEET_TWO.log)
[A_BUGS_LIFE.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/4621844/A_BUGS_LIFE.log)

**Comment by 1337-server** [comment]
Had a quick skim over the code for v2.1 and it seems that a check for Valid dvds was never included. It is for blueray but not for dvd. Meaning that ARM will alway default to using the ARM Directory and not the media directory for DVDs.

You would need to include a check yourself in the main.py.
somewhere around line 144

```
    if job.disctype in ["dvd", "bluray"]:
        # get filesystem in order
        hboutpath = os.path.join(job.config.ARMPATH, str(job.title))

        if (utils.make_dir(hboutpath)) is False:
            ts = round(time.time() * 100)
            hboutpath = os.path.join(job.config.ARMPATH, str(job.title) + "_" + str(ts))
            if(utils.make_dir(hboutpath)) is False:
                logging.info("Failed to create base directory.  Exiting ARM.")
                sys.exit()
```

You can use the job.hasnicetitle something like this 
 ```
 if job.disctype in ["dvd", "bluray"]:
        # get filesystem in order
        if (job.hasnicetitle):
            hboutpath = os.path.join(job.config.MEDIA_DIR, str(job.title))
        else:
            hboutpath = os.path.join(job.config.ARMPATH, str(job.title))
        if (utils.make_dir(hboutpath)) is False:
            ts = round(time.time() * 100)
            hboutpath = os.path.join(job.config.ARMPATH, str(job.title) + "_" + str(ts))
            if(utils.make_dir(hboutpath)) is False:
                logging.info("Failed to create base directory.  Exiting ARM.")
                sys.exit()
```

Hope this helps

**Comment by 1337-server** [comment]
Are you sure youre using the changes from #338 ? 

Your logs are still showing windows media failures, but #338 removes this.
