### ISSUE TITLE
  File "/opt/arm/arm/ripper/main.py", line 110, in main  TypeError: must be str, not NoneType

### ISSUE THREAD

**Issue by emmakat** [automatic-ripping-machine/automatic-ripping-machine#342]
New install of 2.1 dev branch, and a strange error occurred. I searched issues, and someone had this same problem before. Here is my error:
[2020-05-19 19:57:43] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 416, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    utils.notify(job, "ARM notification", "Found music CD: " + job.label + ". Ripping all tracks")
TypeError: must be str, not NoneType

I followed the fix and was able to proceed with ripping audio CD's. 

Previous Error:
___________________________________________________
I should have been a little more clear... the existing main.py has...

`...music CD: " + job.label + ". Ripping...`

...it needs to be changed (in both places) to...

`...music CD: " + str(job.label) + ". Ripping...`

job.label is blank (see my other comment above), but at least this gets the CD rip running...

_Originally posted by @mg-man in https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/292#issuecomment-493022720_

**Comment by flammableliquids** [comment]
There were a few notifications that had str errors.
They are all fixedin v2.2_dev now.
