### ISSUE TITLE
Bug: No detected main feature causes program termination with error (branch v2.1_dev)

### ISSUE THREAD

**Issue by goldcove** [automatic-ripping-machine/automatic-ripping-machine#356]
File: arm/ripper/handbrake.py
Function: handbrake_mainfeature

Line 35 `track = job.tracks.filter_by(main_feature=True).first()` will be empty if there is no main feature.
Line 39 `track.filename = track.orig_filename = filename` will fail since it does not have "filename"

A failed fix attempt on my part was to revert to ripping all tracks, by directly calling handbrake_all. This however leads to a ripping loop...

A consensus on dealing with this issue is needed. Should the program automatically revert to ripping all tracks, restart the identification process and let the user change ripping method via GUI or have the user change global settings?

If I get more time, I'll investigate further.

**Comment by mishley** [comment]
I haven't dug in yet but this appears to only be an issue with Blu-Ray discs and not DVDs. DVDs which do not have a title are tracked as `not_identified` vs `None` and the string concatenation works. Probably has to do with the `backup` ripping method for Blu-Ray vs. whatever it is that is done by default with DVDs?

**Comment by flammableliquids** [comment]
Haven't ripped a BluRay in a while, but when I did, I only experienced a similar problem with Mad Max Triology. I will grab a couple of different Rays and test them out to try and find a common symptom.

**Comment by flammableliquids** [comment]
Tested out with my Mad Max BD box set.
I kept finding tracks, but not one of them was the main track. 
Handbrake simply can't seem to find the Feature. 
Even tried ripping with makemkv at command line and could not find the main movies.

I will try and install the makemkv gui and try and pull content via gui, in case i'm missing something at command line.
