### ISSUE TITLE
Flake8 warnings

### ISSUE THREAD

**Issue by cosmicflame** [automatic-ripping-machine/automatic-ripping-machine#359]
### Description
Running flake8 (as per `travis.yaml` returns warnings. This has caused some recent Travis CI builds to fail.

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

Windows Subsystem for Linux 2 - Ubuntu 20.04, running Python 3.8.2
(The `pythonloc` command below is a [wrapper](https://pypi.org/project/pythonloc/) for using [PEP 582](https://www.python.org/dev/peps/pep-0582/) modules - don't worry about it.

### Log file

```
✘-1 ~/github/cosmicflame-forks/automatic-ripping-machine [v2_fixes {.}|●upstream/v2_fixes…1⚑ 6]
17:12 $ pythonloc -m flake8 arm
arm/getmovietitle.py:43:5: F841 local variable 'e' is assigned to but never used
arm/getmovietitle.py:65:5: F841 local variable 'e' is assigned to but never used
arm/getmovietitle.py:90:22: W605 invalid escape sequence '\['
arm/getmovietitle.py:90:29: W605 invalid escape sequence '\]'
arm/getmovietitle.py:91:22: W605 invalid escape sequence '\s'
arm/getmovietitle.py:95:22: W605 invalid escape sequence '\w'
arm/getmovietitle.py:95:24: W605 invalid escape sequence '\-'
arm/getmovietitle.py:95:27: W605 invalid escape sequence '\.'
arm/getmovietitle.py:95:29: W605 invalid escape sequence '\('
arm/getmovietitle.py:95:31: W605 invalid escape sequence '\)'
arm/handbrake.py:109:56: W605 invalid escape sequence '\('
arm/handbrake.py:109:59: W605 invalid escape sequence '\)'
arm/handbrake.py:111:57: W605 invalid escape sequence '\('
arm/handbrake.py:111:60: W605 invalid escape sequence '\)'
arm/handbrake.py:278:5: F841 local variable 'hb_error' is assigned to but never used
```

The violated rules appear to be [F841](https://www.flake8rules.com/rules/F841.html) and [W605](https://www.flake8rules.com/rules/W605.html).

I will submit a pull request shortly again the `v2_fixes` branch to resolve these.

**Comment by flammableliquids** [comment]
Reolved by #360
