### ISSUE TITLE
Project health & future

### ISSUE THREAD

**Issue by cosmicflame** [automatic-ripping-machine/automatic-ripping-machine#361]
### Description
Is the mainline repo dead, and if so what do we do?

### Status
This project is awesome. It does something really useful, and it does it well. However, the last time a PR was merged was January 2019. The last commit to `v2.1_dev` was July 2019. The other branches haven't been updated for two years. This is not a good sign of project health. Hey, it's been a difficult year for everybody _globally_, so it's perfectly understandable!

![image](https://user-images.githubusercontent.com/2258123/94998041-15e5ef80-05a7-11eb-84ae-416330b3c1e1.png)

### Active Forks

@flammableliquids appears to have the most active fork, with flammableliquids/automatic-ripping-machine. 

There are three sub-forks of this fork, which is more than any other fork has. These commits aren't getting merged back into the upstream repo, unfortunately, although many of them have been submitted as PRs (based on a very quick glance).

![image](https://user-images.githubusercontent.com/2258123/94998144-8c82ed00-05a7-11eb-9001-fbfdacceb436.png)

### Options

Clearly a user fork will never have the same brand recognition as a GitHub organisation. Unfortunately, the `automatic-ripping-machine` org only appears to have one member - he who hath gaveth his project life, @ahnooie himself.

![image](https://user-images.githubusercontent.com/2258123/94998198-f8655580-05a7-11eb-89fc-7d4dc9930a52.png)

In an ideal scenario a few more committers would get access to the org so we can bring commits from forks back into the mainline. If this is not possible, I would like to propose that we create a new org and rally the active committers to around a single fork. I think we'd all like to see this project thrive ❤️.

Paging @ahnooie  , @muckngrind4, and @flammableliquids for opinions - and I do apologise if this has been discussed before and a conclusion reached. I'm just a nobody with a large CD collection who wants to help out!

**Comment by colonelpopcorn** [comment]
I reached out to Ben, and he's made @flammableliquids the admin on the repository. Not sure about the organization, but now some progress can be made at least. I really would love to see the automatic metadata fetching put back in somehow, but there doesn't seem to be an alternative to Windows Media Metaservices yet.

**Comment by cosmicflame** [comment]
That's brilliant! Thank you, @colonelpopcorn, and congratulations @flammaableliquids! 🎉

**Comment by colonelpopcorn** [comment]
@cosmicflame I'm not sure what @ahnooie meant when he said that @flammableliquids is now the admin. There's still no other members of the organization and that seems like it would be a key piece of being made "admin" of the project. I might reach out again and see if he can add the users that you mentioned in the OP to the organization.

**Comment by cosmicflame** [comment]
Thank you, that would be good! I'd be happy to be added as well, but given I've only filed one PR so far I realise that might not be on offer :)

**Comment by MrTechGadget** [comment]
Thanks guys for the interest in this, I did a few minor contributions several years ago about the time Ben moved this to an organization and Derek undertook the major rewrite to v2. I had every intention of helping out with v2 and then life happened and I dropped the ball. Looks like Derek has some stuff going on and can't contribute to this anymore. Not sure all the details of how GitHub does the private vs public views of organization, but there are three people in the org. Ben and Derek are owners, and can add others, and I am a member still from back then. My rights are very limited but I'm very much still interested in this project's future, as are the others that have posted here. @ahnooie probably meant he is ok with making @flammableliquids an admin, looks like that hasn't occurred yet.

I'm happy to step up and help in any way I can.

**Comment by ahnooie** [comment]
@cosmicflame so, I forgot about the org.... @MrTechGadget you're now an org owner and I also invited @flammableliquids to the org as an owner so hopefully, that'll get things moving forward.  If I still missed something feel free to shoot me another email.

**Comment by flammableliquids** [comment]
Thanks for making me an Admin.
I am new to using github, and will try and merge my changes (I labeled v2.2)  into v2.1_dev
Once I do that, I will rebuild my setup test on v2.2.

Sorry for the delayed responses to this thread.
<tangent>I spent a few weeks trying to get my RTX580 working on Ubuntu 20 so that I could use it and VCE to accelerate media encoding. I simply could not get the VCE encoder to appear no matter what I did. And I am now going back to NVENC</tangent>

**Comment by MrTechGadget** [comment]
Excellent, I am ready to rebuild my box as well and am happy to assist with
testing and keep up with some of the repo management so you can focus on
commits. :)

**Comment by flammableliquids** [comment]
Ok, I think I have merged all my changes to the master. @cosmicflame @MrTechGadget do you guys want to be approvers / reviewers on Pull Requests to the master?
For some reason I am hesitating on unilaterally pushing my changes to the master.

**Comment by colonelpopcorn** [comment]
@flammableliquids I'd recommend making a tag for where master is at right now. That way anyone who wants to continue using the older version can just check out the tag. We can add a section in the README that provides that process. It is risky, especially if a user automated the update process and pinned it to master, but adding the tag would make fixing an automation script pretty easy.

**Comment by cosmicflame** [comment]
Sorry @flammableliquids , not sure how I missed your message! I'm happy to be a PR reviewer/approver - feel free to tag me on anything that you want a review on.

**Comment by 1337-server** [comment]
I think this can now be closed as the original question has been resolved.
