### ISSUE TITLE
First Prototype of Docker Image

### ISSUE THREAD

**Issue by BenSchweikert** [automatic-ripping-machine/automatic-ripping-machine#362]
Hello everybody,
based on flammableliquids/automatic-ripping-machine fork I was able to build a first Prototype of ARM including Nvidia NVENC support for my needs. 
1) Is anybody interested in such a solution? If yes I will share my stuff
2) There is still some hard coded code included and the dockerfile is in a "just working" state, so I would need some help for finalizing and testing things. 

Please give me a short feedback, whether this is desired.

How it works:
I have a docker image which starts the ARM Webserver after starting, except of this it is not doing anything. I have a UDEV rule at the host which is started if a new disc is inserted. After that a shell script is started with a "docker exec file in docker image" which executes /bin/su -l -c "/usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr1" -s /bin/bash arm

BR
Ben

**Comment by flammableliquids** [comment]
Ben,
I got NVENC working in handbrake in ARM. 
I am going to publish the step by step procedure on how to do this (There is a specific dance to be done).
Also, I THINK I have no committed my changes to the master.
I now have 3 drives ripping at the same time. I have spent the last 2 weeks modifying the handbrake.py to only do a limited number of rips at the same time (Cheaper Nvidia cards are limited in their driver, and I have found that in a double disk insert scenarios (where the same disk gets ripped twice due to human error) that you will fail both of the rips, and your then left unsure what worked and what didn't).

I have been wanting for a long time to get this whole solution into docker (Mostly because it seems cool), but I couldn't wrap my head around how to grant a docker container privileges on the container. I also stopped when I realised that I might be opening a can of worms with trying to get NVIDIA compatibility working across the multiple variations of how you can set up docker. Plus I have found getting the nvidia docker functionality properly working in docker to be complex. (I tried to get my plex docker to work with nvidia for hardware based transcoding, and in the end gave up and went native plex install, which annoyed me greatly. Mind you, this could all be chalked up to my inexperience with docker.

I would love to see what you have done, even simply to learn.i

**Comment by MrTechGadget** [comment]
Hmm, my current ARM machine doesn’t have room for an nvidia card, but I
have been thinking about rebuilding one of my esxi machines that has an
nvidia card in it as my new ARM server... this could be interesting.

**Comment by BenSchweikert** [comment]
Hi,
I am happy to see, that other people are interested in my work. Here is what I have/ I did. Remember, this setup is working for my server etc.. no guarantee that it will work with yours ;) Currently this is hard coded to Drive **/dev/sr1**!

I have Proxmox Server with a Ubuntu 20.04 VM with a nvidia K2200 passthroughed to it to have dedicate access. (BTW: there are another Plex docker and TVHeadend docker with access to the Nvidia card). I was not able to get it working on Debian Buster, so I stopped my tests and migrated to ubuntu 20.04.


There I added the Nvidia-Docker Repo:

`
uname -a
Linux mediacenter 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/apt/sources.list.d/nvidia-docker.list 
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
`

Install Docker: https://docs.docker.com/engine/install/ubuntu/

And install these packages on it:
`dpkg -l |grep nvidia | awk '{print $2}'
libnvidia-cfg1-450-server:amd64
libnvidia-common-450-server
libnvidia-compute-450-server:amd64
libnvidia-container-tools
libnvidia-container1:amd64
libnvidia-decode-450-server:amd64
libnvidia-encode-450-server:amd64
libnvidia-extra-450-server:amd64
linux-modules-nvidia-450-server-5.4.0-48-generic
linux-modules-nvidia-450-server-5.4.0-51-generic
linux-modules-nvidia-450-server-5.4.0-52-generic
linux-modules-nvidia-450-server-generic
nvidia-compute-utils-450-server
nvidia-container-runtime
nvidia-container-toolkit
nvidia-docker2
nvidia-headless-450-server
nvidia-headless-no-dkms-450-server
nvidia-kernel-common-450-server
nvidia-kernel-source-450-server
nvidia-utils-450-server`

Download and extract the Dockerfile and other needed files: https://beert.de/docker-arm-ubuntu.tar.bz2
Enter extracted Dir of arm.

Build it: docker build --no-cache -t arm:latest .

Start it with e.g.
`
docker run -d --name=arm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=compute,video,utility -e PUID=1000 -e PGID=1000 -e RUN_OPTS="" -e TZ="Europe/Berlin" --net=host -v /dockerconfig/arm/config:/etc/arm -v /dockerconfig/arm/logs:/logs -v /dockerconfig/arm/home:/home/arm -v /mnt/media/movies:/movies -v /mnt/encode:/encode --device /dev/sr0:/dev/sr0 --device /dev/sr1:/dev/sr1 --device /dev/dri:/dev/dri -v /mnt/dev/sr1:/mnt/dev/sr1 -v /mnt/dev/sr0:/mnt/dev/sr0 --restart=always arm:latest
`

Add the following File:
`
cat /etc/udev/rules.d/51-automedia.rules 
# ID_CDROM_MEDIA_BD = Bluray
# ID_CDROM_MEDIA_DVD = DVD
# ID_CDROM_MEDIA_CD = CD
#ACTION=="change", SUBSYSTEM=="block", RUN+="/usr/local/bin/arm-docker-start.sh %k"
ACTION=="change", SUBSYSTEM=="block", RUN+="/usr/local/bin/arm-docker-start.sh"
`

Add this file, too:
`
cat /usr/local/bin/arm-docker-start.sh 

#!/bin/bash
echo "$(date): ARM is started via UDEV" >> /var/log/arm.log
docker exec arm /usr/bin/start_ripping.sh
`
Don't forget to chmod +x /usr/local/bin/arm-docker-start.sh 

Greets
Ben

**Comment by Protektor-Desura** [comment]
Where can I find the dockerfile for this? I don't see any links for it that work.

**Comment by 1337-server** [comment]
https://github.com/deekue/automatic-ripping-machine

Works it's the docker branch.

**Comment by Protektor-Desura** [comment]
I still don't see a Dockerfile or a link to Github. So I still don't see a way to create the docker myself or use an existing docker that someone else made. I thought someone already did it so I wouldn't have to reinvent the wheel myself and create a dockerfile and such. Should be a file something like this one.


FROM ghcr.io/linuxserver/baseimage-ubuntu:focal

# set version label
ARG BUILD_DATE
ARG VERSION
ARG JELLYFIN_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thelamer"

# environment settings
ARG DEBIAN_FRONTEND="noninteractive"
ENV NVIDIA_DRIVER_CAPABILITIES="compute,video,utility"

RUN \
 echo "**** install packages ****" && \
 apt-get update && \
 apt-get install -y --no-install-recommends \
	gnupg && \
 echo "**** install jellyfin *****" && \
 curl -s https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key | apt-key add - && \
 echo 'deb [arch=amd64] https://repo.jellyfin.org/ubuntu focal main' > /etc/apt/sources.list.d/jellyfin.list && \
 if [ -z ${JELLYFIN_RELEASE+x} ]; then \
        JELLYFIN="jellyfin"; \
 else \
        JELLYFIN="jellyfin=${JELLYFIN_RELEASE}"; \
 fi && \
 apt-get update && \
 apt-get install -y --no-install-recommends \
	at \
	i965-va-driver \
	intel-media-va-driver-non-free \
	${JELLYFIN} \
	libfontconfig1 \
	libfreetype6 \
	libssl1.1 \
	mesa-va-drivers && \
 echo "**** cleanup ****" && \
 rm -rf \
	/tmp/* \
	/var/lib/apt/lists/* \
	/var/tmp/*

# add local files
COPY root/ / 

# ports and volumes
EXPOSE 8096 8920
VOLUME /config

**Comment by Protektor-Desura** [comment]
I should also mention that it says that repository is:
This branch is 93 commits behind automatic-ripping-machine:v2_master.

**Comment by 1337-server** [comment]
https://github.com/deekue/automatic-ripping-machine/tree/docker - for the EXACT link to the docker branch
 
If you're unhappy at the linked being behind in commits, here is the pull request that was used to create the Dockerfile
https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/365

You will be able to take the current commit from the main arm repo and use these changes - https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/365/files
to have an updated version.

**Comment by emmakat** [comment]
I used these instructions to make a patch from the pull request https://medium.com/@dilankam/creating-a-patch-from-github-pull-request-a0381fb3606d

here's the patch https://patch-diff.githubusercontent.com/raw/automatic-ripping-machine/automatic-ripping-machine/pull/365.patch

I saved the file as 365.patch into the folder, then I ran
git apply --stat 365.patch
git apply --check 365.patch
git apply 365.patch

magic!

**Comment by emmakat** [comment]
I don't have an NVIDIA and I was planning to run this on an Ubuntu 20.04 LTS with 7 optical drives. Am I better off going with @1337-server fork and v2_devel branch? or.... issue #398 n00b friendly version?

**Comment by 1337-server** [comment]
It depends, if your new to python and just want it to work pull from the main branch it's stable and works 99% of the time. Most commits to this repo are only for bug fixes. And there is no real worry about database versions etc. 

If you're happy/ok with some things breaking or not working, taking longer to setup. And frequent changes, you can pull from my own devel branch. It has more features. But it's much less tested/used so you will be more likely to encounter bugs.

**Comment by Protektor-Desura** [comment]
Eventually it would be nice to have a script that auto imports everything in to Lidarr/Radarr/Sonarr for you automatically.

**Comment by 1337-server** [comment]
# A container/docker version of A.R.M is now available on dockerhub

Instructions are here: [Pull DOCKER](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker)

To build the image from source instructions are here: [Build DOCKER](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Building-ARM-docker-image-from-source)
