### ISSUE TITLE
Crash on processing only bluray disks.

### ISSUE THREAD

**Issue by highspeedwayne** [automatic-ripping-machine/automatic-ripping-machine#364]
I have tried the setup with several different branches and versions of Ubuntu but blueray processing always ends with the below error.  Only blueray disks are affected by this, CDs and DVDs will process correctly.

[2020-11-04 16:36:36] ERROR ARM: main.<module> A fatal error has occured and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 431, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 165, in main
    mkvoutpath = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 43, in makemkv
    rawpath = os.path.join(job.config.RAWPATH, job.title)
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

### Environment
OS Ubuntu 20.04 and 18.04
Issue occurs in multiple versions of Ubuntu.
Issue occurs in multiple branches of ARM. -  v2_Master, V2_fixes, V2_dev, V2.2_Dev

**Comment by flammableliquids** [comment]
I think the error message is saying that that os.path.join is not getting passed strings.
This doesn't make sense to me, as os.path.join is critical to ripping a BD at all, at which point NO ONE, should be able to use the makemkv function at all.
Can you please make the following change to makemkv.py, replacing line 43 in the code with 

`    logging.debug(str(str(job.config.RAWPATH) + str(job.title))`

`   rawpath = os.path.join(str(job.config.RAWPATH), str(job.title))`

and run again at debug logging level, posting the section of the log?

**Comment by highspeedwayne** [comment]
After reinstalling and attempting to recreate this issue now all the logs are 0 size and split into None_#############.log. I will re-reinstall and attempt to test again.

**Comment by flammableliquids** [comment]
I just released a patch to the log file naming. I hope that hasn't caused you a problem.
The patch was to create new log files if ones already existed.

**Comment by highspeedwayne** [comment]
I don't believe so. It was doing this previously as well. I think it has to be on my end because it's done this in several branches.

**Comment by highspeedwayne** [comment]
After another reinstall I cannot seem to get anything to work properly. The process starts once for a BluRay and once for a DVD. It fails for the bluray with the same results. I try to make the changes as referenced and it does not start. It also will not identify the DVD and puts all the logs except the BlueRay log into the None_XXXXXXXXX.log but the bluray into one named with the name of the film.

I reinstall 18.04 and tried with v2_master and v2_fixes.

**Comment by highspeedwayne** [comment]
I finally found something in the sysmail as the arm user. After making the update you had ddescribed I see

**Comment by highspeedwayne** [comment]
Finally finally got a successful reinstall with things working more reliably. With the edited makemkv.py file the process will not start. After all the reinstalls and tests and such I get a different error. Attached is a log file showing the new error.
[CHILDREN_OF_THE_CORN.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5574838/CHILDREN_OF_THE_CORN.log)

**Comment by flammableliquids** [comment]
The error indicated in that log file, appears to be on a function that is used frequently, I need to figure out if I need to fix this for all the times it's called.

**Comment by 1337-server** [comment]
> Finally finally got a successful reinstall with things working more reliably. With the edited makemkv.py file the process will not start. After all the reinstalls and tests and such I get a different error. Attached is a log file showing the new error.
> [CHILDREN_OF_THE_CORN.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5574838/CHILDREN_OF_THE_CORN.log)

You should really remove your log file.

There is a security issue with log files ATM and no user should be posting log files until it is fixed as they all contain all secert keys from your yaml config file.

The file you posted contains your secret keys.

`[2020-11-20 16:33:36] DEBUG ARM: identify.identify Identification starting: Job: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7fb65b10a898>) (imdb_id_manual=None) (start_time=2020-11-20 16:33:36.655068) (year=None) (disctype=bluray) (poster_url=None) (stop_time=None) (label=CHILDREN_OF_THE_CORN) (year_auto=None) (poster_url_auto=None) (job_length=None) (year_manual=None) (ejected=False) (status=active) (poster_url_manual=None) (video_type=unknown) (updated=False) (devpath=/dev/sr0) (no_of_titles=None) (job_id=9) (video_type_auto=None) (pid=3787) (title=None) (mountpoint=/mnt/dev/sr0) (arm_version=2.1.0-dev) (pid_hash=5054431771917246377) (video_type_manual=None) (title_auto=None) (hasnicetitle=False) (crc_id=None) (imdb_id=None) (errors=None) (title_manual=None) (logfile=CHILDREN_OF_THE_CORN.log) (imdb_id_auto=None) (config=Config: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7fb656871940>) (GET_VIDEO_TITLE=True) (WEBSERVER_IP=192.168.86.12) (HB_ARGS_DVD=--subtitle scan -F) (IFTTT_EVENT=arm_event) (RAWPATH=/home/arm/media/raw/) (MKV_ARGS=) (EMBY_USERNAME=) (SKIP_TRANSCODE=False) (WEBSERVER_PORT=8080) (HB_ARGS_BD=--subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio) (PO_USER_KEY=) (MEDIA_DIR=/home/arm/media/movies/) (DELRAWFILES=True) (EMBY_USERID=) (VIDEOTYPE=auto) (SET_MEDIA_PERMISSIONS=False) (EMBY_REFRESH=False) (PO_APP_KEY=) (EXTRAS_SUB=extras) (HASHEDKEYS=False) (EMBY_PASSWORD=) (MINLENGTH=600) (CHMOD_VALUE=777) (EMBY_SERVER=) (OMDB_API_KEY=**REMOVED**) (INSTALLPATH=/opt/arm/) (HB_PRESET_DVD=HQ 720p30 Surround) (EMBY_API_KEY=) (MAXLENGTH=99999) (SET_MEDIA_OWNER=False) (EMBY_PORT=8096) (LOGPATH=/home/arm/logs/) (HB_PRESET_BD=HQ 1080p30 Surround) (NOTIFY_RIP=True) (MANUAL_WAIT=False) (CHOWN_USER=None) (EMBY_CLIENT=ARM) (CONFIG_ID=9) (LOGLEVEL=DEBUG) (DEST_EXT=mkv) (NOTIFY_TRANSCODE=True) (MANUAL_WAIT_TIME=600) (CHOWN_GROUP=None) (EMBY_DEVICE=ARM) (job_id=9) (LOGLIFE=1) (HANDBRAKE_CLI=HandBrakeCLI) (PB_KEY=**REMOVED**) (ARMPATH=/home/arm/media/completed/) (RIPMETHOD=backup) (EMBY_DEVICEID=ARM) (ARM_CHECK_UDF=True) (DBFILE=/home/arm/db/arm.db) (MAINFEATURE=False) (IFTTT_KEY=) )
`

**Comment by alexcoolstar** [comment]
I have the same problem... My ARM will only rip dvd's and not blurays. Im running v2_fixes and ubuntu 18.04. Can someone please help?

**Comment by 1337-server** [comment]
> I have the same problem... My ARM will only rip dvd's and not blurays. Im running v2_fixes and ubuntu 18.04. Can someone please help?

Can you try making the change listed here https://github.com/1337-server/automatic-ripping-machine/commit/4245962f3af04f39d54364bbf26ee602711ec776

You may also need to make further changes but try that first and post back.

**Comment by alexcoolstar** [comment]
> > I have the same problem... My ARM will only rip dvd's and not blurays. Im running v2_fixes and ubuntu 18.04. Can someone please help?
> 
> Can you try making the change listed here [1337-server@4245962](https://github.com/1337-server/automatic-ripping-machine/commit/4245962f3af04f39d54364bbf26ee602711ec776)
> 
> You may also need to make further changes but try that first and post back.

Okay, i made the changes and it seems to work now. i'm still figuring everything out, so i might be back soon with some other issues. But at the moment it seems to work. Thanks for your help
