### ISSUE TITLE
Question Do I have to use handbrake

### ISSUE THREAD

**Issue by Iam2smart** [automatic-ripping-machine/automatic-ripping-machine#367]
I have a question about ARM do I have to use handbrake. If you do can I make a feature request to allow disabling or enabling it.
Thanks

**Comment by flammableliquids** [comment]
Please be more specific. 
Handbrake is used to not only scan the disk for the number of tracks.
And it is also used to rip the tracks, but there are parameters to skip transcode.
or do you mean use a different program to handbrake.

**Comment by Iam2smart** [comment]
Never mind I figured it out when I was setting up the program
