### ISSUE TITLE
Feature Request: Add support for Apprise for notifications

### ISSUE THREAD

**Issue by TheFiZi** [automatic-ripping-machine/automatic-ripping-machine#368]
### Description
Add support for Apprise when sending notifications: https://pypi.org/project/apprise/

It supports soooooooooo many services and might make things simpler instead of you having to add/maintain methods of notification.

### Environment
N/A

### Log file
N/A

**Comment by 1337-server** [comment]
I think a problem with this, is that you would need to add CONFIG variables for each of the services that apprise supports. So even if it makes updates less work. The config file would become much much larger.

**Comment by TheFiZi** [comment]
@1337-server That is a fair point. I guess it could be made more generic by having a "Run custom command for notifications" and you can define the apprise command with a variable for the message content from ARM. That might keep things simple.

**Comment by 1337-server** [comment]
That wasnt to say its bad. Its just that you're looking at doubling the config file size, And probably adding a bunch to the notify function in utils.py.
Im not sure how many people would actually use these though.
Also i think longer config files are better than trying to run custom commands from a variable. Although i could be wrong.

I'll look into adding some of these to the config/notify function and submit a pull request and see if it gets accpted or not.

**Comment by flammableliquids** [comment]
Why not get utils.py to look at a different config file?
Set a single single global variable in arm.yaml that allows for notifications to be globally turned on or off.
And include a comment to point to the notify.yaml (or whatever it's name could be).
That way it localizes configuration problems, and caters for those who do and do not use notifications.
@1337-server , holy crap you have put in some yards into utils.py
