### ISSUE TITLE
Transcode limit is not being respected

### ISSUE THREAD

**Issue by TheFiZi** [automatic-ripping-machine/automatic-ripping-machine#369]
### Description
I have my ARM configured to only allow one transcode at a time via `MAX_CONCURRENT_TRANSCODES: 1`

There are currently 3 transcodes running:

```bash
arm@cumin-02:/opt/arm$ ps aux |grep Hand
arm       138505  0.0  0.0   2608   356 ?        SN   18:16   0:00 /bin/sh -c nice HandBrakeCLI -i '/var/scratch/arm/media/raw/Back to the Future Part III' -o '/var/scratch/arm/media/completed/Back to the Future Part III/Back to the Future Part III.mkv' --main-feature --preset "FiZi-High-x265" --preset-import-file /home/arm/fizi-x265-hddvd.json >> /var/scratch/arm/logs/BACK_TO_FUTURE_3.log 2>&1
arm       138506 87.2 22.2 2776484 897444 ?      SNl  18:16  41:59 HandBrakeCLI -i /var/scratch/arm/media/raw/Back to the Future Part III -o /var/scratch/arm/media/completed/Back to the Future Part III/Back to the Future Part III.mkv --main-feature --preset FiZi-High-x265 --preset-import-file /home/arm/fizi-x265-hddvd.json
arm       138515  0.0  0.0   2608   420 ?        SN   18:16   0:00 /bin/sh -c nice HandBrakeCLI -i '/var/scratch/arm/media/raw/The Physics of Back to the Future with Dr. Michio Kaku' -o '/var/scratch/arm/media/completed/The Physics of Back to the Future with Dr. Michio Kaku/The Physics of Back to the Future with Dr. Michio Kaku.mkv' --main-feature --preset "FiZi-High-x265" --preset-import-file /home/arm/fizi-x265-hddvd.json >> /var/scratch/arm/logs/BACK_TO_FUTURE_1.log 2>&1
arm       138516  110 21.2 2743760 858060 ?      SNl  18:16  52:52 HandBrakeCLI -i /var/scratch/arm/media/raw/The Physics of Back to the Future with Dr. Michio Kaku -o /var/scratch/arm/media/completed/The Physics of Back to the Future with Dr. Michio Kaku/The Physics of Back to the Future with Dr. Michio Kaku.mkv --main-feature --preset FiZi-High-x265 --preset-import-file /home/arm/fizi-x265-hddvd.json
arm       138523  0.0  0.0   2608   420 ?        SN   18:16   0:00 /bin/sh -c nice HandBrakeCLI -i '/var/scratch/arm/media/raw/Back to the Future Part II' -o '/var/scratch/arm/media/completed/Back to the Future Part II/Back to the Future Part II.mkv' --main-feature --preset "FiZi-High-x265" --preset-import-file /home/arm/fizi-x265-hddvd.json >> /var/scratch/arm/logs/BACK_TO_FUTURE_2.log 2>&1
arm       138524 85.0 21.2 2850612 856332 ?      SNl  18:16  40:47 HandBrakeCLI -i /var/scratch/arm/media/raw/Back to the Future Part II -o /var/scratch/arm/media/completed/Back to the Future Part II/Back to the Future Part II.mkv --main-feature --preset FiZi-High-x265 --preset-import-file /home/arm/fizi-x265-hddvd.json
```

Previous to this two transcodes were running. Then one finished, then the other finished and the above three got kicked off.

### Environment
OS: Ubuntu 20.04.1 LTS
ARM: commit 88516d57e39069000f50c504ae9d79790a390a2c (HEAD -> v2_master, origin/v2_master, origin/HEAD)

### Log file
I do not have debug logs. These are my last three discs until I buy more.

**Comment by flammableliquids** [comment]
I will check my loop logic again for mistakes. (Nice to know it's sorta working)
Please set to debug and upload log file. (Even a standard logging file might shed a little light)

**Comment by TheFiZi** [comment]
I have 2-3 more Blurays coming in the mail. Will switch on debug logging and let you know.

**Comment by TheFiZi** [comment]
I should mention, I think this only occurs if I rip multiple discs.

If I rip 1 disc and then 1 more, the limit is respected, the second transcode does not kick off until the first completes.

If I rip 1 disc and then 2 more, the two waiting in queue (or more) will all kick off when the first finishes.

That might help narrow it down a bit while I wait for my 3rd Bluray to get here so I can get you logs.

**Comment by TheFiZi** [comment]
DEBUG logs.

I ripped Spirit first and it transcoded. When it completed Django and Surfs Up both started transcoding at the same time.

Had to compress them since they are over 10MB.

[ARM-Logs-20201129.zip](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5611902/ARM-Logs-20201129.zip)

**Comment by 1337-server** [comment]
Could you try replacing  the SleepCheckProcess() with this 

```
# New function from pull 366
def SleepCheckProcess(process_str: str, transcode_limit: int):
    """ New function to check for max_transcode from cfg file and force obey limits\n
    arguments:
    process_st - The process string from arm.yaml
    transcode_limit - The user defined limit for maximum transcodes\n\n

    returns:
    True when we have space in the transcode queue
    """
    if transcode_limit > 0:
        Loop_Count = transcode_limit + 1
        logging.debug("Loop_Count " + str(transcode_limit))
        logging.info("Starting A sleep check of " + str(process_st))
        while Loop_Count >= transcode_limit:
            Loop_Count = sum(1 for proc in psutil.process_iter() if proc.name() == process_st)
            logging.debug("Number of Processes running is:" + str(transcode_limit) + " going to waiting 12 seconds.")
            if transcode_limit > Loop_Count:
                return True
            # Try to make each check at different times
            x = random.randrange(20, 120, 10)
            logging.debug("sleeping for " + str(x) + " seconds")
            time.sleep(x)
    else:
        logging.info("Number of processes to count is: " + str(Proc_Count))


```

And then add 

`import random`
to the top of your file arm/ripper/utils.py

This should (at least in my tests) get SleepCheckProcess to respect the transcode limits.

**Comment by TheFiZi** [comment]
I can certainly try but it might be a while before I get my next batch of Blurays. It all depends on Amazons sales.

**Comment by hometechblogger** [comment]
> 
> 
> Could you try replacing the SleepCheckProcess() with this
> 
> ```
> # New function from pull 366
> def SleepCheckProcess(process_str: str, transcode_limit: int):
>     """ New function to check for max_transcode from cfg file and force obey limits\n
>     arguments:
>     process_st - The process string from arm.yaml
>     transcode_limit - The user defined limit for maximum transcodes\n\n
> 
>     returns:
>     True when we have space in the transcode queue
>     """
>     if transcode_limit > 0:
>         Loop_Count = transcode_limit + 1
>         logging.debug("Loop_Count " + str(transcode_limit))
>         logging.info("Starting A sleep check of " + str(process_str))
>         while Loop_Count >= transcode_limit:
>             Loop_Count = sum(1 for proc in psutil.process_iter() if proc.name() == process_str)
>             logging.debug("Number of Processes running is:" + str(Loop_Count) + " going to waiting 12 seconds.")
>             if transcode_limit > Loop_Count:
>                 return True
>             # Try to make each check at different times
>             x = random.randrange(20, 120, 10)
>             logging.debug("sleeping for " + str(x) + " seconds")
>             time.sleep(x)
>     else:
>         logging.info("Transcode limit is disabled!")
> ```
> 
> And then add
> 
> `import random`
> to the top of your file arm/ripper/utils.py
> 
> This should (at least in my tests) get SleepCheckProcess to respect the transcode limits.

I'm not the OP but I have set the transcode limit to 1 and have tried the code above while another transcode is running, but ARM fails. Log attached. 

[NOW_YOU_SEE_ME.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5721636/NOW_YOU_SEE_ME.log)

**Comment by hometechblogger** [comment]
Looks like it's working for me so far!

[NOW_YOU_SEE_ME_160850487460.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5721675/NOW_YOU_SEE_ME_160850487460.log)

**Comment by 1337-server** [comment]
That's great!

Just a note though, that this method isn't perfect as there could be times that it will let through more than one job. This should be a lot rarer than with the master branch.
I've tried it a dozen or so times, and it worked every time. But i only have 3 drives, and the higher the number of drives the more likely the jobs will check at the same time.

**Comment by hometechblogger** [comment]
> 
> 
> That's great!
> 
> Just a note though, that this method isn't perfect as there could be times that it will let through more than one job. This should be a lot rarer than with the master branch.
> I've tried it a dozen or so times, and it worked every time. But i only have 3 drives, and the higher the number of drives the more likely the jobs will check at the same time.

Interesting and good to know. I only have one drive and have queued up three blurays and it seems to be ok so far.

Quick side question (not wanting to derail OPs issue) do you know if a quick way to cancel a transcode? I am finding that some discs have 6-12 tracks and are taking many hours to fully transcode, when I really only need the one main track and can just pull it from the "completed" folder.

**Comment by 1337-server** [comment]
`MAINFEATURE: true` will only grab the main feature and save you a bunch of time, but with the trade off that it will transcode direct from the disc so stacking up dvds isnt possible. Not sure what you would prefer. 

At the moment i dont think its possible(its possible, but the coding isnt there for it) to only grab the main feature and have it pulled to the harddrive to let stacking of discs continue.


The only way i know of to cancel a transcode is to use `ps aux | grep HandBrakeCLI` and then kill each process you see.

**Comment by hometechblogger** [comment]
> 
> 
> `MAINFEATURE: true` will only grab the main feature and save you a bunch of time, but with the trade off that it will transcode direct from the disc so stacking up dvds isnt possible. Not sure what you would prefer.
> 
> At the moment i dont think its possible(its possible, but the coding isnt there for it) to only grab the main feature and have it pulled to the harddrive to let stacking of discs continue.
> 
> The only way i know of to cancel a transcode is to use `ps aux | grep HandBrakeCLI` and then kill each process you see.

Thanks once again. I have mounted the ARM folders to a remote share (on my NAS) and so I have found that I can just forcibly delete the disc folders inside raw and completed folders for the specific transcode that I want to end. Terribly unclean and lazy I know, but that seems to kill the task after a minute or so.
