### ISSUE TITLE
Some BluRays fail with "backup failed"

### ISSUE THREAD

**Issue by hometechblogger** [automatic-ripping-machine/automatic-ripping-machine#374]
### Description
Some bluray discs fail to backup to RAW folder resulting in disc being ejected. 

I've only had this system up and running for a few days but it has worked great for the most part. I only had one DVD fail out of 20 but have had 2 blurays fail out of 6 today. I am very new to the whole process of ripping media so I am not sure where the issue lies.

### Environment
Ubuntu 18.04.5 LTS on vmware esxi
ARM 2.1.0-dev

Changes to config:
Changed these two lines to get rid of the timeout error when searching for identification of media (something to do with Microsoft turning off that service on the web?)

# Wait for manual identification
MANUAL_WAIT: false

# Wait tie for manual identification (in seconds)
MANUAL_WAIT_TIME: 10

### Log file
[VEEP_S1_DISC1_160763173585.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5675457/VEEP_S1_DISC1_160763173585.log)

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by hometechblogger** [comment]
For some reason, once I reached the transcode limit of 3, arm wouldn't rip another disc. I changed the transcode limit to 1 and rebooted and cleaned up my folders and started over to re-rip the discs that failed and two have worked fine so far, but I see two concurrent transcoding tasks when I only specified for 1 to be the max in the arm.yaml file.

**Comment by 1337-server** [comment]
The transcode limit doesnt work fully yet its still a testing feature.

Could you try adding "--debug=-stdout" to the MKV_ARGS: "" in your arm.yaml file. Then try to rip the bluray again. This will enable the makeMKV debug log. You will need to post your new log and the makemkv debug log.

The MANUAL_WAIT: true/false is kinda for the Arm web ui, it shouldnt affect anything else. It just enables the ripping to pause so you can update the arm ui to find the correct dvd/bluray title. When it it set to false, the ripper doesnt wait and starts the rip with possibly wrong folders names. This should never affect the rip being successful or not.

**Comment by hometechblogger** [comment]
> 
> 
> The transcode limit doesnt work fully yet its still a testing feature.
> 
> Could you try adding "--debug=-stdout" to the MKV_ARGS: "" in your arm.yaml file. Then try to rip the bluray again. This will enable the makeMKV debug log. You will need to post your new log and the makemkv debug log.
> 
> The MANUAL_WAIT: true/false is kinda for the Arm web ui, it shouldnt affect anything else. It just enables the ripping to pause so you can update the arm ui to find the correct dvd/bluray title. When it it set to false, the ripper doesnt wait and starts the rip with possibly wrong folders names. This should never affect the rip being successful or not.

After a server reboot I was able to re-rip those failed blurays so I am not able to repeat the error (yet). However, I do see the same exact issue as #369 regarding transcode limit and number of discs started. It seems once the first transcode is finished, the transcode limit is not applied as the rest of the waiting transcodes all start up at the same time.

I didn't realize this before I queued up another 4 discs so I guess I will just let it transcode for the next day or two and hope they finish successfully.

Thanks for the reply!

**Comment by hometechblogger** [comment]
> 
> 
> For some reason, once I reached the transcode limit of 3, arm wouldn't rip another disc. I changed the transcode limit to 1 and rebooted and cleaned up my folders and started over to re-rip the discs that failed and two have worked fine so far, but I see two concurrent transcoding tasks when I only specified for 1 to be the max in the arm.yaml file.

Original issue appears to be resolved, I can't reproduce it now so I am guessing a one-time glitch or something.
