### ISSUE TITLE
disk not ejecting after ripping

### ISSUE THREAD

**Issue by TomW1605** [automatic-ripping-machine/automatic-ripping-machine#383]
### Description
is the disk meant to be ejected after the rip is complete but befor it is transcoded?

**Comment by 1337-server** [comment]
Yes.

But currently ARM is bugged and doesn't eject the disc. I believe the thing that fixed it for me was using `users` in the fstab entry in place of `user`

**Comment by TomW1605** [comment]
thanks i will try that change once the curent transcode is done. i will close the issue if this fixes it

**Comment by TomW1605** [comment]
ok it ejects after the transcode but i thought it was meant to eject after it had riped it. that way you could have a few in the transcode queue?

**Comment by 1337-server** [comment]
No it should eject after it has ripped the disc to the raw folder.

Did you reboot after changing the fstab ?

**Comment by TomW1605** [comment]
yes i did reboot. i till try those changes and report back

**Comment by TomW1605** [comment]
so something i did completely nuked the VM. your fork seams to have lots of changes from base. given i am reinstalling anyway does it fix this issue?

**Comment by 1337-server** [comment]
> @1337-server so something i did completely nuked the VM. your fork seams to have lots of changes from base. given i am reinstalling anyway does it fix this issue?

In my own fork any version after v2.2 fixes this issue

**Comment by TomW1605** [comment]
ok i will try installing your fork and see how that goes

**Comment by TomW1605** [comment]
ok i have tried your fork and it is still not ejecting till after it has fully transcoded the movie

**Comment by 1337-server** [comment]
Can you attach a debug log ?

**Comment by TomW1605** [comment]
it has not ejected as of that log
[007_LTK_FEATURE_D1.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5759065/007_LTK_FEATURE_D1.log)

**Comment by 1337-server** [comment]
Could you possibly try a disc with  `RIPMETHOD: "mkv"` to see if that changes anything. Dont enable `MAINFEATURE: false`

The log you posted doesnt show any files being saved to disc before encoding starts. It shows it being encoded straight from disc.
The ripmethod mkv will force arm to rip the files to disc, eject the disc. This will allow discs to be stacked.

You should also be aware that your dvd drive is showing it has no region.
`[13:19:10] dvd: Warning, DVD device has no region set`
That may or may not cause other issues later.

**Comment by TomW1605** [comment]
ok i have enabled that and will try with next disk. will post logs if it does not work

**Comment by TomW1605** [comment]
ok that worked but it is not doing anything with the next disk. will wait for the transcode to finish and see if it starts ripping when the transcode is done.

**Comment by TomW1605** [comment]
ok so it did not start ripping the second disk after the first one had transcoded however it also did not start after rebooting the VM so i think it is either a problem with the disk or some other issue with my install. i will report back when i have more info.

**Comment by 1337-server** [comment]
Did you try running the arm run command in terminal/ssh ?

`sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0`

That should show any errors in the terminal

**Comment by TomW1605** [comment]
i will try that when i get home

**Comment by kruug** [comment]
I changed this:

`/dev/sr0 /mnt/dev/sr0 udf,iso9660 user,noauto,exec,utf8 0 0`

To:

`/dev/sr0 /mnt/dev/sr0 udf,iso9660 users,noauto,exec,utf8 0 0`

And the drive ejected at the end of the process.

**Comment by 1337-server** [comment]
> I changed this:
> 
> `/dev/sr0 /mnt/dev/sr0 udf,iso9660 user,noauto,exec,utf8 0 0`
> 
> To:
> 
> `/dev/sr0 /mnt/dev/sr0 udf,iso9660 users,noauto,exec,utf8 0 0`
> 
> And the drive ejected at the end of the process.

Did you change the commit from this link [87202a7](https://github.com/automatic-ripping-machine/automatic-ripping-machine/commit/87202a78ce6ca118e0133ec899e6a16b4ad046dc)

**Comment by kruug** [comment]
I did not.  I was following https://blog.lohannes.com/2018/08/automatic-disk-ripping-machine-full.html?m=1 so it just pulled v2_master.

**Comment by 1337-server** [comment]
The master branch is **very** old. You should consider pulling the `v2_master` branch instead. It has a bunch of new features.
