### ISSUE TITLE
DVDs transcoding directly from drive

### ISSUE THREAD

**Issue by hometechblogger** [automatic-ripping-machine/automatic-ripping-machine#384]
### Description
Are DVDs able to be ripped / backed up first, then transcoded? (like blurays) What options do I need to set in the config file? I didn't see anything that specifically mentioned the ability for DVDs to be ripped to storage first.

Currently, DVD discs only transcode direct from the drive, then eject. This means I can't stack them up. This occurs regardless of MAINFEATURE being set to true or false (currently set to true to reduce bluray rip times but even when set to false it doesn't stack DVD discs).

### Environment
Ubuntu 18.04.5 LTS
ARM version: 2.1.0-dev

### Log file
no log specific to this.

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Try using `RIPMETHOD: "mkv"` and `MAINFEATURE: false`

**Comment by hometechblogger** [comment]
Thanks, that started to work, then it errored out:

_MSG:5003,0,2,"Failed to save title 0 to file /home/arm/raw/FRIENDS SEASON 5 DISC2/FRIENDS SEASON 5 DISC 2_t00.mkv","Failed to save title %1 to file %2","0","/home/arm/raw/FRIENDS SEASON 5 DISC2/FRIENDS SEASON 5 DISC 2_t00.mkv"_

_MSG:4040,16777216,1,"Unable to execute external program 'ccextractor' as its path is not set in preferences","Unable to execute external program '%1' as its path is not set in preferences","ccextractor"_

_MSG:4041,0,2,"Failed to execute external program 'ccextractor' from location '/usr/bin/mmccextr'","Failed to execute external program '%1' from location '%2'","ccextractor","/usr/bin/mmccextr"_

Not sure if this means the ccextractor program can't be executed, or that the program won't execute because I changed the location of the raw folder (default is /home/arm/media/raw but I consolidated it to /home/arm/raw on my NAS)._

[FRIENDS_SEASON_5_DISC2.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5759511/FRIENDS_SEASON_5_DISC2.log)

**Comment by 1337-server** [comment]
The raw folder isnt the problem, this seems to be issue #273 

Can you try the solution in the thread helps ?

**Comment by hometechblogger** [comment]
That took care of it, thanks! I think I found that thread in a Google search as well but I wasn't able to get it to work the first time. After seeing the later replies at the bottom and adding those extra lines, I got it to work. Thanks.
