### ISSUE TITLE
Advice on TV Series

### ISSUE THREAD

**Issue by rj175** [automatic-ripping-machine/automatic-ripping-machine#385]
### Description
I am trying to rip a TV series from both a bluray and a DVD, I find that it only seems to rip the contents as a single file instead of each episode as a separate file. I am just wondering if I have configured something wrong?

### Environment
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```
Arm Version v2_master

**Comment by 1337-server** [comment]
Can you post the full debug log ?

**Comment by rj175** [comment]
@1337-server My bad, arm ripped one file with all the episodes in it and then separate files with each episode. I changed the max length and now it’s only ripping the episodes. This can be closed thanks. 😊
