### ISSUE TITLE
How to: Native Language Audio with Optional (i.e. not burned-in) Multiple Subtitles Options

### ISSUE THREAD

**Issue by staplemk** [automatic-ripping-machine/automatic-ripping-machine#389]
### Description
Hello,

I would like to know the lines of code I would need to put into the arm.yml file to achieve what the Issue title says - that is to rip the DVD in it's native language, but to have the option to turn on whichever subtitle I want (or none).

I tried a few combinations using the handbrake CLI reference sheet (https://handbrake.fr/docs/en/1.3.0/cli/command-line-reference.html), but it would just burn in the subtitles no matter what I tried.

I looked at #145 but I couldn't figure out how to tweak it to get what I want.  Are subtitles separate files themselves that are being ripped to a local folder? Or would they be part of the video file?

Help! (please)

### Environment
DISTRIB_ID = Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
Sorry, I dont know how to get this...but I just installed it yesterday.

### Log file
N/A

**Comment by 1337-server** [comment]
Have you tried playing around with the `HB_ARGS_DVD`

You should be able to select any or all of the subtitles/audio from there.

**Comment by staplemk** [comment]
Ah, I was missing this command: --subtitle-burned=none
