### ISSUE TITLE
ARM trancodes same movie multiple times

### ISSUE THREAD

**Issue by alexcoolstar** [automatic-ripping-machine/automatic-ripping-machine#392]
### Description
When i insert a bluray-movie it trancodes the movies over and over again. It outputs the exact same file with different names like "title 9", "title 10"... The only way to stop it is to shut down the computer. 

I'm not including a logfile as i heard someone say that there was some kind of security bug with the log files. Not sure if it has been resolved

**Comment by 1337-server** [comment]
The logfile issue was solved with pull #379 

You can safely post your logfiles if you have updated or installed ARM since that pull request.

**Comment by 1337-server** [comment]
With no way of knowing the version your running or any of your environment, its impossible to guess.

Could you try either zipping the logs or splitting them and attaching them.

**Comment by alexcoolstar** [comment]
[SELVHENTER.log.zip](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5896419/SELVHENTER.log.zip)
Okay, I zipped it :)

**Comment by 1337-server** [comment]
Having a look this seems to be an issue with HandBrakeCLI finding way to many titles. It found 387 titles on the disc. 
Could you try enabling mainfeature ?

**Comment by alexcoolstar** [comment]
Thanks a lot for taking time to help out here, btw! 
Mainfeature is already enabled, unfortunately...

**Comment by 1337-server** [comment]
This may be one of the rare discs that ARM cannot deal with automatically.

I dont know of any solutions, sorry.

**Comment by hometechblogger** [comment]
> The only way to stop it is to shut down the computer.

You can kill the handbrake process in a terminal window without rebooting (especially useful if you have discs already ripped queued up and don't want to lose that progress).

Get process number for handbrake (it's usually two PIDs)

ps aux | grep HandBrakeCLI

then

kill -9 <process#>

Courtesy of @1337-server from a previous thread of mine.

**Comment by alexcoolstar** [comment]
> This may be one of the rare discs that ARM cannot deal with automatically.
> 
> I dont know of any solutions, sorry.

Okay, it might be. Thanks a lot for taking your time :)

**Comment by alexcoolstar** [comment]
> > The only way to stop it is to shut down the computer.
> 
> You can kill the handbrake process in a terminal window without rebooting (especially useful if you have discs already ripped queued up and don't want to lose that progress).
> 
> Get process number for handbrake (it's usually two PIDs)
> 
> ps aux | grep HandBrakeCLI
> 
> then
> 
> kill -9 <process#>
> 
> Courtesy of @1337-server from a previous thread of mine.

I've actually wondered if that was possible. Thanks a lot!

**Comment by 1337-server** [comment]
This is most likely the Track 99 protection.
