### ISSUE TITLE
Cleanup Branches

### ISSUE THREAD

**Issue by SysEngDan** [automatic-ripping-machine/automatic-ripping-machine#393]
Perhaps it would be prudent to this project to clean up the branches and consolidate into a true master branch and one or more dev branches. The instructions in the readme references a non-existent branch v2.2_dev. So is the v2_master branch truly the latest master?

As a consumer of the project, I'm confused on the current latest release.

**Comment by 1337-server** [comment]
The branch v2.2_dev refers to flamingliquid's own branch of the repo (that's now behind the main repo) and was an oversight
that's not been corrected.

v2_master is the most updated branch on the main repo.
