### ISSUE TITLE
Add more directory support for placing movies, tv shows, and audio for Plex

### ISSUE THREAD

**Issue by SysEngDan** [automatic-ripping-machine/automatic-ripping-machine#394]
### Description
New Feature: Add more directory support for placing ripped movies, tv shows, and audio into separate folders to support Plex's ability to detect said libraries automatically.

### Use Case
When ARM is configured to store completed rips of movies, tv shows, and audio into separate folder, such as /var/media/movies, /var/media/tvshows, and /var/media/audio, respectively, and say that /var/media is a mounted NFS share which is also mounted to the same mountpoint on a Plex Media Server, then Plex will automatically be able to detect any newly ripped files.

Note: If there is currently a supported method for this, please advise. I only see a movies directory supported in the latest arm.yaml

**Comment by 1337-server** [comment]
This wont help for tv shows, but ARM already uses a different folder for Music. 
The config for the music directory is set in the .abcde.conf and not the arm.yaml

**Comment by SysEngDan** [comment]
> This wont help for tv shows, but ARM already uses a different folder for Music.
> The config for the music directory is set in the .abcde.conf and not the arm.yaml

Well that's good to know, I wasn't aware of that yet. Thanks! Perhaps https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/395 will support the TV show directory better.

**Comment by 1337-server** [comment]
Base on the last sentence in [this comment](https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/373#discussion_r557835448) 
I'm not sure if a tv directory would be supported or added. Although I could be wrong!

**Comment by 1337-server** [comment]
Assuming this is now resolved.
