### ISSUE TITLE
Receving emails with YAMLLoadWarning

### ISSUE THREAD

**Issue by kruug** [automatic-ripping-machine/automatic-ripping-machine#396]
### Description
Receiving two emails per job with the following output:

```
/opt/arm/arm/config/config.py:10: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(f)
/dev/sr0
Log: /home/arm/logs/None_161232922381.log
```

I have changed the config to only log ERROR and the emails are still arriving.

### Environment
Ubuntu 20.04.2 LTS
git branch: v2_master
git log -1:
```
commit 0b055c5ac559e72235e264f3fbe993a10b41036a (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: 8052273 7e9bab4
Author: flammableliquids <geforbes@gmail.com>
Date:   Thu Jan 14 14:44:24 2021 +1100

    Merge pull request #379 from 1337-server/v2.1_dev

    Security fix for logfiles with api/secret keys
```

**Comment by 1337-server** [comment]
can you try this config.py

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/8108b2365c40acaa53fd0a4f0824eee7791435ec/arm/config/config.py

**Comment by kruug** [comment]
That config removed the yaml.load() error.  Thank you.

**Comment by 1337-server** [comment]
Assuming this is now resolved
