### ISSUE TITLE
Not identified title for movies in external drives

### ISSUE THREAD

**Issue by mbreuneval** [automatic-ripping-machine/automatic-ripping-machine#399]
### Description
[Description of Bug, Feature, Question, etc.]
When I insert a disc in an external drive, it always comes up as not identified and created under the folder "not indentified_xxxx". The problem is that it is not linked to the disk because it only happens in the external drives. If I put the same disk in an internal one it identifies it easily. I looked into the logs (attached to this issue). And i can see that I have :

>  [2021-02-17 17:32:23] INFO ARM: Disc identified as video
> [2021-02-17 17:32:24] INFO ARM: DVD CRC64 hash is: 714ca3944881efda
> [2021-02-17 17:32:24] INFO ARM: Fallback title is: None_714ca3944881efda
> [2021-02-17 17:32:24] ERROR ARM: Failed to reach windowsmedia web service.  Error number is: 104
> [2021-02-17 17:32:24] INFO ARM: Disc title: not identified :  : unknown
> [2021-02-17 17:32:24] INFO ARM: Waiting 100 seconds for manual override.
> [2021-02-17 17:34:04] INFO ARM: No manual override found.
> [2021-02-17 17:34:04] INFO ARM: **** Logging ARM variables ****
> [2021-02-17 17:34:04] INFO ARM: devpath: /dev/sr5
> [2021-02-17 17:34:04] INFO ARM: mountpoint: /mnt/dev/sr5
> [2021-02-17 17:34:04] INFO ARM: title: not identified
> [2021-02-17 17:34:04] INFO ARM: year: 
> [2021-02-17 17:34:04] INFO ARM: video_type: unknown

So here I can see the title can't be identified, but still it should be because later in the log, it still manages to indetify the title but doesn't do anything with it as you can see here : 

> [17:34:41] dvd: Region mask 0xfd
> libdvdnav: Using dvdnav version 6.0.0
> libdvdnav: DVD Title: CAPT_CORELLIS_MANDOLIN
> libdvdnav: DVD Serial Number: 3C7D4C7D___MVB__
> libdvdnav: DVD Title (Alternative): 
> libdvdnav: DVD disk reports itself with Region mask 0x00f50000. Regions: 2 4

So I am wondering why I can't access to the title of the movie only when it's in an external drive, which would probable cause problem when importing it to my plex media server.

Thank you apart from that, the app is amazing!

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
v2_master branch (last in date)
### Log file

[None_161366694982.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6004516/None_161366694982.log)

**Comment by 1337-server** [comment]
Can you please attach the full DEBUG log ? 
The log you have attached isnt a debug log, and important information is missing.

You can enable debugging logging in your arm.yaml config file.

**Comment by mbreuneval** [comment]
Hello, sorry for the mistake, you can find the debug file here attached or in the edited original post (this log stops during the ripping so that it is not too heavy and that I can post it now, if needed I can provide the full one )

[None_161366694982.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6004516/None_161366694982.log)

**Comment by 1337-server** [comment]
This appears to be caused by arm not getting the "ID_FS_LABEL" from udev or it being set empty.

Can you run the command (with a disc inserted) `udevadm info /dev/sr0` changing sr0 to your own device in a terminal and post the output ?

**Comment by mbreuneval** [comment]
Here is what i get using the command you gave me. Should I assume it means my disk isn't able to get this ID_FS_LABEL at all ?

> P: /devices/pci0000:00/0000:00:08.1/0000:2b:00.3/usb3/3-3/3-3:1.0/host13/target13:0:0/13:0:0:0/block/sr5
N: sr5
S: disk/by-id/usb-HL-DT-ST_DVDRAM_GP57EB40_KX6K3O20903-0:0
S: disk/by-path/pci-0000:2b:00.3-usb-0:3:1.0-scsi-0:0:0:0
E: DEVLINKS=/dev/disk/by-id/usb-HL-DT-ST_DVDRAM_GP57EB40_KX6K3O20903-0:0 /dev/disk/by-path/pci-0000:2b:00.3-usb-0:3:1.0-scsi-0:0:0:0
E: DEVNAME=/dev/sr5
E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:2b:00.3/usb3/3-3/3-3:1.0/host13/target13:0:0/13:0:0:0/block/sr5
E: DEVTYPE=disk
E: ID_BUS=usb
E: ID_CDROM=1
E: ID_CDROM_CD=1
E: ID_CDROM_CD_R=1
E: ID_CDROM_CD_RW=1
E: ID_CDROM_DVD=1
E: ID_CDROM_DVD_PLUS_R=1
E: ID_CDROM_DVD_PLUS_RW=1
E: ID_CDROM_DVD_PLUS_R_DL=1
E: ID_CDROM_DVD_R=1
E: ID_CDROM_DVD_RAM=1
E: ID_CDROM_DVD_RW=1
E: ID_CDROM_MEDIA=1
E: ID_CDROM_MEDIA_DVD=1
E: ID_CDROM_MRW=1
E: ID_CDROM_MRW_W=1
E: ID_FOR_SEAT=block-pci-0000_2b_00_3-usb-0_3_1_0-scsi-0_0_0_0
E: ID_INSTANCE=0:0
E: ID_MODEL=DVDRAM_GP57EB40
E: ID_MODEL_ENC=DVDRAM\x20GP57EB40\x20
E: ID_MODEL_ID=1887
E: ID_PATH=pci-0000:2b:00.3-usb-0:3:1.0-scsi-0:0:0:0
E: ID_PATH_TAG=pci-0000_2b_00_3-usb-0_3_1_0-scsi-0_0_0_0
E: ID_REVISION=PF01
E: ID_SERIAL=HL-DT-ST_DVDRAM_GP57EB40_KX6K3O20903-0:0
E: ID_SERIAL_SHORT=KX6K3O20903
E: ID_TYPE=cd
E: ID_USB_DRIVER=usb-storage
E: ID_USB_INTERFACES=:080250:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=HL-DT-ST
E: ID_VENDOR_ENC=HL-DT-ST
E: ID_VENDOR_ID=0e8d
E: MAJOR=11
E: MINOR=5
E: SUBSYSTEM=block

**Comment by 1337-server** [comment]
Yes, unfortunatly your DVD drive doesnt seem to be passing the ID_FS_LABEL to your machine.

Im not sure of the cause, it can be worked around. You can modify /opt/arm/arm/models/models.py to use the output you're getting from handbrake.

Find this
```
    def parse_udev(self):
        """Parse udev for properties of current disc"""

        # print("Entering disc")
        context = pyudev.Context()
        device = pyudev.Devices.from_device_file(context, self.devpath)
        self.disctype = "unknown"
```
And then add something like this
```
        if "ID_FS_LABEL" not in device.items():
            logging.debug("NO ID_FS_LABEL")
            handbrake_out = subprocess.call(
                ["HandBrakeCLI",
                 "-t", "0",
                 "-i", self.devpath])
            if len(handbrake_out) < 1:
                logging.debug("Unable to obtain DVD info from %s" % self.devpath)
                logging.debug("HandBrake output: %s" % handbrake_out)
            else:
                for line in handbrake_out.splitlines():
                    if len(line.strip()) == 0:
                        # blank line
                        continue
                    if 'DVD Title:' in line:
                        # example:
                        # libdvdnav: DVD Title: AMADEUS_SIDE_A_16X9_LB
                        self.label = line.rsplit(":", 1)[1].strip()

```

I havent tested this code as i cant reproduce the no ID_FS_LABEL that would trigger the code. But this should give some idea of what you need for ARM to still get the correct titles with your external drive.

**Comment by mbreuneval** [comment]
Thank you for your help, it is now working as expected thanks to your workaround!
