### ISSUE TITLE
Ripping interrupted by dvdnav read error

### ISSUE THREAD

**Issue by mbreuneval** [automatic-ripping-machine/automatic-ripping-machine#400]
### Description
Following this fix #399  proposed, I thought it was all working  right but I found out that most DVD ripping were crashing during the copy showing the error 

"ERROR: dvdnav: Read Error, Error reading from DVD." randomly during the encryption, putting an end to it.

I concluded it was due to fix #399 because I never saw it before and it only happens on external drives.

I saw the same error appearing on  #397  and thought about trying this --no-dvdnav option on HandBrakeCLI but don't know if it would work or even where to use it.

Thank you in advance

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
v2_master branch (last in date)

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]
[L_AUBERGE_ESPAGNOLE.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6072052/L_AUBERGE_ESPAGNOLE.log)
[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Can you double check you have libdvdcss installed ?

**Comment by mbreuneval** [comment]
Thanks for the quick answer!

Yes I did have it installed already, 
while trying to check the install again some lines stated this : 
```
Note, selecting 'libdvdcss2' instead of 'libdvdcss'
libdvdcss2 is already the newest version (1.4.2-1~local).
```
but I don't think it's very meaningfulfor this issue

On top of that, do you think this is the kind of problem origin that could explain it's not working only on external drives?

**Comment by 1337-server** [comment]
> 
> 
> Thanks for the quick answer!
> 
> Yes I did have it installed already,
> while trying to check the install again some lines stated this :
> 
> ```
> Note, selecting 'libdvdcss2' instead of 'libdvdcss'
> libdvdcss2 is already the newest version (1.4.2-1~local).
> ```
> 
> but I don't think it's very meaningfulfor this issue
> 
> On top of that, do you think this is the kind of problem origin that could explain it's not working only on external drives?

Can you try using MakeMKV instead of HandBrake ? 
You will need to change your arm.yaml `RIPMETHOD: "backup"` to `RIPMETHOD: "mkv"`  And have the mainfeature setting turned off.

If that fails i can only assume that this is a faulty or incompatible drive.

**Comment by 1337-server** [comment]
Assuming this is now resolved
