### ISSUE TITLE
Ripping Small TV Show Disc Creating Multiples of Every Episode

### ISSUE THREAD

**Issue by bwbloom** [automatic-ripping-machine/automatic-ripping-machine#405]
### Description
I just got my ARM up and running and figured I should throw some uncommon media at it to get a feel for how it behaves. 

I tried two different bargain bin TV show compilation discs and got very different results:

1. First I ripped [this disc](https://www.familyvideo.com/paw-patrol-the-great-pirate-rescue) and it mostly worked. It ended up outputting 1 file for each episode and then 1 large file with all episodes running concurrently. Not exactly a huge problem, but definitely undesirable given how slow my system is. Is there a way to only get the smaller files, or would that run the risk of messing up other TV shows if they have longer runtimes?
2. Second, and the more significant issue: I put in [this Paw Patrol DVD](https://www.familyvideo.com/paw-patrol-433869) which is a single disc with a bunch of random episodes. This is the second of these types of discs that I am testing. The first . The system has been running all night (although I think it is getting close to finishing soon) and when I examine the output directory I have dozens of files, many that seem to be duplicates. When I open the files There appear to be numerous of each individual episode, then a couple with 2 episodes running concurrently, and then 1 file that appears to have all of or almost all of the episodes running concurrently.
Here is the directory as it is still getting new rips:
```
bwbloom@arm:/media/storage/movies/PAW Patrol (2013–)$ ls -Slhr --block-size=k
total 31997656K
-rw-rw-r-- 1 arm cdrom  228420K Mar  9 13:22 title_53.mkv
-rw-rw-r-- 1 arm cdrom  228420K Mar  9 12:38 title_48.mkv
-rw-rw-r-- 1 arm cdrom  228420K Mar  9 12:32 title_47.mkv
-rw-rw-r-- 1 arm cdrom  228420K Mar  9 12:27 title_46.mkv
-rw-rw-r-- 1 arm cdrom  228420K Mar  9 12:21 title_45.mkv
-rw-rw-r-- 1 arm cdrom  228420K Mar  9 12:06 title_43.mkv
-rw-rw-r-- 1 arm cdrom  228420K Mar  9 11:51 title_41.mkv
-rw-rw-r-- 1 arm cdrom  235247K Mar  9 09:47 title_25.mkv
-rw-rw-r-- 1 arm cdrom  235247K Mar  9 09:23 title_22.mkv
-rw-rw-r-- 1 arm cdrom  235247K Mar  9 08:58 title_19.mkv
-rw-rw-r-- 1 arm cdrom  235247K Mar  9 08:43 title_17.mkv
-rw-rw-r-- 1 arm cdrom  235247K Mar  9 08:37 title_16.mkv
-rw-rw-r-- 1 arm cdrom  235247K Mar  9 07:44 title_10.mkv
-rw-rw-r-- 1 arm cdrom  235247K Mar  9 07:39 title_09.mkv
-rw-rw-r-- 1 arm cdrom  235247K Mar  9 07:14 title_06.mkv
-rw-rw-r-- 1 arm cdrom  235917K Mar  9 14:28 title_62.mkv
-rw-rw-r-- 1 arm cdrom  235917K Mar  9 14:03 title_58.mkv
-rw-rw-r-- 1 arm cdrom  235917K Mar  9 13:47 title_56.mkv
-rw-rw-r-- 1 arm cdrom  241239K Mar  9 15:55 title_73.mkv
-rw-rw-r-- 1 arm cdrom  241239K Mar  9 15:30 title_70.mkv
-rw-rw-r-- 1 arm cdrom  241239K Mar  9 15:24 title_69.mkv
-rw-rw-r-- 1 arm cdrom  241239K Mar  9 15:09 title_67.mkv
-rw-rw-r-- 1 arm cdrom  241239K Mar  9 15:03 title_66.mkv
-rw-rw-r-- 1 arm cdrom  243979K Mar  9 11:45 title_40.mkv
-rw-rw-r-- 1 arm cdrom  243979K Mar  9 11:39 title_39.mkv
-rw-rw-r-- 1 arm cdrom  243979K Mar  9 11:33 title_38.mkv
-rw-rw-r-- 1 arm cdrom  243979K Mar  9 11:28 title_37.mkv
-rw-rw-r-- 1 arm cdrom  243979K Mar  9 11:22 title_36.mkv
-rw-rw-r-- 1 arm cdrom  243979K Mar  9 11:06 title_34.mkv
-rw-rw-r-- 1 arm cdrom  243979K Mar  9 11:01 title_33.mkv
-rw-rw-r-- 1 arm cdrom  395076K Mar  9 13:17 title_52.mkv
-rw-rw-r-- 1 arm cdrom  395076K Mar  9 13:07 title_51.mkv
-rw-rw-r-- 1 arm cdrom  395076K Mar  9 12:57 title_50.mkv
-rw-rw-r-- 1 arm cdrom  395076K Mar  9 12:47 title_49.mkv
-rw-rw-r-- 1 arm cdrom  395076K Mar  9 12:16 title_44.mkv
-rw-rw-r-- 1 arm cdrom  395076K Mar  9 12:00 title_42.mkv
-rw-rw-r-- 1 arm cdrom  409036K Mar  9 07:54 title_11.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 10:35 title_30.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 10:16 title_28.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 09:32 title_23.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 10:45 title_31.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 10:26 title_29.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 10:07 title_27.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 09:57 title_26.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 09:42 title_24.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 09:17 title_21.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 08:52 title_18.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 08:32 title_15.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 08:22 title_14.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 08:13 title_13.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 08:03 title_12.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 07:33 title_08.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 07:23 title_07.mkv
-rw-rw-r-- 1 arm cdrom  409195K Mar  9 09:07 title_20.mkv
-rw-rw-r-- 1 arm cdrom  416413K Mar  9 14:22 title_61.mkv
-rw-rw-r-- 1 arm cdrom  416413K Mar  9 13:57 title_57.mkv
-rw-rw-r-- 1 arm cdrom  416413K Mar  9 13:32 title_54.mkv
-rw-rw-r-- 1 arm cdrom  416422K Mar  9 14:13 title_59.mkv
-rw-rw-r-- 1 arm cdrom  416422K Mar  9 13:42 title_55.mkv
-rw-rw-r-- 1 arm cdrom  420805K Mar  9 11:16 title_35.mkv
-rw-rw-r-- 1 arm cdrom  420805K Mar  9 10:55 title_32.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 16:24 title_76.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 16:15 title_75.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 16:05 title_74.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 15:49 title_72.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 15:40 title_71.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 15:19 title_68.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 14:58 title_65.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 14:48 title_64.mkv
-rw-rw-r-- 1 arm cdrom  420859K Mar  9 14:38 title_63.mkv
-rw-rw-r-- 1 arm cdrom  491249K Mar  9 19:44 title_90.mkv
-rw-rw-r-- 1 arm cdrom  661447K Mar  9 19:32 title_89.mkv
-rw-rw-r-- 1 arm cdrom  661452K Mar  9 17:52 title_84.mkv
-rw-rw-r-- 1 arm cdrom  661458K Mar  9 18:08 title_85.mkv
-rw-rw-r-- 1 arm cdrom  661458K Mar  9 17:16 title_82.mkv
-rw-rw-r-- 1 arm cdrom  661459K Mar  9 17:01 title_81.mkv
-rw-rw-r-- 1 arm cdrom  866054K Mar  9 16:45 title_80.mkv
-rw-rw-r-- 1 arm cdrom  866054K Mar  9 18:56 title_87.mkv
-rw-rw-r-- 1 arm cdrom  866054K Mar  9 19:17 title_88.mkv
-rw-rw-r-- 1 arm cdrom  866054K Mar  9 17:37 title_83.mkv
-rw-rw-r-- 1 arm cdrom 1184807K Mar  9 18:36 title_86.mkv
```
This single DVD is currently taking up 32Gigs! I'm going to let it finish out for pure morbid curiosity, but and understanding of what is happening as well as suggestions on how to improve my configuration would be greatly appreciated.

### Environment
Ubuntu 18.04.5 LTS running on bare metal
ARM version 2.2.0-dev

### Log file
Partial log as it is still running:
[PAW_PATROL_NA.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6111032/PAW_PATROL_NA.log)
<]

**Comment by 1337-server** [comment]
1. I don't remember there being a config variable to change this, it should output every episode singularly and 1 large file with all episodes joined. This allows you to select what to keep without needing to use external software

2. This is kind of working as intended. This is due to the copyright protection of the disc.
Can you try using MakeMKV and see if that corrects the issue ? 
`RIPMETHOD: "mkv"` in your arm.yaml settings

**Comment by bwbloom** [comment]
OK, I want to give this a shot, but the disc is just kind of hung. For a while it was just concatenating videos and doing another rip, but now it is saying it's still in process, but no files are showing up or getting larger and in top the process seems to be using almost no CPU.
How do you kill a stuck rip? If I restart the system will it just resume ripping, or do I just reboot?

**Comment by 1337-server** [comment]
You can do this too kill an active rip to save rebooting

https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/392#issuecomment-770477641

**Comment by bwbloom** [comment]
Interesting. I did that manual kill and that fixed it. Went with the reboot and tried again with this disc in mkv. Still not playing ball. I think this is just a tough disc. I've got the files so I'll just hope I don't run into it again.

**Comment by bwbloom** [comment]
OK, scratch that. I the task kill worked on one stuck disc but the other one is still stuck there. I ejected the disc during the reboot assuming since I didn't want to rip it any longer, but now it is stuck on the web page.
I run the grep for HandBrake CLI but it does not seem to have an active task for the rip any longer.
Thoughts?

**Comment by 1337-server** [comment]
ARM will eventually remove any jobs where the process isnt running, but this isn't immediate.  It can take some time.

**Comment by bwbloom** [comment]
I just popped a new disc into the drive and that got rid of the stuck one. Thanks again.
