### ISSUE TITLE
Enhancement Request: Allow for more Readable Aliases of Devices in Web Portal

### ISSUE THREAD

**Issue by bwbloom** [automatic-ripping-machine/automatic-ripping-machine#408]
### Description
My system has 4 drives attached and when ripping different discs at the same time it can become confusing which disc is in which drive (especially when ripping multi-disc TV shows or more obscure movies that do not get matches automatically).
It would be helpful to be able to assign an alternate reference that would show up in the web portal ie
**Device:** /dev/sr0 could show as "Asus BD"
**Device:** /dev/sr1 could show as "HP BD"
**Device:** /dev/sr2 could show as "LG BD"
**Device:** /dev/sr3 could show as "HP DVD"
Maybe there could be a section in the arm.yaml file in the Web Server section where you could list drives you want to map to specific names. If you don't have a value there then just map show the default device ID like now.

### Environment
Ubuntu 18.04.5 LTS running on bare metal
ARM version 2.2.0-dev

**Comment by microtechno9000** [comment]
I have made some changes to the v2_devel branch adding in some drive functionality
It will scan the system for drives, show the job current and previous status and allow open/close from the settings page

For this PR the drive names can't be changed, but once this PR goes through (hopefully), I will edit it to allow for users to add names to the drives and edit some of the fields stored in the database.

**Comment by microtechno9000** [comment]
@bwbloom recent ARM updates include information on the system drives, their status and links to current/previous jobs.
