### ISSUE TITLE
Ability to cancel a job from the web interface or command line

### ISSUE THREAD

**Issue by phirestalker** [automatic-ripping-machine/automatic-ripping-machine#411]
### Description
I would like to be able to cancel a job and delete all intermediate files. I tried to go too fast and the 3rd rip stopped with a message letting me know it would take more storage than I had available. It seemed to be waiting indefinitely for me to answer yes or no on whether to continue.

I tried to just kill the PID listed in the web interface for the job, but it is still listed, and I don't know what is going to happen with it.

A button on each job to cancel, or a command I can fire off in the terminal would cancel the job, and delete it from the interface and disk would both work.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
v2_master
commit df4be42090c6976526d737c7f82802bf5f5ba715 (HEAD -> v2_master, origin/v2_master, origin/HEAD)

**Comment by 1337-server** [comment]
If the job is still showing in the web interface, it will be removed the next time you run ARM (manually or from disc insert) if its PID isn't found.

**Comment by 1337-server** [comment]
I didn't think to mention it earlier, but after seeing your pull request it might be worth mentioning. I have added this feature in my own repo. There are also a lot of other features added that might be useful or interesting to you.

**Comment by phirestalker** [comment]
I'm glad you mentioned it. I actually visited your repo yesterday. I wasn't sure how to ask you, as I did not want to open a new issue for it.
How easy would it be for me to switch? I know the git commands are trivial, but how compatible is your latest release with this v2_master branch?  Are there any special upgrade instructions?

**Comment by 1337-server** [comment]
Not really anything special you need to do to upgrade. 

Just update the files locally and then either insert a disc or run the ARM run command and ARM will do almost all of the rest of the work. 
The only extra work you will need to do is create an admin account so you can delete jobs or edit the arm settings from the Ui.

If you have a look at the wiki on my own repo( I am waiting for a response about adding these to the wiki here) there are lots of extra info about setup, upgrading , changing the themes, hardware transcoding , etc.

But if you get stuck with anything, let me know and I will try to give you any info I may have missed to detail in the documentation.

**Comment by phirestalker** [comment]
Also, while I have you, does your version setup java with MakeMKV for Blu-ray menus?

**Comment by 1337-server** [comment]
I honestly couldn't say, It's not a feature I've ever used. But if it's in the ARM main repo it should be in my own fork.
