### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by cpesko** [automatic-ripping-machine/automatic-ripping-machine#414]
How to add more drives to 733tservers image? added more lines to dockerfile. Is there another spot too we have to increase drives?

[25-03-2021 02:37:03] INFO ARM: max_concurrent_transcodes 0
[25-03-2021 02:37:03] INFO ARM: **** End of config parameters ****
[25-03-2021 02:37:03] INFO ARM: Checking for fstab entry.
[25-03-2021 02:37:03] ERROR ARM: No fstab entry found.  ARM will likely fail.

**Comment by 1337-server** [comment]
> How to add more drives to 733tservers image? added more lines to dockerfile. Is there another spot too we have to increase drives?
> 
> 
> 
> [25-03-2021 02:37:03] INFO ARM: max_concurrent_transcodes 0
> 
> [25-03-2021 02:37:03] INFO ARM: **** End of config parameters ****
> 
> [25-03-2021 02:37:03] INFO ARM: Checking for fstab entry.
> 
> [25-03-2021 02:37:03] ERROR ARM: No fstab entry found.  ARM will likely fail.

It's only the docker file than needs modified 

You can see the steps here to add more drives 

https://github.com/deekue/automatic-ripping-machine/pull/1

**Comment by cpesko** [comment]
# default directories and configs
RUN \
  mkdir -m 0777 -p /home/arm /home/arm/config /mnt/dev/sr0 /mnt/dev/sr1 /mnt/dev/sr2 /mnt/dev/sr3 /mnt/dev/sr4 /mnt/dev/sr5 /mnt/dev/sr6 /mnt/dev/sr7 && \
  ln -sv /home/arm/config/arm.yaml /opt/arm/arm.yaml && \
  ln -sv /opt/arm/apprise.yaml /home/arm/config/apprise.yaml && \
  echo "/dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab  && \
  echo "/dev/sr1  /mnt/dev/sr1  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab  && \
  echo "/dev/sr2  /mnt/dev/sr2  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab  && \
  echo "/dev/sr3  /mnt/dev/sr3  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab  && \
  echo "/dev/sr4  /mnt/dev/sr4  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab  && \
  echo "/dev/sr5  /mnt/dev/sr5  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab  && \
  echo "/dev/sr6  /mnt/dev/sr6  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab  && \
  echo "/dev/sr7  /mnt/dev/sr7  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab  
# copy ARM source last, helps with Docker build caching
COPY . /opt/arm/

EXPOSE 8080root@9801ad1a8501:/home/arm# cat /etc/fstab
# UNCONFIGURED FSTAB FOR BASE SYSTEM
/dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
/dev/sr1  /mnt/dev/sr1  udf,iso9660  users,noauto,exec,utf8,ro  0  0
/dev/sr2  /mnt/dev/sr2  udf,iso9660  users,noauto,exec,utf8,ro  0  0
/dev/sr3  /mnt/dev/sr3  udf,iso9660  users,noauto,exec,utf8,ro  0  0
/dev/sr4  /mnt/dev/sr4  udf,iso9660  users,noauto,exec,utf8,ro  0  0
root@9801ad1a8501:/home/arm#

**Comment by cpesko** [comment]
do I have to rebuild the image?

**Comment by 1337-server** [comment]
Yes

**Comment by cpesko** [comment]
root@zero:/opt/arm# vi /home/arm/config/arm.yaml 
root@zero:/opt/arm# docker exec -it arm-rippers bash
root@50be8b8dafe5:/home/arm# eject sr0
root@50be8b8dafe5:/home/arm# eject -t sr0
root@50be8b8dafe5:/home/arm# python3 /opt/arm/arm/ripper/main.py -d sr0
ERROR:root:Failed to check status of device sr0: [Errno 2] No such file or directory: 'sr0'
Drive empty or is not ready. Exiting ARM Ripper.
root@50be8b8dafe5:/home/arm#

**Comment by 1337-server** [comment]
can you share your docker run command ?

and your syslog dmesg when you insert a disc ?

**Comment by cpesko** [comment]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runui.py", line 8, in <module>
    import arm.ui.routes  # noqa E402
  File "/opt/arm/arm/../arm/ui/routes.py", line 28, in <module>
    armui_cfg = UISettings.query.filter_by().first()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: ui_settings
[SQL: SELECT ui_settings.id AS ui_settings_id, ui_settings.use_icons AS ui_settings_use_icons, ui_settings.save_remote_images AS ui_settings_save_remote_images, ui_settings.boostrap_skin AS ui_settings_boostrap_skin, ui_settings.language AS ui_settings_language, ui_settings.index_refresh AS ui_settings_index_refresh, ui_settings.database_limit AS ui_settings_database_limit 
FROM ui_settings
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by cpesko** [comment]
root@zero:/opt/arm/arm# docker run -d    -p "8080:8080"    -e UID="1000" -e GID="1000"    -v "/home/arm:/home/arm"    -v "/home/arm/music:/home/arm/music"    -v "/home/arm/config:/home/arm/config"    -v "/home/arm/logs:/home/arm/logs"    -v "/media:/home/arm/media/"  --device="/dev/sr*:/dev/sr*"    --privileged    --restart "always"    --name "arm-rippers"

**Comment by cpesko** [comment]
How do I fix ui thing?

**Comment by 1337-server** [comment]
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: ui_settings`

You need to insert a disc to update the database. Your db is still on version `e688fe04d305` or lower but you need at version `9cae4aa05dd7` or higher.

Inserting a disc should trigger the upgrade.

**Comment by cpesko** [comment]
root@zero:/opt/arm# git branch
* (HEAD detached at v2.5.2_docker)
  docker
root@zero:/opt/arm# 

it made a new arm.db.... but still not starting the runui.py

Am I in the wrong branch

**Comment by cpesko** [comment]
I personally dont care if I use docker or not. I was on 2.4 I think on yours and it was ripping fine. then I was like hey I want to try it on docker now everything is just broken I guess.

**Comment by 1337-server** [comment]
Yeah 2.4 on my own branch is considered stable, but docker and the v2_devel branch are both unstable and should only really be used for testing/messing around.

The branch is fine, its the db file that isn't matched with your current version. This is most likely the docker not upgrading your db file to the correct version. 
I'll look into this when i get some free time.

**Comment by cpesko** [comment]
ok so I went to v2_master. arm webpage is now running but does nothing when I put disk in.

**Comment by 1337-server** [comment]
did you check the syslog ?
`tail -f /var/log/syslog`
That should show messages from ARM when it tries to start (when you insert a disc).
Something like this
```

Mar 25 23:58:17 homeserver ARM: [ARM] Starting ARM on sr0
Mar 25 23:58:17 homeserver systemd[1]: Started Session c5 of user root.
Mar 25 23:58:17 homeserver systemd[1]: session-c5.scope: Succeeded.
Mar 25 23:58:17 homeserver ARM: [ARM] ARM Webgui running.

```

**Comment by cpesko** [comment]
root@zero:/home/arm/logs# eject -t sr5
root@zero:/home/arm/logs# tail -f /var/log/syslog
Mar 26 03:26:02 zero kernel: [ 5150.315126] ata7: SATA link up 1.5 Gbps (SStatus 113 SControl 300)
Mar 26 03:26:02 zero kernel: [ 5150.322615] ata7.00: configured for UDMA/33
Mar 26 03:26:02 zero kernel: [ 5150.631107] ata9: SATA link up 1.5 Gbps (SStatus 113 SControl 300)
Mar 26 03:26:02 zero kernel: [ 5150.634519] ata9.00: configured for UDMA/33
Mar 26 03:26:02 zero kernel: [ 5150.635143] pktcdvd: pktcdvd6: pkt_get_last_written failed
Mar 26 03:26:02 zero multipathd[1146]: pktcdvd7: unusable path (wild) - checker failed
Mar 26 03:26:05 zero systemd-udevd[7678]: sr5: Process '/opt/arm/scripts/arm_wrapper.sh sr5' failed with exit code 1.
Mar 26 03:26:05 zero systemd-udevd[7678]: sr5: Process '/opt/arm/scripts/docker_arm_wrapper.sh sr5' failed with exit code 1.
Mar 26 03:26:17 zero systemd-udevd[7695]: sr5: Process '/opt/arm/scripts/arm_wrapper.sh sr5' failed with exit code 1.
Mar 26 03:26:17 zero systemd-udevd[7695]: sr5: Process '/opt/arm/scripts/docker_arm_wrapper.sh sr5' failed with exit code 1.

**Comment by 1337-server** [comment]
You need to 
`rm /opt/arm/scripts/arm_wrapper.sh`
and 
`nano /opt/arm/scripts/arm_wrapper.sh` 
and paste the contents from

https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/v2_master/scripts/arm_wrapper.sh

```
chown arm:arm /opt/arm/scripts/arm_wrapper.sh
chmod +x /opt/arm/scripts/arm_wrapper.sh
```
And then it should run

**Comment by cpesko** [comment]
so I changed it but for some reason now its trying to find docker lol. I dont know what I got messed up but I pulled a fresh arm folder from git and my branch is v2_master. 

Mar 26 04:04:01 zero kernel: [ 7429.779807] sr 9:0:0:0: [sr5] tag#12 Sense Key : Illegal Request [current] 
Mar 26 04:04:01 zero kernel: [ 7429.779811] sr 9:0:0:0: [sr5] tag#12 Add. Sense: Read of scrambled sector without authentication
Mar 26 04:04:01 zero kernel: [ 7429.779815] sr 9:0:0:0: [sr5] tag#12 CDB: Read(10) 28 00 00 3e 9f 80 00 00 40 00
Mar 26 04:04:01 zero kernel: [ 7429.779819] blk_update_request: I/O error, dev sr5, sector 16416256 op 0x0:(READ) flags 0x80700 phys_seg 9 prio class 0
Mar 26 04:04:01 zero kernel: [ 7429.903807] sr 9:0:0:0: [sr5] tag#14 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Mar 26 04:04:01 zero kernel: [ 7429.903811] sr 9:0:0:0: [sr5] tag#14 Sense Key : Illegal Request [current] 
Mar 26 04:04:01 zero kernel: [ 7429.903815] sr 9:0:0:0: [sr5] tag#14 Add. Sense: Read of scrambled sector without authentication
Mar 26 04:04:01 zero kernel: [ 7429.903819] sr 9:0:0:0: [sr5] tag#14 CDB: Read(10) 28 00 00 3e 9f 81 00 00 01 00
Mar 26 04:04:01 zero kernel: [ 7429.903822] blk_update_request: I/O error, dev sr5, sector 16416260 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
Mar 26 04:04:01 zero kernel: [ 7429.904914] Buffer I/O error on dev sr5, logical block 4104065, async page read
Mar 26 04:04:01 zero systemd-udevd[10466]: sr5: Process '/opt/arm/scripts/arm_wrapper.sh sr5' failed with exit code 1.
Mar 26 04:04:01 zero systemd-udevd[10466]: sr5: Process '/opt/arm/scripts/docker_arm_wrapper.sh sr5' failed with exit code 1.

**Comment by 1337-server** [comment]
Check the permission of `/opt/arm/scripts/docker_arm_wrapper.sh` It seems to be a permission issue.

You would be best to remove the udev rule for docker while you're at it, to save any possible conflicts later.

**Comment by 1337-server** [comment]
Assuming this is now resolved
