### ISSUE TITLE
Not ripping in Debian

### ISSUE THREAD

**Issue by heatvent** [automatic-ripping-machine/automatic-ripping-machine#415]
### Description
I used the attended install script on a fresh install of Debian.  I can get to the ARM webpage but if I insert a disk, nothing.  No logs, nothing.

I did look in /etc/fstab and the installer mounted the drive to /mnt/dev/sr0, however, there was already an entry for mounting the drive to /media/cdrom0.  I commented out the line added by ARM and I can see the bluray mounted on the /media/cdrom0 directory.  If I comment out the cdrom0 entry in fstab and use the /mnt/dev/sr0 entry instead, I see nothing when I look at the /mnt/dev/sr0 directory ... just empty.  It seems like Debian wants the drive mounted to /media/cdrom0 to work.  Is this correct? And if so, is there some way to get ARM to work with the drive mounted here or does it have to be at /mnt/dev/srX?

### Environment
Debian 10 64-bit
Latest ARM off of github using attended install script

### Log file
No log files.  In fact, there isn't even a /home/arm/logs directory created yet.  I assume this is because ARM isn't even triggering since the bluray is at /media/cdrom instead of /mnt/dev/sr0.

**Comment by 1337-server** [comment]
did you check the syslog ?
`tail -f /var/log/syslog`
That should show messages from ARM when it tries to start.
Something like this
```

Mar 25 23:58:17 homeserver ARM: [ARM] Starting ARM on sr0
Mar 25 23:58:17 homeserver systemd[1]: Started Session c5 of user root.
Mar 25 23:58:17 homeserver systemd[1]: session-c5.scope: Succeeded.
Mar 25 23:58:17 homeserver ARM: [ARM] ARM Webgui running.

```
what's the output of `sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0`

Personally on debian i could never get ARM to run as the 'arm' user, i had to modify the file `/opt/arm/scripts/arm_wrapper.sh` and change

`/bin/su -l -c "echo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d ${DEVNAME} | at now" -s /bin/bash arm`
to
`/bin/su -l -c "echo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d ${DEVNAME} | at now" -s /bin/bash root`


Did you reboot after updating the fstab ? You need to comment the entry with '/media/cdrom0' and add the arm, then reboot.

**Comment by heatvent** [comment]
I tried the various commands and didn't seem to produce anything that I recognized as an issue.  The sudo -u didn't work and gave a permission error which was strange because I was logged in as root.

I changed arm to root in the wrapper.sh script and that at least go the disk to be recognzied.  However, when ripping, MakeMKV kicked out an error as well.

The short of it is I tried Debian because I liked the idea of having a desktop environment and the auto install script made things pretty simple.  Not sure I am up for trying to tweak and troublshoot Debian however.  I was trying to just install and use.  So I will probably revert back to Ubuntu Server 18.  I was trying to do this in a vmware workstation vm and Ubuntu server wasn't working correctly with the virtual bluray.  However, it was working on the machine if I installed it directly to a hard drive.  I will probably end up piecing together a ripping PC using Ubuntu Server to get away from the other variables and try to keep this simple. 

Thanks for the help. If someone got Debian working and has a step-by-step that is probably as far as I am willing to go time wise on this project.

Thanks again and thanks for all the work on putting ARM together and sharing!

**Comment by 1337-server** [comment]
If `sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0` get a permission error it means that the user 'arm' doesn't have permission to write to the directories in your arm.yaml

MakeMKV is most likely error'ed out because the link in the install scripts is outdated (they update frequently) Most likely MakeMKV wasn't installed and is throwing a missing/not found error

Here is a how-to install guide for Debian 
https://github.com/1337-server/automatic-ripping-machine/wiki/Setting-up-ARM-manually-(Debian-OMV)
I've tested and used ARM on Debian for over 2 years, the setup process isn't perfect or simple on either Debian or Ubuntu. Both will need some setup time to get everything in order.

I also created a ubuntu install script, You might find helpful 
https://github.com/1337-server/automatic-ripping-machine/wiki/Setting-up-ARM-script-(Ubuntu)

**Comment by heatvent** [comment]
So I followed the part of the instructions for installing MakeMKV assuming the rest installed OK and it seems to be working.  Thanks for all the help.  In the meantime, I pieced together a dedicated PC with some old parts.  I had already setup ARM in Ubuntu 18.04 on a hard drive so I used that for now. If things go south at some point, I will probably reinstall with a desktop Ubuntu version based on your guide.  I just don't want to break anything at the moment.

My last step is to customize the use of HandBrake.  I don't care for the presets as none of them copy over HD audio and I would to use a video quality similar to the Amazon Fire TV 1080 along with HD audio only.  I modified the call to HandBrakeCLI in the /opt/arm/arm/ripper/handbrake.py script to be a custom command using a custom preset rather than one of the pre-defined presets in HandBrake although it is not quite working correctly yet.  Getting closer!

**Comment by 1337-server** [comment]
You should be able to modify 
`HB_ARGS_DVD` for dvd's
or
`HB_ARGS_BD` for Blu-rays
in the arm.yaml to get the right audio ? These are passed into the HandBrakeCLI so anything your adding to the 
`/opt/arm/arm/ripper/handbrake.py` Should be able to be passed in via the arm.yaml config

Unless your modifying something different in ` /opt/arm/arm/ripper/handbrake.py`

 
I went the (probably more difficult) route of building HandBrake from source adding my own profile as a preset, It meant i didn't need to modify any python files. It was more difficult to setup, but it means i can pull any updates without issue.

It also meant i got to add Intel QSV and AMD VCE support to HandBrake, which made things much quicker for debugging/setup.

**Comment by heatvent** [comment]
So the issue I thought was an issue was that ARM used presets so I thought you had to use a preset or customize the command in handbrake.py to use an imported custom preset.  Which I tried and was having issues getting to work correctly as audio kept getting dropped.  I noticed at one point that there is a default preset in HandBrakeCLI called "CLI Default".  

```
# Handbrake preset profile for Blurays
# Execute "HandBrakeCLI -z" to see a list of all presets
HB_PRESET_BD: "CLI Default"
```

I am currently using this as the preset in the arm.yaml settings and put handbrake.py back to original (with one tweak, there is a debug printout of the handbrakecli command that was used and I changed this from logging.debug to logging.info so it printed out in the logs without debugging enabled so I can see/confirm what is sent to handbrakecli).

I then used the HB_ARGS_BD noted above to customize what handbrakecli is doing.  The following is what I currently have which is based on some of the settings used in the HQ and Amazon Fire TV presets but using a MKV container and copying DTSHD or TrueHD audio...

```
# Additional Handbrake arguments for Bluray Discs.  Based off of Amazon Fire TV 1080p30 and HQ presets
HB_ARGS_BD: "--markers --encoder=x264 --quality=20.0 --rate=30 --two-pass --no-turbo --comb-detect --decomb --encoder-profile=high --encoder-level=4.0 --audio-lang-list=eng --all-audio --aencoder=copy --audio-copy-mask=dtshd,truehd --audio-fallback=none --subtitle-lang-list=eng --first-subtitle"
```

**Comment by 1337-server** [comment]
Assuming this is now resolved
