### ISSUE TITLE
Discs Not Auto-Ripping On Load

### ISSUE THREAD

**Issue by GoremanX** [automatic-ripping-machine/automatic-ripping-machine#421]
### Description
When I insert a disc into my DVD drive, I get the following error message in the empty.log file:
`INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.`

However, if I manually run:
`sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0`
from the command line while the disc is in the drive, then everything works fine.

### Environment
Ubuntu 20.04.2
ARM v2_master (March 27th, 2021)

**Comment by shitwolfymakes** [comment]
Same here on 18.04, although I only get this on sr1. Sr0 gives a different error.

**Comment by 1337-server** [comment]
> 
> 
> Same here on 18.04, although I only get this on sr1. Sr0 gives a different error.

Can you open an issue with details of the error ?

**Comment by shitwolfymakes** [comment]
Shit, I couldn't get it working so I deleted the vm. Trying your branch now

**Comment by 1337-server** [comment]
Assuming this is now resolved
