### ISSUE TITLE
Can’t seem to mount external blu ray drive within WSL 2 on Win10. Is this supported?

### ISSUE THREAD

**Issue by nazgul6** [automatic-ripping-machine/automatic-ripping-machine#422]
Was hoping to get this running in Ubuntu via Windows Subsystem for Linux 2 on Windows 10.

Seems to have gotten stuck at mounting the external blu ray drive that is connected via USB step. Running dmesg doesn’t seem to find it.

Does anyone have ideas on how to work around this? Or is it just not supported? Anyone managed to get it running under WSL?

Thanks

**Comment by 1337-server** [comment]
Its not currently possible without a lot of extra work. 

You can see the WSL issue here https://github.com/microsoft/WSL/issues/689 
 
A user has posted in the thread a possible solution, but this requires you to modify/build the kernel. You can see what it would require [HERE](https://www.starwindsoftware.com/blog/enable-block-storage-devices-in-wsl2) And even with this ARM may not work as expected.

**Comment by nazgul6** [comment]
Thank you, appreciate the reply. Hopefully in WSL 3 then :)
