### ISSUE TITLE
Ripping finishes successfully + Want to skip transcode = Everything gets deleted in the end?

### ISSUE THREAD

**Issue by nreymundo** [automatic-ripping-machine/automatic-ripping-machine#423]
### Description
Hello! Wasn't sure if this was the proper way to request some troubleshooting help but couldn't find any forum or chat link.

I installed ARM into a new VM yesterday and after getting all the setup working I'm really struggilng with a weird behavior now. Here's what happens: 

1. I pop a BluRay disk on.
2. The udev rule correctly picks it up and starts ARM who then correctly identifies it as a movie. 
3. It starts ripping and I see MakeMKV output files appearing in the raw directory. I can even play them and all is great. 
4. At the same time it also creates an empty folder with the movie name in the final movie directory. 
5. Once everything is finished the disc pops out and the logs say everything was moved to the final movies directory correctly.

What actually happens though is that instead of the files getting moved they get deleted from the raw folder (even though I have the retain raw flag to true) and they are not moved to the final place. In fact, the folder with the movie name under `/movies` also gets deleted. 

I'm redirecting all the ARM directories to a couple mounted SMB shares but that shouldn't be an issue as I can see it creates files and I mounted everything so it belongs to the `arm` user. Here's how I'm mounting everything anyway just in case you guys spot an error: 

```
# NAS stuff
//192.168.1.5/media	/mnt/media		cifs	uid=1001,gid=1001,credentials=/home/arm/.smb,iocharset=utf8,noperm 0 0
//192.168.1.5/ingest	/mnt/ingest		cifs	uid=1001,gid=1001,credentials=/home/arm/.smb,iocharset=utf8,noperm 0 0

# Optical drives
/dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8  0  0
```

```
arm in vm-makemkv in ~ 
❯ ls -las /mnt/
total 12
4 drwxr-xr-x  5 root root 4096 Apr 18 00:30 .
4 drwxr-xr-x 20 root root 4096 Apr 17 19:39 ..
4 drwxr-xr-x  3 root root 4096 Apr 18 00:30 dev
0 drwxr-xr-x  2 arm  arm     0 Apr 18 00:48 ingest
0 drwxr-xr-x  2 arm  arm     0 Mar 27 19:34 media
```

I've tried with 2 different blurays and several times with those two with the results being always the same. Any ideas where I might be screwing up?. 

### Environment

```
arm in vm-makemkv in ~ 
❯ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```
```
arm in vm-makemkv in arm on  v2_master [!] via 🐍 v3.8.5 
❯ git branch
* v2_master

arm in vm-makemkv in arm on  v2_master [!] via 🐍 v3.8.5 
❯ git log -1
commit 851db6f4862a3872702a64e5467a853cca0d058d (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: 3815ddc 47c4f04
Author: flammableliquids <geforbes@gmail.com>
Date:   Fri Apr 16 11:32:14 2021 +1000

    Merge pull request #412 from phirestalker/v2_master
    
    some quick fixes
```

### Log file
I can't find anything wrong on the logs other than it says it failed to eject the drive but it did it as expected. 

[Rocky.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6331384/Rocky.log)

**Comment by 1337-server** [comment]
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/851db6f4862a3872702a64e5467a853cca0d058d/arm/ripper/main.py#L292

This is the line thats causing the issue, you can edit it and put a \# before the s of  `shutil.rmtree(hboutpath) ` and it will stop it from deleting the raw files.

**Comment by MarcTimperley** [comment]
If you're skipping the transcode, check the **completed** folder. I skip transcode to batch them up for overnight processing via HandBrakeCLI. The mkv files that have been ripped are probably in subfolders of the **completed** folder as the raw files will have been moved,

**Comment by ftronel** [comment]
Hello,

I have the same problem with my arm local installation. The problem appears with SKIP_TRANSCODE: true, RIP_METHOD: mkv and when the title of the DVD is found. The code leads to extract the MKV files directly to their final destination (MEDIA_DIR), instead of RAWPATH, which is then deleted as if it was a temporary directory ...

I have commented the following lines:
#logging.debug("Attempting to remove extra folder in ARMPATH: " + hboutpath)
                    #try:
                    #   shutil.rmtree(hboutpath)
                    #   logging.debug("Removed sucessfully: " + hboutpath)
                    #except Exception:
                    #   logging.debug("Failed to remove: " + hboutpath)

**Comment by Sono-Gomorrha** [comment]
I can confirm, that commenting line 292 in main.py (as mentioned above) seems to solve the issue. 
```
[2022-04-27 21:39:46] INFO ARM: Exiting MakeMKV processing with return value of: /mnt/arm/media/raw/Total Recall
[2022-04-27 21:39:46] INFO ARM: SKIP_TRANSCODE is true.  Moving raw mkv files.
[2022-04-27 21:39:46] INFO ARM: NOTE: Identified main feature may not be actual main feature
[2022-04-27 21:39:46] INFO ARM: Track is the Main Title.  Moving 'Total Recall_t00.mkv' to /mnt/arm/media/movies/Total Recall (1990)
[2022-04-27 21:39:46] INFO ARM: Removing raw files
[2022-04-27 21:39:46] INFO ARM: ARM processing complete
```
Now I can find the file in the mentioned folder 'movies' named correctly.

**Comment by 1337-server** [comment]
This issue is fixed in later versions, but they aren't merged to the main repo yet.

**Comment by 1337-server** [comment]
Issue should now be fixed!
