### ISSUE TITLE
Ripping very slow (+16h / DVD)

### ISSUE THREAD

**Issue by wvbesien** [automatic-ripping-machine/automatic-ripping-machine#424]
### Description
Ripping one DVD takes more than 16h.
I found [this](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/273), and I did what cclarke591 wrote on 17 Jan 2019, but this didn't solve my issue.
Could someone please take a look at my log-file to see what could be wrong?

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
ARM version: 2.1.0-dev
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
CPU: Intel(R) Atom(TM) CPU D525   @ 1.80GHz

### Log file
[ARM.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6454845/ARM.log)

**Comment by bwbloom** [comment]
@wvbesien I only gave the log a cursory glance and I did not see some error that stopped the process.

I think this could very likely be the expected performance of a decade old low power CPU. This does not have any features I can see that would support quicker ripping time. Without a major hardware change this very well might be the expected performance for your system.

**Comment by 1337-server** [comment]
You should also avoid using the other branches. 

Pull from v2_master not v2.1.0-dev

**Comment by wvbesien** [comment]
Thanks a lot for  your answers.
Could someone show me the right way to modify my ARM installation from v2.1.0-dev to v2_master, without loosing my configurations?

**Comment by 1337-server** [comment]
Sorry for the late response. 

v2.1.0 is now the most updated branch. You should be able to run the following commands in a terminal/ssh to update to the latest version.

```
cd /opt/arm
git pull
```
You could also try the solution inside https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/435 this might help with performance issues.

**Comment by 1337-server** [comment]
Assuming this is now resolved
