### ISSUE TITLE
Arm not working

### ISSUE THREAD

**Issue by HaroldRobi** [automatic-ripping-machine/automatic-ripping-machine#425]
### Description
When inserting a disk arm reports the drive empty. When running the command manually it tells me job 96 submitted (or something like that) and returns to the command prompt.  I have read all the troubleshooting guides but they are not helping much

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")] running Ubuntu 20.04
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]v2_devel
HEAD -> v2_devel, origin/v2_devel, origin/HEAD

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

Nothing to post. Just reports the drive is empty when a DVD is inserted into the drive

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Have you check the wiki ? https://github.com/1337-server/automatic-ripping-machine/wiki/FAQ

**Comment by HaroldRobi** [comment]
I have been troubleshooting this for the last week including installing the software on to my target machine 3 times.  After following the install document found here, I finally got it working, some what.  I have consulted the Wiki but it was not helpful  in resolving my issue.  Here is the run down of my troubleshooting.

> When a disc is inserted, udev rules should launch a script (scripts/arm_wrapper.sh) that will launch ARM. Here are some basic troubleshooting steps:
> 
> Look for empty.log.
> 
> Every time you eject the cdrom, an entry should be entered in empty.log like:
> [2018-08-05 11:39:45] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.

Yes I get this statement when I eject the disk .. but NOT every time.  It also created a "Harry Potter Sorcerers's Stone" log file but its empty. I started MakeMKV and MakeMKV found and read the disk just fine.  I know I might be having some hardware issues with some DVD ROM drives I have, and I am going to remove these from the server until I have the software issues resolved.   I have the log level set to DEBUG for troubleshooting purposes.

> Make sure the user arm has write permission to the location you have set in your arm.yaml You can test these permission by inserting a disc and running (remember to replace sr0 with the name of your own device)
> 
> sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0

confirmed, arm user has write permissions to /opt/arm

> Check that the arm_wrapper.sh is executable try running tail -f /var/log/syslog before you insert a disc, then watch for
> sr0: Process '/opt/arm/scripts/arm_wrapper.sh sr0' failed with exit code 1
> If you see this in your logs it can mean arm_wrapper.sh isn't executable, you can fix this by running
> sudo chmod +x /opt/arm/scripts/arm_wrapper.sh

I did not see this error, but I went to /opt/arm/scripts and executed sudo chmod 777 arm_wrapper.sh which did not change anything.

**Comment by 1337-server** [comment]
What is the output from the syslog when a disc is inserted ?

Is it possible that the arm user doesn't have access to the cdrom group ? (`groups arm` in terminal)
Try letting ARM run as root to maybe help narrow down issues.
open `/opt/arm/scripts/arm_wrapper.sh` and change
`/bin/su -l -c "echo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d ${DEVNAME} | at now" -s /bin/bash arm`
to 
`/bin/su -l -c "echo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d ${DEVNAME} | at now" -s /bin/bash root`

I can't think of any other issues, other than hardware that would cause this.

**Comment by HaroldRobi** [comment]
Thanks for the clues.  I have found my problem.  As I was watching the syslog while ARM was starting, I saw ARM spit out an email, then terminate.  I looked at the messages that were mailed to the arm user and found this little error in the message:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database

After googleing this error I found out that the database was in a read only state. (you can tell that from the error as well)  So I carefully looked at the file, and found arm.db had arm:arm as the user.  I changed the write access to the file rights from 664 to 666 but this did not fix the issue.  Next I moved up one directory to /home/arm then executed a ls -alh and found the db folder ownership set to root:root  I changed the ownership by executing the command sudo chown arm:arm db

ARM then came to life and ripped the first DVD.

Is there a way to disable handbreak encoding, I just want to rip the whole feature leaving it a .mkv file.

Thank you for the help

**Comment by 1337-server** [comment]
Glad you got it fixed.

Skip_transcode in the arm.yaml is what you're looking for.

**Comment by HaroldRobi** [comment]
The real issue I was having was not the branch issue but the documentation.  Some people posted documentation on how to get ARM working with Ubuntu.  Because they were missing instructions or missing "Sudo" commands and their installation would file ... like missing database files, and the like, when I used the document you posed here, it started working after I followed all the steps.
