### ISSUE TITLE
Error with Title Searches

### ISSUE THREAD

**Issue by HaroldRobi** [automatic-ripping-machine/automatic-ripping-machine#426]
### Description
I get "TypeError: argument of type 'NoneType' is not iterable" when I execute a title search from the web interface.

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
* v2_devel
-------------
commit 7dcda92a84b834217ff0ce95afe9f4c2f090644c (HEAD -> v2_devel, origin/v2_devel, origin/HEAD)
Author: 1337-server <62730074+1337-server@users.noreply.github.com>
Date:   Sat May 8 02:49:38 2021 +0100

    Create ubuntu-quicksync.sh

### Log file
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
return func(*args, **kwargs)
File "/opt/arm/arm/ui/routes.py", line 606, in list_titles
if 'Error' in search_results or ('Search' in search_results and len(search_results['Search']) < 1):
TypeError: argument of type 'NoneType' is not iterable

Additional info from syslog:

May 15 02:12:37 ripasaurus python3[2037]: Traceback (most recent call last):
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
May 15 02:12:37 ripasaurus python3[2037]:     return self.wsgi_app(environ, start_response)
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
May 15 02:12:37 ripasaurus python3[2037]:     response = self.handle_exception(e)
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
May 15 02:12:37 ripasaurus python3[2037]:     reraise(exc_type, exc_value, tb)
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
May 15 02:12:37 ripasaurus python3[2037]:     raise value
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
May 15 02:12:37 ripasaurus python3[2037]:     response = self.full_dispatch_request()
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
May 15 02:12:37 ripasaurus python3[2037]:     rv = self.handle_user_exception(e)
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
May 15 02:12:37 ripasaurus python3[2037]:     reraise(exc_type, exc_value, tb)
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
May 15 02:12:37 ripasaurus python3[2037]:     raise value
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
May 15 02:12:37 ripasaurus python3[2037]:     rv = self.dispatch_request()
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
May 15 02:12:37 ripasaurus python3[2037]:     return self.view_functions[rule.endpoint](**req.view_args)
May 15 02:12:37 ripasaurus python3[2037]:   File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
May 15 02:12:37 ripasaurus python3[2037]:     return func(*args, **kwargs)
May 15 02:12:37 ripasaurus python3[2037]:   File "/opt/arm/arm/ui/routes.py", line 606, in list_titles
May 15 02:12:37 ripasaurus python3[2037]:     if 'Error' in search_results or ('Search' in search_results and len(search_results['Search']) < 1):
May 15 02:12:37 ripasaurus python3[2037]: TypeError: argument of type 'NoneType' is not iterable
May 15 02:12:37 ripasaurus python3[2037]: 10.1.1.200 - - [15/May/2021 02:12:37] "#033[37mGET /list_titles?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1#033[0m" 200 -
May 15 02:12:37 ripasaurus python3[2037]: 10.1.1.200 - - [15/May/2021 02:12:37] "#033[37mGET /list_titles?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1#033[0m" 200 -
May 15 02:12:37 ripasaurus python3[2037]: 10.1.1.200 - - [15/May/2021 02:12:37] "#033[37mGET /list_titles?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1#033[0m" 200 -
May 15 02:12:37 ripasaurus python3[2037]: 10.1.1.200 - - [15/May/2021 02:12:37] "#033[37mGET /list_titles?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1#033[0m" 200 -
May 15 02:12:37 ripasaurus python3[2037]: 10.1.1.200 - - [15/May/2021 02:12:37] "#033[37mGET /list_titles?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1#033[0m" 200 -
May 15 02:17:01 ripasaurus CRON[5756]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

**Comment by 1337-server** [comment]
https://github.com/1337-server/automatic-ripping-machine/commit/fca25f851b364600b76549926388066ed0e92886 Should fix this

**Comment by HaroldRobi** [comment]
This seems to have fixed the issue.  Thank you.

**Comment by microtechno9000** [comment]
@1337-server are you rolling this change into v2.1_dev branch?

**Comment by 1337-server** [comment]
I'm still waiting for #436 to be merged/rejected to the main branch.

I submit pull requests when the previous pulls get merged/ejected. But as soon as 436 is resolved, ill submit another pull with the latest commit from my fork.
