### ISSUE TITLE
Not Ripping,  ejects before rip

### ISSUE THREAD

**Issue by coacharnold1** [automatic-ripping-machine/automatic-ripping-machine#430]
### Description
When I put in a disc it reads,  then ejects.  ARM has been working great for a long time,  Ive upgraded to Ubuntu server 21.04 and all seems lost 

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
not sure ....  runnig git-branch doesnt get me any info

### Log file

ID_FS_USAGE=filesystem
ID_FOR_SEAT=block-pci-0000_00_1f_2-ata-2_0
DEVLINKS=/dev/cdrom /dev/disk/by-label/sonia\x20and\x20time /dev/dvdrw /dev/dvd /dev/disk/by-id/wwn-0x5001480000000000 /dev/disk/by-path/pci-0000:00:1f.2-ata-2.0 /dev/disk/by-id/ata-HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833 /dev/cdrw /dev/disk/by-path/pci-0000:00:1f.2-ata-2 /dev/disk/by-uuid/418c783b20202020
TAGS=:uaccess:systemd:seat:
CURRENT_TAGS=:uaccess:systemd:seat:
identified udf
found sonia_and_time on /dev/sr0
identified udf as video
failed to get title Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 7, in 
    import pydvdid
ModuleNotFoundError: No module named 'pydvdid'
got to here
HAS_NICE_TITLE is false
video title is now sonia_and_time
video type is unknown
Starting video_rip.sh
Video Title is sonia_and_time
Ripping video sonia_and_time from /dev/sr0
Using mkv method ID_REVISION=LN00
ID_TYPE=cd
ID_CDROM=1
SYSTEMD_MOUNT_DEVICE_BOUND=1
ID_ATA=1
ID_BUS=ata
ID_SERIAL=HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833
ID_SERIAL_SHORT=KKBDC981833
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_WWN=0x5001480000000000
ID_WWN_WITH_EXTENSION=0x5001480000000000
ID_PATH=pci-0000:00:1f.2-ata-2.0
ID_PATH_TAG=pci-0000_00_1f_2-ata-2_0
ID_PATH_ATA_COMPAT=pci-0000:00:1f.2-ata-2
ID_FOR_SEAT=block-pci-0000_00_1f_2-ata-2_0
DEVLINKS=/dev/disk/by-id/wwn-0x5001480000000000 /dev/disk/by-path/pci-0000:00:1f.2-ata-2.0 /dev/disk/by-id/ata-HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833 /dev/disk/by-path/pci-0000:00:1f.2-ata-2
TAGS=:uaccess:systemd:seat:
CURRENT_TAGS=:uaccess:systemd:seat:
drive seems empty, not ejecting of ripping.

**Comment by 1337-server** [comment]
``` 
File "/opt/arm/getmovietitle.py", line 7, in
import pydvdid
ModuleNotFoundError: No module named 'pydvdid'
got to here
HAS_NICE_TITLE is false

```

You need to reinstall the python module 'pydvdid', or reinstall a newer version of ARM

**Comment by coacharnold1** [comment]
This didn't work.  re-installed pydvdid ... 
Also ... I'm not exactly sure how to tell what version I'm running ..    this is the changelog from the my arm folder ... is it possible I'm only running 1.3??

if so  - :-( 
whats the best way to get everything back?

 Changelog

## v1.3.0
 - Get Title for DVD and Blu-Rays so that media servesr can identify them easily.
 - Determine if video is Movie or TV-Show from OMDB API query so that different actions can be taken (TV shows usually require manual episode identification)
 - Option for MakeMKV to rip using backup method.
 - Option to rip only main feature if so desired.

## v1.2.0
- Distinguish UDF data from UDF video discs

## v1.1.1

- Added devname to abcde command
- Added logging stats (timers). "grep STAT" to see parse them out.

## v1.1.0

- Added ability to rip from multiple drives at the same time
- Added a config file for parameters
- Changed logging
  - Log name is based on ID_FS_LABEL (dvd name) variable set by udev in order to isolate logging from multiple process running simultaneously
  - Log file name and path set in config file
  - Log file cleanup based on parameter set in config file
- Added phone notification options for Pushbullet and IFTTT
- Remove MakeMKV destination directory after HandBrake finishes transcoding
- Misc stuff

## v1.0.1

- Fix ripping "Audio CDs" in ISO9660 format like LOTR.

## v1.0.0

**Comment by coacharnold1** [comment]
Did not work after software fix... posting new issue
