### ISSUE TITLE
Not ripping DVD,  ejecting after a few seconds 

### ISSUE THREAD

**Issue by coacharnold1** [automatic-ripping-machine/automatic-ripping-machine#431]
### Description
Not ripping DVD,  ejecting after a few seconds 

### Environment
ubuntu 21.04
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

### Log file
** Start config parameters ****
        Timestamp: Tue, 25 May 2021 17:47:04 -0400
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
ARMPATH="/home/fausto/rips"
RAWPATH="/home/fausto/rips/raw"
MEDIA_DIR="/home/fausto/rips/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
SET_MEDIA_OWNER=false
CHOWN_USER=
CHOWN_GROUP=
MINLENGTH="100"
RIPMETHOD="mkv" 
MKV_ARGS=""
HB_PRESET="High Profile" 
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--native-language eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle-default=1 --subtitle-forced=1 --audio-lang-list eng --all-audio"
PLEX_SUPPORT=false
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files: 
DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/block/sr0
DEVNAME=/dev/sr0
DEVTYPE=disk
MAJOR=11
MINOR=0
SUBSYSTEM=block
USEC_INITIALIZED=5609321
SCSI_TPGS=0
SCSI_TYPE=cd/dvd
SCSI_VENDOR=HL-DT-ST
SCSI_VENDOR_ENC=HL-DT-ST
SCSI_MODEL=DVDRAM_GH24NSB0
SCSI_MODEL_ENC=DVDRAM\x20GH24NSB0\x20
SCSI_REVISION=LN00
ID_SCSI=1
ID_SCSI_INQUIRY=1
ID_VENDOR=HL-DT-ST
ID_VENDOR_ENC=HL-DT-ST
ID_MODEL=HL-DT-ST_DVDRAM_GH24NSB0
ID_MODEL_ENC=HL-DT-ST\x20DVDRAM\x20GH24NSB0\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_REVISION=LN00
ID_TYPE=cd
ID_CDROM=1
SYSTEMD_MOUNT_DEVICE_BOUND=1
ID_ATA=1
ID_BUS=ata
ID_SERIAL=HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833
ID_SERIAL_SHORT=KKBDC981833
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_WWN=0x5001480000000000
ID_WWN_WITH_EXTENSION=0x5001480000000000
ID_PATH=pci-0000:00:1f.2-ata-2.0
ID_PATH_TAG=pci-0000_00_1f_2-ata-2_0
ID_PATH_ATA_COMPAT=pci-0000:00:1f.2-ata-2
ID_FOR_SEAT=block-pci-0000_00_1f_2-ata-2_0
DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-2 /dev/disk/by-id/wwn-0x5001480000000000 /dev/disk/by-id/ata-HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833 /dev/disk/by-path/pci-0000:00:1f.2-ata-2.0
TAGS=:seat:systemd:uaccess:
CURRENT_TAGS=:seat:systemd:uaccess:
drive seems empty, not ejecting
*** Start config parameters ****
        Timestamp: Tue, 25 May 2021 18:16:24 -0400
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
ARMPATH="/home/fausto/rips"
RAWPATH="/home/fausto/rips/raw"
MEDIA_DIR="/home/fausto/rips/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
SET_MEDIA_OWNER=false
CHOWN_USER=
CHOWN_GROUP=
MINLENGTH="100"
RIPMETHOD="mkv" 
MKV_ARGS=""
HB_PRESET="High Profile" 
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--native-language eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle-default=1 --subtitle-forced=1 --audio-lang-list eng --all-audio"
PLEX_SUPPORT=false
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files: 
DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/block/sr0
DEVNAME=/dev/sr0
DEVTYPE=disk
MAJOR=11
MINOR=0
SUBSYSTEM=block
USEC_INITIALIZED=5609321
SCSI_TPGS=0
SCSI_TYPE=cd/dvd
SCSI_VENDOR=HL-DT-ST
SCSI_VENDOR_ENC=HL-DT-ST
SCSI_MODEL=DVDRAM_GH24NSB0
SCSI_MODEL_ENC=DVDRAM\x20GH24NSB0\x20
SCSI_REVISION=LN00
ID_SCSI=1
ID_SCSI_INQUIRY=1
ID_VENDOR=HL-DT-ST
ID_VENDOR_ENC=HL-DT-ST
ID_MODEL=HL-DT-ST_DVDRAM_GH24NSB0
ID_MODEL_ENC=HL-DT-ST\x20DVDRAM\x20GH24NSB0\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_REVISION=LN00
ID_TYPE=cd
ID_CDROM=1
SYSTEMD_MOUNT_DEVICE_BOUND=1
ID_CDROM_CD=1
ID_CDROM_CD_R=1
ID_CDROM_CD_RW=1
ID_CDROM_DVD=1
ID_CDROM_DVD_R=1
ID_CDROM_DVD_RW=1
ID_CDROM_DVD_RAM=1
ID_CDROM_DVD_PLUS_R=1
ID_CDROM_DVD_PLUS_RW=1
ID_CDROM_DVD_PLUS_R_DL=1
ID_CDROM_MEDIA=1
ID_CDROM_MEDIA_DVD=1
ID_CDROM_MEDIA_STATE=complete
ID_CDROM_MEDIA_SESSION_COUNT=1
ID_CDROM_MEDIA_TRACK_COUNT=1
ID_CDROM_MEDIA_TRACK_COUNT_DATA=1
ID_ATA=1
ID_BUS=ata
ID_SERIAL=HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833
ID_SERIAL_SHORT=KKBDC981833
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_WWN=0x5001480000000000
ID_WWN_WITH_EXTENSION=0x5001480000000000
ID_PATH=pci-0000:00:1f.2-ata-2.0
ID_PATH_TAG=pci-0000_00_1f_2-ata-2_0
ID_PATH_ATA_COMPAT=pci-0000:00:1f.2-ata-2
ID_FS_UUID=4558084900000000
ID_FS_UUID_ENC=4558084900000000
ID_FS_LABEL=THE_IMITATION_GAME
ID_FS_LABEL_ENC=THE_IMITATION_GAME
ID_FS_VERSION=1.02
ID_FS_TYPE=udf
ID_FS_USAGE=filesystem
ID_FOR_SEAT=block-pci-0000_00_1f_2-ata-2_0
DEVLINKS=/dev/cdrw /dev/disk/by-path/pci-0000:00:1f.2-ata-2.0 /dev/disk/by-uuid/4558084900000000 /dev/disk/by-id/wwn-0x5001480000000000 /dev/cdrom /dev/disk/by-id/ata-HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833 /dev/disk/by-label/THE_IMITATION_GAME /dev/dvdrw /dev/dvd /dev/disk/by-path/pci-0000:00:1f.2-ata-2
TAGS=:systemd:uaccess:seat:
CURRENT_TAGS=:systemd:uaccess:seat:
identified udf
found THE_IMITATION_GAME on /dev/sr0
identified udf as video
failed to get title Traceback (most recent call last):
  File "/opt/arm/getmovietitle.py", line 9, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'
got to here
HAS_NICE_TITLE is false
video title is now THE_IMITATION_GAME
video type is unknown
Starting video_rip.sh
Video Title is THE_IMITATION_GAME
Ripping video THE_IMITATION_GAME from /dev/sr0
Using mkv method of ripping.
STAT: THE_IMITATION_GAME ripped in 0 hours, 0 minutes and 5 seconds.
/opt/arm/video_transcode.sh "/home/fausto/rips/raw/THE_IMITATION_GAME_20210525_181627" "THE_IMITATION_GAME" "false" "unknown" 20210525_181627
THE_IMITATION_GAME sent to transcoding queue...
Start video transcoding script
transcoding without a nice title
Transcoding all files.
STAT:  transcoded in 0 hours, 0 minutes and 0 seconds.
Pushbullet notifications not enabled
IFTTT notifications not enabled
Pusover notifications not enabled
*** Start config parameters ****
        Timestamp: Tue, 25 May 2021 18:16:33 -0400
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
ARMPATH="/home/fausto/rips"
RAWPATH="/home/fausto/rips/raw"
MEDIA_DIR="/home/fausto/rips/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
SET_MEDIA_OWNER=false
CHOWN_USER=
CHOWN_GROUP=
MINLENGTH="100"
RIPMETHOD="mkv" 
MKV_ARGS=""
HB_PRESET="High Profile" 
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--native-language eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle-default=1 --subtitle-forced=1 --audio-lang-list eng --all-audio"
PLEX_SUPPORT=false
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files: 
DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/block/sr0
DEVNAME=/dev/sr0
DEVTYPE=disk
MAJOR=11
MINOR=0
SUBSYSTEM=block
USEC_INITIALIZED=5609321
SCSI_TPGS=0
SCSI_TYPE=cd/dvd
SCSI_VENDOR=HL-DT-ST
SCSI_VENDOR_ENC=HL-DT-ST
SCSI_MODEL=DVDRAM_GH24NSB0
SCSI_MODEL_ENC=DVDRAM\x20GH24NSB0\x20
SCSI_REVISION=LN00
ID_SCSI=1
ID_SCSI_INQUIRY=1
ID_VENDOR=HL-DT-ST
ID_VENDOR_ENC=HL-DT-ST
ID_MODEL=HL-DT-ST_DVDRAM_GH24NSB0
ID_MODEL_ENC=HL-DT-ST\x20DVDRAM\x20GH24NSB0\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_REVISION=LN00
ID_TYPE=cd
ID_CDROM=1
SYSTEMD_MOUNT_DEVICE_BOUND=1
ID_CDROM_CD=1
ID_CDROM_CD_R=1
ID_CDROM_CD_RW=1
ID_CDROM_DVD=1
ID_CDROM_DVD_R=1
ID_CDROM_DVD_RW=1
ID_CDROM_DVD_RAM=1
ID_CDROM_DVD_PLUS_R=1
ID_CDROM_DVD_PLUS_RW=1
ID_CDROM_DVD_PLUS_R_DL=1
SYSTEMD_READY=0
ID_ATA=1
ID_BUS=ata
ID_SERIAL=HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833
ID_SERIAL_SHORT=KKBDC981833
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_WWN=0x5001480000000000
ID_WWN_WITH_EXTENSION=0x5001480000000000
ID_PATH=pci-0000:00:1f.2-ata-2.0
ID_PATH_TAG=pci-0000_00_1f_2-ata-2_0
ID_PATH_ATA_COMPAT=pci-0000:00:1f.2-ata-2
ID_FOR_SEAT=block-pci-0000_00_1f_2-ata-2_0
DEVLINKS=/dev/disk/by-path/pci-0000:00:1f.2-ata-2 /dev/cdrom /dev/dvdrw /dev/disk/by-id/wwn-0x5001480000000000 /dev/dvd /dev/cdrw /dev/disk/by-path/pci-0000:00:1f.2-ata-2.0 /dev/disk/by-id/ata-HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833
TAGS=:systemd:uaccess:seat:
CURRENT_TAGS=:systemd:uaccess:seat:
drive seems empty, not ejecting
*** Start config parameters ****
        Timestamp: Tue, 25 May 2021 18:16:33 -0400
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
ARMPATH="/home/fausto/rips"
RAWPATH="/home/fausto/rips/raw"
MEDIA_DIR="/home/fausto/rips/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
SET_MEDIA_OWNER=false
CHOWN_USER=
CHOWN_GROUP=
MINLENGTH="100"
RIPMETHOD="mkv" 
MKV_ARGS=""
HB_PRESET="High Profile" 
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--native-language eng --subtitle scan,1,2,3,4,5,6,7,8,9,10 --subtitle-default=1 --subtitle-forced=1 --audio-lang-list eng --all-audio"
PLEX_SUPPORT=false
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files: 
DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata2/host1/target1:0:0/1:0:0:0/block/sr0
DEVNAME=/dev/sr0
DEVTYPE=disk
MAJOR=11
MINOR=0
SUBSYSTEM=block
USEC_INITIALIZED=5609321
SCSI_TPGS=0
SCSI_TYPE=cd/dvd
SCSI_VENDOR=HL-DT-ST
SCSI_VENDOR_ENC=HL-DT-ST
SCSI_MODEL=DVDRAM_GH24NSB0
SCSI_MODEL_ENC=DVDRAM\x20GH24NSB0\x20
SCSI_REVISION=LN00
ID_SCSI=1
ID_SCSI_INQUIRY=1
ID_VENDOR=HL-DT-ST
ID_VENDOR_ENC=HL-DT-ST
ID_MODEL=HL-DT-ST_DVDRAM_GH24NSB0
ID_MODEL_ENC=HL-DT-ST\x20DVDRAM\x20GH24NSB0\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_REVISION=LN00
ID_TYPE=cd
ID_CDROM=1
SYSTEMD_MOUNT_DEVICE_BOUND=1
ID_ATA=1
ID_BUS=ata
ID_SERIAL=HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833
ID_SERIAL_SHORT=KKBDC981833
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_WWN=0x5001480000000000
ID_WWN_WITH_EXTENSION=0x5001480000000000
ID_PATH=pci-0000:00:1f.2-ata-2.0
ID_PATH_TAG=pci-0000_00_1f_2-ata-2_0
ID_PATH_ATA_COMPAT=pci-0000:00:1f.2-ata-2
ID_FOR_SEAT=block-pci-0000_00_1f_2-ata-2_0
DEVLINKS=/dev/disk/by-id/ata-HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833 /dev/disk/by-id/wwn-0x5001480000000000 /dev/disk/by-path/pci-0000:00:1f.2-ata-2 /dev/disk/by-path/pci-0000:00:1f.2-ata-2.0
TAGS=:uaccess:systemd:seat:
CURRENT_TAGS=:uaccess:systemd:seat:
drive seems empty, not ejecting
fausto@Auto-Box:/opt/arm/logs$ tail 100
tail: cannot open '100' for reading: No such file or directory
fausto@Auto-Box:/opt/arm/logs$ tail 
^C
fausto@Auto-Box:/opt/arm/logs$ tail empty.log 
ID_WWN=0x5001480000000000
ID_WWN_WITH_EXTENSION=0x5001480000000000
ID_PATH=pci-0000:00:1f.2-ata-2.0
ID_PATH_TAG=pci-0000_00_1f_2-ata-2_0
ID_PATH_ATA_COMPAT=pci-0000:00:1f.2-ata-2
ID_FOR_SEAT=block-pci-0000_00_1f_2-ata-2_0
DEVLINKS=/dev/disk/by-id/ata-HL-DT-ST_DVDRAM_GH24NSB0_KKBDC981833 /dev/disk/by-id/wwn-0x5001480000000000 /dev/disk/by-path/pci-0000:00:1f.2-ata-2 /dev/disk/by-path/pci-0000:00:1f.2-ata-2.0
TAGS=:uaccess:systemd:seat:
CURRENT_TAGS=:uaccess:systemd:seat:
drive seems empty, not ejecting

**Comment by 1337-server** [comment]
```
failed to get title Traceback (most recent call last):
File "/opt/arm/getmovietitle.py", line 9, in
import xmltodict
ModuleNotFoundError: No module named 'xmltodict'
got to here
HAS_NICE_TITLE is false
```

You need to reinstall the python module 'xmltodict', or reinstall a newer version of ARM

Is there a reason/feature you are pulling from the master branch ?

**Comment by coacharnold1** [comment]
This is a version of ARM that has been running perfectly for several years.   I just updated the server it is on to 21.04 and this problem began.     I don't really want to get into updating ARM as there was so much configuring originally with MAKEMKV,  I'd rather not start from scratch.   How can I get this working without having to re-install everything,   Is there an easy way to update without killing all my configs?

Also,  I'm not even sure where the main config is...

**Comment by 1337-server** [comment]
> Is there an easy way to update without killing all my configs?

Not really with that version of ARM. ARM has had a total rewrite since then, some values may be the same in the newer config versions, but you would need to update the new config manually.

> How can I get this working without having to re-install everything,

You could try `cd /opt/arm` and then running `pip3 install -r requirements.txt` 
But if that doesn't work, there isn't really any other option but to upgrade to the newer version.

> Also, I'm not even sure where the main config is...

`/opt/arm/config` is the default location for the config file on that version.

**Comment by coacharnold1** [comment]
Re installed to newest version...   Seems to be working great!!
