### ISSUE TITLE
CD audio file owner and permissons settings

### ISSUE THREAD

**Issue by mscj1983** [automatic-ripping-machine/automatic-ripping-machine#438]
### Description
I cannot figure out how to get ARM to make my CD rips belong to everybody and chmod 777. Those settings I changed in the arm.yaml but it didn't fix anything. Everything else is working just fine so far.

### Environment
Linux openmediavault 5.10.0-0.bpo.5-amd64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64 GNU/Linux

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
2.2.0-dev

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

**Comment by 1337-server** [comment]
If you are running ARM as the default arm user then i don't believe its possible to change/use the chmod or chown as they both require root permissions.

**Comment by mscj1983** [comment]
Ok. Just trying to see if I missed something easy. I installed ARM on my OpenMediaVault NAS system. I will just set OMV to chmod the rip directories nightly.
