### ISSUE TITLE
OMDB Not working 

### ISSUE THREAD

**Issue by coacharnold1** [automatic-ripping-machine/automatic-ripping-machine#439]
### Description
So OMDB is not working ... here's what I have in my arm.raml file

OMDB_API_KEY: "365a2891"

Here's the key from the activation email from OMdB

Here is your key: 365a2891

Please append it to all of your API requests,

Here's what I get in the logs:

[16-06-2021 23:14:31] DEBUG ARM: utils.call_omdb_api omdb call failed with error - HTTP Error 401: Unauthorized
[16-06-2021 23:14:31] INFO ARM: identify.identify Disc title Post ident -  title:BEHINDENEMYLINES_US_DTS year: video_type:unknown disctype: dvd
[16-06-2021 23:14:31] DEBUG ARM: identify.identify identify.job.end -

### Environment
[BEHINDENEMYLINES_US_DTS.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6666396/BEHINDENEMYLINES_US_DTS.log)
[BEHINDENEMYLINES_US_DTS.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6666398/BEHINDENEMYLINES_US_DTS.log)
"Ubuntu 20.04.2 LTS"

* v2_devel

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Did you activate the key ?

When you got the email containing the key it should say at the bottom to click x link to activate the key.

the link should look something similar to  

`Click the following URL to activate your key: http://www.omdbapi.com/apikey.aspx?VERIFYKEY=60606060-6060-6060-6060-60606060`

**Comment by jack-dvd-ripper** [comment]
I too made this mistake.

**Comment by eitch** [comment]
It seems a few restarts of the docker container later, it works =)
