### ISSUE TITLE
Log filling up hard drive 

### ISSUE THREAD

**Issue by coacharnold1** [automatic-ripping-machine/automatic-ripping-machine#440]
### Description
Web UI log filling up hard drive storage.  Below is an ls of my arm/log folder 

drwxrwxr-x  2 arm  arm          4096 Jul  2 01:40 .
drwxrwxrwx 11  777 arm          4096 Jun 17 13:17 ..
-rw-rw-r--  1 arm  arm      29466624 Jul  2 00:44 WHOLPHIN_NO_5.log
-rw-rw-r--  1 arm  arm      15446016 Jul  2 00:46 WHOLPHIN_NO_6.log
-rw-rw-r--  1 arm  arm           103 Jul  2 01:40 WHOLPHIN_NO_6_162519004082.log
-rw-r--r--  1 root root 161886253508 Jul  3 20:34 WebUI.log
-rw-rw-r--  1 arm  arm      31555584 Jul  2 00:46 Wholphin_#3.log
-rw-rw-r--  1 arm  arm          1464 Jul  2 01:40 empty.log

### Environment
Ubuntu 20.04

### Log file
Can't post it as it is many gigs:   here's a little whats inside

vg 1.18 fps, ETA 02h06m07s)\rEncoding: task 1 of 1, 49.85 % (0.89 fps, avg 1.18 fps, ETA 02h06m07s)\rEncoding: task 1 of 1, 49.85 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.85 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.86 % (0.94 fps, avg 1.18 fps, ETA 02h06m06s)\rEncoding: task 1 of 1, 49.87 % (0.81 fps, avg 1.18 fps, ETA 02h06m05s)\rEncoding: task 1 of 1, 49.87 % (0.81 fps, avg 1.18 fps, ETA 02h06m05s)\rEncoding: task 1 of 1, 49.87 % (0.81 fps, avg 1.18 fps, ETA 02h06m05s)\rEncoding: task 1 of 1, 49.87 % (0.81 fps, avg 1.18 fps, ETA 02h06m05s)\rEncoding: task 1 of 1, 49.87 % (0.81 fps, avg 1.18 fps, ETA 02h06m05s)\rEncoding: task 1 of 1, 49.88 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.88 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.89 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fps, ETA 02h06m03s)\rEncoding: task 1 of 1, 49.90 % (0.92 fps, avg 1.18 fp^Z

**Comment by 1337-server** [comment]
I knew about this issue, i have been manually deleting the log for now as a stopgap solution. As I'm not sure the best way to solve it.

You could manually delete the log.
You could change the service file to not append to the file, and instead overwrite the file each time the service is run.
You could have ARM rotate the logs once it reaches x size

But i wasn't sure what would be best, i may need to add something to the wiki until the best/long term solution is found.

**Comment by coacharnold1** [comment]
"You could change the service file to not append to the file, and instead overwrite the file each time the service is run."

Cool,  glad to know its not just me 
This is probably the best solution I think ....   not sure how to do this. Where do I start?

**Comment by 1337-server** [comment]
You would need to modify the service file

`sudo nano /etc/systemd/system/armui.service` 

and then change these lines

```
StandardOutput=append:/PATH-TO-MY-LOGFILES/WebUI.log
StandardError=append:/PATH-TO-MY-LOGFILES/WebUI.log
```

to 


```
StandardOutput=file:/PATH-TO-MY-LOGFILES/WebUI.log
StandardError=file:/PATH-TO-MY-LOGFILES/WebUI.log
```

Then 

`sudo systemctl daemon-reload`
`sudo systemctl restart armui`

This should stop the file from ever getting too large and should overwrite the previous log everytime you restart

**Comment by 1337-server** [comment]
Assuming this is now resolved
