### ISSUE TITLE
Special Characters in Album Title

### ISSUE THREAD

**Issue by JFTiger** [automatic-ripping-machine/automatic-ripping-machine#442]
I was attempting to rip Depeche Mode Home / Useless. Since it has a forward Slash in it, it would not work. So I did a custom name of Depeche Mode Home - Useless and it still did not work. Thanks to a search in issues I found the command to trigger arm manually. I get this error.

sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0
/dev/sr0
Log: /home/arm/logs/Depeche_Mode-Home_/_Useless.log
mount: /mnt/dev/sr0: wrong fs type, bad option, bad superblock on /dev/sr0, missing codepage or helper program, or other error.
umount: /dev/sr0: not mounted.
/bin/sh: 1: cannot create /home/arm/logs/Depeche_Mode-Home_/_Useless.log: Directory nonexistent
ERROR:root:Call to abcde failed with code: 2(b'')

I created the folder Depeche_Mode-Home_ and was able to rip the CD. I'm curious if there is a setting to work around this so I don't have to create a temp folder if this happens again?

**Comment by 1337-server** [comment]
You would probably need to modify  /opt/arm/arm/ripper/getmusictitle.py

You could try this - Find this line
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/851db6f4862a3872702a64e5467a853cca0d058d/arm/ripper/getmusictitle.py#L133

and add this to the line after
`a = str(s).replace("/", "_")`


So the final code should look like this 
```
def clean_for_log(s):
    a = str(s).replace(" ", "_")
    a = str(s).replace("/", "_")
    return a

```

Can you reply back and let me know if this works so i can submit a new pull ? Thanks
