### ISSUE TITLE
Ubuntu 20.04 wont work on media insertion

### ISSUE THREAD

**Issue by speedtoys** [automatic-ripping-machine/automatic-ripping-machine#443]
### Description
I put in a DVD, and not much happens automatically at all

### Environment
Ubuntu 20.04, installed everything as the instructions say.
ARM 2.2
Large AMD CPU
256G
Nvidia 3080
This was working for me in a 2.1 branch on Ubuntu 18.xx, but I had to reinstall, so 2.2 is where I am at right now.

### Log file
Raw syslog from disc insertion

Jul 26 19:30:14 Burner ARM: [ARM] Starting ARM on sr0
Jul 26 19:30:14 Burner systemd[1]: Started Session c38 of user arm.
Jul 26 19:30:14 Burner systemd[1]: session-c38.scope: Succeeded.
Jul 26 19:30:14 Burner ARM: [ARM] ARM Webgui running. 
Jul 26 19:30:14 Burner tracker-store[253711]: OK
Jul 26 19:30:14 Burner systemd[1339]: tracker-store.service: Succeeded.
Jul 26 19:30:20 Burner ARM: [ARM] Starting ARM on sr0
Jul 26 19:30:20 Burner systemd[1]: Started Session c39 of user arm.
Jul 26 19:30:20 Burner systemd[1]: session-c39.scope: Succeeded.
Jul 26 19:30:20 Burner ARM: [ARM] ARM Webgui running. 
Jul 26 19:30:45 Burner ARM: [ARM] Starting ARM on sr0
Jul 26 19:30:45 Burner systemd[1]: Started Session c40 of user arm.
Jul 26 19:30:45 Burner systemd[1]: session-c40.scope: Succeeded.
Jul 26 19:30:45 Burner ARM: [ARM] ARM Webgui running.
(end..drive light goes dark)

Now, if I run this command by hand, it works GREAT:

sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0

But it wont do this automatically.

**Comment by speedtoys** [comment]
I changed the loader to run as room and not arm...and I got a lot more syslog output, but same end result:
---
Jul 27 16:48:54 Burner ARM: [ARM] Starting ARM on sr0
Jul 27 16:48:54 Burner systemd[1]: Started Session c49 of user root.
Jul 27 16:48:54 Burner systemd[1]: session-c49.scope: Succeeded.
Jul 27 16:48:54 Burner ARM: [ARM] ARM Webgui running. 
Jul 27 16:48:59 Burner ARM: [ARM] Starting ARM on sr0
Jul 27 16:48:59 Burner systemd[1]: Started Session c50 of user root.
Jul 27 16:48:59 Burner systemd[1]: session-c50.scope: Succeeded.
Jul 27 16:48:59 Burner ARM: [ARM] ARM Webgui running. 
Jul 27 16:49:09 Burner systemd[1]: Stopping User Manager for UID 0...
Jul 27 16:49:09 Burner systemd[322956]: Stopped target Main User Target.
Jul 27 16:49:09 Burner systemd[322956]: Stopped target Basic System.
Jul 27 16:49:09 Burner systemd[322956]: Stopped target Paths.
Jul 27 16:49:09 Burner systemd[322956]: ubuntu-report.path: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Stopped Pending report trigger for Ubuntu Report.
Jul 27 16:49:09 Burner systemd[322956]: Stopped target Sockets.
Jul 27 16:49:09 Burner systemd[322956]: Stopped target Timers.
Jul 27 16:49:09 Burner systemd[322956]: dbus.socket: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Closed D-Bus User Message Bus Socket.
Jul 27 16:49:09 Burner systemd[322956]: dirmngr.socket: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Closed GnuPG network certificate management daemon.
Jul 27 16:49:09 Burner systemd[322956]: gpg-agent-browser.socket: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Jul 27 16:49:09 Burner systemd[322956]: gpg-agent-extra.socket: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Jul 27 16:49:09 Burner systemd[322956]: gpg-agent-ssh.socket: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Jul 27 16:49:09 Burner systemd[322956]: gpg-agent.socket: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Closed GnuPG cryptographic agent and passphrase cache.
Jul 27 16:49:09 Burner systemd[322956]: pk-debconf-helper.socket: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Closed debconf communication socket.
Jul 27 16:49:09 Burner systemd[322956]: snapd.session-agent.socket: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Closed REST API socket for snapd user session agent.
Jul 27 16:49:09 Burner systemd[322956]: Reached target Shutdown.
Jul 27 16:49:09 Burner systemd[322956]: systemd-exit.service: Succeeded.
Jul 27 16:49:09 Burner systemd[322956]: Finished Exit the Session.
Jul 27 16:49:09 Burner systemd[322956]: Reached target Exit the Session.
Jul 27 16:49:09 Burner systemd[1]: user@0.service: Succeeded.
Jul 27 16:49:09 Burner systemd[1]: Stopped User Manager for UID 0.
Jul 27 16:49:09 Burner systemd[1]: Stopping User Runtime Directory /run/user/0...
Jul 27 16:49:09 Burner systemd[3076]: run-user-0.mount: Succeeded.
Jul 27 16:49:09 Burner systemd[1]: run-user-0.mount: Succeeded.
Jul 27 16:49:09 Burner systemd[1]: user-runtime-dir@0.service: Succeeded.
Jul 27 16:49:09 Burner systemd[1]: Stopped User Runtime Directory /run/user/0.
Jul 27 16:49:09 Burner systemd[1339]: run-user-0.mount: Succeeded.
Jul 27 16:49:09 Burner systemd[1]: Removed slice User Slice of UID 0.
Jul 27 16:49:11 Burner ARM: [ARM] Starting ARM on sr0
Jul 27 16:49:11 Burner systemd[1]: Created slice User Slice of UID 0.
Jul 27 16:49:11 Burner systemd[1]: Starting User Runtime Directory /run/user/0...
Jul 27 16:49:11 Burner systemd[1]: Finished User Runtime Directory /run/user/0.
Jul 27 16:49:11 Burner systemd[1]: Starting User Manager for UID 0...
Jul 27 16:49:11 Burner systemd[323077]: Started Pending report trigger for Ubuntu Report.
Jul 27 16:49:11 Burner systemd[323077]: Reached target Paths.
Jul 27 16:49:11 Burner systemd[323077]: Reached target Timers.
Jul 27 16:49:11 Burner systemd[323077]: Starting D-Bus User Message Bus Socket.
Jul 27 16:49:11 Burner systemd[323077]: Listening on GnuPG network certificate management daemon.
Jul 27 16:49:11 Burner systemd[323077]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Jul 27 16:49:11 Burner systemd[323077]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Jul 27 16:49:11 Burner systemd[323077]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Jul 27 16:49:11 Burner systemd[323077]: Listening on GnuPG cryptographic agent and passphrase cache.
Jul 27 16:49:11 Burner systemd[323077]: Listening on debconf communication socket.
Jul 27 16:49:11 Burner systemd[323077]: Condition check resulted in Sound System being skipped.
Jul 27 16:49:11 Burner systemd[323077]: Listening on REST API socket for snapd user session agent.
Jul 27 16:49:11 Burner systemd[323077]: Listening on D-Bus User Message Bus Socket.
Jul 27 16:49:11 Burner systemd[323077]: Reached target Sockets.
Jul 27 16:49:11 Burner systemd[323077]: Reached target Basic System.
Jul 27 16:49:11 Burner systemd[323077]: Condition check resulted in Sound Service being skipped.
Jul 27 16:49:11 Burner systemd[323077]: Condition check resulted in Tracker metadata extractor being skipped.
Jul 27 16:49:11 Burner systemd[323077]: Condition check resulted in Tracker file system data miner being skipped.
Jul 27 16:49:11 Burner systemd[323077]: Reached target Main User Target.
Jul 27 16:49:11 Burner systemd[323077]: Startup finished in 76ms.
Jul 27 16:49:11 Burner systemd[1]: Started User Manager for UID 0.
Jul 27 16:49:11 Burner systemd[1]: Started Session c51 of user root.
Jul 27 16:49:11 Burner systemd[1]: session-c51.scope: Succeeded.
Jul 27 16:49:11 Burner ARM: [ARM] ARM Webgui running. 
Jul 27 16:49:21 Burner systemd[1]: Stopping User Manager for UID 0...
Jul 27 16:49:21 Burner systemd[323077]: Stopped target Main User Target.
Jul 27 16:49:21 Burner systemd[323077]: Stopped target Basic System.
Jul 27 16:49:21 Burner systemd[323077]: Stopped target Paths.
Jul 27 16:49:21 Burner systemd[323077]: ubuntu-report.path: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Stopped Pending report trigger for Ubuntu Report.
Jul 27 16:49:21 Burner systemd[323077]: Stopped target Sockets.
Jul 27 16:49:21 Burner systemd[323077]: Stopped target Timers.
Jul 27 16:49:21 Burner systemd[323077]: dbus.socket: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Closed D-Bus User Message Bus Socket.
Jul 27 16:49:21 Burner systemd[323077]: dirmngr.socket: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Closed GnuPG network certificate management daemon.
Jul 27 16:49:21 Burner systemd[323077]: gpg-agent-browser.socket: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Jul 27 16:49:21 Burner systemd[323077]: gpg-agent-extra.socket: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Jul 27 16:49:21 Burner systemd[323077]: gpg-agent-ssh.socket: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Jul 27 16:49:21 Burner systemd[323077]: gpg-agent.socket: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Closed GnuPG cryptographic agent and passphrase cache.
Jul 27 16:49:21 Burner systemd[323077]: pk-debconf-helper.socket: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Closed debconf communication socket.
Jul 27 16:49:21 Burner systemd[323077]: snapd.session-agent.socket: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Closed REST API socket for snapd user session agent.
Jul 27 16:49:21 Burner systemd[323077]: Reached target Shutdown.
Jul 27 16:49:21 Burner systemd[323077]: systemd-exit.service: Succeeded.
Jul 27 16:49:21 Burner systemd[323077]: Finished Exit the Session.
Jul 27 16:49:21 Burner systemd[323077]: Reached target Exit the Session.
Jul 27 16:49:21 Burner systemd[1]: user@0.service: Succeeded.
Jul 27 16:49:21 Burner systemd[1]: Stopped User Manager for UID 0.
Jul 27 16:49:21 Burner systemd[1]: Stopping User Runtime Directory /run/user/0...
Jul 27 16:49:21 Burner systemd[3076]: run-user-0.mount: Succeeded.
Jul 27 16:49:21 Burner systemd[1339]: run-user-0.mount: Succeeded.
Jul 27 16:49:21 Burner systemd[1]: run-user-0.mount: Succeeded.
Jul 27 16:49:21 Burner systemd[1]: user-runtime-dir@0.service: Succeeded.
Jul 27 16:49:21 Burner systemd[1]: Stopped User Runtime Directory /run/user/0.
Jul 27 16:49:21 Burner systemd[1]: Removed slice User Slice of UID 0.
---

**Comment by 1337-server** [comment]
Did you make sure that the arm user has write permissions to the directories ? And that the db file is also writeable. Most of the time this kind of silent/non-error stop of arm is caused by permissions not being set for either the directories or the db file.

Can you also verify the version of ARM you are currently running ? As the current `v2.1_dev` branch is much further ahead of v2.2 from the master branch.

You can check the version by `cat /opt/arm/VERSION` (if its install to the default location)

**Comment by speedtoys** [comment]
2.2.0-dev

Hmm, I followed all instructions...ill check perms..
"sudo -u arm touch me"

This works in every defined media and db directory..

total 56
drwxrwxr-x  2 arm arm  4096 Jul 27 17:08 .
drwxr-xr-x 11 arm arm  4096 Jul 27 18:19 ..
-rw-r--r--  1 arm arm 45056 Jul 27 17:08 arm.db

**Comment by speedtoys** [comment]
..moving to your tree, 2.5.3
