### ISSUE TITLE
Feture request

### ISSUE THREAD

**Issue by fluffysfriends** [automatic-ripping-machine/automatic-ripping-machine#444]
### Description
Set language and subtitels in config file or in webgui
### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Could you explain a little what you mean by Set langauge ? 
Do you mean the movie/shows audio and subtitles ? As this is already possible via arm.yaml

These are the settings you most likely will want to use.
```
# Additional HandBrake arguments for DVDs.  
HB_ARGS_DVD: "--subtitle scan -F"

# Additional Handbrake arguments for Bluray Discs.
HB_ARGS_BD: "--subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio"
```

You may want to look at https://handbrake.fr/docs/en/1.3.0/cli/command-line-reference.html for more details on what you can put inside `HB_ARGS_DVD` and `HB_ARGS_BD` it should have everything you need to specify both the audio language and subtitle langauge.

Let me know if ive misunderstood and i can try to provide more info.
