### ISSUE TITLE
Duplicate log files created during rip

### ISSUE THREAD

**Issue by microtechno9000** [automatic-ripping-machine/automatic-ripping-machine#445]
### Description
Duplicate log files are created during the ripping process, noticed when ripping either a movie or series DVD.
Ripping music doesn't create the issue.

```
...:/home/arm/logs$ ls -la
...
-rw-rw-r-- 1 arm arm 4168589 Aug  7 11:57  NCIS_S5_EU_D2.log
-rw-rw-r-- 1 arm arm   57652 Aug  7 11:57 'NCIS_S5_EU_D2.log '
-rw-rw-r-- 1 arm arm      146 Aug  1 15:22  XFILES_DISC1.log
-rw-rw-r-- 1 arm arm    23128 Aug  2 08:48 'XFILES_DISC1.log '
-rw-rw-r-- 1 arm arm  2149795 Aug  3 04:23  XFILES_DISC2.log
-rw-rw-r-- 1 arm arm    25817 Aug  3 04:23 'XFILES_DISC2.log '
-rw-rw-r-- 1 arm arm     3362 Aug  3 05:27 'XFILES_DISC3.log '
```

Looking at the log for the NCIS rip (attached), the files get split around the initilisation of handbrake, the timestamp jumps from 08:51:23 to 09:15:45, with the second log file starting, per below
[08:51:23] Nvenc version 11.1
```
[2021-08-07 08:51:23] DEBUG ARM: handbrake.handbrake_all Sending command: nice HandBrakeCLI -i /dev/sr0 -o '/home/arm/media/movies/NCIS- Naval Criminal Investigative Service (2003–)/title_01.mkv' --preset "HQ 720p30 Surround" -t 1 --subtitle scan -F>> /home/arm/logs/NCIS_S5_EU_D2.log  2>&1
```
Looking at [logger.py](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/v2_master/arm/ripper/logger.py), it appears there is an error at line 45, with white space after the .log
```
            logfull = cfg['LOGPATH'] + newlogfile if os.path.isfile(TmpLogFull) else cfg['LOGPATH'] + str(job.label) + ".log "
```

removing the whitespace after ".log ", I was able to rip to NCIS disks and only one log was created for each
```
...:/home/arm/logs$ ls -la
-rw-rw-r-- 1 arm arm 3822303 Aug  7 15:23  NCIS_S5_EU_D2_162833964421.log
-rw-rw-r-- 1 arm arm 3600367 Aug  7 21:53  NCIS_S5_EU_D3.log
```

### Environment
Ubuntu 20.04
```
git branch
* v2_master

git log -1
commit 851db6f4862a3872702a64e5467a853cca0d058d (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: 3815ddc 47c4f04
Author: flammableliquids <geforbes@gmail.com>
Date:   Fri Apr 16 11:32:14 2021 +1000

    Merge pull request #412 from phirestalker/v2_master
    
    some quick fixes
```

### Log file
[NCIS_S5_EU_D2.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6950152/NCIS_S5_EU_D2.log)
[NCIS_S5_EU_D2.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6950154/NCIS_S5_EU_D2.log)

**Comment by microtechno9000** [comment]
Hey
Looking to raise a pull request against this issue, but it appears the v2_fixes branch is quite behind the v2_master
Should I raise a PR against the master or fixes branch?

:)

**Comment by 1337-server** [comment]
As far as i am aware pulls should be against the branch you pulled from.

I believe that the other branches were used a long time ago, so that changes could be tested before adding possible bugs to the main repo. But this is no longer true anymore.

**Comment by microtechno9000** [comment]
closing, realised master is behind dev_2.1 and the issues has been fixed in the dev bracnch
