### ISSUE TITLE
Uninstall Script

### ISSUE THREAD

**Issue by omegahack0** [automatic-ripping-machine/automatic-ripping-machine#448]
### Description
[Description of Bug, Feature, Question, etc.]

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

It would be nice if there was a Uninstall script to accompany the install script

**Comment by 1337-server** [comment]
I did create one for myself but i was hesitant to include it, as there isnt a way that I know of to check if the program was already installed or not. So including a un-install script might have caused issues if the un-install script removed something that the users needs for other programs.

But here is the script i use if you want it.

**arm-uninstall.sh**
```
sudo apt-get purge git -y
sudo add-apt-repository -r -y ppa:heyarje/makemkv-beta
sudo add-apt-repository -r -y ppa:stebbins/handbrake-releases
sudo add-apt-repository -r -y ppa:mc3man/xerus-media
sudo add-apt-repository -r -y ppa:mc3man/bionic-prop
sudo add-apt-repository -r -y ppa:mc3man/focal6
sudo apt update -y && \
sudo apt purge makemkv-bin makemkv-oss -y && \
sudo apt purge handbrake-cli libavcodec-extra -y && \
sudo apt purge abcde flac imagemagick glyrc cdparanoia -y && \
sudo apt purge at -y && \
sudo apt purge libcurl4-openssl-dev libssl-dev -y && \
sudo apt purge libdvd-pkg -y && \
sudo apt purge default-jre-headless -y
cd /opt/arm
sudo pip3 uninstall -y -r requirements.txt 
cd ~
sudo rm -R /opt/arm
sudo rm -R /home/arm
sudo rm -R /etc/arm/
sudo rm -R /mnt/dev/sr0
sudo rm /etc/systemd/system/armui.service
sudo systemctl disable armui
sudo systemctl daemon-reload
```

**Comment by 1337-server** [comment]
Uninstall instructions have been added to the wiki: [Uninstall.sh](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Uninstall-A.R.M)
