### ISSUE TITLE
Feature Request - Better Status indication

### ISSUE THREAD

**Issue by originalnr8** [automatic-ripping-machine/automatic-ripping-machine#450]
### Description
The web ui should indticate the true status of it all. Ripping and Transcoding are not the only two stages. If ripping completes and transcoding cannot start it is waiting for transcoding. I can see this is available but it doesn't show up in any testing that I've done. I'm using backup because I'm doing bluray and DVD. I believe this may be linked to [Issue #369](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/369) as if you rip loads it just seems to clog up with "transcoding" things but they aren't actually doing it.

### Environment
Ubuntu 20.04LTS Basic install as per instructions. The only changes made to configuration are folder locations and to force subtitles on both Bluray and DVD instead of just DVD.

**Comment by 1337-server** [comment]
Please provide logs

**Comment by RickB1974** [comment]
How do I enable Web UI?

**Comment by 1337-server** [comment]
This feature has been added to the v2_devel branch!
