### ISSUE TITLE
Blue ray drive only rips sometimes

### ISSUE THREAD

**Issue by omegahack0** [automatic-ripping-machine/automatic-ripping-machine#451]
### Description
[Description of Bug, Feature, Question, etc.]

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

For some reason my LG WH16NS40 blue ray drive doesn't rip all the time and seems pretty picky about what few disks it will actually rip. I have tried updating the system and remounting the drives. but my blue ray drive is still experiencing this odd behavior. I did change the config so that instead of reencoding blue rays it would actually rip them directly from the disk, however I have this issue when ripping DVDs as well. Any thoughts or suggestions are much appreciated.

**Comment by 1337-server** [comment]
Please attach logs

**Comment by omegahack0** [comment]
Where would I see the logs? I was having a hard time finding it within the gui

**Comment by omegahack0** [comment]
MSG:1005,0,1,"MakeMKV v1.16.4 linux(x64-release) started","%1 started","MakeMKV v1.16.4 linux(x64-release)"
MSG:5074,0,0,"Automatic checking for updates is enabled, you may disable it in preferences if you don't want MakeMKV to contact web server.","Automatic checking for updates is enabled, you may disable it in preferences if you don't want MakeMKV to contact web server."
MSG:2019,0,2,"Error 'Posix error - Permission denied' occurred while creating '/home/arm/.MakeMKV/dump_FW_5DEF6C00B34A17092831.tgz'","Error '%1' occurred while creating '%2'","Posix error - Permission denied","/home/arm/.MakeMKV/dump_FW_5DEF6C00B34A17092831.tgz"
DRV:0,2,999,1,"DVD+R-DL HL-DT-ST DVDRAM GH60N UG01","MR_MOM","/dev/sr0"
DRV:1,2,999,1,"BD-RE HL-DT-ST BD-RE  WH16NS40 1.05","MY_BIG_FAT_GREEK_WEDDING","/dev/sr1"
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:3007,0,0,"Using direct disc access mode","Using direct disc access mode"
MSG:3028,0,3,"Title #1 was added (17 cell(s), 1:34:44)","Title #%1 was added (%2 cell(s), %3)","1","17","1:34:44"
MSG:3028,0,3,"Title #2 was added (17 cell(s), 1:34:45)","Title #%1 was added (%2 cell(s), %3)","2","17","1:34:45"
MSG:3032,0,2,"Region setting of drive HL-DT-ST:BD-RE  WH16NS40 does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","HL-DT-ST","BD-RE  WH16NS40"
MSG:3032,0,2,"Region setting of drive HL-DT-ST:BD-RE  WH16NS40 does not match the region of currently inserted disc, trying to work around...","Region setting of drive %1:%2 does not match the region of currently inserted disc, trying to work around...","HL-DT-ST","BD-RE  WH16NS40"
MSG:5011,0,0,"Operation successfully completed","Operation successfully completed"
DRV:0,0,999,0,"DVD+R-DL HL-DT-ST DVDRAM GH60N UG01","","/dev/sr0"
MSG:5014,131072,2,"Saving 2 titles into directory file:///mnt/smallPool/Media/raw/MY BIG FAT GREEK WEDDING","Saving %1 titles into directory %2","2","file:///mnt/smallPool/Media/raw/MY BIG FAT GREEK WEDDING"

**Comment by 1337-server** [comment]
Default location would be `/home/arm/logs`

You would need to attach the full .log file here
