### ISSUE TITLE
Trailing space in logfile name

### ISSUE THREAD

**Issue by bwarden** [automatic-ripping-machine/automatic-ripping-machine#452]
Logfile name generation adds a trailing space after ".log", resulting in two files used for logging (e.g. `foo.log` and `foo.log `), the latter of which is not reaped by the date-based cleanup.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/851db6f4862a3872702a64e5467a853cca0d058d/arm/ripper/logger.py#L45

**Comment by microtechno9000** [comment]
bwarden this is a duplicate of #445
