### ISSUE TITLE
Where can I place scp command???

### ISSUE THREAD

**Issue by austinbrown101** [automatic-ripping-machine/automatic-ripping-machine#453]
My media server is a seperate remote machine from my ARM, I want a way to automate uploading the files after the ARM finishes. I've seen some people using rsync, which would be a lot easier but isn't an option for my setup. I need to be able to use an scp command. I've tried disecting the code to figure out where I could place it, but it is too complex and too much for me to understand with my very limited python experience. 

So where in the ARM code could I put an scp command after everything finishes and how to I get the folder I need to upload to use as an argument?

**Comment by 1337-server** [comment]
Ben still has the instructions to mount drives on Linux on the original page.
This would save you from needing any copy command, and instead mounting the remote folder, allowing you to rip straight to the remote folder.

https://b3n.org/automatic-ripping-machine/


Look for the section on `Mount Samba/CIFS Media Share`
