### ISSUE TITLE
ARM on Ubuntu 21.10 Docker fails to rip CD

### ISSUE THREAD

**Issue by tmonfiletto** [automatic-ripping-machine/automatic-ripping-machine#464]
### Description
I've installed ARM via docker following the instrutions found here:
https://hub.docker.com/r/1337server/automatic-ripping-machine

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"

### Log file
ARM never creates a log but here is my output from syslog when inserting a CD:

Dec 26 22:10:50 vs1 ARM: Entering docker wrapper
Dec 26 22:10:50 vs1 ARM: No ID_s
Dec 26 22:10:50 vs1 ARM: xxx
Dec 26 22:10:56 vs1 ARM: Entering docker wrapper
Dec 26 22:10:56 vs1 ARM: No ID_s
Dec 26 22:10:56 vs1 ARM: xxx
Dec 26 22:11:01 vs1 ARM: Entering docker wrapper
Dec 26 22:11:01 vs1 ARM: /opt/arm/scripts/docker_arm_wrapper.sh xxx1 sr0
Dec 26 22:11:01 vs1 ARM: xxx3
Dec 26 22:11:01 vs1 ARM: fixing devname
Dec 26 22:11:06 vs1 ARM: Entering docker wrapper
Dec 26 22:11:06 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:11 vs1 ARM: Entering docker wrapper
Dec 26 22:11:11 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:16 vs1 ARM: Entering docker wrapper
Dec 26 22:11:16 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:21 vs1 ARM: Entering docker wrapper
Dec 26 22:11:21 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:26 vs1 ARM: Entering docker wrapper
Dec 26 22:11:26 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:31 vs1 ARM: Entering docker wrapper
Dec 26 22:11:31 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:36 vs1 ARM: Entering docker wrapper
Dec 26 22:11:36 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:41 vs1 ARM: Entering docker wrapper
Dec 26 22:11:41 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:46 vs1 ARM: Entering docker wrapper
Dec 26 22:11:46 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:51 vs1 ARM: Entering docker wrapper
Dec 26 22:11:51 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:57 vs1 ARM: Entering docker wrapper
Dec 26 22:11:57 vs1 systemd-udevd[10204]: sr0: Spawned process '/opt/arm/scripts/docker_arm_wrapper.sh sr0' [10272] is taking longer than 59s to complete
Dec 26 22:11:57 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:11:57 vs1 systemd-udevd[500]: sr0: Worker [10204] processing SEQNUM=4257 is taking a long time
Dec 26 22:12:02 vs1 ARM: Entering docker wrapper
Dec 26 22:12:02 vs1 ARM: /usr/bin/docker xxx1 container ls -l -f name=arm-rippers --format {{json .Status}}
Dec 26 22:13:57 vs1 systemd-udevd[10204]: sr0: Spawned process '/opt/arm/scripts/docker_arm_wrapper.sh sr0' [10272] timed out after 2min 59s, killing

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by tmonfiletto** [comment]
Also something wierd is going on, everytime I try and run a docker command like docker ps it seems to be running the docker_arm_wrapper.sh
root@vs1:/opt/arm/scripts# docker container ls -l -f
<13>Dec 26 22:19:38 ARM: Entering docker wrapper
<13>Dec 26 22:19:38 ARM: No ID_s
<13>Dec 26 22:19:38 ARM: xxx
root@vs1:/opt/arm/scripts# docker ps
<13>Dec 26 22:20:36 ARM: Entering docker wrapper
<13>Dec 26 22:20:36 ARM: No ID_s
<13>Dec 26 22:20:36 ARM: xxx

**Comment by 1337-server** [comment]
Docker image is currently in the middle of being upgraded to the latest version of A.R.M, once this is completed this issue will be resolved.

**Comment by 1337-server** [comment]
Closing, as this may be out of date with the latest version of docker.
