### ISSUE TITLE
Help please! Keep getting error with flask_sqlalchemy

### ISSUE THREAD

**Issue by parkerRose** [automatic-ripping-machine/automatic-ripping-machine#465]
### Description
I can't get the ripper to work! I have flask-sqlalchemy installed Flask-SQLAlchemy       2.5.1    (from running pip3 list) but I keep getting the error ModuleNotFoundError: No module named 'flask_sqlalchemy'
when I run the test  sudo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr1 | at now
new to this, so if you need troubleshooting steps please let me know

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]
* v2_devel
commit b308b184cd05bf8dae2cee6d011b75747c345145 (HEAD -> v2_devel, origin/v2_devel, origin/HEAD)
Author: 1337-server <sndspamfilter@gmail.com>
Date:   Wed Oct 20 00:26:10 2021 +0100

    Removing logging of OMDB key

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

sudo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr1 | at now
warning: commands will be executed using /bin/sh
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 18, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa: E402
  File "/opt/arm/arm/ripper/__init__.py", line 2, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, getkeys  # noqa F401
  File "/opt/arm/arm/ripper/utils.py", line 18, in <module>
    from arm.ui import app, db
  File "/opt/arm/arm/ui/__init__.py", line 6, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
job 215 at Mon Dec 27 01:43:00 2021

pip3 list
Package                Version             
---------------------- --------------------
alembic                1.7.5               
apprise                0.9.6               
apturl                 0.5.2               
bcrypt                 3.2.0               
beautifulsoup4         4.10.0              
blinker                1.4                 
Brlapi                 0.7.0               
certifi                2019.11.28          
cffi                   1.15.0              
chardet                3.0.4               
click                  8.0.3               
colorama               0.4.3               
command-not-found      0.3                 
cryptography           2.8                 
cupshelpers            1.0                 
dbus-python            1.2.16              
defer                  1.0.6               
discid                 1.2.0               
distro                 1.4.0               
distro-info            0.23ubuntu1         
entrypoints            0.3                 
flake8                 4.0.1               
Flask                  2.0.2               
Flask-Cors             3.0.10              
Flask-Login            0.5.0               
Flask-Migrate          3.1.0               
Flask-SQLAlchemy       2.5.1               
Flask-WTF              1.0.0               
greenlet               1.1.2               
httplib2               0.14.0              
idna                   2.8                 
importlib-metadata     4.10.0              
importlib-resources    5.4.0               
itsdangerous           2.0.1               
Jinja2                 3.0.3               
keyring                18.0.1              
language-selector      0.1                 
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
louis                  3.12.0              
macaroonbakery         1.3.1               
Mako                   1.1.6               
Markdown               3.3.6               
MarkupSafe             2.0.1               
mccabe                 0.6.1               
musicbrainzngs         0.7.1               
netifaces              0.11.0              
oauthlib               3.1.0               
olefile                0.46                
omdb                   0.10.1              
pexpect                4.6.0               
Pillow                 7.0.0               
pip                    20.0.2              
prettytable            2.5.0               
protobuf               3.6.1               
psutil                 5.8.0               
pushbullet.py          0.12.0              
pycairo                1.16.2              
pycodestyle            2.8.0               
pycparser              2.21                
pycups                 1.9.73              
pycurl                 7.44.1              
pydvdid                1.1                 
pyflakes               2.4.0               
pyfttt                 0.3.2               
PyGObject              3.36.0              
pyinotify              0.9.6               
PyJWT                  1.7.1               
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
pyOpenSSL              19.0.0              
pyRFC3339              1.1                 
python-apt             2.0.0+ubuntu0.20.4.6
python-dateutil        2.7.3               
python-debian          0.1.36ubuntu1       
python-magic           0.4.24              
python-pushover        0.4                 
pytz                   2019.3              
pyudev                 0.22.0              
pyxdg                  0.26                
PyYAML                 5.3.1               
reportlab              3.5.34              
requests               2.22.0              
requests-oauthlib      1.3.0               
requests-unixsocket    0.2.0               
robobrowser            0.5.3               
SecretStorage          2.3.1               
setuptools             45.2.0              
simplejson             3.16.0              
six                    1.14.0              
soupsieve              2.3.1               
SQLAlchemy             1.4.29              
systemd-python         234                 
tinydownload           0.1.0               
ubuntu-advantage-tools 27.4                
ubuntu-drivers-common  0.0.0               
ufw                    0.36                
unattended-upgrades    0.1                 
urllib3                1.25.8              
wadllib                1.3.3               
wcwidth                0.2.5               
websocket-client       1.2.3               
Werkzeug               2.0.2               
wheel                  0.34.2              
WTForms                3.0.1               
xkit                   0.0.0               
xmltodict              0.12.0              
zipp                   3.6.0 

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Did you find a solution to this ?

**Comment by 1337-server** [comment]
Closing as stale.
