### ISSUE TITLE
[Ubuntu 18] Web Server does not restart and UDEV rules won't work

### ISSUE THREAD

**Issue by coacharnold1** [automatic-ripping-machine/automatic-ripping-machine#466]
### Description
Web Server does not restart and UDEV rules won't work

Everything seems to be working,   I rebuilt my 18.04 machine re-installed ARM,  could not get udev to operate,  so I started it with:
sudo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0
The disc didn't want to transcode completly.  THe web server was running perfectly,   but the rip was stuck at 86%..  I assumed maybe something to do with the disc.  SO I rebooted the machine and cleaned the disc.   I went through the same process,   but this time,  the webserver isn't up.  The disc appears to be happily ripping when I look at the log

### Environment
Ubuntu 18.04
commit 851db6f4862a3872702a64e5467a853cca0d058d

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]
libdvdnav: DVD disk reports itself with Region mask 0x00f60000. Regions: 1 4
[00:20:02] sync: expecting 163626 video frames
[00:20:02] encx264: min-keyint: 24, keyint: 240
[00:20:02] encx264: encoding at constant RF 19.000000
[00:20:02] encx264: unparsed options: level=3.1:ref=5:direct=auto:subme=8:trellis=2:vbv-bufsize=17500:vbv-maxrate=17500:rc-lookahead=50
x264 [info]: using SAR=32/27
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 Cache64
x264 [info]: profile High, level 3.1
Encoding: task 2 of 2, 0.00 %[00:20:02] sync: first pts video is 0
[00:20:02] sync: "Chapter 1" (1) at frame 1 time 0
[00:20:02] sync: first pts audio 0x80bd is 0
[00:20:02] sync: first pts audio 0x80bd is 0
Encoding: task 2 of 2, 7.22 % (4.25 fps, avg 5.03 fps, ETA 08h23m18s)[00:59:14] sync: "Chapter 2" (2) at frame 11825 time 44384340
Encoding: task 2 of 2, 11.24 % (5.71 fps, avg 4.94 fps, ETA 08h09m33s)
[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
ARM with Ubuntu 18 is bugged on the main branches. 

A fix is in progress

**Comment by 1337-server** [comment]
You should now be able to pull from the v2_devel branch to fix issues with Ubuntu 18
