### ISSUE TITLE
Restart transcode from raw files

### ISSUE THREAD

**Issue by cpesko** [automatic-ripping-machine/automatic-ripping-machine#467]
Is there a way to restart all the transcodes with lesser ones actually transcoding. Had about 60 transcodes server froze. Tried to reboot all jobs still show up now but none of them are moving. Tried to use the abandon job not working. Any suggestions to get it going again without reinstall?

**Comment by cpesko** [comment]
if I try and delete db and recreate I get this error. 733T I hope you out there I am using your build.

(sqlite3.OperationalError) no such table: user [SQL: INSERT INTO user (email, password, hash) VALUES (?, ?, ?)] [parameters: ('arm', b'$2b$12$nXVlVbtBEDeveP/8lLQ/F.PYwMPdceEcZ9/KiTd3kUA4izSk/nMJm', b'$2b$12$nXVlVbtBEDeveP/8lLQ/F.')] (Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by cpesko** [comment]
Deleting all the logs allowed me to clear abandon jobs. Wish there was a function to allow the transcode to take place anyone have the command handy in the code to allow the transcode portion to happen? handbrake command?

**Comment by 1337-server** [comment]
ARM can't continue jobs after a reboot.

**Comment by 1337-server** [comment]
The ability to start batch encoding on a folder does sound great, I'll look into this later when I get some free time.

**Comment by 1337-server** [comment]
Closing as stale. We have a lot of other work to do, so this won't be possible for quite some time.

**Comment by sphaero** [comment]
It would be a great addition. For example after the initial transcode you could change transcode settings and re-transcode. I just found a job which didn't catch subtitles. Now I changed to the correct settings and would like to rerun the HandBrakeCLI command.

**Comment by sphaero** [comment]
Btw, any pointers where this would/could be implemented are very welcome as well. I'm just getting used to the codebase

**Comment by 1337-server** [comment]
Personally I would start at the UI and work back from the database page.

Having a button to click to restart will be much quicker for testing/development.  Than coding the function and having to run manually from the terminal.

But that's just my own personal choice.
