### ISSUE TITLE
unable to rip any type of disk in VMWARE esxi

### ISSUE THREAD

**Issue by luis4199** [automatic-ripping-machine/automatic-ripping-machine#472]
### Description
creating a new VM system for ARM 
I have an older pc running ARM working but it's running native (not VM).  I was looking into replacing it with a new server using VMware esxi 6.7.  initial I though it was a CDrom problem with makemkv I tried another cdrom from the older system and the same result.  Any guidance would be appreciated.  Thanks

### Environment
VMWARE EXI 6.7 - Linux 18.04 server
version 2.2
[LOG FILE.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/7920971/LOG.FILE.txt)

**Comment by 1337-server** [comment]
https://forum.makemkv.com/forum/viewtopic.php?t=14329

Should explain your issues.

More specifically, this comment should explain it.
https://forum.makemkv.com/forum/viewtopic.php?p=48266&sid=480342ac304d238b7a08d706d93a18a8#p48266

The Quick/Simple Version 
-----------
MakeMKV uses keys to decode the disc, but newer discs revoke old keys. You have used a newer disc in the drive that has revoked the key MakeMKV is using. So no matter what drive MakeMKV uses, the key will always be revoked. You will need to wait for a newer version of MakeMKV to be released and update it when you can.

There is no way to fix this from our side of things, so ill close this issue.
