### ISSUE TITLE
Could the transcoding job be offloaded to a different device?

### ISSUE THREAD

**Issue by RaddedMC** [automatic-ripping-machine/automatic-ripping-machine#473]
### Description
[Description of Bug, Feature, Question, etc.]
I'd like to use this script in a Plex server that I plan to build in the summer when I move. The server in question doesn't have much GPU power and needs to stay running stably (ie not being cpu pegged) pretty much all the time as I also want to run Home Assistant / UniFi / other things on it. I have another machine with a decent enough CPU/GPU for my needs that I plan to use to offload heavy tasks (mainly rendering youtube videos so that my laptop isn't held up rendering and I can use it to do something else), but I would love to use that second machine to encode my blu-rays/dvds and send them back to the storage (main) machine.

I was wondering if this script had an ability built-in to offload the encoding job to another server?

### Environment
Linux on storage machine, probably Windows on encode machine (maybe Linux as well, I haven't started planning project too much yet)

**Comment by MrJay84** [comment]
Tdarr will do that for you mate. You can add as many network processing nodes as you want.

**Comment by Protektor-Desura** [comment]
Unmanic will do similar as well and it is open source unlike Tdarr these days.

**Comment by MrJay84** [comment]
Currently I rip the ISO directly to an unRaid server where Handbrake takes over the conversion to whatever profile I require. This version of Handbrake has GPU support.
