### ISSUE TITLE
DVD ripping fails when checking for duplicate jobs.

### ISSUE THREAD

**Issue by ewkinder** [automatic-ripping-machine/automatic-ripping-machine#479]
### Description
DVD ripping fails when checking for duplicate jobs.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

v2.0.1

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]
[Across_The_Universe_164541028259.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8105949/Across_The_Universe_164541028259.log)

**Comment by 1337-server** [comment]
This issue should be fixed in the latest commit.
