### ISSUE TITLE
Add "Cancel" or "Skip" button that stop the automation.

### ISSUE THREAD

**Issue by FinlandApollo** [automatic-ripping-machine/automatic-ripping-machine#481]
Hi!

I would like to add one suggestion: Some of the BD movies are bit pain as they might have multiple playlists of same film, resulting over 50 titles of 25-35GB files. Can there be a "Skip" or "Cancel" button so that we could make ARM ignore the disc so that we could do the MakeMKV manually?

Thanks!

-FinlandApollo

**Comment by 1337-server** [comment]
The v2.1_dev branch has had this feature for quite some time now.
