### ISSUE TITLE
Custom Title

### ISSUE THREAD

**Issue by ryanaud** [automatic-ripping-machine/automatic-ripping-machine#482]
When I'm ripping there is some disk that is not getting identified.  I'm using the Customer Title to set the title correctly, however this isn't naming the rip correctly.  
Is there a setting I need to enable to use the Customer Title to edit the name of the rip?

For example... Ripping an audio cd that isn't identified.   I use Custom Title to name the rip  "My Title Disk 1"  when it rips, it still uses Unknown.  I was hoping I could catch at the beginning to make the cleanup easier.

**Comment by 1337-server** [comment]
A.R.M doesn't currently support Custom Title for music CDs or data discs.
