### ISSUE TITLE
MacOs Support

### ISSUE THREAD

**Issue by j-dogcoder** [automatic-ripping-machine/automatic-ripping-machine#491]
Would be awesome if this could be run on macOS

**Comment by 1337-server** [comment]
Natively is most likely never going to happen, I have no way to test it. But mac does support docker, so you would be able to run this in docker.

Docker image: [DockerHub](https://hub.docker.com/repository/docker/1337server/automatic-ripping-machine)

The dev_build requires no extra steps, just run the command and insert a disc
The 'latest' tag requires the extra steps in the README.
