### ISSUE TITLE
Ubuntu 20.04 Automatic Installation script not working

### ISSUE THREAD

**Issue by FlashyDuck** [automatic-ripping-machine/automatic-ripping-machine#494]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Not a Linux expert, so forgive me, but this seems to be a bug in the automatic install script for ubuntu server 20.04. Or at least an incomplete wiki? 

_After the script finishes, Firefox should open to http:<machine_ip>:8080/setup and prompt the user to create an admin account. If this doesn't happen, check the installer console log for error messages._

The script finishes with the following messages:

```
E: The repository 'https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/stebbins/handbrake-releases/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**To Reproduce**
1. install ubuntu server 20.04
2. follow https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Ubuntu-20.04-Automatic-Installation
3. after running sudo ./ubuntu-20.04-install.sh you will encounter above errors

### Environment
Ubuntu Server 20.04

**Comment by 1337-server** [comment]
Confirmed. The installation scripts need some more work, for now use this as a temp measure.

[ubuntu-server-20.04-install.sh.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8617374/ubuntu-server-20.04-install.sh.txt)

Remove the `.txt` from the file name and run that as root.
This will take a lot longer than usual as it has to build the packages from source, the one upside from this is that I have enabled both Intel QuickSync and AMD VCE. So if your hardware supports it, you should be able to use one of the build in hardware transcoding profiles.

**Comment by FlashyDuck** [comment]
> Confirmed. The installation scripts need some more work, for now use this as a temp measure.
> 
> [ubuntu-server-20.04-install.sh.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8617374/ubuntu-server-20.04-install.sh.txt)
> 
> Remove the `.txt` from the file name and run that as root. This will take a lot longer than usual as it has to build the packages from source, the one upside from this is that I have enabled both Intel QuickSync and AMD VCE. So if your hardware supports it, you should be able to use one of the build in hardware transcoding profiles for HandBrake.

Like you said, transfered the script to the server, ran it as root but no luck unfortunately

`Err:8 https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release
  404  Not Found [IP: 91.189.95.85 443]
Err:9 https://ppa.launchpadcontent.net/stebbins/handbrake-releases/ubuntu jammy Release
  404  Not Found [IP: 91.189.95.85 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/stebbins/handbrake-releases/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

Same error message as before.

**Comment by 1337-server** [comment]
You first need to remove the apps, I forgot you said you aren't great with Linux. You will need to remove the 3 repos these commands, run each of them.

```
    sudo add-apt-repository -r ppa:mc3man/focal6 -y
    sudo add-apt-repository -r ppa:heyarje/makemkv-beta -y
    sudo add-apt-repository -r ppa:stebbins/handbrake-releases -y
```

Then run the install script again.

**Comment by FlashyDuck** [comment]
> You first need to remove the repos, I forgot you said you aren't great with Linux. You will need to remove the 3 repos these commands, run each of them.
> 
> ```
>     sudo add-apt-repository -r ppa:mc3man/focal6 -y
>     sudo add-apt-repository -r ppa:heyarje/makemkv-beta -y
>     sudo add-apt-repository -r ppa:stebbins/handbrake-releases -y
> ```
> 
> Then run the install script again.

Awesome, that did it! Thank you for your quick responses! 

Script ran without a hassle. Rebooted afterwards and ARM is up and running. Time to figure out how to set it up ;)

**Comment by 1337-server** [comment]
Glad that sorted it. If you need anymore, just drop a message.

**Comment by shitwolfymakes** [comment]
It looks like Ubuntu's repos are broken, so I don't think there's anything I can do about that. I'll keep an eye on this during testing though. Thanks for pointing this out!

**Comment by Jopler93** [comment]
everytime i run the corrected script, i get this error:

> cp: cannot stat './scripts/30-arm.conf': No such file or directory

i looked at the script & the error occures in the syslog part
could you help me?

**Comment by shitwolfymakes** [comment]
Like looks like it might be an issue with the relative path notation. Try replacing it with `/opt/arm/scripts/30-arm.conf`?

**Comment by 1337-server** [comment]
It was git cloning my own repo, I've updated it to use the main repo. My repo has moved things around a bit.

This should work.
[ubuntu-server-20.04-install.sh.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8660986/ubuntu-server-20.04-install.sh.txt)

**Comment by Elliott-Liu** [comment]
I ran into the same issue whilst running the automatic script.

I'm also new to Linux so for anyone needing more explicit instructions on how to get up and running here's what I did - the whole process took around 30 minutes to do it's thing for me.

**Disclaimer: I have no idea if this is correct!** I'm sure someone more experienced will correct me if I've made any errors!

1. `wget https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8660986/ubuntu-server-20.04-install.sh.txt`
2. `mv ubuntu-server-20.04-install.sh.txt ubuntu-server-20.04-install.sh`
3. `sudo chmod +x ubuntu-server-20.04-install.sh`
4. `do ./ubuntu-server-20.04-install.sh`
5. There's a prompt about mail server, I chose "NO CONFIGURATION"
6. Promot for "Configuring libdvd-pkg"
    - Instruction to please run `sudo dpkg-reconfigure libdvd-pkg` to launch this process for the first time - I confirmed
    - Enable automatic upgrades for libdvdcss2? - I chose "Yes"
    - Download and build libdvdcss_1.4.3 - I chose "Yes"
7. Run `reboot` as instructed!

Hope that helps someone!

**Comment by 1337-server** [comment]
That will work, just a note though.

That step  5. `There's a prompt about mail server, I chose "NO CONFIGURATION"` will mean that any issues won't be sent to the arm user via mail. 

Recommended is to use local if you don't use any other notifications (discord, slacks, etc), it makes things easier to debug when things go wrong.

**Comment by csbarlas** [comment]
Having same problem here but following @Elliott-Liu 's suggestion didn't solve my issues. Using Ubuntu Server 20.04, can get to the Web UI but whenever I insert a disc, computer instantly ejects. Doesn't have this behavior before running the script. No logs get generated from ARM either, so very confusing to know the culprit. Service is running fine.

**Comment by 1337-server** [comment]
Have you checked the syslogs ? `tail -f /var/log/syslog`

I tested on a fresh vm, and it worked without issue. 

Have you check the permissions for the arm media folder, the arm user needs to have write permission to all of them. Including the log directory.

**Comment by csbarlas** [comment]
I'm going to try a fresh install on a new VM... When install is done Firefox doesn't launch (not sure if it should) and after reboot I don't think there are any folders in media. Last attempt after reboot armui service wouldn't run either (some sort of error). I can show the syslogs when I get there

**Comment by shitwolfymakes** [comment]
Yeah I've not had this issue in the tests I've run

**Comment by csbarlas** [comment]
Yeah, just tried testing and it doesn't seem like it's a permission issue. I don't think the problem pertains to this thread anymore but this is what the script output at the end of installation (didn't launch firefox):
![ss1](https://user-images.githubusercontent.com/62313241/174422356-7d36ec5e-0596-40ec-8d8d-9aa962cdead1.png)
 
Syslog looks good, Systemctl looks good, from what I see now I don't think I can actually find the disc files at any path (/dev/sr1/, any /media/ any /mnt/). Once this fails the drive just powers off, doesn't eject. See the ARM log from a DVD rip test I tried to do:

[18-06-2022 04:08:52] INFO ARM: Starting ARM processing at 2022-06-18 04:08:52.275942
[18-06-2022 04:08:52] INFO ARM: Database is up to date
[18-06-2022 04:08:53] INFO ARM: ARM version: 2.6.0
[18-06-2022 04:08:53] INFO ARM: Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
[18-06-2022 04:08:53] INFO ARM: User is: arm
[18-06-2022 04:08:53] INFO ARM: Looking for log files older than 1 days old.
[18-06-2022 04:08:53] INFO ARM: Job: IRON_MAN_2_D1
[18-06-2022 04:08:53] INFO ARM: Job #1 with PID 1316 is currently running.
[18-06-2022 04:08:53] INFO ARM: Starting Disc identification
[18-06-2022 04:08:53] INFO ARM: Mounting disc to: /mnt/dev/sr1
[18-06-2022 04:08:57] INFO ARM: Disc identified as video
[18-06-2022 04:08:57] INFO ARM: DVD CRC64 hash is: e2dd52fba77ba5b7
[18-06-2022 04:08:58] INFO ARM: Disc title Post ident -  title:IRON_MAN_2_D1 year:None video_type:unknown disctype: dvd
[18-06-2022 04:08:58] ERROR ARM: There are service(s) to notify
[18-06-2022 04:08:58] INFO ARM: Setting umask to 0o002
[18-06-2022 04:08:58] INFO ARM: Waiting 60 seconds for manual override.
[18-06-2022 04:09:59] INFO ARM: No manual override found.
[18-06-2022 04:09:59] INFO ARM: **** Logging ARM variables ****
[18-06-2022 04:09:59] INFO ARM: devpath: /dev/sr1
[18-06-2022 04:09:59] INFO ARM: mountpoint: /mnt/dev/sr1
[18-06-2022 04:09:59] INFO ARM: title: IRON_MAN_2_D1
[18-06-2022 04:09:59] INFO ARM: year: None
[18-06-2022 04:09:59] INFO ARM: video_type: unknown
[18-06-2022 04:09:59] INFO ARM: hasnicetitle: False
[18-06-2022 04:09:59] INFO ARM: label: IRON_MAN_2_D1
[18-06-2022 04:09:59] INFO ARM: disctype: dvd
[18-06-2022 04:09:59] INFO ARM: **** End of ARM variables ****
[18-06-2022 04:09:59] INFO ARM: **** Logging config parameters ****
[18-06-2022 04:09:59] INFO ARM: skip_transcode: False
[18-06-2022 04:09:59] INFO ARM: mainfeature: False
[18-06-2022 04:09:59] INFO ARM: minlength: 600
[18-06-2022 04:09:59] INFO ARM: maxlength: 99999
[18-06-2022 04:09:59] INFO ARM: videotype: auto
[18-06-2022 04:09:59] INFO ARM: manual_wait: True
[18-06-2022 04:09:59] INFO ARM: manual_wait_time: 60
[18-06-2022 04:09:59] INFO ARM: ripmethod: backup
[18-06-2022 04:09:59] INFO ARM: mkv_args: 
[18-06-2022 04:09:59] INFO ARM: delrawfiles: True
[18-06-2022 04:09:59] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[18-06-2022 04:09:59] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[18-06-2022 04:09:59] INFO ARM: hb_args_dvd: --subtitle scan -F
[18-06-2022 04:09:59] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[18-06-2022 04:09:59] INFO ARM: raw_path: /home/arm/media/raw/
[18-06-2022 04:09:59] INFO ARM: transcode_path: /home/arm/media/transcode/
[18-06-2022 04:09:59] INFO ARM: completed_path: /home/arm/media/completed/
[18-06-2022 04:09:59] INFO ARM: extras_sub: extras
[18-06-2022 04:09:59] INFO ARM: emby_refresh: False
[18-06-2022 04:09:59] INFO ARM: emby_server: 
[18-06-2022 04:09:59] INFO ARM: emby_port: 8096
[18-06-2022 04:09:59] INFO ARM: notify_rip: True
[18-06-2022 04:09:59] INFO ARM: notify_transcode: True
[18-06-2022 04:09:59] INFO ARM: max_concurrent_transcodes: 0
[18-06-2022 04:09:59] INFO ARM: **** End of config parameters ****
[18-06-2022 04:09:59] INFO ARM: Checking for fstab entry.
[18-06-2022 04:09:59] INFO ARM: fstab entry is: /dev/sr1    /mnt/dev/sr1    udf,iso9660    users,noauto,exec,utf8    0    0
[18-06-2022 04:09:59] INFO ARM: Processing files to: /home/arm/media/transcode/unidentified/IRON_MAN_2_D1
[18-06-2022 04:09:59] INFO ARM: Transcode limit is disabled
[18-06-2022 04:09:59] INFO ARM: Starting BluRay/DVD transcoding - All titles
[18-06-2022 04:09:59] INFO ARM: Using HandBrake to get information on all the tracks on the disc.  This will take a few minutes...
[18-06-2022 04:10:02] ERROR ARM: Couldn't find a valid track with utf-8 encoding. Trying with cp437
[18-06-2022 04:10:02] ERROR ARM: Specific error is: Command 'HandBrakeCLI -i /dev/sr1 -t 0 --scan' returned non-zero exit status 2.
[18-06-2022 04:10:02] ERROR ARM: Couldn't find a valid track. Try running the command manually to see more specific errors.
[18-06-2022 04:10:02] ERROR ARM: Specific error is: Command 'HandBrakeCLI -i /dev/sr1 -t 0 --scan' returned non-zero exit status 2.
[18-06-2022 04:10:02] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 478, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 313, in main
    handbrake.handbrake_all(hb_in_path, hb_out_path, logfile, job)
  File "/opt/arm/arm/ripper/handbrake.py", line 117, in handbrake_all
    get_track_info(srcpath, job)
  File "/opt/arm/arm/ripper/handbrake.py", line 257, in get_track_info
    for line in hb:
TypeError: 'int' object is not iterable
[18-06-2022 04:10:02] ERROR ARM: There are service(s) to notify

**Comment by shitwolfymakes** [comment]
That's a weird error, I haven't seen that before

**Comment by csbarlas** [comment]
Yeah, just tried to eject the disc and the drive is fully powered off so the eject button doesnt work. Got the same behavior when I run bare-metal too (not in a vm)

**Comment by shitwolfymakes** [comment]
Have you tried a different disk? This looks like it could be a disk issue

**Comment by csbarlas** [comment]
I can try that. After a simple reboot the armui service fails to run now, though:
![image](https://user-images.githubusercontent.com/62313241/174422853-b6a3ab6e-a011-4fd4-bc73-5318e1f97b99.png)
![image](https://user-images.githubusercontent.com/62313241/174422868-4837e3f7-7e63-4ddc-a764-c5885ebb9c37.png)

Really have no idea what could be using the 8080 port.

**Comment by shitwolfymakes** [comment]
That's a common issue when arm tries to start itself twice

**Comment by csbarlas** [comment]
Unfortunately stopping starting, restarting, and waiting for a reasonable amount of time all don't seem to do the trick. So many weird seemingly unrelated errors hard to diagnose. To double check, I'm running Ubuntu Server 22.04.4 LTS. Should I be running Ubuntu Server 22.04.0 LTS?

**Comment by shitwolfymakes** [comment]
Oh. *20.04* LTS. We don't support 22.04 and have had issues when people have tried to run it on 22.04

**Comment by shitwolfymakes** [comment]
Like my documentation says, I'm only supporting 20.04 with the install script. It's even hardcoded to use the `focal6` repos, which is probably part of the issue

**Comment by csbarlas** [comment]
Ok, that is definitely my fault for assuming that .4 would hopefully not be too different than just 22.04. Let me test that out (I'm sure it will work great now). Thanks for the help in the meantime.

**Comment by shitwolfymakes** [comment]
No worries. Let me know how it goes once you've set it up on 20.04 LTS

**Comment by csbarlas** [comment]
Sorry I typo'd earlier. I had been using Ubuntu 20.04.4. Now installing Ubuntu 20.04.0.

**Comment by shitwolfymakes** [comment]
Oh, then I don't know why you're having issues. .4 should be fine. Have you tried a different disk?

**Comment by csbarlas** [comment]
Haven't been able to since the service will not start again. By the way, is this thread still appropriate to use since I feel it is not down to the installation script after all?

**Comment by shitwolfymakes** [comment]
We're already here, I would update the initial post tho

**Comment by csbarlas** [comment]
Could it be the way I am passing in my disc drive to the VM that would cause the title search to fail (seemingly due to it seeing no files on the disc)? Obviously, don't know what is causing the service starting problems. Using VirtualBox on Windows 11.

**Comment by shitwolfymakes** [comment]
Depends on if something like vlc sees the disk. I would try with this disk and a different disk in VLC, then try to run ARM and test with the new disk

**Comment by csbarlas** [comment]
Thanks, seeing if VLC could play the disc helped me diagnose to what (I think) was the problem which had to do with how I was passing in the drive through VirtualBox (which doesn't answer why ARM wasn't working with a bare metal install but I'll let it go). Ripping as we speak. One question I had looking through the configuration, if I only want to rip the DVD and not transcode/compress, I set skip transcode to true but saw that this setting only affects MakeMKV behavior. Is there anyway to skip transcode and get the video 1:1 off a DVD? Or is that not the best way to go about with things.

**Comment by shitwolfymakes** [comment]
If you want to do that, set `REPMETHOD` to `backup`

**Comment by bob5731** [comment]
E: The repository 'https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 https://ppa.launchpadcontent.net/heyarje/makemkv-beta/ubuntu jammy InRelease
Ign:6 https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy InRelease
Err:7 https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by flammableliquids** [comment]
take a look at the fixes in this branch, and see if those help:

https://github.com/automatic-ripping-machine/automatic-ripping-machine/tree/bare_metal_ubuntu_update_22
