### ISSUE TITLE
Installing the ARMui service portion of wiki leads to error with systemd

### ISSUE THREAD

**Issue by Sono-Gomorrha** [automatic-ripping-machine/automatic-ripping-machine#496]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
In the wiki under "Installing the ARMui service" the line `ExecStart=python3 /opt/arm/arm/runui.py` leads to an error 
` /etc/systemd/system/armui.service:16: Executable path is not absolute: python3 /opt/arm/arm/runui.py`

I had to change it to 
`ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py`
in order to get it working

**To Reproduce**
1. Use the wiki instructions as given, this will lead to the error upon using `sudo systemctl start armui`

### Environment
OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"

ARM Release:
git branch: v2_master
git log -1
```
commit f4496dab18181171eb072e35787b1031185d4af5 (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Merge: 0ce72de 0e3821b
Author: 1337-server <62730074+1337-server@users.noreply.github.com>
Date:   Tue May 3 05:02:18 2022 +0100

    Merge branch 'v2_master' of https://github.com/automatic-ripping-machine/automatic-ripping-machine into v2_master
```

### Log file
no log file, as this is not related to a rip.

**Comment by 1337-server** [comment]
You're on the master branch. Currently, that doesn't support 18.  A previous update I made broke support for it.  This wasn't intended, and has been fixed, but it wont be on the main v2_master branch until the next release.

The v2_devel branch does have support for Ubuntu 18, but it has a lot more testing items in it. So it's something to keep in mind when pulling from it.
