### ISSUE TITLE
Audio discs do not eject on success

### ISSUE THREAD

**Issue by Barthax** [automatic-ripping-machine/automatic-ripping-machine#498]
I'm not sure if I should have posted this as a feature (in case there's something I'm not understanding about the framework).  In the main.py, it feels like there should be an eject for audio discs on success.

    elif job.disctype == "music":
        if utils.rip_music(job, logfile):
            utils.notify(job, NOTIFY_TITLE, f"Music CD: {job.label} {PROCESS_COMPLETE}")
            utils.scan_emby(job)
            job.eject() #<- add this line
            # This shouldn't be needed. but to be safe
            job.status = "success"
            db.session.commit()
        else:
            logging.info("Music rip failed.  See previous errors.  Exiting. ")
            job.eject()
            job.status = "fail"
            db.session.commit()

**Comment by 1337-server** [comment]
Fixed in the v2_devel branch.

It will be added to the master branch on the next release.
