### ISSUE TITLE
Bluray's misidentified as data

### ISSUE THREAD

**Issue by newhinton** [automatic-ripping-machine/automatic-ripping-machine#499]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
All tested bluray disks are detected as data. Even ones that i already ripped on my pc (with the exact same drive) successfully.

**To Reproduce**
1. Install arm from git
2. Insert Bluray
3. See logs.

**Expected Behaviour:**
The Bluray should be automatically ripped as an mkv.
DVD's are beeing ripped properly. On a sidenote: Thanks for your great work! This is a great tool!

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
2.6.0 (f4496dab18181171eb072e35787b1031185d4af5)

### Log file
See comment

**Comment by 1337-server** [comment]
please attach the full log

**Comment by 1337-server** [comment]
Could you also provide the output of `ls -la /mnt/dev/sr0` after the disc loads?

**Comment by newhinton** [comment]
[WESTWORLD_S1_D1.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8662844/WESTWORLD_S1_D1.log)

**Comment by newhinton** [comment]
> Could you also provide the output of `ls -la /mnt/dev/sr0` after the disc loads?

It is empty. As far as i can see, it never gets mounted. The directory belongs to the arm-user.

**Comment by 1337-server** [comment]
This seems odd, it seems like the arm user doesn't have access to the mnt folder, so the second check fails to find the folders and defaults to data disc. I'll need to test this more for a full fix.

But if you just need it to work until get it fixed, you can comment  this line.
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/f4496dab18181171eb072e35787b1031185d4af5/arm/models/models.py#L125

And it will stop reverting to data discs.

**Comment by newhinton** [comment]
Commenting out seems to work. (Changing the value to bluray does not) So thanks for the quick workaround!

A quick question, does this affect dvds in any way? I will have to do both, and if i cant switch media witout changing it again,  i will plan accordingly.

On a note: My /mnt folder is owned by root, both /mnt/dev and /mnt/dev/sr0 are owned by arm

**Comment by 1337-server** [comment]
> A quick question, does this affect dvds in any way? I will have to do both, and if i cant switch media witout changing it again, i will plan accordingly.

I'll be honest and say I don't know, I'm not 100% sure what is causing the read issues that stop the second identify from working, so I'm not sure if it will affect DVD's. But commenting that line should only really negatively impact data discs.

> On a note: My `/mnt` folder is owned by root, both `/mnt/dev` and `/mnt/dev/sr0` are owned by arm

These should be owned by root but readable by others.
