### ISSUE TITLE
Enormous log files cause enormouse ARM UI RAM usage.

### ISSUE THREAD

**Issue by Barthax** [automatic-ripping-machine/automatic-ripping-machine#501]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Enormous log files cause enormous ARM UI RAM usage.

**To Reproduce**
1. Enable DEBUG
2. Use a disc/drive which triggers masses of debug.

My specific circumstance was an overnight rip which was left unchecked: I suspect a power surge/outage (UPS powered machine) caused an issue with the USB optical drive.  The final log files was in excess of 70GB (24GB RAM).  I suspect (haven't tested because I don't want to foobar my machine again) this can be replicated by stopping the UI while ripping a good disc; allow the good rip to complete and then concatenate numerous files into the good discs' file to expand it beyond reasonable output sizes.

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Ubuntu 20.04.4 LTS
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
v2_master

### Log file
70GB file which I've already deleted.  The size is the likely key factor, not the content.

**Comment by Barthax** [comment]
I have confirmed that this can be replicated using concatenation into an existing log file:

Stop the armui.
Repeatedly concatenate log files to a temp file.
Replcace a previous rip's log file with the temp file.
Start the armui.

Monitoring top will show the rapid RAM increase of the python instance running the UI.

**Comment by 1337-server** [comment]
Can duplicate this issue.  It happens even with files as small as 2GB.  

Will do more testing when I have more free time.  But if you find a fix please submit a PR.

**Comment by Barthax** [comment]
Never dev'd Python but it looks like utils.py is processing the entire log file in process_logfile() (final function of the file).

        with open(logfile, encoding="utf8", errors='ignore') as f:
            line = f.readlines()

The function goes on to perform some regex searches of each line.  I noticed further up there was a call to the external tail program.

Spitballing a solution based on my lack of Python knowledge!  Perhaps a piped pair of external calls: grep into tail.  The grep util could take the regex search via its -E parameter and the tail could limit to number of lines python has to process.

**Comment by Barthax** [comment]
If such a pipe set is possible, then alternatively an initial tail could limit the file content going to grep - say last ~100 lines piped into the regex'd grep.  That would cut down the amount of HDD foot print grep would cause.

**Comment by cmbernard333** [comment]
I am also experiencing this issue on `v2_master`. The proposed solution sounds plausible.

**Comment by cmbernard333** [comment]
It seems like it would be better to use seek behavior and only fetch a certain amount of the file at a time instead of reading the entirety of it's contents in at once. You could page the file using seek and only return a certain amount of content at once like between 64k and 128k at once. That's quite a bit of data to work with and more efficient in the long run.

**Comment by 1337-server** [comment]
> It seems like it would be better to use seek behavior and only fetch a certain amount of the file at a time instead of reading the entirety of it's contents in at once. You could page the file using seek and only return a certain amount of content at once like between 64k and 128k at once. That's quite a bit of data to work with and more efficient in the long run.

Did you have a look at https://github.com/1337-server/automatic-ripping-machine/commit/a01cc462e96a5f287e564ed89c6e0d1e0dd8d86e ? I tested it and this fixed the issue for me, but it won't be merged till I have more time to test.
