### ISSUE TITLE
Gotify Notification not working with https-server

### ISSUE THREAD

**Issue by newhinton** [automatic-ripping-machine/automatic-ripping-machine#503]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Gotify fails to run if the server uses https.

**To Reproduce**

1. Add Gotify Token and Host to apprise.yaml
2. Start Rip
3. No notification

## Workaround
The issue lies here: https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/cf5fbed48613b3711ac35a255bc51dcb69e61a40/arm/ripper/apprise_bulk.py#L113

As the apprise documentation states, https servers can be reached with `gotifys://`. ARM currently does not deal with that and should handle https properly

**Comment by newhinton** [comment]
@1337-server Thanks for fixing this, but wouldn't hardcoding gotifys:// mean that non https-connections break? 
 
 We should at least document this behavior in the default apprise.yaml. If you like i can create a PR for that

**Comment by 1337-server** [comment]
Yeah, this will break for non-secure connections. And the user will need to change this themselves. But I thought it would be better the standard be secure, and the user have to opt into insecurity, than the other way round.

The other option is to add a bunch of `if`'s and I would prefer we not revert to that. But I'm open to other ideas.

---
> We should at least document this behavior in the default apprise.yaml. If you like i can create a PR for that

This would be great, thanks!

**Comment by newhinton** [comment]
We could "force" the user to provide a FQDN in GOTIFY_HOST, eg:

`GOTIFY_HOST=https://example.com/gotify`

And then use a replace on that to replace https:// with gotifys:// and for http respectively. This way both works without doing magic.

Let me know if thats somethink you'd like to do, then i will create PR for that.

**Comment by 1337-server** [comment]
Yeah that would be great thanks!
