### ISSUE TITLE
Docker install issue

### ISSUE THREAD

**Issue by thewascokid** [automatic-ripping-machine/automatic-ripping-machine#504]
- [ *] I have checked the wiki
- [ *] I have searched for similar issues

**Describe the bug**
I am running Debian 10 amd64 and the Webgui works but when I insert a cd or movie it doesn't start..

**To Reproduce**
1.I ran tail -f /var/log/root@OMS0aa820:~# tail -f /var/log/syslog | grep ARM
May 27 20:23:23 OMS0aa820 ARM: [ARM] Starting ARM on sr0
May 27 20:23:23 OMS0aa820 ARM: [ARM] ARM Webgui running.
May 27 20:23:28 OMS0aa820 ARM: Entering docker wrapper
May 27 20:23:28 OMS0aa820 ARM: /opt/arm/scripts/docker_arm_wrapper.sh xxx1 sr0
May 27 20:23:28 OMS0aa820 ARM: xxx3
May 27 20:23:28 OMS0aa820 ARM: fixing devname
May 27 20:26:14 OMS0aa820 ARM: [ARM] Starting ARM on sr0
May 27 20:26:14 OMS0aa820 ARM: [ARM] ARM Webgui running.
May 27 20:26:21 OMS0aa820 ARM: [ARM] Starting ARM on sr0
May 27 20:26:21 OMS0aa820 ARM: [ARM] ARM Webgui running.
May 27 20:26:26 OMS0aa820 ARM: Entering docker wrapper
May 27 20:26:26 OMS0aa820 ARM: No ID_s
May 27 20:26:26 OMS0aa820 ARM: xxx
May 27 20:26:31 OMS0aa820 ARM: [ARM] Starting ARM on sr0
May 27 20:26:31 OMS0aa820 ARM: [ARM] ARM Webgui running.
May 27 20:26:36 OMS0aa820 ARM: Entering docker wrapper
May 27 20:26:36 OMS0aa820 ARM: No ID_s
May 27 20:26:36 OMS0aa820 ARM: xxx
May 27 20:26:41 OMS0aa820 ARM: [ARM] Starting ARM on sr0
May 27 20:26:41 OMS0aa820 ARM: [ARM] ARM Webgui running.
May 27 20:26:46 OMS0aa820 ARM: Entering docker wrapper
May 27 20:26:46 OMS0aa820 ARM: /opt/arm/scripts/docker_arm_wrapper.sh xxx1 sr0
May 27 20:26:46 OMS0aa820 ARM: xxx3
May 27 20:26:46 OMS0aa820 ARM: fixing devname
May 27 20:27:19 OMS0aa820 ARM: [ARM] Starting ARM on sr0
May 27 20:27:19 OMS0aa820 ARM: [ARM] ARM Webgui running.
May 27 20:27:27 OMS0aa820 ARM: [ARM] Starting ARM on sr0
May 27 20:27:27 OMS0aa820 ARM: [ARM] ARM Webgui running.
May 27 20:27:32 OMS0aa820 ARM: Entering docker wrapper
May 27 20:27:32 OMS0aa820 ARM: No ID_s
May 27 20:27:32 OMS0aa820 ARM: xxx
May 27 20:27:59 OMS0aa820 ARM: [ARM] Starting ARM on sr0
May 27 20:27:59 OMS0aa820 ARM: [ARM] ARM Webgui running.
May 27 20:28:04 OMS0aa820 ARM: Entering docker wrapper
May 27 20:28:04 OMS0aa820 ARM: /opt/arm/scripts/docker_arm_wrapper.sh xxx1 sr0
May 27 20:28:04 OMS0aa820 ARM: xxx3
May 27 20:28:04 OMS0aa820 ARM: fixing devname
syslog | grep ARM and here is the results.

### Environment

This is the website that I used to install
 https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Building-ARM-docker-image-from-source

[OS Distribution and version Debian 10 Buster (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
The docker is bugged at the moment, it is being worked on, It's just taking longer than expected.

I'll update when this is fixed. For now you should use the [dev_build](https://hub.docker.com/layers/202225918/1337server/automatic-ripping-machine/dev_build/images/sha256-eeb621ac0fa3c2e9d0663c555a8e318719ec132f189659f0e403a38b2725975f?context=repo) of the docker image.

This new image has all the files inside and doesnt require any extra files on the host. They will need to be removed.

**Comment by thewascokid** [comment]
Thanks for the update. Have a great holiday weekend

**Comment by thewascokid** [comment]
Sorry I am still having issues with the 1337server/automatic-ripping-machine:dev_build 
[docker_arm.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8936479/docker_arm.txt)
I when I try to rip a cd it takes hours. One track could take 2 hours to rip. How do you install the  1337server/arm-dependencies image.

**Comment by shitwolfymakes** [comment]
`dev_build` is not intended for use, like the README on it's GitHub branch states.

I've gotten a containerized arm implementation working, you can find it on DockerHub at `shitwolfymakes/automatic-ripping-machine:latest`

**Comment by thewascokid** [comment]
I am trying to change the output format of .abcde.conf for ripping my CD’s, right now it creates a folder with like this (R.E.M. Reckoning) then a subfolder with the track and song  01 - Harborcoat.flac I would first create an Artist the a sub folder with the Album name then the folder with the track and song info. 

 

/Music

    /Artist

        /Album

            01 - Song.flac

            02 - Song.flac

 

 

 

I am using your docker dev build.

 

docker run -d \

  -p "8080:8080" \

  -e UID="1000" -e GID="1000" \

  -v "/mnt/storage/arm:/home/arm" \

  -v "/mnt/storage/arm/music:/home/arm/music" \

  -v "/mnt/storage/arm/config:/home/arm/config" \

  -v "/mnt/storage/arm/logs:/home/arm/logs" \

  -v "/mnt/storage/arm/media:/home/arm/media" \

  --privileged \

  --restart "always" \

  --name "arm-rippers" \

  1337server/automatic-ripping-machine:dev_build

 

 

Thanks,

 

Mike Kanak
