### ISSUE TITLE
Set job before rip

### ISSUE THREAD

**Issue by sourpatched** [automatic-ripping-machine/automatic-ripping-machine#506]
**Is your feature request related to a problem? Please describe.**
Just started ripping TV Shows and found that because the episodes have no info, the files get overwritten . Once a disk finished I would put another one in (21 disks) and after some time I notice what was happening.  If I didn't move the files (named title_02) once a new disk finished that file would now be overwritten. Also it kept auto claiming Title: The 101-Year-Old Man Who Skipped Out on the Bill and Disappeared (2016) this as a show even when in settings I have it listed as TV

**Describe the solution you'd like**
A way to do a custom job.
From the webui click on new job, enter the details like: 
DVD Name:
Job ID:
Rip poster:
TV show: [Yes or no]
Handbrake info:
Number of disks: 
Submit

After that is been submitted, you've told the system that the next 21 disks are for that tv show and only that show and maybe it could auto try and keep count of the episodes 

**Describe alternatives you've considered**
Not using the software :(

**Are you able to help code/implement this feature ?**
No

**Additional context**
I am happy to help test this.

**Comment by AxelJust** [comment]
I would see that as verry usefull as well

**Comment by 1337-server** [comment]
Nothing wrong with this idea, but for now you could use manual wait.

inside the arm.yaml you could change 
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d/docs/arm.yaml.sample#L67

to something much higher to give yourself time to fix the disc with the correct info. The only downside is that there is no manual start button. But the job should start once you manually update/save the job.
