### ISSUE TITLE
ARM web UI not compatible with Safari

### ISSUE THREAD

**Issue by JohnEridium** [automatic-ripping-machine/automatic-ripping-machine#509]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
While the web ui works just fine in Firefox, it keeps loading in Safari on macOS.
I'm not sure what logs I should include here, please let me know which ones are relevant.

**To Reproduce**
Try opening the ARM web UI on macOS 12.4 in Safari Version 15.5 (17613.2.7.1.8). The tab keeps loading but no contents show up.

### Environment
[OS Distribution: Debian 11.3, `Linux arm-HW 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux`]
ARM Release Version: 
v2_master 

commit cf5fbed48613b3711ac35a255bc51dcb69e61a40 (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Author: 1337-server <sndspamfilter@gmail.com>
Date:   Thu May 12 13:12:30 2022 +0100

### Log file
* Serving Flask app 'arm.ui' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://192.168.2.152:8080 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 917-868-455
192.168.2.100 - - [01/Jun/2022 17:41:48] "^[[32mGET / HTTP/1.1^[[0m" 302 -
192.168.2.100 - - [01/Jun/2022 17:41:48] "^[[32mGET /login HTTP/1.1^[[0m" 302 -
192.168.2.100 - - [01/Jun/2022 17:41:48] "GET /setup-stage2 HTTP/1.1" 200 -
192.168.2.100 - - [01/Jun/2022 17:41:48] "^[[36mGET /static/manifest.json HTTP/1.1^[[0m" 304 -
192.168.2.100 - - [01/Jun/2022 17:41:48] "^[[36mGET /static/img/arm40nw.png HTTP/1.1^[[0m" 304 -
192.168.2.100 - - [01/Jun/2022 17:41:48] "^[[36mGET /static/js/dark-mode-switch.min.js HTTP/1.1^[[0m" 304 -
192.168.2.100 - - [01/Jun/2022 17:41:48] "^[[36mGET /static/css/bootstrap.min.css HTTP/1.1^[[0m" 304 -
192.168.2.100 - - [01/Jun/2022 17:41:48] "^[[36mGET /static/css/dark-mode.css HTTP/1.1^[[0m" 304 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "^[[32mGET / HTTP/1.1^[[0m" 302 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "^[[32mGET /login HTTP/1.1^[[0m" 302 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "GET /setup-stage2 HTTP/1.1" 200 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "GET /static/js/dark-mode-switch.min.js HTTP/1.1" 200 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "GET /static/css/dark-mode.css HTTP/1.1" 200 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "GET /static/img/arm40nw.png HTTP/1.1" 200 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "GET /static/img/apple-touch-icon.png HTTP/1.1" 200 -
192.168.2.100 - - [01/Jun/2022 17:43:48] "GET /static/img/favicon.png HTTP/1.1" 200 -

**Comment by 1337-server** [comment]
Those logs are great. It looks like it tries to go to the login page, can't find the database, then tries to redirect to set up page. 

I'm pretty sure this issue is resolved on the devel branch

**Comment by JohnEridium** [comment]
Just out of curiosity, how do I properly update my instance to get the latest version?
I couldn't find anything in the wiki apart from the initial install guides.
Do I just git pull in the ARM directories and reboot?

**Comment by 1337-server** [comment]
Yeah, just git pull inside the /opt/arm directory

But if you installed from the v2_master then you won't have any of the new features you would need to switch branch.

You can see something like this → https://stackoverflow.com/questions/47630950/how-can-i-switch-to-another-branch-in-git
on how to switch branches.
