### ISSUE TITLE
HD and SD versions of Blu Rays

### ISSUE THREAD

**Issue by brutalgg** [automatic-ripping-machine/automatic-ripping-machine#51]
I guess this would be considered more of a feature request then bug but I was wondering how i would be able to make an HD and an SD version of a blu ray with this process. My streaming box isn't very powerful so when I'm traveling I use the SD versions of movies.

**Comment by ahnooie** [comment]
I think it would be pretty trivial to add an option for multiple transcoding options.  I'll try to get it in the next release.
