### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by Evo221** [automatic-ripping-machine/automatic-ripping-machine#511]
Hi,

the installation instructions are somewhat lengthy and make a number of assumptions about the users system. Is there any reason to not just list the dependencies and to convert automatic-ripping-machine into a pip package on pypi to greatly simplify installation?

I'd be willing to work on this if it is something that you might be interested in.

Cheers,

Evo.

**Comment by Evo221** [comment]
Hello bot,

> If youre having issues, please remember to read the [wiki](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/FAQ) and follow the instructions carefully

I've read the wiki... that is kind of my point. It contains a bunch of stuff that would not be needed if this was actually packaged.

Evo.

**Comment by 1337-server** [comment]
Could you go into more detail about what assumptions the wiki makes ?

Creating the PyPi most likely wouldn't be the issue, it would be continued support for it.
Right now, A.R.M only has 2 active developers @shitwolfymakes and me. And I don't think either of us can add anymore to our workloads at the moment.

Right now the main focus is on getting A.R.M containerized without any extra settings/scripts from the host.

I understand that CI is a possibility, that could be added to fully automate the release, but this would also need testing and right now I can't commit to this.
This is the same reason we cannot support Ubuntu 22.04 right now (https://github.com/1337-server/automatic-ripping-machine/issues/177#issuecomment-1144105823). It's just not possible to work on so many variants of A.R.Ms with only the devs we have working in their free time.

**Comment by Evo221** [comment]
Hi,
> Could you go into more detail about what assumptions the wiki makes ?

The methods for installing makemkv and libdvdcss were two of the standouts. For example, makemkv could presumably be installed as either a flatpak or a snap. Maybe it could be as simple as
```
flatpak install com.makemkv.MakeMKV
```
I'm a little a puzzled about using MakeMKV though. I see that it is a gui tool but naturally, arm just uses its cli interface.
I wonder if tools like vobcopy and mkvtoolnix could be used in its place. If so, it would greatly simplify arm installation since they are already packaged for most distros. It also has the advantage that they are actively maintained, where as makemkv seems to both beta and not had a release for 12 years.

The libdvdcss instructions are a bit weird. It has:
```
wget http://download.videolan.org/pub/debian/stable/libdvdcss2_1.2.13-0_amd64.deb
wget http://download.videolan.org/pub/debian/stable/libdvdcss_1.2.13-0.debian.tar.gz
wget http://ftp.us.debian.org/debian/pool/contrib/libd/libdvd-pkg/libdvd-pkg_1.4.0-1-2_all.deb
sudo dpkg -i libdvdcss2_1.2.13-0_amd64.deb
sudo dpkg -i libdvd-pkg_1.4.0-1-2_all.deb
```
Why? If libdvd-pkg is installed, the other `wget` and `dpkg -i` are not needed. Also using wget to download libdvd-pkg
just looks strange. I understand that it is probably done that way so that the user doesn't have to add contrib to their
sources but may confuse some users.

The instructions also have "apt install" called a dozen or so times. Why not just install the required packages in one hit?

> Creating the PyPi most likely wouldn't be the issue, it would be continued support for it. Right now, A.R.M only has 2 active developers @shitwolfymakes and me. And I don't think either of us can add anymore to our workloads at the moment.

The beauty of creating a proper pip package is that they are easy to maintain. It would mean many of the things currently done by hand (documented in the wiki) would not be necessary. Eg copying files around chmod, chown, making sym links.
Additionally, once a pip package exists it becomes almost trivial to create a compliant deb package. The massive advantage of using a deb package is that it could be make to look after all (most) of the pre and post install steps. So no longer would there be any need for the user to manually create the arm user, create and mange the service file etc.

 > Right now the main focus is on getting A.R.M containerized without any extra settings/scripts from the host.

I see, that seems to be the direction many people are taking.
 
> I understand that CI is a possibility, that could be added to fully automate the release, but this would also need testing and right now I can't commit to this. This is the same reason we cannot support Ubuntu 22.04 right now ([1337-server#177 (comment)](https://github.com/1337-server/automatic-ripping-machine/issues/177#issuecomment-1144105823)). It's just not possible to work on so many variants of A.R.Ms with only the devs we have working in their free time.

From the outside (to me) it looks like the biggest thing holding this back may be using makemkv. I think that replacing that as  dependency with standard tools would be a huge step forward. Do you think this might be possible? Or perhaps there is some showstopper that I'm not aware of. Please note that I'm not requesting that either of you take on extra work, I'm asking if you would be interested in the project moving in this direction. If so, I think I can help.

Cheers,

Evo.

**Comment by 1337-server** [comment]
> where as makemkv seems to both beta and not had a release for 12 years.

MakeMKV v1.16.7 was releases on 27.2.2022 (2-27-2022)
It's updated every time a new Blu-ray encryption type is added/found on a disc.

MakeMKV is used as it decrypts Blu-ray discs, so they can be ripped to files.
I'm not sure if vobcopy and mkvtoolnix have this functionality. I haven't looked into either tool.


> Please note that I'm not requesting that either of you take on extra work, I'm asking if you would be interested in the project moving in this direction. If so, I think I can help.

I don't think there is any opposition to this. I'll speak with @shitwolfymakes

**Comment by Evo221** [comment]
> > where as makemkv seems to both beta and not had a release for 12 years.
> 
> MakeMKV v1.16.7 was releases on 27.2.2022 (2-27-2022) It's updated every time a new Blu-ray encryption type is added/found on a disc.

My bad. Shortly after posting, I realised I was mistaken and edited my post, but it seems you had already started to reply.

> MakeMKV is used as it decrypts Blu-ray discs, so they can be ripped to files. I'm not sure if vobcopy and mkvtoolnix have this functionality. I haven't looked into either tool.

I've not tested it, but it seems it mkvtoolnix has been used this way. See for example:
https://mkvtoolnix.download/links.html

> > Please note that I'm not requesting that either of you take on extra work, I'm asking if you would be interested in the project moving in this direction. If so, I think I can help.
> 
> I don't think there is any opposition to this. I'll speak with @shitwolfymakes

**Comment by shitwolfymakes** [comment]
My .02:

1. I have always hated the manual install instructions on the wiki, mostly because I think that if it can be automated, it should be automated. So the first thing I did was created the automated install script for Ubuntu 20.04
2. I'm am doing everything in my power to turn this project into a docker container, for many of the reasons you enumerated earlier. If my installation instructions involve more than running an installation script, I'm doing something wrong.

So that kind of negates the idea of making this a pypi package, I think?

**Comment by Evo221** [comment]
> My .02:
> 
>     1. I have always hated the manual install instructions on the wiki, mostly because I think that if it can be automated, it should be automated. So the first thing I did was created the automated install script for Ubuntu 20.04
> 
>     2. I'm am doing everything in my power to turn this project into a docker container, for many of the reasons you enumerated earlier. If my installation instructions involve more than running an installation script, I'm doing something wrong.
> 
> 
> So that kind of negates the idea of making this a pypi package, I think?

Ok, so no pip package. Fair enough. From what I've been seeing over the last few years, most people expect every little project to ship their app in a container. So maybe there is no need to simplify the installation.
