### ISSUE TITLE
Set media Goal over web-ui to to Cloud

### ISSUE THREAD

**Issue by AxelJust** [automatic-ripping-machine/automatic-ripping-machine#516]
I Sucsesfully instaled ARM on a old HP Slimline 260-a105ng I gof for free and running Ubuntu on a 256 sandisk usb.
after first Trial and Error I wanted to select my Nextcloud-Music folder as Target for CD's but I couldn't find the [.abcde.conf](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/.abcde.conf) .

The coolest thing would be to choose a Cloudprovider like Nextcloud the Linux user might already bee looged in.

Or at least navigate te Fileexplorer.

unfortunatly I'm not deep enouth to have the cooding scill but I became a Fan of the [CasaOS](https://github.com/IceWhaleTech/CasaOS) UI.

What do you Think?

**Comment by 1337-server** [comment]
The .abcde.conf is moving, and is being added to the armui soon. From there you will be able to manage the config from the ui.

This will most likely be a small text editor though, and the abcde config file is vast and has a huge number of very specific customizable settings that are better set inside a text box/text file for now. Unless someone else wants to add more detailed settings.

**Comment by 1337-server** [comment]
Closing as stale
