### ISSUE TITLE
Find Movie metadata over barcode

### ISSUE THREAD

**Issue by AxelJust** [automatic-ripping-machine/automatic-ripping-machine#517]
Not everything is automaticaly recognised or found. 

Ading the Barcode number could posibly bring more results. Thus adding it manuly or even scanning it could improve the Metadata Asingment.
Could a Link to discogs or rottentomatoes be helpfull

What do you think?

**Comment by sourpatched** [comment]
Barcodes are for shops/warehouses, they do not store data only numbers but would be a cool idea if they did.
What about something like this? https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/506

**Comment by microtechno9000** [comment]
hey,  I have an idea on how to solve this for TV Shows and other formats. Havent worked on ARM before so taking some time to implement

**Comment by sourpatched** [comment]
> hey, I have an idea on how to solve this for TV Shows and other formats. Havent worked on ARM before so taking some time to implement edit: to clarify, not a barcode but a way better rip series

ARM searches and matches using online data. What is your idea?

**Comment by microtechno9000** [comment]
Thinking of creating a user configured session or similar, to specify a specific type of data, series or movie type.

**Comment by AxelJust** [comment]
> Thinking of creating a user configured session or similar, to specify a specific type of data, series or movie type.

That's exactly to what what @sourpatched is looking for in his issue `#506`. I would be Happy to see that For audiobooks ect.



> > hey, I have an idea on how to solve this for TV Shows and other formats. Havent worked on ARM before so taking some time to implement edit: to clarify, not a barcode but a way better rip series
> 
> ARM searches and matches using online data. What is your idea?

Amazon or Ebay use them to find the same CD or Moovie. That might help as well

**Comment by sourpatched** [comment]
> Thinking of creating a user configured session or similar, to specify a specific type of data, series or movie type.

That's exactly what I am talking about, you've summed it up in one sentence.

**Comment by sourpatched** [comment]
@AxelJust 
I think ARM uses https://musicbrainz.org/

**Comment by 1337-server** [comment]
> Amazon or Ebay use them to find the same CD or Moovie. That might help as well

Neither have available API's, so implementing this would be a lot of work. Awesome idea though!

**Comment by AxelJust** [comment]
Oh, Ok. Is [this](https://stackoverflow.com/questions/6007524/barcode-lookups-for-games-books-cds) outdated then?

If they speak of music, do they recognise audio books as well?

**Comment by 1337-server** [comment]
> Oh, Ok. Is [this](https://stackoverflow.com/questions/6007524/barcode-lookups-for-games-books-cds) outdated then?

Actually, no I was wrong. The barcode scanner (https://www.upcdatabase.com) looks to be current and working. Although the examples are no longer working, but the site/database works.

> If they speak of music, do they recognise audio books as well?

MBz (musicbrainz.org) only deal with audio CD's I believe, I have never tested it beyond audio CD's


I didn't know there was a barcode database, or and Amazon API. This is why ARM currently falls back to scrapping for images should MBz fail https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/946150c37efd0fdc7b97d385a6af96c5b414a66a/arm/ripper/music_brainz.py#L175

**Comment by 1337-server** [comment]
Update: I've started testing with this. There are some issues to overcome, but https://www.upcdatabase.com/ seems to bring back only very limited information. 

I'll keep working on it, and ill keep updating.

**Comment by 1337-server** [comment]
Closing as stale 

We won't have the time or resources to add this.
Please open a PR if someone else is able to implement this.
