### ISSUE TITLE
Automatic Ripping Machine Ubuntu 20.3

### ISSUE THREAD

**Issue by Richard-Sk** [automatic-ripping-machine/automatic-ripping-machine#518]
I have installed the ARM on to a PC with nvme solid state drives (Base Board Information: 	Manufacturer: Gigabyte Technology Co., Ltd. Product Name: Z370N WIFI-CF). I used the ubuntu_20.04_install.sh script as user arm as instructed. The system works fine on an old pc with "standard" hard drives but every time I install it on the machine with these newer SSD drives I get an error message in the log: "[22-06-2022 16:27:18] INFO ARM: Failed to open device /dev/nvme0n1p1 to check status."
I cannot find any solution to this issue and as a relatively limited Linux individual I don't want to go poking around and not do any further damage! (I have already reinstalled from scratch more times than enough to get me out of a hole).

If anyone can advise I'd be most grateful.

**Comment by Richard-Sk** [comment]
Thanks, I've done constant updates and upgrades so no concerns there. I'll try the reseating approaching report back, but there are no problems accessing the disc normally and it passes all the bios tests.

Regards
Richard Skaife
Sent from Samsung Tablet
________________________________

**Comment by shitwolfymakes** [comment]
Lovely. I'll take a closer look at the Linux code later tonight.

**Comment by Richard-Sk** [comment]
ARM doesn't rip the DVD, it ejects it after about a minute.

Regards
Richard Skaife
Sent from Samsung Tablet
________________________________

**Comment by 1337-server** [comment]
What is the output from  these commands ?

`ls -la /home/arm/`
`ls -la /home/arm/logs`

**Comment by Richard-Sk** [comment]
I'll send them tomorrow as it is 00.15 here in UK!

Regards
Richard Skaife
Sent from Samsung Tablet
________________________________

**Comment by Richard-Sk** [comment]
I reinstalled the ARM with the ubuntu_20.3_install script. I also changed the arm.yaml file to SKIP_TRANSCODE to "true", and the system now works OK.
Many thanks for your assistance anyway.

Regards
Richard Skaife
Mobile: +44 7785 393130

**Comment by 1337-server** [comment]
Glad this is resolved!
