### ISSUE TITLE
Ubuntu 20.04 Script has a dead link

### ISSUE THREAD

**Issue by lyingriotman** [automatic-ripping-machine/automatic-ripping-machine#519]
Hello, 

I've been trying to install ARM the last two days and I noticed while going through the initial steps that your link to the Ubuntu script is dead on [this page](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Ubuntu-20.04-Automatic-Installation). 

Here is the link and command in question:
`wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/v2_devel/scripts/ubuntu-20.04-install.sh`

I've been dealing with hardware issues in the meantime since I knew that my optical drive wasn't properly passed through. However, the link is still dead so I wanted to bring it to your attention.  The Discussions forum doesn't seem that active, so I posted an issue instead.

**Comment by shitwolfymakes** [comment]
Looks like this was overlooked when downstream changes were merged in. As a stopgap, update the command to the following and rerun:

`wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/v2_devel/scripts/install/ubuntu-20.04-install.sh`

Let me know if that works!
