### ISSUE TITLE
webui: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by shw-dev** [automatic-ripping-machine/automatic-ripping-machine#520]
I installed the dev_build docker image of ARM and am receiving this error whenever I try to go to the setup page in the webui.

Here is a copy of some of the docker log:

```
[2022-06-23 15:03:27,776] DEBUG in utils: Head is: c54d68996895
[2022-06-23 15:03:27,776] DEBUG in utils: Database version is: c54d68996895
[2022-06-23 15:03:27,777] INFO in utils: Database is up to date
172.17.0.1 - - [23/Jun/2022 15:03:27] "GET / HTTP/1.1" 302 -
[2022-06-23 15:03:27,826] DEBUG in routes: perm /opt/arm/installed
[2022-06-23 15:03:27,827] DEBUG in routes: Successfully created all of the ARM directories
[2022-06-23 15:03:27,830] DEBUG in routes: Setup of the database was successful.
172.17.0.1 - - [23/Jun/2022 15:03:27] "GET /setup HTTP/1.1" 302 -
[2022-06-23 15:03:27,854] DEBUG in utils: Head is: c54d68996895
[2022-06-23 15:03:27,855] DEBUG in utils: Database version is: c54d68996895
[2022-06-23 15:03:27,855] INFO in utils: Database is up to date
172.17.0.1 - - [23/Jun/2022 15:03:27] "GET /index HTTP/1.1" 302 -
[2022-06-23 15:03:27,877] DEBUG in routes: perm /opt/arm/installed
172.17.0.1 - - [23/Jun/2022 15:03:27] "GET /setup HTTP/1.1" 302 -
[2022-06-23 15:03:27,900] DEBUG in utils: Head is: c54d68996895
[2022-06-23 15:03:27,901] DEBUG in utils: Database version is: c54d68996895
[2022-06-23 15:03:27,901] INFO in utils: Database is up to date
172.17.0.1 - - [23/Jun/2022 15:03:27] "GET / HTTP/1.1" 302 -
[2022-06-23 15:03:27,928] DEBUG in routes: perm /opt/arm/installed
```
The log keeps repeating this as long as I have the webui page open. I've tried deleting the "installed" file in /opt/arm, but after the initial setup the issue persists. 

I did initially try to install the latest docker image first and the webui worked, but it wouldn't rip the disc.

**Comment by 1337-server** [comment]
The latest tag is now fixed. You can use that instead.

1337server/automatic-ripping-machine:latest

**Comment by shw-dev** [comment]
Thanks!

I'm seeing this error now:

FileNotFoundError: [Errno 2] No such file or directory: '/etc/arm/config/.abcde.conf'

**Comment by 1337-server** [comment]
Latest image should fix this. 

You will need to pull the latest image.

**Comment by shw-dev** [comment]
Now I'm seeing this loop endlessly:

`runsvdir /etc/service: warning: unable to stat /etc/service: file does not exist`

**Comment by shw-dev** [comment]
Oh I looked at your commit and line 62 doesn't match the updated directory.

**Comment by 1337-server** [comment]
Can you run these commands, replacing the `/home/arm` with the directory you passed into docker
`ls -la /home/arm/`
`ls -la /home/arm/logs`
`ls -la /home/arm/db/`

And post the output here.
`ls -la /home/arm/media/`

**Comment by shw-dev** [comment]
/home/arm
```
drwxrwxrwx  1      1001           1001    92 Jun 23 12:22 .
drwxrwxrwx+ 1 admin administrators    28 Jun 23 12:41 ..
-rwxrwxrwx  1      1001           1001 21575 Jun 23 00:04 .abcde.conf
drwxrwxrwx  1      1001           1001     0 Jun 23 12:20 config
drwxr-xr-x  1 arm       users             12 Jun 23 13:59 db
drwxrwxrwx  1 arm       users             14 Jun 23 14:00 logs
drwxrwxrwx  1 arm       users             26 Jun 23 00:12 .MakeMKV
drwxrwxrwx  1 arm       users             54 Jun 23 01:40 media
drwxrwxrwx  1      1001           1001     0 Jun 23 01:38 music
drwxr-xr-x  1 root      root               0 Jun 23 12:14 Music
```
/home/arm/logs
```
drwxrwxrwx 1 arm  users 14 Jun 23 14:00 .
drwxrwxrwx 1 1001  1001 92 Jun 23 12:22 ..
-rw-r--r-- 1 arm  users  0 Jun 23 14:00 arm.log
```

/home/arm/db
```
drwxr-xr-x 1 arm  users    12 Jun 23 13:59 .
drwxrwxrwx 1 1001  1001    92 Jun 23 12:22 ..
-rw-r--r-- 1 arm  users 45056 Jun 23 13:59 arm.db
```

/home/arm/media/
```
drwxrwxrwx 1 arm  users 54 Jun 23 01:40 .
drwxrwxrwx 1 1001  1001 92 Jun 23 12:22 ..
drwxrwxrwx 1 arm  users  0 Jun 23 00:38 completed
drwxrwxrwx 1 arm  users  0 Jun 23 00:38 movies
drwxrwxrwx 1 arm  users  0 Jun 23 00:38 raw
drwxrwxrwx 1 arm  users  0 Jun 23 01:40 transcode
```

**Comment by 1337-server** [comment]
what's your arm uid ?

**Comment by shw-dev** [comment]
The arm id is 1029 and it's in the users group 101. I passed both into the container

**Comment by 1337-server** [comment]
This will need more time to debug

**Comment by shw-dev** [comment]
Anything I can do to help?

**Comment by 1337-server** [comment]
Could you share the docker run command that you used to start the container ?

**Comment by shw-dev** [comment]
I'm pretty sure it was the one in the Wiki, but I changed the volumes and ids. I'll double check when I get home.

**Comment by 1337-server** [comment]
Sorry about that, the instructions weren't updated with the new image. The wiki has been updated.

Link here -> https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker

**Comment by shitwolfymakes** [comment]
Also changed by my PR is the environment variables. `UID` is now `ARM_UID`, and `GID` is now `ARM_GID`

**Comment by shw-dev** [comment]
sudo docker run -d   
-p "8080:8080"   
-e UID="1029" -e GID="100"   
-v "/volume1/NAS/Output/ARM:/home/arm"  
 -v "/volume1/NAS/Output/ARM/music:/home/arm/music"   
-v "/volume1/NAS/Output/ARM/config:/home/arm/config"   
-v "/volume1/NAS/Output/ARM/logs:/home/arm/logs"   
-v "/volume1/NAS/Output/ARM/media:/home/arm/media"   
--privileged   
--restart "always"   
--name "arm-rippers"   
1337server/automatic-ripping-machine:latest

**Comment by shw-dev** [comment]
I see, so I'll have to run docker-setup script first?

**Comment by 1337-server** [comment]
It's recommended.  It just makes sure everything is set up correctly.

But if you want to skip that step and try using the run command, you can find out the default here
-> https://github.com/1337-server/automatic-ripping-machine/blob/v2_devel/scripts/docker/start_arm_container.sh

**Comment by shw-dev** [comment]
I just tried the scripts and so far it's still the same error

**Comment by shw-dev** [comment]
I ran this command in a bash terminal in the docker container:

`/usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0`

and received this output. Is this helpful?

```
Traceback (most recent call last):                                                                                                                                   
  File "/opt/arm/arm/ripper/main.py", line 141, in <module>                                                                                                          
    job = Job(devpath)                                                                                                                                               
  File "<string>", line 4, in __init__                                                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/state.py", line 480, in _initialize_instance                                                           
    manager.dispatch.init_failure(self, args, kwargs)                                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__                                                                 
    compat.raise_(                                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_                                                                       
    raise exception                                                                                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/state.py", line 477, in _initialize_instance                                                           
    return manager.original_init(*mixed[1:], **kwargs)                                                                                                               
  File "/opt/arm/arm/models/models.py", line 79, in __init__                                                                                                         
    self.parse_udev()                                                                                                                                                
  File "/opt/arm/arm/models/models.py", line 104, in parse_udev                                                                                                      
    device = pyudev.Devices.from_device_file(context, self.devpath)                                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/pyudev/device/_device.py", line 241, in from_device_file                                                              
    return cls.from_device_number(context, device_type, device_number)                                                                                               
  File "/usr/local/lib/python3.8/dist-packages/pyudev/device/_device.py", line 198, in from_device_number                                                            
    raise DeviceNotFoundByNumberError(typ, number)                                                                                                                   
pyudev._errors.DeviceNotFoundByNumberError: No block device with number 2816 
```

**Comment by 1337-server** [comment]
Can you share the run command you used ? Is it still the same as above ?

It may help to pass in each device you have with the --device flag

Example is here: https://github.com/1337-server/automatic-ripping-machine/blob/v2_devel/scripts/docker/start_arm_container.sh

**Comment by shw-dev** [comment]
I used this run command

```
sudo docker run -d -p "8080:8080" -e ARM_UID="1029" -e ARM_GID="100" -v "/volume1/NAS/Output/ARM:/home/arm" -v "/volume1/NAS/Output/ARM/music:/home/arm/music" -v "/volume1/NAS/Output/ARM/logs:/home/arm/logs" -v "/volume1/NAS/Output/ARM/media:/home/arm/media" -v "/volume1/NAS/Output/ARM/config:/etc/arm/config" 
--device="/dev/sr0:/dev/sr0" --device="/dev/sg5:/dev/sg5" --privileged --restart "always" --name "arm-rippers" 
--cpuset-cpus='2,3' 1337server/automatic-ripping-machine:latest
```

**Comment by shw-dev** [comment]
I also ran `dd if=/dev/sr0 of=test.iso` in the bash terminal to see if the container could make an iso from a dvd and it worked.

**Comment by shw-dev** [comment]
Looks like I'm having the same issue here:

> I was able to find the script in the docker container and now I can see the webui.
> 
> This appears when I open the disc drive Jun 23 21:26:17 arm-rippers ARM: Entering docker wrapper Jun 23 21:26:17 arm-rippers ARM: [ARM] Not CD, Bluray, DVD or Data. Bailing out on sr0 Jun 23 21:26:20 arm-rippers ARM: Entering docker wrapper Jun 23 21:26:20 arm-rippers ARM: [ARM] Not CD, Bluray, DVD or Data. Bailing out on sr0
> 
> This appears after the disc loads, but the drive stops reading right after Jun 23 21:26:48 arm-rippers ARM: Entering docker wrapper Jun 23 21:26:48 arm-rippers ARM: [ARM] Starting ARM for Bluray on sr0

**Comment by 1337-server** [comment]
Can you explain ? Are you now receiving a different error ?

**Comment by 1337-server** [comment]
Assuming this is resolved.
