### ISSUE TITLE
It reads the CD then when it goes to rip it the CD gets ejected

### ISSUE THREAD

**Issue by thewascokid** [automatic-ripping-machine/automatic-ripping-machine#521]
- [* ] I have checked the wiki
- [* ] I have searched for similar issues

**Describe the bug**
It reads the CD then when it goes to rip it the CD gets ejected

**To Reproduce**
1. x
2. y
3. z

### Environment
[Debian Buster]
[  1337server/automatic-ripping-machine:latest] 

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DR
[UB40-Promises-and-Lies.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8972513/UB40-Promises-and-Lies.log)
AG AND DROP LOG FILE HERE <<<<<]

**Comment by sourpatched** [comment]
mkdir: cannot create directory ‘//abcde.9b0b120b’: Permission denied
abcde: Temp directory //abcde.9b0b120b could not be created.
[06-24-2022 01:38:29] DEBUG ARM: utils.database_updater status=fail:<class 'str'>
[06-24-2022 01:38:29] DEBUG ARM: utils.database_updater errors=Call to abcde failed with code: 1 (b''):<class 'str'>
[06-24-2022 01:38:29] DEBUG ARM: utils.database_updater successfully written to the database
[06-24-2022 01:38:29] ERROR ARM: utils.rip_music Call to abcde failed with code: 1 (b'')
[06-24-2022 01:38:29] INFO ARM: main.main Music rip failed.  See previous errors.  Exiting. 
[06-24-2022 01:38:29] DEBUG ARM: models.eject Unmounted disc /dev/sr0
[06-24-2022 01:38:32] DEBUG ARM: models.eject Failed to eject /dev/sr0

Looks to be a Permission issue? What's your config file?

**Comment by sourpatched** [comment]
Same error as https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/266

**Comment by thewascokid** [comment]
When I deployed ARM it created all the directories but in the config directory it is empty.

**Comment by sourpatched** [comment]
It's on going issue with docker

**Comment by 1337-server** [comment]
Should be fixed with latest build, let me know if not.

**Comment by thewascokid** [comment]
I still am having an issue with "mkdir: cannot create directory ‘/home/arm/abcde.9b0b120b’: Permission denied
abcde: Temp directory /home/arm/abcde.9b0b120b could not be created." 
Do you have any thought?

**Comment by thewascokid** [comment]
Thanks I fixed the permissions but now this error "Unknown lookup method musicbrainz
. Aborting."
Is this because of something set up wrong in .abcde.config

**Comment by 1337-server** [comment]
Can you share the full log ?

**Comment by thewascokid** [comment]
[UB40-Promises-and-Lies.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/8996981/UB40-Promises-and-Lies.log)

**Comment by 1337-server** [comment]
Open your .abcde.conf and near the top it should say what version you have. Can you share that.

**Comment by thewascokid** [comment]
Thanks for all your help here is that info  # System defaults for abcde version 2.8.2

**Comment by 1337-server** [comment]
This might be the same issue

https://github.com/1337-server/automatic-ripping-machine/issues/119

**Comment by 1337-server** [comment]
If the above doesn't work, you could test this much more compact version of the abcde.conf. It's much smaller, so it's easier to focus on what is broken.

https://github.com/1337-server/automatic-ripping-machine/issues/66

**Comment by thewascokid** [comment]
Thanks'  that worked but how can I change the output format to be Artist/Album/Track - Song Instead of Artist-Album/Track - Song
 /Music
    /Artist
        /Album
            01 - Song.flac
            02 - Song.flac

**Comment by 1337-server** [comment]
You can play around with `OUTPUTFORMAT` to get it to your liking

This is probably close to what you want, but you can mess around and find it what you like.
```
OUTPUTFORMAT='${ARTISTFILE} ${ALBUMFILE}/${TRACKNUM} - ${TRACKFILE}'
```

**Comment by thewascokid** [comment]
Thanks again for all your help Your the best !!!!!

**Comment by 1337-server** [comment]
No worries, glad it's working for you!
