### ISSUE TITLE
DVD rip only has dubbed language

### ISSUE THREAD

**Issue by t3dc** [automatic-ripping-machine/automatic-ripping-machine#524]
- [x ] I have checked the wiki
- [x] I have searched for similar issues

Hey folks,

I've got DVDs of Psych I bought while living in Germany where the disc's primary language is German, but, of course, there is also the original English track. I'd like the rips to have that original english track rather than the dubbed German, but no matter what I try, I wind up with an MKV with two tracks of German and no English.

It looks to me as thought the correct fix is to create a default.mmcp.xml file and add it to the makemkv args section of ARM. I tried that, however, my MakeMKV did not include a default file, so I had to find one on the internet. It wasn't from an authoritative source, so I don't know how "default" it was.

I used this as my selection string: app_DefaultSelectionString="-sel:all,+sel:(ger|eng|nolang),-sel:(havecore),-sel:mvcvideo,=100:all,-50:ger,-10:forced"

I believe that should grab both the English and German audio and make the German audio secondary to the English. However, it simply produced the same German/German mkv as ARM without any MKV Args.

### Environment
Ubuntu 20.04.4 LTS
v2_master
commit a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d

### Log file

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]
[PSYCH_SEASON_1_DISC_2.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9028378/PSYCH_SEASON_1_DISC_2.log)

**Comment by 1337-server** [comment]
You're trying to set MakeMKV settings correctly, but your log shows it is a DVD and A.R.M is using HandBrake. If you set the correct settings for HandBrake, your issue should be resolved.
setting
`HB_ARGS_DVD: "--subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio"`
Should get you the English tracks

**Comment by t3dc** [comment]
Trying it now and I'll report back. :)

**Comment by t3dc** [comment]
Alright! Rips are now in english. 

However, the system isn't respecting the DELRAWFILES: False flag. So, when disc 1 finishes ripping and I put in disc 2, the files from disc 2 happily write over the files from disc 1. Any good way to fix that?

**Comment by 1337-server** [comment]
This is a known issue. It was fixed here 1337-server/automatic-ripping-machine/issues/163, But this hasn't been merged yet.

I'll close this now as the original issue has been resolved
