### ISSUE TITLE
Rocky not ripping

### ISSUE THREAD

**Issue by TinyTheBrontosaurus** [automatic-ripping-machine/automatic-ripping-machine#53]
I have DVDs of Rocky I-VI (don't judge me, they're great movies). Anyways, I and II are not ripping. Any recommendations for how I can debug it? I did verify that `ID_CDROM_MEDIA_TRACK_COUNT_AUDIO`
 and `ID_FS_TYPE` were both empty

```
*** Start config parameters ****
ARM_CHECK_UDF=true
GET_VIDEO_TITLE=true
SKIP_TRANSCODE=false
ARMPATH="/nfs/apple_patch/PlexMedia/Movies/New/"
RAWPATH="/nfs/apple_patch/PlexMedia/Movies/New/Raw/"
MEDIA_DIR="/nfs/apple_patch/PlexMedia/Movies/"
LOGPATH="/opt/arm/logs/"
LOGLIFE=1
SET_MEDIA_PERMISSIONS=false
CHMOD_VALUE=777
MINLENGTH="600"
RIPMETHOD="mkv"
MKV_ARGS=""
HB_PRESET="High Profile"
DEST_EXT=mkv
HANDBRAKE_CLI=HandBrakeCLI
MAINFEATURE=false
HB_ARGS="--subtitle scan -F"
PLEX_SUPPORT=false
EMBY_REFRESH=false
EMBY_SUBFOLDERS=true
EMBY_SERVER=""
EMBY_PORT="8096"
EMBY_CLIENT="ARM"
EMBY_DEVICE="ARM"
EMBY_DEVICEID="ARM"
EMBY_USERNAME=""
EMBY_USERID=""
IFTTT_EVENT="arm_event"
LOG=$LOGPATH$LOGFILE
*** End config parameters ****
Starting Identify Script...
Deleting 0 old log files:
DEVLINKS=/dev/disk/by-id/ata-HL-DT-ST_DVD+_-RW_GHB0N_K4KF1LD5346 /dev/disk/by-id/wwn-0x1207980033x
DEVNAME=/dev/sr0
DEVPATH=/devices/pci0000:00/0000:00:1f.2/ata5/host4/target4:0:0/4:0:0:0/block/sr0
DEVTYPE=disk
ID_ATA=1
ID_ATA_SATA=1
ID_ATA_SATA_SIGNAL_RATE_GEN1=1
ID_BUS=ata
ID_CDROM=1
ID_MODEL=HL-DT-ST_DVD+_-RW_GHB0N
ID_MODEL_ENC=HL-DT-ST\x20DVD+\x2f-RW\x20GHB0N\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20
ID_REVISION=A1B1
ID_SERIAL=HL-DT-ST_DVD+_-RW_GHB0N_K4KF1LD5346
ID_SERIAL_SHORT=K4KF1LD5346
ID_TYPE=cd
ID_WWN=0x1207980033x
ID_WWN_WITH_EXTENSION=0x1207980033x
MAJOR=11
MINOR=0
SUBSYSTEM=block
TAGS=:seat:systemd:uaccess:
USEC_INITIALIZED=2667
unable to identify


*** Start config parameters ****

```

**Comment by TinyTheBrontosaurus** [comment]
I have a growing list of DVDs for which is hitting the `unable to identify` path (Rocky, Rocky II, Pulp Fiction, South Park, The Gamers: Dorkness Rising). 

I'm interested in shoring up the logging in ARM to help track these down. Afterwards, I might add a test harness (since I imagine the combination of parameters used to determine disk type and title can get unwieldy). Do you have any recommendations for how I should attack these? Or should I just go for it and create a PR?

**Comment by TinyTheBrontosaurus** [comment]
Digging deeper, it looks like I'm able to fix the issue by calling `makemkvcon info dev:"${DEVNAME}" -r` before the `ID_FS_TYPE` call in identify.sh. Also, I had to prevent the 'unable to identify' case from ejecting the disk since arm_wrapper appears to get triggered about 3x per disk. Not sure if this is an issue specific to my setup or what.

**Comment by ahnooie** [comment]
Interesting, feel free to do a PR for the unable to identify issue and also the logging.  I don't have that problem, but I don't have any of those movies.   Are you by chance running Ubuntu under virtualization such as esxi? I've heard of some issues there where HandBrake ripping wouldn't work until MakeMKV ran once... then Handbrake worked fine so it may be we just need to call makemkvcon first like you did to "prime" the drive.

**Comment by TinyTheBrontosaurus** [comment]
Nope. i'm running on the metal. It's failing before it gets to makemkv. I'll make a PR.  I'm very interested to see what your feedback is, because it works perfect on my machine now but I'm only doing DVDs.

**Comment by TinyTheBrontosaurus** [comment]
OK. The PR is finally ready. I was having a heck of a time with getting the CI to pass the linter, which then ended up breaking my code. I ended up losing an evening of DVD ripping before I realized there was an issue. But it's both passing and working now! review away.

**Comment by 1337-server** [comment]
Assuming this is now resolved
