### ISSUE TITLE
v2_devel pull does not update changes to config directory

### ISSUE THREAD

**Issue by microtechno9000** [automatic-ripping-machine/automatic-ripping-machine#530]
- [ x] I have checked the wiki
- [ x] I have searched for similar issues

**Describe the bug**
The latest PR for v2_devel branch does not update / create the new /etc/arm/config folder or move the configuration files.
WebUI log reports missing folder and files
```
FileNotFoundError: [Errno 2] No such file or directory: '/etc/arm/config/apprise.yaml'
...
FileNotFoundError: [Errno 2] No such file or directory: '/etc/arm/config/arm.yaml'
...
FileNotFoundError: [Errno 2] No such file or directory: '/etc/arm/config/abcde.conf'
```

Resolved with
```
sudo mkdir -p /etc/arm/config
sudo cp setup/apprise.yaml /etc/arm/config/.
sudo mv arm.yaml /etc/arm/config/.
sudo mv /etc/abcde.conf /etc/arm/config/.
sudo chown arm:arm -R /etc/arm
```

### Environment
Ubuntu 20.04

### Log file
Nil

**Comment by 1337-server** [comment]
The Ubuntu install script ?

**Comment by microtechno9000** [comment]
Didnt try the install script as it was an update not a fresh install.

I did check the ubuntu installation wiki, but there wasn't anything listed.

**Comment by 1337-server** [comment]
Ahh, that makes sense, I don't want to update the wiki until v2_devel is merged as it will cause breaking changes.

Thanks, I'll leave this open as it might help others.

**Comment by microtechno9000** [comment]
cheers

**Comment by davedujour** [comment]
The Ubuntu install script is giving a 404 now. wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/v2_devel/scripts/install/ubuntu-20.04-install.sh

**Comment by 1337-server** [comment]
> The Ubuntu install script is giving a 404 now. wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/v2_devel/scripts/install/ubuntu-20.04-install.sh

Should be fixed now

**Comment by foocp** [comment]
running the install script on a fresh 20.04 gives me
```
creating config file /etc/arm/config/arm.yaml
cp: cannot stat '/opt/arm/setup/arm.yaml': No such file or directory
```

**Comment by iplusplus42** [comment]
> running the install script on a fresh 20.04 gives me
> 
> ```
> creating config file /etc/arm/config/arm.yaml
> cp: cannot stat '/opt/arm/setup/arm.yaml': No such file or directory
> ```

Can confirm; I'm having the same issue on a fresh 20.04 install.

**Comment by 1337-server** [comment]
What script did you run ?

**Comment by johndoc** [comment]
I'm having a similar issue with Debian.

`cp: cannot stat './setup/arm.yaml': No such file or directory`

**Comment by 1337-server** [comment]
> I'm having a similar issue with Debian.
> 
> `cp: cannot stat './setup/arm.yaml': No such file or directory`

How are you installing ?
On what version of Debian ?

**Comment by foocp** [comment]
Thanks. I got it (the Ubuntu 20.04 install script) working by changing line 125 (git checkout v2_master) to   "git checkout v2_devel“ - but I suppose removing it entirely does the same job.
