### ISSUE TITLE
Run A.R.M on WSL

### ISSUE THREAD

**Issue by 1337-server** [automatic-ripping-machine/automatic-ripping-machine#531]
**Is your feature request related to a problem? Please describe.**
It may now be possible to run A.R.M on Windows
Will need lots of testing, and It's something that will take a while before I have time to implement

**Describe the solution you'd like**
Run ARM on Windows

**Describe alternatives you've considered**
....

**Are you able to help code/implement this feature ?**
Yes

**Additional context**

https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk
https://docs.microsoft.com/en-us/windows/wsl/connect-usb

**Comment by Daniel-Basnar** [comment]
I am on Windows 10 right now, which means WSL 2 doesn't use systemd, and disc mounting isn't a thing.
I got as far as running WSL Ubuntu 20.04 with systemd using genie (https://github.com/arkane-systems/genie), and everything untill this point seems to work. Inserting a disc didn't do anything though, becuase I cant mount the DVD Drive in WSL.

If I were to upgrade to Windows 11 (which supposedly has systemd, and the ability to mount discs), I believe it would more or less work out of the box..

I could be wrong though, as I am quite a noob when it comes to Linux :'D

**Comment by 1337-server** [comment]
Yeah, this is also my understanding, so it should mean that windows support is possible.

**Comment by 1337-server** [comment]
Due to a recent poll, we will no longer be looking to support extra versions.
