### ISSUE TITLE
Remove requirement to run as root

### ISSUE THREAD

**Issue by TinyTheBrontosaurus** [automatic-ripping-machine/automatic-ripping-machine#54]
I assume this is possible, but it will be difficult when it comes to mounting. But I get nervous when directories are being `mkdir`'d and `rm`'d as root.

**Comment by ahnooie** [comment]
Agreed, definitely want to get it working as non-root soon.  The ARM could either su to an underprivileged user for most tasks, or sudo to root only when it needs it.

**Comment by 2long1** [comment]
Adding User=foo to the arm@.service file would cause the identify script to be be run as the user foo.  With a judicious use of sudo, you could probably drastically reduce what runs as root.

**Comment by muckngrind4** [comment]
Added feature in commit https://github.com/automatic-ripping-machine/automatic-ripping-machine/commit/d3b9c6de97856f9d7ecb09c40f7ddd8361364ed2
