### ISSUE TITLE
werkzeug 2.2.0?

### ISSUE THREAD

**Issue by thepandaman2000** [automatic-ripping-machine/automatic-ripping-machine#546]
I'm a bit of a docker noob so please bear with me. 

I'm attempting to run the arm in docker on unraid. When I launch the container is loops the following error in the log endlessly and fails to start the web ui.

Starting web ui
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import app, db
  File "/opt/arm/arm/../arm/ui/__init__.py", line 13, in <module>
    from flask_login import LoginManager
  File "/usr/local/lib/python3.8/dist-packages/flask_login/__init__.py", line 12, in <module>
    from .login_manager import LoginManager
  File "/usr/local/lib/python3.8/dist-packages/flask_login/login_manager.py", line 35, in <module>
    from .utils import _create_identifier
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/usr/local/lib/python3.8/dist-packages/werkzeug/routing/__init__.py)

Some quick googling points to werkzeug 2.2.0 being the potential culprit

**Comment by shitwolfymakes** [comment]
Never had this issue, but it looks like a routing issue specific to your unraid box. Please post the run command used when creating the container.

**Comment by 1337-server** [comment]
This is part of an ongoing issue

https://github.com/1337-server/arm-dependencies/pull/26

The is because both `Werkzeug` and `flask-login` are being allowed to >= to the latest version. Instead of being pinned to specific versions.

But this causes issues as if pip gets werkz=>2.1.0, things break as it removed some functions and flask login didn't update their usages till versions 0.6.0.
Meaning you can end up with newer versions of werkz, but older versions of flask login, breaking the images and installer scripts.

I have pushed a new commit to pin werkz to 2.0.3, this should be a temp fix, but something more stable will need to be found for long term.

**Comment by thepandaman2000** [comment]
pulling from https://hub.docker.com/r/automaticrippingmachine/automatic-ripping-machine/

rather than https://hub.docker.com/r/1337server/automatic-ripping-machine/

seems to (at least in the short term) resolved the issue

**Comment by 1337-server** [comment]
Should be fixed now, I triggered a build of my own dockerhub.
It hadn't been triggered on the main image, only the base image, as it takes 24h to update the main image automatically.

**Comment by thepandaman2000** [comment]
That did it, thanks for your help

**Comment by thepandaman2000** [comment]
I might have spoken too soon, dvds seem to be working fine but when I tried a Blu-ray it seems to have crashed. I've attached a log below
[LATESPRING.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9236465/LATESPRING.log)
.

**Comment by 1337-server** [comment]
Docker image updated. Can you try the new image ?

**Comment by shitwolfymakes** [comment]
Closing as stale, feel free to reopen if the problem persists
