### ISSUE TITLE
🐛 ARM doesnt log errors to job logfile

### ISSUE THREAD

**Issue by 1337-server** [automatic-ripping-machine/automatic-ripping-machine#548]
After fixing the broken json and rebuilding the docker container, I am still getting a failed rip due to `json_api.process_handbrake_logfile` erroring `Can't find index`.

I use this Blu-ray disc for testing so I know it's good. The RIPMETHOD is set to `mkv`. Attached is the logfile.
[MOULIN_ROUGE_165936741511.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9236220/MOULIN_ROUGE_165936741511.log)

_Originally posted by @shitwolfymakes in https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/535#issuecomment-1201545982_

**Comment by shitwolfymakes** [comment]
Closing as stale, feel free to reopen if the problem persists

**Comment by shitwolfymakes** [comment]
Side note, these logs have been normal for a looong time now. Should get cleaned up as part of the log rewrite
