### ISSUE TITLE
v2_devel doesn't auto run with new arm_wrapper script

### ISSUE THREAD

**Issue by microtechno9000** [automatic-ripping-machine/automatic-ripping-machine#550]
- [ x] I have checked the wiki
- [ x] I have searched for similar issues

**Describe the bug**
latest updated to the arm_wrapper.sh script doesn't auto start the ripping process on either drive (sr0 or sr1).
No log files are produced, the error is not reported to the default arm log files.

**To Reproduce**
1. Insert media to a drive
2. Nothing happens

### Environment
Ubuntu 20.04

### Log file
No log files generated when running

Manual output from arm_wrapper.sh
```
mtech@server:/opt/arm$ ./scripts/thickclient/arm_wrapper.sh /dev/sr0
<13>Aug  7 14:53:01 ARM: [ARM] Not CD, Bluray, DVD or Data. Bailing out on /dev/sr0
mtech@server:/opt/arm$ ./scripts/thickclient/arm_wrapper.sh /dev/sr1
<13>Aug  7 14:53:07 ARM: [ARM] Not CD, Bluray, DVD or Data. Bailing out on /dev/sr1
```
Modified the arm_wrapper to output the values from udev, it doesnt look like they are being passed from the arm udev config. Using the new 51-automedia.rules.
```
echo "[DEBUG] Device ${DEVNAME}"
echo "[DEBUG] ID_CDROM_MEDIA_DVD ${ID_CDROM_MEDIA_DVD}"
echo "[DEBUG] ID_CDROM_MEDIA_BD ${ID_CDROM_MEDIA_BD}"
echo "[DEBUG] ID_CDROM_MEDIA_CD ${ID_CDROM_MEDIA_CD}"
echo "[DEBUG] ID_FS_TYPE ${ID_FS_TYPE}"
```
output:
```
mtech@server:/opt/arm$ ./scripts/thickclient/arm_wrapper.sh /dev/sr0
[DEBUG] Device /dev/sr0
[DEBUG] ID_CDROM_MEDIA_DVD 
[DEBUG] ID_CDROM_MEDIA_BD 
[DEBUG] ID_CDROM_MEDIA_CD 
[DEBUG] ID_FS_TYPE 
```

**Comment by 1337-server** [comment]
Is this the latest commit ?
Did you run the installation script ?

**Comment by microtechno9000** [comment]
latest commit v2_devel

I didn't run the install script, only copies across the 51-automedia rules config file, as I noticed it had changed.

Is there a way that it can be documented in the README or a release note detailing the changes, such that users / I know if the installation script or some other script needs to be run.

**Comment by shitwolfymakes** [comment]
Closing as this issue is out of date and hasn't been updated
