### ISSUE TITLE
ARM is repeatedly ripping the same movie when ALLOW_DUPLICATES is false

### ISSUE THREAD

**Issue by drwonky** [automatic-ripping-machine/automatic-ripping-machine#554]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
There are a few things to unpack here.
- When discs are ejected, the drive closes the tray again after a short period of time (drive does not remain ejected)
- When the tray closes automatically, ARM is triggered to rip the disc again, duplicate detection is not working
  - Duplicate detection seems to also be foiled when you do a manual Title Search because the auto-detected title is wrong

**To Reproduce**
1. Insert _Mission Impossible 3_ disc
2. Let ARM rip it
3. Tray auto-closes
4. Repeat 12 times in 1 night

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Ubuntu 20.04.4 LTS
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
v2_master HEAD

I built a machine with 5 identical TS-H653B drives
3 of the drives are connected to a PCIe SATA card
2 of the drives are connected to mobo chipset SATA
Behavior does not follow a specific drive, all seem to auto-retract and result in dupes
When I abandon a rip, the drives seem to stay open, but auto-completion results in retraction and re-ripping

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by drwonky** [comment]
Here's a screenshot of the behavior, let me know if you want any logs:
![image](https://user-images.githubusercontent.com/35117150/185774128-a0b9cc6f-6937-4469-b8f4-0a577b014091.png)

**Comment by drwonky** [comment]
As a workaround I renamed `eject` and symlinked `true` to `eject`, this requires me to manually curate the herd (hobby farming vs cattle ranching).

**Comment by drwonky** [comment]
More info, this time trying to track down the "eject and insert" issue.  I make a shell script to replace /usr/bin/eject that just called the old eject program and then added a 10 second sleep.  As soon as the sleep finishes, the tray closes.

This indicates that something is "pinging" the drive immediately after the "eject" command returns.

Is there anything in ARM that tries to access the device immediately after eject has completed?

Yes, this is 2 issues, one is the cycle of re-ripping movies, the other is the eject/close behavior.

**Comment by shitwolfymakes** [comment]
Keep up the good work! This issue has been a pain in the ass for at least two years now.

**Comment by 1337-server** [comment]
https://github.com/1337-server/automatic-ripping-machine/issues/82#issuecomment-897338175

Should help you fix this issue.

**Comment by drwonky** [comment]
> [1337-server#82 (comment)](https://github.com/1337-server/automatic-ripping-machine/issues/82#issuecomment-897338175)
> 
> Should help you fix part of this issue.

I can confirm that setting this sysctl does prevent the eject-close cycle from occurring.  I will include a change to the install script for this.

I have an idea of how to fix the duplicate recording issue:  Keep an inventory of "successful" DVD CRC64 values and titles.  I have to dig into the software to figure out if this is feasible.

**Comment by 1337-server** [comment]
This is a bug, ARM should already be stopping duplicates. I'll look into this.

**Comment by shitwolfymakes** [comment]
@1337-server when you find the source, let me know so I can keep it in mind for the logic rewrite

**Comment by 1337-server** [comment]
`arm/ripper/main.py` calls on `utils.job_dupe_check()` and this should check the local db for successful jobs with the same crc64

And then when the run/rip starts, it calls `utils.check_for_dupe_folder` it should kill the run at that point if the disc is a dupe and dupe rips are disabled.

But without a log, I'm not sure what part failed yet.

**Comment by drwonky** [comment]
I'm done ripping the collection (took a month), I'll re-enable autoclose and see if I can catch it in the act.

**Comment by 1337-server** [comment]
> I'm done ripping the collection (took a month), I'll re-enable autoclose and see if I can catch it in the act.

This would be very helpful.  Thanks.

**Comment by drwonky** [comment]
I ripped RoboCop 2 several times in a row, here's the logs.  All I did was reinsert the disc after it ejected, I did not re-enable autoclose.

[ROBOCOP2.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9523891/ROBOCOP2.log)
[ROBOCOP2_166261315074.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9523890/ROBOCOP2_166261315074.log)
[ROBOCOP2_166261416651.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9523892/ROBOCOP2_166261416651.log)

**Comment by 1337-server** [comment]
It looks like you are using an older version. Using the latest version should fix this issue.
