### ISSUE TITLE
ARM install instructions for VCE do not work unless X11 is installed

### ISSUE THREAD

**Issue by drwonky** [automatic-ripping-machine/automatic-ripping-machine#555]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
I spent most of the week figuring this out and hit on _magic_ finally.
I have an AMD RX550 for encoding and Ubuntu 20.04.4, so I can run the command exactly.
The AMD drivers **will not work** for VCE unless the following is true:
- The AMD card is the primary display
- The AMD card has been initialized into graphics mode with X11

If you fail to use the AMD card as primary display, the drivers will lockup and just plain won't initialize properly, this manifests as kernel oopses in the driver and `sensors` will hang trying to talk to the hwmon device.

If you do not enable X11 and allow it to initialize the card into graphics mode, Vulkan cannot open the device and use it for encoding, this results in `AMF failed to initialise on the given Vulkan device`.

The TL;DR is that it is **absolutely critical** that the AMD device is the default video card and that it is initialized by X11 into graphics mode.  It's not enough for the card to be default and in text mode, X11 must initialize the card into graphics mode.  I don't know what happens with multiple cards in the same system.

**To Reproduce**
1. Install AMD card as secondary display device (use onboard graphics as primary)
2. Use Ubuntu Server with multi-user.target as default runlevel

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Ubuntu 20.04.0
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
v2_master

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by drwonky** [comment]
Update, I swapped my RX550 for an RX560 and after the full power cycle I was having more initialization errors.  If I enabled IGPU graphics in the CPU, X11 would crash on start and Vulkan/AMF would not initialize.  Disabled IGPU again and X11 is working, but Vulkan/AMF would not initialize.  Had to login and run HandBrakCLI once to initialize Vulkan on the graphical console and from that point forward "headless" operation worked.

FWIW, the RX560 is exactly twice as fast as the RX550 at **everything**.  Kinda seems like the RX550 is a cut down RX560, but ironically the RX560s are usually found with half the RAM of an RX550.

**Comment by shitwolfymakes** [comment]
Production process are such that lower quality silicon in batches of chips have cores disabled and then are binned as a lower-tier SKU in the product stack. 

Thanks for solving this for me! If it's this unstable/much of a pain to get headless working on Ubuntu Server, it's probably best if we just drop that support. One less thing to worry about.

**Comment by drwonky** [comment]
FWIW, I'm seeing around 220-270fps aggregate with the RX560 across 3 encodes.  This same card topped at 400fps, usually in the 250-300fps in Windows.  It seems that the AMF support under Linux is slower.  I put the RX550 back in the Windows box and I'm seeing 200-250fps during encoding.  Before it was ~125fps in Linux.  So the "Linux" penalty seems to be anywhere from 25-50% over Windows.

AFA removing support, well VCE is part of the "thar be dragons" part of ARM install, so it's not exactly "supported".  However this problem is centered firmly around AMD's drivers.  Even using the "pro" drivers results in all sorts of really goofy stuff.  Sadly, while VA-API seems to be "stable" and cross manufacturer, Handbrake decided against supporting it.

I can attest that VCE and NVENC under Windows work well, but QSV has issues due to pipeline starvation when you encounter a re-read on a disc.

**Comment by shitwolfymakes** [comment]
If you can write up a guide for this, I'd be happy to add it to the wiki

**Comment by drwonky** [comment]
I wasn't clear, so let me reiterate:  removing VCE from the "do it yourself" realm is a disservice IMO.  There *is* a breakpoint where hardware encoding is about useless as far as FPS is concerned, but from an efficient standpoint it's a big difference.

My GPU is consuming 13W peak during encoding, my CPU has a 93W TDP.  I can CPU encode at thermal limit around 180fps, the GPU is more efficient.

While I *can* notice a quality difference in the encoding, when watching on a 55" TV from 15 feet away, it's not enough to be annoying.  For me, having the chapters and subtitles is extremely important, something that downloaded rips often lack.

**Comment by shitwolfymakes** [comment]
Fair enough. Should I go ahead and close this then?

**Comment by drwonky** [comment]
> If you can write up a guide for this, I'd be happy to add it to the wiki

Yeah, let me sort some more stuff out and I'll fork/branch this and contribute some changes.  As for the Wiki, let me figure out the exact details of what is necessary to make it work every time.  I think it should be possible to automate the "bootstrap" process so Vulkan/AMF is initialized at bootup.

**Comment by drwonky** [comment]
> Fair enough. Should I go ahead and close this then?

Let me submit a PR to resolve this, then close it as part of that :grin:

**Comment by 1337-server** [comment]
Closing as stale
