### ISSUE TITLE
Instead of using HandBrakeCLI profiles, use a custom command line

### ISSUE THREAD

**Issue by koalix** [automatic-ripping-machine/automatic-ripping-machine#56]
The default profiles are very limited and HandBrakeCLI have problems to use custom profiles. I use a custom line to encode my data and I would love to have an option to cast the options that I want to use to encode my files instead of using default profiles

For reference, these are my parameters:

HandBrakeCLI -i /file/input.mp4 -o /file/out.mp4 -E fdk_faac -B 96k -6 stereo -R 44.1 -e x264 -q 27 -x cabac=1:ref=5:analyse=0x133:me=umh:subme=9:chroma-me=1:deadzone-inter=21:deadzone-intra=11:b-adapt=2:rc-lookahead=60:vbv-maxrate=10000:vbv-bufsize=10000:qpmax=69:bframes=5:b-adapt=2:direct=auto:crf-max=51:weightp=2:merange=24:chroma-qp-offset=-1:sync-lookahead=2:psy-rd=1.00,0.15:trellis=2:min-keyint=23:partitions=all

**Comment by jswetzen** [comment]
I think I've solved this in the commit above, maybe you can try it? Just leave $HB_PRESET empty in your config and put your custom parameters in $HB_ARGS. If it works I'll make a pull request.
You can get the fixed video_transcode.sh at https://raw.githubusercontent.com/jswetzen/automatic-ripping-machine/master/video_transcode.sh
