### ISSUE TITLE
Movie titles are truncated when they contain an ampersand `&`

### ISSUE THREAD

**Issue by drwonky** [automatic-ripping-machine/automatic-ripping-machine#560]
- [X ] I have checked the wiki
- [X ] I have searched for similar issues

**Describe the bug**
Movie titles such as `Me, Myself & Irene` are truncated at the ampersand.

**To Reproduce**
1. Rip a movie with an ampersand in the title
![image](https://user-images.githubusercontent.com/35117150/187523611-776637d5-5ccf-4556-b494-daeb4040551b.png)

I think replacing the ampersand with the word `and` (lower case) would suffice to sanitize this.

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Ubuntu 20.04
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
v2_master a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Tested and confirmed for all current versions

**Comment by 1337-server** [comment]
Was a database issue from the remote database (https://1337server.pythonanywhere.com/)

Should be fixed now. Let me know if not and ill reopen.
