### ISSUE TITLE
Add graphical indicators to upper right of UI page to show last status of device

### ISSUE THREAD

**Issue by drwonky** [automatic-ripping-machine/automatic-ripping-machine#561]
**Is your feature request related to a problem? Please describe.**
I have to inspect the history page after each rip to determine if the rip was successful, thus directing my remediation process for bad rips.

**Describe the solution you'd like**
I would like an icon indicator for each ROM device showing the last status of the device

**Describe alternatives you've considered**
The current workaround is to inspect history, then inspect the logs to find out if the failure was due to:
- Database was locked (eject and re-insert)
- Read error (attempt in good BDROM drive or put in polishing queue)
- MAINFEATURE was not detected (rip in another machine using Handbrake directly)

This does not resolve short rips caused by `libdvdread: Zero check failed in src/ifo_read.c:570`

**Are you able to help code/implement this feature ?**
Yes

**Additional context**
The list of states to consider are:
- Good rip (green checkmark)
- Bad rip
  - Database locked (Blue crossing arrows)
  - Read failure (red X)
  - MAINFEATURE not detected (Yellow hourglass)

Those are just some suggested icons, however the MAINFEATURE errors might be better as a yellow exclamation instead of hourglass.

**Comment by microtechno9000** [comment]
hey, the current PR I need to fix has some of the desired functionality. From the setting page it reports current and previous rips against a drive.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/551
