### ISSUE TITLE
Issue to discuss `libdvdread: Zero check failed in src/ifo_read.c:570`

### ISSUE THREAD

**Issue by drwonky** [automatic-ripping-machine/automatic-ripping-machine#563]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
This isn't a bug per-se, but I felt it was important to start a discussion about the error `libdvdread: Zero check failed in src/ifo_read.c:570`.

I'm in the process of ripping ~1300 movies right now (Craigslist find) and have encountered a number of undamaged discs which exhibit a "short rip" behavior where Handbrake reports everything is fine, but emits an error like `Zero check failed`.

Attempts to rip the movie using ghb result in the same outcome, so it's not a disc, drive, or software issue.

The workaround I've been using to complete these rips is to use MakeMKV to copy the main feature track to an MKV file then using Handbrake to transcode these to the final desired format.

All of these rips are less than 10KB in size, but report a successful exit from Handbrake, so it should be possible to detect and mitigate these failures:
- Is MAINFEATURE True?
  - Was the main feature less than 10KB in size?
  - Did Handbrake return exit code 0?
    - Fall back to using MakeMKV pipeline to rip movie and send to transcoding

**To Reproduce**
Steps to reproduce the behavior, here are the movies I've confirmed this on:
1. Blades of Glory WS DVD
2. Disaster Movie FF DVD
3. The Golden Compass FF DVD
4. Bewitched Special Edition WS DVD
5. Good Luck Chuck FF DVD
6. Employee of the Month WS DVD

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Can you attach the logs from these rips ?

**Comment by shitwolfymakes** [comment]
Closing due to lack of response.
