### ISSUE TITLE
docker install fails to mount

### ISSUE THREAD

**Issue by joelishness** [automatic-ripping-machine/automatic-ripping-machine#564]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Error during docker-setup.sp

From terminal:
...
Digest: sha256:9b64344942100be03900df43490224d065b14724ac7d272305619038cae24757
Status: Downloaded newer image for automaticrippingmachine/automatic-ripping-machine:latest
docker.io/automaticrippingmachine/automatic-ripping-machine:latest
Creating mount points
mkdir: cannot create directory ‘/mnt/dev’: Permission denied

Manually executing results in the same:
sudo -u arm mkdir -p /mnt/dev/sr0
mkdir: cannot create directory ‘/mnt/dev’: Permission denied

**To Reproduce**
1. Fresh install of Ubuntu Desktop 22.04
2. Follow the wiki until:
3. sudo ./docker-setup.sh

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
Attempting latest Docker as of 8/31/2022

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]
n/a

**Comment by shitwolfymakes** [comment]
Closed by #565
