### ISSUE TITLE
docker Blu Ray fails

### ISSUE THREAD

**Issue by joelishness** [automatic-ripping-machine/automatic-ripping-machine#567]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
ARM installed via docker does not rip Blu Ray.
makemkv is missing from the logs

**To Reproduce**
1. Fresh install Ubuntu 22.04 desktop minimal non-free
2. Install ARM via docker (wiki)
3. Insert Blu Ray

### Environment
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

automaticrippingmachine/automatic-ripping-machine:latest created 9/1/2022

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG F
[SPIDER-MAN_HOMECOMING_166208323428.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9486752/SPIDER-MAN_HOMECOMING_166208323428.log)
ILE HERE <<<<<]

**Comment by shitwolfymakes** [comment]
Reading through the log https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/2aa364e4ae0643c1310d1e439ac0363204859ab7/arm/ripper/arm_ripper.py#L174 returned false, leading it to skip the rip and go straight to transcoding. It likely broke there because the file it was trying to transcode didn't exist. 

Please attach a copy of your current `arm.yaml` so we can determine which combination of your settings resulted in the call returning false

**Comment by joelishness** [comment]
arm.yaml attached
[arm.tar.gz](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9492376/arm.tar.gz)
I believe the only change I made was to the OMDB_API_KEY, the rest should be default.

I changed RIPMETHOD: from "backup" to "mkv", and previously known-good Blu Ray is ripping now.

This seems effective, but I would like to understand why this works as a solution.
In particular, was the behavior changed?
Reason #1: My previous bare-metal install of ARM (known-good rip state) was set to "backup" and it successfully ripped. So why now do I have to change it to "mkv" for the same disc?

Reason #2: The RIPMETHOD description seems to say not to use mkv method for Blu Ray?
Excerpt with bold added by me:

> Method of MakeMKV to use for Blu Ray discs.  Options are "mkv" or "backup".
> 
> **backup decrypts the dvd** and then copies it to the hard drive.  This allows HandBrake to apply some of it's
> analytical abilities such as the main-feature identification.  This method seems to offer success on **bluray 
> discs that fail in "mkv" mode**. *** NOTE: **MakeMKV only supports the backup method on BluRay discs**.  ARM does
> not use MakeMKV for DVDs. 

Am I misreading this description?

**Comment by joelishness** [comment]
The makemkv.py makemkv function seems to expect Blu Rays for backup method:
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/2aa364e4ae0643c1310d1e439ac0363204859ab7/arm/ripper/makemkv.py#L54-L58

Is it intentional that arm_ripper.py skips calling makemkv for "backup" method?

**Comment by shitwolfymakes** [comment]
The truth tables for arm to decide what to do are an absolute mess at the moment. I'm working on fixing that, but as for this specific combination, I couldn't tell you.

**Comment by shitwolfymakes** [comment]
Should be fixed with #577
