### ISSUE TITLE
Docker: Files only found in /var/lib/docker/volumes/

### ISSUE THREAD

**Issue by johndoc** [automatic-ripping-machine/automatic-ripping-machine#569]
- [ Y] I have checked the wiki
- [Y ] I have searched for similar issues

**Describe the bug**
Once ripping has completed the files are not in /home/arm/ they are in /var/lib/docker/volumes/../../..
When searching the entire system this is the only place the files exist.

This is my first time submitting an issue on github. If you have direction on how I could have done this better please let me know.

**To Reproduce**
1. Install Docker app
2. Insert Disc

### Environment
Debian 11
Current Docker

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE 
[FIREFLY_D1_166243233905.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9497717/FIREFLY_D1_166243233905.log)
HERE <<<<<]

**Comment by 1337-server** [comment]
Can you share the docker run command you used ?

**Comment by johndoc** [comment]
I see in the wiki what happened. I tried to change the path in the yaml. I see where it needs to be changed in the container. I removed the container and tried again. It's working perfect now.

**Comment by 1337-server** [comment]
Glad this is fixed!
