### ISSUE TITLE
Ubuntu 20.04 armui.py: No such file or directory: '/etc/arm/config/abcde.conf'

### ISSUE THREAD

**Issue by thurstylark** [automatic-ripping-machine/automatic-ripping-machine#575]
After a fresh install of Ubuntu 20.04, and using the automatic installation script, I wasn't able to get to the setup ui. I didn't see any errors in the install script output, but I did see a reference to armui.service getting enabled...

`systemctl status armui` returned the following:

````
● armui.service - Arm service
     Loaded: loaded (/etc/systemd/system/armui.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2022-09-11 09:12:47 UTC; 1s ago
    Process: 5250 ExecStartPre=/bin/bash -xc /usr/bin/systemctl is-active --quiet armui.service && exit 1 || exit 0 (code=exited, status=0/SUCCESS)
    Process: 5252 ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py (code=exited, status=1/FAILURE)
   Main PID: 5252 (code=exited, status=1/FAILURE)
````

I wasn't able to find any logs that were relevant, so I tried running the ExecStart line as the armui user manually using `sudo -u arm /usr/bin/python3 /opt/arm/arm/runui.py`, which returned:

````
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 1, in <module>
    import arm.config
  File "/opt/arm/arm/../arm/config/__init__.py", line 1, in <module>
    from . import config  # noqa: F401
  File "/opt/arm/arm/../arm/config/config.py", line 20, in <module>
    with open(abcde_config_path, "r") as abcde_read_file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/arm/config/abcde.conf'
````

I wasn't able to find any guidance in the wiki or any related issues. Where should I go from here?

**Comment by shitwolfymakes** [comment]
Which branch did you download? At the moment there is a difference between branches using `.abcde.conf and abcde.conf`

**Comment by thurstylark** [comment]
I'm not sure how to tell. I just followed the instructions [here](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Ubuntu-20.04-Automatic-Installation) and let the script do everything.

**Comment by shitwolfymakes** [comment]
Mmkay. For the time being, copy `/opt/arm/setup/.abcde.conf`to `/etc/config/.abcde.conf` that should get everything working

**Comment by thurstylark** [comment]
That didn't work, but copying `/opt/arm/setup/.abcde.conf` to `/etc/arm/config/abcde.conf` did get me into the gui.

**Comment by shitwolfymakes** [comment]
Awesome! I'll make a note to fix that
