### ISSUE TITLE
Adding repo "ppa:stebbins/handbrake-releases" fails - Ubuntu manual install

### ISSUE THREAD

**Issue by networkfilth** [automatic-ripping-machine/automatic-ripping-machine#576]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**:
Following the manual Ubuntu install guide - adding repo "ppa:stebbins/handbrake-releases" fails.

**To Reproduce**:
"sudo add-apt-repository ppa:stebbins/handbrake-releases" produces the following error:

tag:launchpad.net:2008:redacted
More info: https://launchpad.net/~stebbins/+archive/ubuntu/handbrake-releases
'Error reading https://launchpad.net/api/devel/~stebbins/+archive/ubuntu/handbrake-releases?ws.op=getSigningKeyData (4 tries): Unauthorized'

### Environment
Ubuntu 20.04.5 LTS
ARM v2 Master Release

**Comment by shitwolfymakes** [comment]
Documentation updated, good work!
