### ISSUE TITLE
a.r.m. docker-compose 

### ISSUE THREAD

**Issue by jaud7of8** [automatic-ripping-machine/automatic-ripping-machine#579]
- [x ] I have checked the wiki
- [x ] I have searched for similar issues

docker-compose for a.r.m.

Wanted to share getting a.r.m. working with docker-compose.
Following [Dotheevo](https://github.com/DoTheEvo/selfhosted-apps-docker) taught me how to setup and run many services on my computers.  With a.r.m. being able to be dockerized I wanted to use docker-compose.

With the help of [www.composerize.com](https://www.composerize.com/) and what I have learned along the way, I was able to get a.r.m. working with docker-compose.
YMMV (your mileage may vary), I know enjoy to be dangerous, using this you accept responsibility for everything that happens...
With that out of the way, below is a (working on my system) docker-compose.yml for a.r.m.

I used the manual build method for this.  I also setup the linux mint 20.04 computer with the username of arm.
Neither docker or docker-compose would work with  privileged: true, it is commented out.  I would get the error unable to mount /dev/sr0

Docker Compose version v2.11.1
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.3
DISTRIB_CODENAME=una
DISTRIB_DESCRIPTION="Linux Mint 20.3 Una"
git branch
* main

version: '3.3'
services:
    automatic-ripping-machine:
        ports:
            - '8080:8080'
        volumes:
            - '/home/arm:/home/arm'
            - '/home/arm/music:/home/arm/Music'
            - '/home/arm/logs:/home/arm/logs'
            - '/home/arm/media:/home/arm/media'
            - '/home/arm/docker/arm/config:/etc/arm/config'
        devices:
            - '/dev/sr0:/dev/sr0'
            - '/dev/sg0:/dev/sg0'
            - '/dev/sr1:/dev/sr1'
        restart: always
        container_name: automatic-ripping-machine
        image: automatic-ripping-machine

**Comment by shitwolfymakes** [comment]
ARM does not support Linux Mint, and I can't understand what you're trying to do here so I'm closing this for the time being. 

If you go back and edit for clarity, and include logs of successful test runs with your setup, feel free to open a new Issue or Pull Request!
