### ISSUE TITLE
Update Openmediavault Install instruction to include python3-libdiscid

### ISSUE THREAD

**Issue by jeanpaulrh** [automatic-ripping-machine/automatic-ripping-machine#584]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
I followed the instruction for openmediavault install but on first run no web server was listening,
In my daemon.log file I found an error complaining about a missing libsdiscid.so.0 so I installed it using 
`sudo apt install python3-libdiscid`
And the web server went up ok.

### Environment
Openmediavault 6
latest available today 09/30/22

**Comment by shitwolfymakes** [comment]
Was this related to the manual installation instructions or the OMV installation script?

**Comment by shitwolfymakes** [comment]
Correct, thanks for your help!
