### ISSUE TITLE
Ubuntu 20.04 Automatic Script Install Error

### ISSUE THREAD

**Issue by lemlemnet** [automatic-ripping-machine/automatic-ripping-machine#586]
-I have checked the wiki
-I have searched for similar issues

Bug Description:
After running the script, it gives me this error message:

E: The repository 'https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

To Reproduce:
1. Follow this wiki: https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Ubuntu-20.04-Automatic-Installation
2. Run the script
3. Wait until it gives you the error message

Environment:
Ubuntu 22.04 Desktop in a VM running on Truenas Scale.

Note:
I am a beginner when it comes to Linux, Github and this project, but i love the idea of this arm and would like to run it myself. I spend several hours and multiple attempts/VMs trying to get this to work, but i haven't found a solution yet. Thanks in advance for your help!

**Comment by shitwolfymakes** [comment]
I'll check this out when I have time. In the meantime, try commenting out that line in the script and re-running

**Comment by csepulv** [comment]
FWIW, I had this same error and then I realized I installed wrong version of Ubuntu. I had installed 22.04 

I then corrected my error and installed 20.04 and the install script worked. I don't know if this is the OP's error, but I figured I would share my mishap in case it helped.

**Comment by lemlemnet** [comment]
> I had installed 22.04

Oh, i just noticed that I installed 22.04 too. But how do i get 20.04? I was only able to find 22.04 on the official website.

**Comment by lemlemnet** [comment]
> I installed wrong version of Ubuntu. I had installed 22.04

I just noticed that I have accidentally installed 22.04 instead of 20.04 too. Thank you for the advice! I will try the installl with [this](https://releases.ubuntu.com/20.04/) version.

**Comment by csepulv** [comment]
I will note I had to run the install script twice. It failed the first time because `curl` is not on the box. I installed curl and re-ran and it worked.

you might do `sudo apt install curl` before running the installer.

After the installer ran, I had to follow the instructions in this [issue](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/587)

**Comment by shitwolfymakes** [comment]
Glad to hear! I'll add a curl install command to the script later today

Closing this issue.
