### ISSUE TITLE
Album Art Embed fails due to being placed in the wrong location.

### ISSUE THREAD

**Issue by Cleanup-Crew-From-Discord** [automatic-ripping-machine/automatic-ripping-machine#588]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
The album art is successfully downloaded, but it is placed in the root of the mp3 folder and not in the album's subfolder. Then, when it comes time to embed the album art, it is obviously missing and fails, but reports a success for some reason.

Noteworthy lines from the log include:
```
46: copying cover to target directory /media/secondary/cdr/mp3
47: copying cover to target directory /media/secondary/cdr/flac
```
i store my music at /media/secondary/cdr/***/album-name/ and previously it would move to these locations properly, but now it just drops them in the wrong location.
```
105: mkdir: cannot create directory ‘/media/secondary/cdr/mp3/albumart_backup’: File exists
106: Successfully embedded the album art into your mp3 tracks
```
it is still trying to create a directory for them in the incorrect location. it somehow reports a success but there just isn't any album art in the mp3.

**To Reproduce**
Just insert a music CD, i changed nothing and it happened after I did not use the ripper for a week or so. It was working completely fine for months previously.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<
[Poison-Every Rose Has Its Thorn.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9750610/Poison-Every.Rose.Has.Its.Thorn.log)
<<]

**Comment by microtechno9000** [comment]
Can you post your abcde config, as it looks like this is a setting or configuration being passed to Musicbrainz

**Comment by Cleanup-Crew-From-Discord** [comment]
> Can you post your abcde config, as it looks like this is a setting or configuration being passed to Musicbrainz

sorry, i forgot this even existed after "fixing" it ~3 days later. the issue was in this line:
```
OUTPUTFORMAT='${OUTPUT}/${ARTISTFILE}-${ALBUMFILE}/${TRACKFILE}'
```
for some odd reason, removing the tracknum tag from the original line:
```
OUTPUTFORMAT='${OUTPUT}/${ARTISTFILE}-${ALBUMFILE}/${TRACKNUM}.${TRACKFILE}'
```
was enough to make abcde absolutely lose it. replacing the tracknum tag set it back to normal. 

I just decided to deal with having the tracknum in the file name; i never notice it as the player just draws from the metadata. this isn't really a real fix, but ive at least found where things started to go wrong. Here's the whole conf file:

[abcde.conf.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10302252/abcde.conf.txt)

**Comment by microtechno9000** [comment]
Closing this issue as stale and on review is due to user settings within the abcde configuration

If this issue is still present and not due to the abcde configuration please re-open with additional information
