### ISSUE TITLE
Web UI does not start; Cannot verify if ARM is fully installed.

### ISSUE THREAD

**Issue by J-Farmer** [automatic-ripping-machine/automatic-ripping-machine#592]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
The UI never launches once ARM is installed. Running the runui.py file manually errors out on both Ubuntu Desktop and Server.

**To Reproduce**
1. Install based on automatic setup in wiki. ARM user is set up at install time.

2. Ui never launches. systemctl status armui.service shows the following: Process: 53440 ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py (code=exited, status=1/FAILURE)

3. Running the runui.py file at /opt/arm/arm errors out with: 
 ```
./runui.py: 1: Main run page for armui: not found
import-im6.q16: attempt to perform an operation not allowed by the security policy \`PS' @ error/constitute.c/IsCoderAuthorized/408.
import-im6.q16: attempt to perform an operation not allowed by the security policy \`PS' @ error/constitute.c/IsCoderAuthorized/408.
./runui.py: 6: Syntax error: word unexpected (expecting ")")
```

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
This should be running the latest release based on the instructions in the wiki.

I had this working in a VM on Proxmox, and was attempting to set it up on bare metal so I could have access to more DVD drives at once. I did run into some similar issues starting this on Proxmox, but despite errors, the web ui would start and I could rip movies. I can't on a dedicated machine.

**Comment by J-Farmer** [comment]
One correction from my post: I set up the arm user when installing the OS, not at arm install time.

**Comment by shitwolfymakes** [comment]
I would recommend trying to reinstall ARM, which simply requires running the script again. I've never seen this issue before. I have no idea why an ImageMagick error is occurring, as this project does not have it in the dependencies.

Also, it would be helpful if you could fix the error log, please put all relevant text into a \`\`\`...\`\`\` code block (you may need to escape some tilda's to make it work)

Two questions:
1. Was Firefox already running in the VM when you ran the installer script
2. Did you do anything other than create a default installation with the `arm` user?

Also there appears to have been a modification to the runui.py file. `./runui.py: 6: Syntax error: word unexpected (expecting ")")` should not occur, as the release code contains all the correct parentheses.

**Comment by kiteless** [comment]
Affected by this as well. Followed ubuntu directions, no Web UI. No logs generated, I don't know how to start debugging this issue. I've tried reinstalling, tried the docker version, no luck.

**Comment by shitwolfymakes** [comment]
@kiteless @J-Farmer Did y'all have firefox open when you ran the installer? The installer can't open up to the proper address if firefox is already running. 

Please confirm that <ip_address>:8080 does not resolve to the local instance of ARMui, and post the results of running `sudo systemctl status armui`

**Comment by J-Farmer** [comment]
@shitwolfymakes, I don't recall if Firefox was open or not. I'll do a fresh install and repeat the steps to reproduce again tomorrow evening. I was eventually able to get it up and running after linking abcde.conf like the issue in #587. I linked that file, rebooted a few times, and it eventually came up. 

I'll do some digging and pipe the entire output of the installer to a file tomorrow, as well as any commands that lead to issues. 

As far as the armui status, the output of it is included in the main bug post. That's what I got immediately after installing it.

**Comment by shitwolfymakes** [comment]
Sounds good. I still have know idea why the hell imagemagick would be causing issues, that makes literally no sense to me

**Comment by J-Farmer** [comment]
https://controlc.com/37cfbefd

Looks like the issue is the same as #587. abcde.conf is not being copied or linked to /etc/arm/config/abcde.conf. The runui.py file is failing because of that according to the Ubuntu error report box that popped up.

**Comment by shitwolfymakes** [comment]
Ah, this is due to the project reorganization that hasn't been merged from `v2_devel` into `v2_master` yet. Manually correcting should fix things in the meantime

**Comment by shitwolfymakes** [comment]
This has been fixed
