### ISSUE TITLE
ARM Will not RIP Disk or create log file - Error

### ISSUE THREAD

**Issue by poppab** [automatic-ripping-machine/automatic-ripping-machine#596]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
When I insert disk log created but nothing else happens

**To Reproduce**
1. Insert Disk

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"]
ARM v 2.6.0 

### Log file
No Log file create

I got this from /var/mail/arm file:
```
Subject: Output from your job       89
To: arm@arm
Message-Id: <20221022215238.3DF3616E00AD@arm>
Date: Sat, 22 Oct 2022 17:52:38 -0400 (EDT)
From: rick <arm@arm>

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 443, in <module>
    running_jobs = db.session.query(Job).filter(Job.status.notin_(['fail', 'success']), Job.devpath == devpath).all()
  File "<string>", line 2, in query
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.
```
This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**Comment by kiteless** [comment]
I'm affected by this as well, on Ubuntu 20.04. Nothing in empty.log, and the 3 logs created for the DVD inserted are empty:

```
user@server:/home/arm/logs$ sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 443, in <module>
    running_jobs = db.session.query(Job).filter(Job.status.notin_(['fail', 'success']), Job.devpath == devpath).all()
  File "<string>", line 2, in query
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
    return self.registry()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/_collections.py", line 1006, in __call__
    key = self.scopefunc()
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
user@server:/home/arm/logs$ 
```

**Comment by shitwolfymakes** [comment]
@theRealBassist 
ARM does not support Ubuntu 22.04, as there were breaking changes introduced by 22.04 that we haven't been able to address yet, so you will need to switch anyway.

@kiteless can you post the results of running `sudo systemctl status armui`? It seems like ripper can't find the UI.

**Comment by theRealBassist** [comment]
> @theRealBassist
ARM does not support Ubuntu 22.04, as there were breaking changes introduced by 22.04 that we haven't been able to address yet, so you will need to switch anyway.

That sounds about right. Well I will take care of that this weekend then! Appreciate the info.

**Comment by shitwolfymakes** [comment]
Yep! Sorry for the confusion, we do need to formalize the list of supported OSs. I figured the file name would be enough but it's easy to misread the numbers.

If downgrading fixes the problem, please let us know and close this issue.

**Comment by theRealBassist** [comment]
@shitwolfymakes 

Alright, so I've downgraded to Ubuntu 20.04.5 LTS, and I am having the same issue. However, I now no longer get an empty.log file at all, but the disc specific log files are still generated and still empty (of information). I have also run `sudo systemctl status armui` and it returned (I have removed my namefrom the message):

`● armui.service - Arm service
     Loaded: loaded (/etc/systemd/system/armui.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-10-26 22:10:45 UTC; 6min ago
   Main PID: 23865 (python3)
      Tasks: 3 (limit: 9331)
     Memory: 118.4M
     CGroup: /system.slice/armui.service
             ├─23865 /usr/bin/python3 /opt/arm/arm/runui.py
             └─23881 /usr/bin/python3 /opt/arm/arm/runui.py

Oct 26 22:16:53 user-arm python3[23881]: [2022-10-26 22:16:53,108] DEBUG in routes: joblist
Oct 26 22:16:53 user-arm python3[23881]: 192.168.0.171 - - [26/Oct/2022 22:16:53] "GET /json?mode=joblist HTTP/1.1" >
Oct 26 22:16:58 user-arm python3[23881]: [2022-10-26 22:16:58,113] DEBUG in routes: joblist
Oct 26 22:16:58 user-arm python3[23881]: 192.168.0.171 - - [26/Oct/2022 22:16:58] "GET /json?mode=joblist HTTP/1.1" >
Oct 26 22:17:03 user-arm python3[23881]: [2022-10-26 22:17:03,114] DEBUG in routes: joblist
Oct 26 22:17:03 user-arm python3[23881]: 192.168.0.171 - - [26/Oct/2022 22:17:03] "GET /json?mode=joblist HTTP/1.1" >
Oct 26 22:17:08 user-arm python3[23881]: [2022-10-26 22:17:08,119] DEBUG in routes: joblist
Oct 26 22:17:08 user-arm python3[23881]: 192.168.0.171 - - [26/Oct/2022 22:17:08] "GET /json?mode=joblist HTTP/1.1" >
Oct 26 22:17:13 user-arm python3[23881]: [2022-10-26 22:17:13,122] DEBUG in routes: joblist
Oct 26 22:17:13 user-arm python3[23881]: 192.168.0.171 - - [26/Oct/2022 22:17:13] "GET /json?mode=joblist HTTP/1.1" >
`


Please let me know if there is any additional information or files that I can provide!

**Comment by poppab** [comment]
I was using 22.04 perfectly fine until it went into "emergency" which I tried in vain to fix. When I did the fresh install of 22.04 that is when this issue started.

**Comment by shitwolfymakes** [comment]
@poppab As mentioned previously, 22.04 is not supported and ARM is known to not work on it. Please reimage using 20.04 and try it.

@theRealBassist Please attach some of the disk logs if they are available.

Also, if you are using the automated installer and are not installing from `v2_devel` see #587 and #592. We reorganized the directory structure and the automated install currently only works for installing `v2_devel`. However, we are close to a release that will unify the file structure across both branches.

**Comment by theRealBassist** [comment]
@shitwolfymakes 

By disk logs are you referring to the ones generated when the disk is read, or some other logs.

I followed the installation instructions at [here](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Setting-up-ARM-manually-(Ubuntu))

**Comment by macklenc** [comment]
I had the same problem with the  `RuntimeError: Working outside of application context.` trying to run on Manjaro. After reading:

> Okay. The manual installation instructions are out of date as well. Please use the automated installer, and refer to the linked issues to make sure everything is working properly. I'll update the wiki once I have some time to do so.

I loosely followed the install script, and it seems that something in there fixed my problem. I suspect the solution was in switching from the main branch to `v2.6.7` since the OS distribution shouldn't affect the Flask context IMHO.

**Comment by theRealBassist** [comment]
Alright my issue seems to be resolved by completing the following steps:

1. Installed Ubuntu Server 20.04.5 LTS
2. Used the "Setup 'arm' user and ubuntu basics" & "Set up repos and install dependencies" steps of [Setting up ARM manually (Ubuntu)](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Setting-up-ARM-manually-(Ubuntu))
3. Added 'arm' as a sudoer `usermod -aG sudo arm`
4. Changed to the `arm` user `su - arm`
5. Used the "Prepare Ubuntu" & "Install ARM" steps of [Ubuntu 20.04 Automatic Installation](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Ubuntu-20.04-Automatic-Installation)
6. Changed to my main user `su - USERNAME`
7. Ran the fix found in Issue #587 `ln -s /etc/.abcde.conf /etc/arm/config/abcde.conf`
8. Rebooted `sudo reboot`
9. Waited about a minute
10. Opened a web browser on another network device and went to `[Your IP]:8080`
11. Logged in with the Username: `admin` & Password: `password` (using `arm` for both entries will not work)
12. Put a disk in the tray.

Everything seems to be working fine!

**Comment by shitwolfymakes** [comment]
Glad to hear! I'm gonna leave these issues open until the next update when the new file tree will be unified

**Comment by jmerdich** [comment]
For what it's worth, I traced this back to a too-new version of flask_sqlalchemy on my machine (was 3.0.2, 2.5.1 worked). A lot of other functionality like the 'database' page would crash the server due to breaking changes from the new major version.

If you're hitting this, try `pip install flask_sqlalchemy==2.5.1`.

**Comment by shitwolfymakes** [comment]
Interesting. Thanks for running that down for us!

**Comment by 1337-server** [comment]
This should get fixed when we merge v2_devel into v2_master, but ill leave this open until then, as It's still a possible issue.

Thanks for your help!

**Comment by 1337-server** [comment]
Should now be Fixed
