### ISSUE TITLE
Sed Syntax bug in docker setup script

### ISSUE THREAD

**Issue by Zackptg5** [automatic-ripping-machine/automatic-ripping-machine#598]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
[On line 82 of the docker setup script](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/v2_devel/scripts/installers/docker-setup.sh#L82), the sed statement uses forward slashes as the delimited which will throw errors when any path is filled in by the variable (which also contains forwards slashes). 

** Fix **
Use a different delimiter such as '|'

**To Reproduce**
1. Run the script

### Environment
Ubuntu Server LTS 22.04

**Comment by shitwolfymakes** [comment]
ARM does not support Ubuntu 22.04 (Desktop or Server) for the moment, though we will keep an eye on this. 

If you find that the bug repeats when executing this script on Ubuntu *Desktop* 20.04, please reopen this issue.
