### ISSUE TITLE
Allow file names to include colons

### ISSUE THREAD

**Issue by TastyPi** [automatic-ripping-machine/automatic-ripping-machine#601]
**Is your feature request related to a problem? Please describe.**

I prefer my files to include colons. I know that not all filesystems support colons in file names, but the ones I use do.

**Describe the solution you'd like**

Maybe a config option, e.g. `COLON_REPLACEMENT`, which can be set to the string colons should be replaced with. Default would be `"-"`, to keep them as colons set it to `":"`.

**Describe alternatives you've considered**

- A `REPLACE_COLONS` boolean config option would also work, but the flexibility of the other options wouldn't be much more work.

- Don't replace colons - does not work for all filesystems, especially for Windows.

**Are you able to help code/implement this feature ?**

Yes

**Additional context**

None

**Comment by shitwolfymakes** [comment]
This will not be added, for the same reason you described, among others

The best way to address this would be for you to write a script to rename the files, and then add it to your crontab.
