### ISSUE TITLE
dashboard stops updating, refreshing page results in error

### ISSUE THREAD

**Issue by bjquinn** [automatic-ripping-machine/automatic-ripping-machine#605]
I have the latest version of ARM, installed via the automated install on Ubuntu 20.04.

When I insert a disc, it shows up on the "home" page, but then stops updating after a few seconds.  If I try to refresh the page, sometimes I get a 500 server error, and other times I get ASCII art saying the page doesn't exist yet and that there are too many open files.  Eventually, if I refresh a few more times, the home page comes up with the correct ripping status of the current DVD, and then stops updating again.

running ulimit -n 65535 as the arm user seems to fix it until reboot, which is good.  Should this be part of the auto installer, and what should we do to set it permanently?

update: spoke too soon.  seems to make it better, but does not fix it.

update: sometimes the error is "cannot open database file"

**Comment by shitwolfymakes** [comment]
Please submit issues using the Issue Template we have provided
