### ISSUE TITLE
WebUI doesn't open/work after script installation, armui service not running

### ISSUE THREAD

**Issue by domiflichi** [automatic-ripping-machine/automatic-ripping-machine#610]
- [X] I have checked the wiki
- [X] I have searched for similar issues (My problem seems to be similar to [Issue #592](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/592), but I'm getting different errors)

**Describe the bug**
The UI never launches once ARM is installed. Tried on both Ubuntu Server v20 (I understand there is no UI on Ubuntu Server, but I can't access the ARM's IP:8080 from a browser on another PC on the network) on a VirtualBox virtual machine AND Ubuntu Desktop v20 on bare metal.
When I run:
`systemctl status armui`
I get the following:
```
● armui.service - Arm service
     Loaded: loaded (/etc/systemd/system/armui.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-11-09 07:38:26 PST; 1s ago
    Process: 29407 ExecStartPre=/bin/bash -xc /usr/bin/systemctl is-active --quiet armui.service && exit 1 || exit 0 (c>
    Process: 29409 ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py (code=exited, status=1/FAILURE)
   Main PID: 29409 (code=exited, status=1/FAILURE)
```

If I try to run /opt/arm/arm/runui.py file manually on the Ubuntu Desktop (haven't tried on Server yet), I get:
```
./runui.py: line 1: Main run page for armui: command not found
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/359.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/359.
./runui.py: line 6: syntax error near unexpected token `os.path.join'
./runui.py: line 6: `sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))'
```

**To Reproduce**
1. Install Ubuntu Desktop v20.04.5 LTS, creating a user called arm at time of installation.
2. Followed instructions to install ARM found on the following page:
https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Ubuntu-20.04-Automatic-Installation
3. (Installed the 'ARM LIVE')

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
```

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
I'm just using the 'ubuntu-20.04-install.sh' script.

**Comment by shitwolfymakes** [comment]
Looks like a duplicate of #592 even though it's showing a different error. The root cause is described in #587. Please try following the fix described [here](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/587#issuecomment-1271027961) and report back

**Comment by domiflichi** [comment]
You are right! I ran that same command:
`ln -s /etc/.abcde.conf /etc/arm/config/abcde.conf`
Then rebooted. Then ran:
`systemctl status armui`
Looks like it's running!
Thank you! Sorry about not realizing it was not actually the same issue (I'm a bit of a Linux newb)

**Comment by mgruca** [comment]
guys, can you link to this issue (or one of the others) from wiki? I've done a couple of approaches to the ARM, and had a hard time running it. The instruction & script look solid and there are no open issues, so I've digged into it myself just to find this issue when I wanted to contribute.
