### ISSUE TITLE
Issues getting nvenc_h265 to show up on handbrake

### ISSUE THREAD

**Issue by Luckyday84** [automatic-ripping-machine/automatic-ripping-machine#613]
- [x] I have checked the wiki
- [x] I have searched for similar issues

So, I can get the ripper running in Ubuntu 20.04 server but no matter which NVidia drive I use Nvenc never shows as a opiton under HandBrakeCLI --help | grep -A12 "Select video encoder"

**To Reproduce**
1. Tried Ubuntu 20.04 Desktop with the same issues
2. Windows 10 on the same PC with handbrake picks up Nvenc so i know it works on this hardware

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
Arm version v2.6.0 Stable

HandBrakeCLI --help | grep -A12 "Select video encoder"
[04:03:29] hb_init: starting libhb thread
[04:03:29] thread 7f17b2ba3700 started ("libhb")
   -e, --encoder <string>  Select video encoder:
                               x264
                               x264_10bit
                               x265
                               x265_10bit
                               x265_12bit
                               mpeg4
                               mpeg2
                               VP8
                               VP9
                               theora
       --encoder-preset <string>

nvidia-smi
Sat Nov 12 04:03:54 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   45C    P8     5W / 120W |    123MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1370      G   /usr/lib/xorg/Xorg                 23MiB |
|    0   N/A  N/A     56875      G   /usr/lib/xorg/Xorg                 23MiB |
|    0   N/A  N/A     86539      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A     86805      G   /usr/bin/gnome-shell                3MiB |
+-----------------------------------------------------------------------------+

**Comment by shitwolfymakes** [comment]
I believe you will need to compile handbrake with NVENC support, as it is not included in the default distribution we use

**Comment by Luckyday84** [comment]
Okay thank you I will look into adding that. Just didn't know if that would break something.
