### ISSUE TITLE
Install issue - cannot use repo’s

### ISSUE THREAD

**Issue by kosielemmer** [automatic-ripping-machine/automatic-ripping-machine#620]
- [x] I have checked the wiki
- [x] I have searched for similar issues

On running the latest master environment, I get the following

E: The repository 'https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**To Reproduce**
1. run the download scripts
2. run install script
3

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10

* v2_master 

commit a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d (HEAD -> v2_master, origin/v2_master, origin/HEAD)
Author: 1337-server <sndspamfilter@gmail.com>

### Log file
don't get to do a rip as install doesn't finish

**Comment by kosielemmer** [comment]
Managed to fix this by using focal repo and then ensuring files like abcde.conf and all the folders in arm.yaml are available and open to arm user.  Also ran armuio.py manually and then an "if -i :8080".  Strange that nobody else had this issue.

**Comment by NotAMorningSpartan** [comment]
Encountering this issue as well. 

: The repository 'https://ppa.launchpadcontent.net/mc3man/focal6/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

? lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Comment by shitwolfymakes** [comment]
@kosielemmer @NotAMorningSpartan As is stated in the [wiki](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki#supported-operating-systems), Ubuntu 22.04 is **not** supported.
