### ISSUE TITLE
MakeMKV failed with code: 2 (DVD ejects a few minutes after insertion)

### ISSUE THREAD

**Issue by tamasgal** [automatic-ripping-machine/automatic-ripping-machine#626]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
I installed ARM via the `docker-setup.sh` script and followed the instructions to run the container with the provided script. It starts and I am able to interact with the web interface. When I insert a DVD, the job starts but after a few minutes, when the ripping process begins, the DVD makes some noises and then ejects the disk with the error below. I tried different DVDs but it's the same for each of them.

Any ideas?

**To Reproduce**
1. Follow docker installation instructions
2. Instert DVD

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")] Debian 11
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
"latest" Docker images: `automaticrippingmachine/automatic-ripping-machine   latest    cde3a25b2c07   5 weeks ago   1.59GB`

ARM Git version: 47b8e540b555e1cfc1287a5a49a4f032476bfa8d

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]
[ANGELS_SHARE.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10158584/ANGELS_SHARE.log)

**Comment by tamasgal** [comment]
So I got ARM working nicely with a manual install and then decided to change the ripping method from `backup` to `mkv` to see if it's faster (currently it takes 4 hours to rip a DVD) and then got the same error as with the Docker instance. I guess this is related to MakeMKV. Is a key needed in any case? I'll check that but maybe @thepandaman2000 you have the same issue.

The last part of the log with the error is here, again "code 2" (whatever that means):

```
[07-12-2022 15:04:38] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 213, in get_track_info
    mkv = subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r --progress=-stdout --messages=-stdout --cache=1 info disc:0
3;5GO"
' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 478, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 284, in main
    mkvoutpath = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 63, in makemkv
    get_track_info(mdisc, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 219, in get_track_info
    raise MakeMkvRuntimeError(mdisc_error)
  File "/opt/arm/arm/ripper/makemkv.py", line 24, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException
[07-12-2022 15:04:38] ERROR ARM: There are no service(s) to notify
```


Here is the full log:

[MACHOMAN.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10176764/MACHOMAN.log)

**Comment by tamasgal** [comment]
I debugged a bit further and hunted it down to a `Syntax error: Unterminated quoted string` from `/bash/sh`. Here is the output of the `makemkvcon` command (I truncated it a bit):

```
MSG:1005,0,1,"MakeMKV v1.17.2 linux(x64-release) started","%1 started","MakeMKV v1.17.2 linux(x64-release)"
PRGT:5018,0,"Scanning CD-ROM devices"
PRGC:5018,0,"Scanning CD-ROM devices"
PRGV:0,0,65536
PRGV:0,0,65536
PRGV:65536,0,65536
PRGV:65536,65536,65536
DRV:0,2,999,1,"DVD+R-DL HL-DT-ST DVDRAM GP08NU20 1.01 ;9:3;5GO","MACHOMAN","/dev/sr0"
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
...
...
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
PRGV:0,65536,65536
PRGV:0,0,65536
PRGT:3100,0,"Opening DVD disc"
MSG:3007,0,0,"Using direct disc access mode","Using direct disc access mode"
PRGC:3102,0,"Processing title sets"
PRGV:0,0,65536
PRGV:0,0,65536
PRGV:10922,0,65536
PRGV:10922,524,65536
...
...
PRGV:65536,2621,65536
PRGV:65536,3145,65536
PRGC:3120,1,"Scanning contents"
PRGV:0,3145,65536
PRGV:655,3145,65536
...
...
PRGV:65536,12582,65536
PRGV:65536,55574,65536
PRGC:3103,0,"Processing titles"
PRGV:0,55574,65536
MSG:3028,0,3,"Title #1 was added (13 cell(s), 1:21:41)","Title #%1 was added (%2 cell(s), %3)","1","13","1:21:41"
PRGV:5041,55574,65536
PRGV:5041,56098,65536
MSG:3025,0,3,"Title #2 has length of 1 seconds which is less than minimum title length of 120 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","2","1","120"
PRGV:10082,56098,65536
PRGV:10082,56623,65536
MSG:3025,0,3,"Title #3 has length of 2 seconds which is less than minimum title length of 120 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","3","2","120"
PRGV:15123,56623,65536
PRGV:15123,57147,65536
MSG:3025,0,3,"Title #4 has length of 14 seconds which is less than minimum title length of 120 seconds and was therefore skipped","Title #%1 has length of %2 seconds which is less than minimum title length of %3 seconds and was therefore skipped","4","14","120"
PRGV:20164,57147,65536
PRGV:20164,57671,65536
...
..
PRGV:65536,63963,65536
MSG:5011,0,0,"Operation successfully completed","Operation successfully completed"
TCOUNT:5
CINFO:1,6206,"DVD disc"
CINFO:2,0,"MACHOMAN"
...
...
...
SINFO:4,1,17,0,"48000"
SINFO:4,1,22,0,"0"
SINFO:4,1,30,0,"DD Stereo English"
SINFO:4,1,31,6121,"<b>Track information</b><br>"
SINFO:4,1,33,0,"90"
SINFO:4,1,38,0,"d"
SINFO:4,1,39,0,"Default"
SINFO:4,1,40,0,"stereo"
SINFO:4,1,42,5088,"( Lossless conversion )"
/bin/sh: 3: Syntax error: Unterminated quoted string
```

Now I need to understand where this comes from. Any hints are welcome 😉

**Comment by tamasgal** [comment]
OK got it, the "disc number" is wrongly determined, it's parsed as something which includes a quote. Not sure if this is due to some differences in `grep` or `makemkvcon` versions across systems:

![Screenshot 2022-12-07 at 15 47 28](https://user-images.githubusercontent.com/1730350/206210017-001cf007-7391-4f7c-8491-2d339235e7f6.png)

I'll try to figure out.

**Comment by tamasgal** [comment]
Sorry to ping you directly @1337-server but I am trying to understand the disc number determination login and you are the last person who touched that line, so I hope you can shed light on this https://github.com/automatic-ripping-machine/automatic-ripping-machine/blame/v2_master/arm/ripper/makemkv.py#L41

So in principle the following lines fail due to a wrong parsing:

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/a20f95ec9a73b3cb33457fcc2c2f0eadc4106f8d/arm/ripper/makemkv.py#L41-L49

I am not sure how the disc number should look like normally and I also could not find a DVD (I only tried a few) where the parsing works, but I assume this should work since everyone is happily converting 😉

One of the outputs of `makemkvcon -r info disc:9999` looks like this:

```
MSG:1005,0,1,"MakeMKV v1.17.2 linux(x64-release) started","%1 started","MakeMKV v1.17.2 linux(x64-release)"
DRV:0,2,999,1,"DVD+R-DL HL-DT-ST DVDRAM GP08NU20 1.01 ;9:3;5GO","MACHOMAN","/dev/sr0"
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:5010,0,0,"Failed to open disc","Failed to open disc"
TCOUNT:0
```

Now the question is: is the disc number the 4th number (1) in the line which contains `/dev/sr0`? The second question is: why does it not work for me, but for many other people out there. Is that a new version of MakeMKV which has a different output?

I am happy to provide a PR with a fix but I need more information.

**Comment by 1337-server** [comment]
It seems you are correct, and it seems that MakeMKV might have changed how they returned their data for the disc number and the parser is failing to properly catch the correct disc number.

The issue seems to stem from this
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/614268c59deb8feaa5ace4ef2848ed2ffb814d44/arm/ripper/makemkv.py#L42-L49

Which returns this as the variable mdisc
`disc number: 0
3;5GO"`

When it should return
`disc number: 0`

So we may need to add a regex at line 47 to remove anything with a whitespace

**Comment by 1337-server** [comment]
Just the disc number would be returned.

From an old log:
`[2019-01-25 20:37:45] INFO ARM: MakeMKV disc number: 0`

Looking for and splitting on whitespace should do it.

**Comment by tamasgal** [comment]
That's already the parsed output. I'd need the raw output from MakeMKV, see the quoted block above: https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/626#issuecomment-1341104657

**Comment by zeus86** [comment]
I've got a very similar issue (non-docker) with makemkv v1.17.2:
```
 LANG=c makemkvcon -r info disc:9999
MSG:1005,0,1,"MakeMKV v1.17.2 linux(x64-release) started","%1 started","MakeMKV v1.17.2 linux(x64-release)"
DRV:0,2,999,1,"BD-RE PIONEER BD-RW   BDR-XD07 1.03 ADDL010140WL","DVD4","/dev/sr0"
DRV:1,1,999,0,"DVD+R-DL HL-DT-ST DVDRAM GP60NB60 RF01 K0OM29B5528","","/dev/sr1"
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:5010,0,0,"Failed to open disc","Failed to open disc"
TCOUNT:0
```
(/dev/sr0 is the relevant drive here) The inserted dvd is from the german version from the full-dvd-set of the tv-show "ReGenesis" (DVD4 of Season1). The parser seems to crash, and sometimes (when eject got wrong somehow) leaving a zombie-process behind. Relevant log-lines:
```
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999  |grep /dev/sr0 |grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 478, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 284, in main
    mkvoutpath = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 49, in makemkv
    raise MakeMkvRuntimeError(mdisc_error)
  File "/opt/arm/arm/ripper/makemkv.py", line 24, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException
[20-01-2023 17:24:49] ERROR ARM: There are no service(s) to notify
```

**Comment by zeus86** [comment]
Maybe i should add:
* this only happens with "mkv" instead of "backup" as method. i wanted to try mkv, because it does not seem to be possible in MP4-Mode to rip all languages and all subtitles "as is" from aDVD with tv-show-series episodes without burning the first subtitle in. i need them to be optional, but i want to keep all of them.
* if i apply the above regex manually, it just matches a `0`

**Comment by zeus86** [comment]
i think, i nailed it down. My drive behaved in 10 times wildly inconsistent, but that's only half the story.

first of:  in `arm/arm/ripper/makemkv.py`, line 24, you should rasie the exception as 'BaseException`. After doing that, i finally figured out , what makemkv was trying to tell me: it was not finding a suitable device to read from. 

The reason for that is my usb-drive in itself. for some wild reason it is absurdly power-hungry, and depending on how you access the drive, it draws too much power while spinning up, resulting in a device reset from a low-power-condition. (which can be observed also in dmesg). In handbrake on backup-mode the drive is fine btw, but for some reasonwith makemkv the behaviour described above happens depending on the power-condition (this happens even on powered usb-3-hubs and as well on usb3-ports directly at the mainboard (not a notebook), so this thing (poineer BDR-XD07TB) is just power-hungry....

**Comment by 1337-server** [comment]
> i think, i nailed it down. My drive behaved in 10 times wildly inconsistent, but that's only half the story.
> 
> first of: in `arm/arm/ripper/makemkv.py`, line 24, you should rasie the exception as 'BaseException`. After doing that, i finally 

@shitwolfymakes Can you check this ? I've also seen this message about must be raised from base exception.

**Comment by shitwolfymakes** [comment]
I'll add this to #751
