### ISSUE TITLE
Install needs to create a log directory..

### ISSUE THREAD

**Issue by speedtoys** [automatic-ripping-machine/automatic-ripping-machine#631]
- [ X] I have checked the wiki
- [X ] I have searched for similar issues

**If you define a WebUI log in the service config file, the UI will not start**

If you define a log, such as:
[Unit]
Description=Arm service
## Added to force armui to wait for network
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
User=arm
Group=arm
## Remember to remove the # at the start of the line
StandardOutput=append:/home/arm/logs/WebUI.log <<---
StandardError=append:/home/arm/logs/WebUI.log  <<---
Restart=always
RestartSec=3
ExecStart=python3 /opt/arm/arm/runui.py
[Install]

The UI will not start

---
sudo systemctl status armui
● armui.service - Arm service
     Loaded: loaded (/etc/systemd/system/armui.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-12-14 18:38:16 PST; 1s ago
    Process: 14713 ExecStart=/usr/bin/python3 /opt/arm/arm/runui.py (code=exited, status=209/STDOUT)
   Main PID: 14713 (code=exited, status=209/STDOUT)
---

> mkdir /home/logs
> sudo chown arm:arm /home/logs

Fixed this...retarted service
---
sudo systemctl status armui
● armui.service - Arm service
     Loaded: loaded (/etc/systemd/system/armui.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-12-14 18:38:46 PST; 39s ago
   Main PID: 14734 (python3)
      Tasks: 3 (limit: 57616)
     Memory: 115.7M
     CGroup: /system.slice/armui.service
             ├─14734 /usr/bin/python3 /opt/arm/arm/runui.py
             └─14738 /usr/bin/python3 /opt/arm/arm/runui.py
___

]
### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Ubuntu 20.04

**Comment by vbdjames** [comment]
Ran into this same issue (as I think would anyone using the Ubuntu install script. Are you taking pull requests for this kind of thing?

**Comment by shitwolfymakes** [comment]
Fixed by #655
