### ISSUE TITLE
Hundreds of requests per second refreshing jobs

### ISSUE THREAD

**Issue by supercoffee** [automatic-ripping-machine/automatic-ripping-machine#636]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
From the home page of the UI (index.html), hundreds of requests per second are made to the backend to refresh the running jobs.  This can be easily observed by opening up the inspector tools in any browser and watching the network console.

<img width="741" alt="Screen Shot 2022-12-18 at 11 54 54 AM" src="https://user-images.githubusercontent.com/3880240/208316595-32b36fc6-06dd-462d-90df-5a3078ae4073.png">

**To Reproduce**
1. View ARM home page
2. Open network console
3. View flood of network request in Network tab

### Probably cause

`refreshJobs` is called on a configurable interval, but the default interval is set to 10, which is 10ms.  

```html

    <script type="application/javascript">
    $(document).ready(function () {
        const intervalId = window.setInterval(refreshJobs, {{ armui_cfg['index_refresh'] }});
    });

```

### Environment

**OS INFO**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

**ARM VERSION:**
commit 47b8e540b555e1cfc1287a5a49a4f032476bfa8d (HEAD, tag: v2.6.8)

### Log file

N/A

**Comment by shitwolfymakes** [comment]
Removing the bug tag, as this is expected behavior. In the UI Settings, `index_refresh` is a configurable option that determines how long the delay is between requests. Super low numbers can effectively DoS the system running ARM. Personally, 2000 is ideal.

The default is super low, but that is in the process of being fixed.
