### ISSUE TITLE
Request: Show version in webUI

### ISSUE THREAD

**Issue by PriamX** [automatic-ripping-machine/automatic-ripping-machine#637]
It would be helpful to list the version on the ARM webUI home page.

**Comment by microtechno9000** [comment]
the current v2_devel branch has this under the settings page, showing the version and some other stats
![Screenshot_20221224-101118_Firefox](https://user-images.githubusercontent.com/62650032/209413822-898da1b3-8d54-4bd9-92ff-f7bc3344856d.jpg)

**Comment by PriamX** [comment]
Nice, thank you! I have not tried the dev branch.
