### ISSUE TITLE
Web UI cannot be reached

### ISSUE THREAD

**Issue by thompcha** [automatic-ripping-machine/automatic-ripping-machine#644]
I have been using ARM for several weeks without issue. Started a rip last night before bed and when I visited `http://<arm-ip>:8080/index` this morning, I get an `ERR_CONNECTION_TIMED_OUT` response.

I inserted a new DVD and the logs indicate that it is ripping normally.

I couldn't find anything in the wiki about this issue

`sudo systemctl status armui` indicates that armui.service is loaded and active.

**Comment by microtechno9000** [comment]
Not sure what might be causing this, Can you post your Webui.log file, found in /home/arm/logs

**Comment by thompcha** [comment]
It looks like I don't have a log file with that name. Is there some way that I can enable it?

My /home/arm/logs directory just contains log files named after the various DVD's that I have ripped.

**Comment by microtechno9000** [comment]
Ok, have a look in the below armui config and enable the webui log. Open the below file with an editor, like nano.

`sudo nano /etc/systemd/system/armui.service`
change the below lines from:
```
#StandardOutput=append:/PATH-TO-MY-LOGFILES/WebUI.log
#StandardError=append:/PATH-TO-MY-LOGFILES/WebUI.log
```
To:
```
StandardOutput=append:/home/arm/logs/WebUI.log
StandardError=append:/home/arm/logs/WebUI.log
```
Once edited, you will need to reload and restart the armui service
`sudo systemctl daemon-reload`

**Comment by thompcha** [comment]
Thank you, when I enabled the log and restarted the service, I could see in the log that somehow my server IP address had changed!

**Comment by microtechno9000** [comment]
glad I could help

please close the issue if there are no further issues
