### ISSUE TITLE
cp: cannot create regular file '/etc/rsyslog.d/30-arm.conf': No such file or directory

### ISSUE THREAD

**Issue by GreyHatz** [automatic-ripping-machine/automatic-ripping-machine#645]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
_[debian-install.sh](https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/v2_devel/scripts/installers/debian-install.sh)_ fails when attempting to create _/etc/rsyslog.d/30-arm.conf_ on Virtual Machine running Dietpi.

**To Reproduce**
Set up Dietpi VM using VirtualBox:
1. Import _DietPi_VirtualBox-x86_64-Bullseye.OVF_ file to _VirtualBox
3. Start VM and configure network adapter with static IP, etc...
4. `sudo apt-get update`
5. `sudo apt-get install net-tools` <<< [Suggested by a Redditor](https://www.reddit.com/r/debian/comments/yx4fns/automatic_ripping_machine_on_debian_11/) and thought it may help get webui running, but haven't reached that stage yet.

Following official steps using [Auto Install Script For OpenMediaVault/Debian](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Setting-up-ARM-script-(Debian-OMV)):
1. `sudo apt install wget`
2. `wget https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/v2_devel/scripts/installers/debian-install.sh`
3. `sudo chmod +x debian-install.sh`
4. `sudo ./debian-install.sh` <<< Script ends with output `"cp: cannot create regular file '/etc/rsyslog.d/30-arm.conf': No such file or directory"`

### Environment
- _DietPi_VirtualBox-x86_64-Bullseye_... Downloaded _.OVA_ file from [dietpi.com](https://dietpi.com/#download)
- _VirtualBox Version 7.0.4 r154605 (Qt5.15.2)_ Running on Windows 10

Do you think it might be an issue with this particular flavor of Debian 11.6? Any help is appreciated!

**Comment by shitwolfymakes** [comment]
Debian installation script is out of date. Try installing on Ubuntu 20.04 or running the docker release

**Comment by shitwolfymakes** [comment]
Closing as stale, feel free to reopen if the problem persists!
