### ISSUE TITLE
Support Hotplugging of USB DVD drives in Docker

### ISSUE THREAD

**Issue by MoralCode** [automatic-ripping-machine/automatic-ripping-machine#646]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use ARM but only have an external USB DVD drive that I also use for other things. Having to start the ARM docker container every time I want to use it (so it sees my DVD drive) makes ARM less convenient to  use, especially by other DVD-buying, home-media-server-loving users in the same house who aren't as tech savvy and cant restart a docker container (because they don't have access).

**Describe the solution you'd like**
I think it would be nice if ARM could support hotplugging DVD drive devices. Then users without a permanently-attached DVD drive could have a workflow like:

1. plug DVD drive into NAS that has ARM running in docker
2. insert DVD into dvd drive
3. ARM automatically rips and ejects the DVD as usual.
4. unplug DVD drive when done or when its needed for other things

**Describe alternatives you've considered**
Since the ARM docker containers already have udev installed, I have attempted to play with the solution described in https://www.balena.io/docs/reference/base-images/base-images/#working-with-dynamically-plugged-devices, but it seems to get stuck because of https://github.com/balena-io-library/base-images/issues/597

I have also tried thoroughly searching this repository for terms like "udev" and "hotplug" and dont seem to see any existing issues for this

**Are you able to help code/implement this feature ?**
Yes, but i lack the knowledge/understanding of udev, passing devices, or the various permissions things involved to know what im doing wrong. Happy to help test and debug though.

**Comment by microtechno9000** [comment]
I am not across how docker handles drives when hot plugged. However, the v2_devel branch has recently been updated with a scan for drives using the web interface.
If you are able to check your docker container against this branch and let me know if it solves your problem. Might be easier than updating udev rules.

**Comment by MoralCode** [comment]
Thanks for the info, I'll give that a try! Is there a set of instructions (or even just a script) somewhere that would explain how the official docker images are compiled so i can make one against the v2_devel branch?

**Comment by MoralCode** [comment]
gave it a try:
1. checkout the branch and build the new docker image
2. change the image in my run command from before
3. run ARM with no DVD drive connected. upgrade the DB when prompted
4. go to the arm settings tab and run a scan for drives
5. plug in drive
6. rescan

based on this it doesn't seem to be detecting new drives connected after the container started running. running a `docker container exec -it <dev image> bash` and poking around /dev also didnt sugest the drive was seen by the container

`lsblk` within the container does show an `sr0` device, although I don't know if that's just showing whats connected to my host given that the container is privileged.

is that useful or is there any other info that would be helpful for finding out what would be needed to get this working?

**Comment by microtechno9000** [comment]
glad you got the v2_devel running 😀
I am not too familiar with docker and how it handles passing drives into the container sorry.

I was hoping that with the dev version it might show up automatically and 'just work'.

@shitwolfymakes is the container expert.

**Comment by MoralCode** [comment]
did some poking around and noticed that in `dmesg` logs when plugging in a drive, i see the following error:
```
[ 6696.884641] systemd-udevd[802]: sr0: Process '/sbin/setuser arm /opt/arm/scripts/docker/docker_arm_wrapper.sh sr0' failed with exit code 1.
```
seems to me like it may be just a permission issue with getting the /dev/srX devices to be owned by the `arm` user

**Comment by shitwolfymakes** [comment]
You might be able to hotplug usb drives anyway with the docker container. It creates 10 mount points in the image during the build. 

As long as you execute the run command with the volume mappings, then you shouldn't have any issues with this.

**Comment by MoralCode** [comment]
> You might be able to hotplug usb drives anyway with the docker container. It creates 10 mount points in the image during the build.

is there documentation somewhere on how the mounting process works for drives? I'm curious how the docker setup script plays into this. is that script run automatically as part of the image build process? or am I expected to run it manually beforehand?

I noticed through my testing that if `docker-setup.sh` didn't run correctly (i.e. no drives were present when it sets up the mount points), it creates a mountpoint literally at `/mnt/dev/sr?` and hotplugging drives doesnt seem to work. Is this something that would be helpful to update so that it creates mountpoints regardless of how many drives are connected at setup?

**Comment by 1337-server** [comment]
Sorry for the late reply, if security isn't an issue, you could map the USB bus ?

Since by default, the docker image is considered insecure by most standards, it may be acceptable for you. But it's your own choice to make.

You can do this by mapping 
`-v /dev/bus/usb:/dev/bus/usb`
OR
`-v /dev:/dev`

**But be warned this is considered bad practice, as it gives the container full device privileges to the host (sda, sdb, etc.)**
Again though, if you are running with the `--privileged` flag this is already considered insecure.

The safer alternative is to add a new rule to remount the device when changes are detected via udev with a udev rule.

**Comment by MoralCode** [comment]
Doesnt the container already support mounting already-connected USB DVD/CD drives with the `-v` mapping and/or `--privileged`? 

To me it seems like the only things preventing a fully hands-off hotplug-capable user experience like the one i described in the initial issue message (where there isnt a disk drive that can be permanently assigned just to ARM)  is mainly the two small changes I suggested in my earlier comment (fixing the scripts to not fail if the container is created/started without any drives available, and adding an auto refresh to the new drive scanning feature).

**Comment by 1337-server** [comment]
> Doesnt the container already support mounting already-connected USB DVD/CD drives with the `-v` mapping and/or `--privileged`?

Yes, but I was talking about hot plugging and not having the drive in as standard.

> and adding an auto refresh to the new drive scanning feature).

Unless I have misunderstood.... if I have, please let me know.

This is what I was talking about with my previous comment. udev should already trigger when a new drive is added (at least in my own experience with removable drives), it would just need a udev rule to mount it to the correct mount points so that ARM can access it.
This should remove the need for a new drive scanning feature, and would mean ARM would still behave normally when you hotplug devices

> would a contribution to fix the setup script be helpful?

Help is always appreciated!

**Comment by 1337-server** [comment]
Closing as stale
