### ISSUE TITLE
Notifications from Docker link to 127.0.0.1

### ISSUE THREAD

**Issue by tjbenator** [automatic-ripping-machine/automatic-ripping-machine#648]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
ARM in docker is sending notifications linking to localhost (127.0.0.1). 

**To Reproduce**
1. Setup Emby using docker: https://hub.docker.com/r/1337server/automatic-ripping-machine
2. I enabled Discord notifications via Apprise
3. Ripped a movie and received a message that links to 127.0.0.1. Bottom message (3:48PM) is one sent from ARM in docker.

The messages prior to that I had set the WEBSERVER_IP in the web UI to match the docker host, which made the notifications correct until the UI crashed. Changed it back to x.x.x.x and the UI started working.

![Screenshot from 2023-01-07 15-49-15](https://user-images.githubusercontent.com/1761657/211174457-73e25580-9057-40fb-ac3e-6ffcc37624c6.png)

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
Docker

Python version: 3.8.10
A.R.M version: 2.6.4
Current git version: 8be2adf3717d27ae14c814193adfb36669985e9e

REPOSITORY                             TAG       IMAGE ID       CREATED        SIZE
1337server/automatic-ripping-machine   latest    c385893baa8e   47 hours ago   1.58GB

https://hub.docker.com/layers/1337server/automatic-ripping-machine/latest/images/sha256-23e667605d642e341a0835f2017b427503ab3bb2494fb91134023c7cc983d4b2?context=explore

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 

### Log file
N/A

**Comment by shitwolfymakes** [comment]
The official docker repo is automaticrippingmachine/automatic-ripping-machine, and make sure to use the `v2_devel` tag

**Comment by sdjernes** [comment]
I can confirm as of a week ago this bug still exists and has a fatal reaction. If you set the IP via the Web UI to the IP of the docker host machine ARM’s web server will not start when the container runs.

**Comment by 1337-server** [comment]
Cant replicate this on bare-metal, will have time later today to test this on docker.

**Comment by 1337-server** [comment]
Output from docker on new virtual machine
```
DEBUG ARM: utils.check_ip ******************************************************************************************************************************************************
DEBUG ARM: utils.check_ip {'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'peer': '127.0.0.1'}
DEBUG ARM: utils.check_ip ******************************************************************************************************************************************************
DEBUG ARM: utils.check_ip ******************************************************************************************************************************************************
DEBUG ARM: utils.check_ip {'addr': '172.17.0.3', 'netmask': '255.255.0.0', 'broadcast': '172.17.255.255'}
DEBUG ARM: utils.check_ip ******************************************************************************************************************************************************
```

The only way I can really see forward, is to add a check for being inside docker and then detach the link from `WEBSERVER_IP` so that you can set this without it breaking the UI.

**Comment by eitch** [comment]
I can confirm that this is still an issue on docker. I have a new installation, running A.R.M version: 2.6.71  and i get this:

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/245382/c7504a2e-9158-4cb9-90ee-770048ae32f6)
