### ISSUE TITLE
Typo in arm_wrapper.sh

### ISSUE THREAD

**Issue by vbdjames** [automatic-ripping-machine/automatic-ripping-machine#659]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
Automatic ripping will fail on new install.

**To Reproduce**
1. Do a fresh install using ubuntu script as described in the wiki
2. Insert a DVD
3. The rip will fail

I ran udev with debug flags set, and it reported an exception that ID_CDROM_MEDIA_BD is not a valid function.

Looked at arm_wrapper.sh - these three lines are comments in the dev branch, but in the release branch, the leading "#" has been removed. Commented these out in my local copy, and ARM works like a charm!

    # ID_CDROM_MEDIA_BD = Bluray
    # ID_CDROM_MEDIA_CD = CD
    # ID_CDROM_MEDIA_DVD = DVD

**Comment by shitwolfymakes** [comment]
This has been fixed with the release of 2.6.10
