### ISSUE TITLE
Setup documentation (Ubuntu 20.04)

### ISSUE THREAD

**Issue by delovelady** [automatic-ripping-machine/automatic-ripping-machine#662]
The last command in the documentation for section "Install and setup ARM" reads:

sudo -u arm ln -sf /etc/.abdce.conf /etc/arm/config/abcde.conf

This command is unintelligible.

Command cannot succeed since there is no /etc/arm/config folder.  Are we to make one?  Should that be /opt/arm/config/abcde (which also will fail for the same reason) or something else?

Everything went great up until that point.  Confidence was at the "hold my beer" level.

> sudo -u arm ln -sf /etc/.abdce.conf /etc/arm/config/abcde.conf
ln: failed to create symbolic link '/etc/arm/config/abcde.conf': No such file or directory

**Comment by microtechno9000** [comment]
Hi @delovelady , welcome to the community 

It looks like the wiki hasn't been updated with the latest change to ARM. All the config files for ARM should be in /etc/arm/config as below

```
mtech@server:/etc/arm/config$ ls
abcde.conf  apprise.yaml  arm.yaml
```

**Comment by delovelady** [comment]
Thanks, @microtechno9000 .  That solved that issue (of course)

Two follow-up questions.  If I need to open new issues for each/either, let me know.

1) Later in the setup steps, there is mention of connecting to the webserver at webserver:port/setup in order to initialize the database.  However, I don't see where this setup file (or folder) was set up in Apache or whatever.  Did I miss a step?

2) I'd like to install this on a Ubuntu 22.04 server, but this line needs adjustment.  

NumOnly=$(cut -f2 <<< `lsb_release -r`) && case $NumOnly in "16.04" ) sudo add-apt-repository ppa:mc3man/xerus-media;; "18.04" ) sudo add-apt-repository ppa:mc3man/bionic-prop;; "20.04" ) sudo add-apt-repository ppa:mc3man/focal6;; *) echo "error in finding release version";; esac

Is that something under development?  For me, it's a catch-22, since ubuntu 20.04 wouldn't let user arm mount the drive (https://askubuntu.com/questions/1428575/must-be-superuser-to-mount-even-though-etc-fstab-option-includes-users).  Ubuntu 22.04 does that as necessary (no changes anywhere other than OS upgrade), but of course there's that pesky step I'm missing  

Thanks again.

**Comment by microtechno9000** [comment]
glad to help.

1. The database will be created when ARM starts there is no user input required. The Setup page doesn't do much anymore. If you go to webserver:port, what ever you have configured in the arm.yaml file, ARM will be there.
2. Currently ARM doesn't support 22.04, there are a lot of breaking changes that are introduced with updated versions in 22.04. It is something to be worked on.

**Comment by delovelady** [comment]
Thanks, @microtechno9000 - I appreciate the response and the candor.  :)

You have a great day!

**Comment by microtechno9000** [comment]
@delovelady wiki has been updated to resolve this issue
