### ISSUE TITLE
Rip fails when external dvd drive is used

### ISSUE THREAD

**Issue by thompcha** [automatic-ripping-machine/automatic-ripping-machine#664]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
My integrated optical drive jammed, so I attached an external dvd drive and inserted a disc. After several seconds it gets ejected and ARM produces a log with a single line:
`INFO ARM: main.<module> Drive appears to be empty or is not ready. Exiting ARM.`

**To Reproduce**
1. Insert a dvd into the external dvd drive

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
2.6.0

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]
[STREET_KINGS_167385693816.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10429370/STREET_KINGS_167385693816.log)

**Comment by shitwolfymakes** [comment]
Try re-inserting after leaving the drive open for 5-10 seconds, sometimes it's an initialization delay

**Comment by thompcha** [comment]
Thank you, I tried this and now I see that there's a permission error:
```
[16-01-2023 14:53:35] INFO ARM: identify.identify Mounting disc to: /mnt/dev/sr1
[16-01-2023 14:53:35] ERROR ARM: main.<module> A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 479, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 177, in main
    identify.identify(job, logfile)
  File "/opt/arm/arm/ripper/identify.py", line 31, in identify
    os.makedirs(str(job.mountpoint))
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/dev/sr1'
```
Any idea how to address this?

**Comment by thompcha** [comment]
I managed to resolve the issue by opening a terminal and manually mounting /dev/sr1 to /mnt/dev/sr1
