### ISSUE TITLE
Retroactively fix filenames/locations of already-transcoded files

### ISSUE THREAD

**Issue by fluffy-critter** [automatic-ripping-machine/automatic-ripping-machine#676]
**Is your feature request related to a problem? Please describe.**

ARM often guesses titles or media types completely wrong for a lot of the discs I'm ripping, and sometimes I don't notice this until after transcoding has finished, but since transcoding has already completed, updating the title and media type doesn't update the output files.

**Describe the solution you'd like**

If the transcoded files are still in the output location, it would be nice if changing the job title would retroactively change the media files to be in the correct folder name and structure.

**Are you able to help code/implement this feature ?**

No

**Additional context**

**Comment by lawhazl** [comment]
I second this, i have about 100 discs to rip and i'm trying to just smash through them using myself and others in my household to put in the discs when they see one ejected. 

So renaming is really needed as i'm often out the house and cant react to all the new disc notifications

**Comment by shitwolfymakes** [comment]
The complexity of doing this mid- or post-rip is infeasible for us at present. As a note, there are almost certainly tools that do this (especially for music).

Closing this for now, but feel free to open a PR if you are able to add the functionality yourself!
