### ISSUE TITLE
arm_user_files_setup.sh exiting with error: sudo: command not found

### ISSUE THREAD

**Issue by Laurendus** [automatic-ripping-machine/automatic-ripping-machine#679]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
When pulling the latest v2_devel docker container it restarts with the following error message.
```
/etc/my_init.d/arm_user_files_setup.sh: line 63: sudo: command not found
```

The container runs with the user root which does not have sudo in its $PATH. Alternatively `su arm -c ...` could be used.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/2f96a5020f3e30a8eac65784dee4b14ea05b1336/scripts/docker/runit/arm_user_files_setup.sh#L63

**To Reproduce**
1. Pull latest v2_devel container tag
2. start the container with default parameters

### Environment (of the container)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

### Log file
irrelevant

**Comment by shitwolfymakes** [comment]
This has been fixed by #680. Give it a bit and then pull the new `v2_devel` image
