### ISSUE TITLE
Docker image error: KeyError HANDBRAKE_LOCAL causes all jobs to fail on v2_devel

### ISSUE THREAD

**Issue by cmbernard333** [automatic-ripping-machine/automatic-ripping-machine#688]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
When attempting to rip a bluray/dvd using the latest docker image from v2_devel - the latest config does not contain the proper keys in order to work correctly. 

This can be observed by running a normal job.

 I believe I've traced the issue here in handbrake.py
 
 ```python
    cmd = f'{cfg.arm_config["HANDBRAKE_LOCAL"]} -i {shlex.quote(srcpath)} -t 0 --scan'
    logging.debug(f"Sending command: {cmd}")
    hand_break_output = handbrake_char_encoding(cmd)
 ```

**To Reproduce**
1. Try to rip bluray/dvd
2. Go to the log for the job
3. Get the error: 
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/4392507/215371951-28ee03b6-6b2f-4a97-8906-165580dfe509.png">

### Environment
Docker image automaticrippingmachine/automatic-ripping-machine:v2_devel

### Log file
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/4392507/215371951-28ee03b6-6b2f-4a97-8906-165580dfe509.png">

**Comment by 1337-server** [comment]
Is it possible your arm.yaml is outdated ?

You might need to check that the `HANDBRAKE_LOCAL` variable exists inside the arm.yaml

**Comment by cmbernard333** [comment]
I added this but it is not documented on the wiki so it required me to dig around a little bit in the code to find it.
