### ISSUE TITLE
No NVENC hardware encoding option with 1.3.x handbrake installed with the script on Ubuntu 20.04.x

### ISSUE THREAD

**Issue by rpelissi** [automatic-ripping-machine/automatic-ripping-machine#690]
- [ x] I have checked the wiki
- [x ] I have searched for similar issues

**Describe the bug**
So it's no really a bug, just something that I have found. 
I have a GTX 1060 NVENC compatible card seen by nvidia-smi tool but handbrake does not list the nvenc encoding option, juste like the hardware encoding is not available with the installed version

**To Reproduce**
1.  Install an ubuntu 20.04.x vm in promox (pci pasthrought should be enable and the card should be listed when executing the nvida-smi tool)
2. Install ARM using the script
3. use Handbranke-cli to check the encoding options

### Environment
Ubuntu 20.04.5 LTS
ARM: 2.6.10

**Comment by rpelissi** [comment]
So, with the script install, the handbrake version is 1.3.x I think and the NVENC hardware encoding is not listed. I have compile handbrake using:
https://handbrake.fr/docs/en/latest/developer/install-dependencies-ubuntu.html
and
https://handbrake.fr/docs/en/latest/developer/build-linux.html
And now I have the version:
root@pdrripp01:/opt/arm# HandBrakeCLI --version
```
[23:37:19] Compile-time hardening features are enabled
[23:37:19] nvenc: version 12.0 is available
[23:37:19] nvdec: is not compiled into this build
[23:37:19] hb_init: starting libhb thread
[23:37:19] thread 7f002300e700 started ("libhb")
HandBrake 20230130172537-a5238f484-master
```

And then:
```
root@pdrripp01:/opt/arm# HandBrakeCLI --help | grep -A12 "Select video encoder"
[23:38:17] Compile-time hardening features are enabled
[23:38:17] nvenc: version 12.0 is available
[23:38:17] nvdec: is not compiled into this build
[23:38:17] hb_init: starting libhb thread
[23:38:17] thread 7fdb4b1b4700 started ("libhb")
   -e, --encoder <string>  Select video encoder:
                               svt_av1
                               svt_av1_10bit
                               x264
                               x264_10bit
                               nvenc_h264
                               x265
                               x265_10bit
                               x265_12bit
                               nvenc_h265
                               nvenc_h265_10bit
                               mpeg4
                               mpeg2
```

It's not really a bug per say, maybe you can add this to the https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/nvidia section in case other people face the same issue.

You can close the ticket if you want.
Thanks again for this cool solution! :)

**Comment by 1337-server** [comment]
I think this is due to HandBrakeCLI when installed via package manager doesn't include HW encoding, and if you want it you need to build the package from source.

In one of the installer versions it actually built everything from source, but this increased the installation time from around 10–15 mins to an hour or so depending on machine. So it was reverted to the quicker install method and users would need to compile HB if they wanted to include HW transcoding.

Hope this helps

**Comment by rpelissi** [comment]
Sure no problem! Just mention this in the documentation so people will not do the same mistake as me :) I have an nvidia quadro 400 card installed and try ARM and face this issue. So I thought that my card was not supported so I buy a new one :) It's when I see that even the new one was not even detected for hardwar encoding that I have tried the compile option.
Btw, I have a quadro 400 to sell if you are interested ;) Just joking.
Again, a couple of line n the documentaiton mentioning this will be helpful. I can even do it if you want.

Thanks!
You can close this bug report if you want
