### ISSUE TITLE
BluRay rip failes, makemkv.get_track_info Found 0 titles

### ISSUE THREAD

**Issue by joelishness** [automatic-ripping-machine/automatic-ripping-machine#692]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
BluRay rip suddenly fails to find any titles and errors out.
This same disc ripped successfully just last night, now fails.

**To Reproduce**
1. Insert disc
2. Update title
3. Rip fails

### Environment
docker v2_devel

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]
[STAR_TREK_TNG_S2_D3_167523220979.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10553832/STAR_TREK_TNG_S2_D3_167523220979.log)

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by joelishness** [comment]
Ran a test to see if output was the same when arm-rippers running, it was not!
Instead I got evaluation expired errors and
```
MSG:5010,0,0,"Failed to open disc","Failed to open disc"
TCOUNT:0
```
Not sure why the different behaviors between makemkvcon executed manually vs makemkv.py

Test method:
```
# Backup
cp /opt/arm/arm/ripper/makemkv.py /opt/arm/arm/ripper/makemkv.py.backup

# Edit
vim /opt/arm/arm/ripper/makemkv.py
From:
    cmd = f'makemkvcon -r --progress=-stdout --messages=-stdout --minlength={job.config.MINLENGTH} ' \
          f'--cache=1 info disc:{mdisc}'
To:
    cmd = f'makemkvcon -r --progress=/home/arm/debugtest.txt --messages=/home/arm/debugtest.txt --minlength={job.config.MINLENGTH} ' \
          f'--cache=1 info disc:{mdisc}'

# Restore orig
mv /opt/arm/arm/ripper/makemkv.py.backup /opt/arm/arm/ripper/makemkv.py
```
Log attached:
[debugtest.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10561397/debugtest.txt)

**Comment by joelishness** [comment]
Okay, well I got my issue resolved by purchasing a key.

It seems the root cause is that Beta key has not been updated for February yet:
> and is valid until end of January 2023. Please check back for updated key on this page.

Suggest that [1337-server#121](https://github.com/1337-server/automatic-ripping-machine/pull/121) may not be sufficiently catching expired keys

**Comment by shitwolfymakes** [comment]
Confirmed this is now broken somehow. Will investigate tomorrow

**Comment by shitwolfymakes** [comment]
Confirmed the error code being returned for an expired key now is 11, will test a fix in a sec

**Comment by 1337-server** [comment]
Closing as issues is resolved
