### ISSUE TITLE
Can't update ARM

### ISSUE THREAD

**Issue by rpelissi** [automatic-ripping-machine/automatic-ripping-machine#694]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
I have ARM installed using the script method on Ubuntu 20.04.x Now I see there is an update available but whatever I click on the update button, nothing happens

**To Reproduce**
1. Install 2.6.10 using script method on Ubuntu 20.04.xx
2. Get the update notification
3. Try to update

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

ARM: 2.6.10 

### Log file
I do not see any obvious errors in the logs but I can upload them if you want

Note: For the fun I try to go under the ARM user and then /opt/arm and try to do a git pull, not sure it is the correct way of doing the update. Still, I got this:

```
arm@pdrripp01:/opt/arm$ git pull origin master
From https://github.com/automatic-ripping-machine/automatic-ripping-machine
 * branch            master     -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'arm@pdrripp01.(none)')
```

Thanks!

**Comment by rpelissi** [comment]
![image](https://user-images.githubusercontent.com/385483/216054111-f510df03-6546-41c9-a815-7217588ad7f5.png)

**Comment by rpelissi** [comment]
[empty.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10557414/empty.log)
[WebUI.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10557415/WebUI.log)

**Comment by microtechno9000** [comment]
I will look into the UI bug, and see what it is doing. Looks like we might need to provide a bit more indication on the failure.

as for setting up git, it looks like you haven't assigned any credentials. Have a look at https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup under 'Your Identity. Then try the git pull again.

**Comment by rpelissi** [comment]
Hi,
So I have filled the infos for my username and email but get this when I try to pull from master:

```
arm@pdrripp01:/opt/arm$ git pull origin master
From https://github.com/automatic-ripping-machine/automatic-ripping-machine
 * branch            master     -> FETCH_HEAD
CONFLICT (modify/delete): video_transcode.sh deleted in HEAD and modified in b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f. Version b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f of video_transcode.sh left in tree.
CONFLICT (modify/delete): video_rip.sh deleted in HEAD and modified in b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f. Version b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f of video_rip.sh left in tree.
CONFLICT (modify/delete): notify.sh deleted in HEAD and modified in b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f. Version b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f of notify.sh left in tree.
CONFLICT (modify/delete): identify.sh deleted in HEAD and modified in b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f. Version b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f of identify.sh left in tree.
CONFLICT (modify/delete): data_rip.sh deleted in HEAD and modified in b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f. Version b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f of data_rip.sh left in tree.
CONFLICT (modify/delete): config.sample deleted in HEAD and modified in b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f. Version b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f of config.sample left in tree.
CONFLICT (modify/delete): arm_wrapper.sh deleted in HEAD and modified in b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f. Version b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f of arm_wrapper.sh left in tree.
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
CONFLICT (add/add): Merge conflict in CONTRIBUTING.md
Auto-merging CONTRIBUTING.md
CONFLICT (modify/delete): 51-automedia.rules deleted in HEAD and modified in b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f. Version b5f34ad3c8fde443a4e62ffd16c8be7b17bf855f of 51-automedia.rules left in tree.
Auto-merging .gitignore
CONFLICT (content): Merge conflict in .gitignore
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by rpelissi** [comment]
```
arm@pdrripp01:/opt/arm$ git branch -a
* (no branch)
  remotes/origin/HEAD -> origin/v2_master
  remotes/origin/dev
  remotes/origin/docker-fixes
  remotes/origin/master
  remotes/origin/v2_devel
  remotes/origin/v2_master
  remotes/origin/v2_master_fixes
```

**Comment by shitwolfymakes** [comment]
Looks like the branch isn't being checked out after cloning

**Comment by ivuorinen** [comment]
Shouldn't the branch be `v2_master` instead of `master`? At least the `HEAD` is pointing to `v2_master`.

**Comment by microtechno9000** [comment]
The master or HEAD is v2_master
Will it update if you checkout the v2_master and then do a git pull?

**Comment by 1337-server** [comment]
Closing as no longer valid as docker is now the main installation method.
