### ISSUE TITLE
🐛 ARM on an NVMe 

### ISSUE THREAD

**Issue by LiketoTinker** [automatic-ripping-machine/automatic-ripping-machine#710]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I am having a similar issue to this: https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/518#issue-1280386948

My instance does not RIP the discs either, but does not eject them after any amount of time.

Here are the outputs from the commands requested in issue mentioned:

**ls -la /home/arm/**

total 80
drwxrwxr-x 17 arm  arm  4096 Feb  6 09:37 .
drwxr-xr-x  4 root root 4096 Feb  4 22:02 ..
-rwxrwxr-x  1 arm  arm   220 Jan  6  2022 .bash_logout
-rwxrwxr-x  1 arm  arm  3771 Jan  6  2022 .bashrc
drwxrwxr-x 10 arm  arm  4096 Feb  6 09:38 .cache
drwxrwxr-x 11 arm  arm  4096 Feb  6 09:58 .config
drwxr-xr-x  2 arm  arm  4096 Feb  4 22:37 db
drwxr-xr-x  2 arm  arm  4096 Feb  6 09:37 Desktop
drwxr-xr-x  2 arm  arm  4096 Feb  6 09:37 Documents
drwxr-xr-x  2 arm  arm  4096 Feb  6 09:37 Downloads
drwx------  3 arm  arm  4096 Feb  4 22:37 .local
drwxrwxr-x  2 arm  arm  4096 Feb  4 22:31 logs
drwxrwxr-x  5 arm  arm  4096 Feb  4 22:31 media
drwxr-xr-x  2 arm  arm  4096 Feb  6 09:37 Music
drwxr-xr-x  2 arm  arm  4096 Feb  6 09:37 Pictures
-rwxrwxr-x  1 arm  arm   807 Jan  6  2022 .profile
drwxr-xr-x  2 arm  arm  4096 Feb  6 09:37 Public
drwx------  3 arm  arm  4096 Feb  4 22:31 snap
drwxr-xr-x  2 arm  arm  4096 Feb  6 09:37 Templates
drwxr-xr-x  2 arm  arm  4096 Feb  6 09:37 Videos

**ls -la /home/arm/logs**

total 12
drwxrwxr-x  2 arm arm 4096 Feb  4 22:31 .
drwxrwxr-x 17 arm arm 4096 Feb  6 09:37 ..
-rwxrwxr-x  1 arm arm  516 Feb  6 09:59 empty.log

**ls -la /home/arm/db**

total 48
drwxr-xr-x  2 arm arm  4096 Feb  4 22:37 .
drwxrwxr-x 17 arm arm  4096 Feb  6 09:37 ..
-rw-r--r--  1 arm arm 36864 Feb  4 22:37 arm.db

**ls -la /home/arm/db**

total 48
drwxr-xr-x  2 arm arm  4096 Feb  4 22:37 .
drwxrwxr-x 17 arm arm  4096 Feb  6 09:37 ..
-rw-r--r--  1 arm arm 36864 Feb  4 22:37 arm.db

### To Reproduce

Here is my log file:
[empty.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10664673/empty.log)

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.6.12

### Expected behavior?

Inserted disc completes RIP

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
If you installed via Install script you are most likely missing the raw folder from `/home/arm/media/raw/` issue #722 
You can check this by looking over the arm.log and see if it matches with that issue.

I have been using NVME since i started with arm and had no issues, so i dont think that is related.
If you have something esle in your arm.log please post it here.

**Comment by LiketoTinker** [comment]
This doesn't seem to describe my issue at all. I do not have that error in my log file. 

My log is attached above in my original post. The logs are completely empty other than an error in reference to the nvme drive. 

My instance doesn't seem to spin up the disk at all and does not log any events other than the failed device(nvme) when I boot the machine.

**Comment by 1337-server** [comment]
Can you run this and post the output `sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0`

Can you also `ls -la /home/arm/media`

**Comment by LiketoTinker** [comment]
No, unfortunately not.

I reinstalled ubuntu fresh to try to fix the issue,  and it seems that running arm without docker is no longer supported, I'm unable to reinstall arm in my preferred method. 

I don't really want to run this in docker, so I will be using a different method now.

**Comment by LiketoTinker** [comment]
ARM is running and working! I think the main DVD drive I was using was dead 😂 I will have to swap that one out.

 I am having an issue with Blu-ray, but I have not looked into this yet. I will take a look and attempt to fix it myself. If not, I will open a new thread!

**Comment by microtechno9000** [comment]
@LiketoTinker do you have any udev or dmesg logs that you could post showing the faulty drive, might be something we could look at checking and informing via the UI if possible.

**Comment by LiketoTinker** [comment]
Sorry for the late reply! I welcomed my first born this past week!

I will take a look and post any I find!

**Comment by LiketoTinker** [comment]
The faulty drive is mounted at sr0, but I don’t have anything in the logs for that drive, only my two others: sr1 & sr2.

I am going to try replacing the drive now and see if it really is the drive. I will post my findings later! 

I also had a problem with the bluray I tried. It could just be that specific disc, I’ll try another one and make another issue if needed.

Thank you for the help.
