### ISSUE TITLE
🔧 Is it possible to backup the dvd to iso (dvdbackup) before transcode?

### ISSUE THREAD

**Issue by sphaero** [automatic-ripping-machine/automatic-ripping-machine#726]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

To correctly backup the DVD it would be great to convert it to an iso format. This could preserve the menus system and other specific DVD features. 

### Describe the solution you'd like?

To add the dvdbackup command prior to doing the MakeMKV command.

### Describe alternatives you've considered?

None sofar

### Anything else?

It would be great to add this as an configurable extra setting

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Not currently. Eventually I plan to test making disk isos with `dd` for use in automatic testing

**Comment by 1337-server** [comment]
ARM doesn't have this feature built in to do both ISO backup and ripping/transcoding.
However, you could re-run the disc with manual wait on and then change the disc type to data.
This would force arm to rip with `dd` giving you an ISO copy.

Or you could modify main.py:main() finding this
```
    log_arm_params(job)
    check_fstab()

    # Entry point for dvd/bluray
    if job.disctype in ["dvd", "bluray"]:
```

and changing to this

```
    log_arm_params(job)
    check_fstab()
    rip_data(job)
    # Entry point for dvd/bluray
    if job.disctype in ["dvd", "bluray"]:
```

I haven't tested, but it should give you an idea of how to do it if you wanted to. You won't get the easy settings to change it, but it should work.
