### ISSUE TITLE
🐋 Docker doesnt create all folders

### ISSUE THREAD

**Issue by 1337-server** [automatic-ripping-machine/automatic-ripping-machine#730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Docker doesnt create transcode folder leading to failure of all jobs

### To Reproduce

1. pull latest docker on fresh system
2. run latest docker image
3. start disc

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Run job and start ripping

### Relevant log output

```shell
ERROR ARM: utils.arm_setup Cant read from folder, Permission ERROR: /home/arm/media/transcode/ - ARM Will Fail!
ERROR ARM: utils.arm_setup Cant read from folder, Permission ERROR: /home/arm/media/transcode/ - ARM Will Fail!
ERROR ARM: utils.arm_setup Cant write to folder, Permission ERROR: /home/arm/media/transcode/ - ARM Will Fail!
ERROR ARM: utils.arm_setup Cant write to folder, Permission ERROR: /home/arm/media/transcode/ - ARM Will Fail!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Not sure if its related but it appears that docker also creates some files with root such as the log folders. Meaning arm-ripper cant run when a disc is entered.
```
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 134, in <module>
    arm_log = logger.create_logger("ARM", logging.DEBUG, True, True, True)
  File "/opt/arm/arm/ripper/logger.py", line 114, in create_logger
    file_handler = logging.FileHandler('/home/arm/logs/arm.log')
  File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/arm/logs/arm.log'
arm@ddeb135321e5:~$ /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0
```

**Comment by shitwolfymakes** [comment]
This shouldn't be happening. If the `arm` host uid or gid are not 1000, then you need to set the relevant environment variables in the container run command

**Comment by 1337-server** [comment]
> This shouldn't be happening. If the `arm` host uid or gid are not 1000, then you need to set the relevant environment variables in the container run command

Yep, I know. 
They were set correctly. Issue still happened.
