### ISSUE TITLE
🐛 Build docker github action failing because of tag

### ISSUE THREAD

**Issue by 1337-server** [automatic-ripping-machine/automatic-ripping-machine#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Build github action failing to create/test pull requests, caused by the PR using a branch name that includes a `/`. This caused the docker push tags to be invalid.

Breaking the build.

### To Reproduce

1. open pull request
2. docker build will fail as 

### What OS are you seeing the problem on?

all

### ARM Release Version or Git hash (You can find this in the arm settings page)

latest

### Expected behavior?

Build the PR but not to push

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
I've solved this on my fork. I'll PR the fixes tonight
