### ISSUE TITLE
🐋launch_setup function permissions error

### ISSUE THREAD

**Issue by megacorvega** [automatic-ripping-machine/automatic-ripping-machine#735]
The launch_setup function in the provided docker-setup.sh script does not correctly add the arm user to the docker group. The command should be 

`sudo usermod -aG docker arm`

I have confirmed this by manually running the command above, and re-running the docker-steup.sh script.

**Comment by shitwolfymakes** [comment]
Did you not run the script with `sudo`?

**Comment by johncm** [comment]
`sudo usermod -aG docker arm`

is only executed if docker is NOT installed and the script performs the install. Hope this helps.

**Comment by microtechno9000** [comment]
This issue has been resolved in #751
