### ISSUE TITLE
Launch scripts from systemd instead of udev

### ISSUE THREAD

**Issue by kmarhold** [automatic-ripping-machine/automatic-ripping-machine#74]
On my machine I get some I/O errors whenever I insert a disc (probably because I'm using a cheap slim-SATA to regular SATA adapter for the optical drive). As a consequence udev fails to launch the script as it won't wait until the drive is ready. The solution was to use systemd instead. This should probably be the default because having the script called from udev is not very robust when there is even a small delay. Tested and works on Ubuntu 17.04.

The udev rule:

`ACTION=="change", SUBSYSTEM=="block", TAG+="systemd", RUN+="/bin/systemctl start arm@%k.service"`

The %k substitution passes on the device name to `arm@.service` which can use it as instance argument %i:

```
[Unit]
Description=Automatic Ripping Machine

[Service]
Type=oneshot
ExecStart=/opt/arm/arm_wrapper.sh %i

[Install]
WantedBy=multi-user.target
```

arm_wrapper.sh then gets the disc info from udevadm, writes it into a temporary file and passes it on to the identify and ripper scripts:

```
DEVNAME=$1
udevadm info --query=env "/dev/$DEVNAME" > /tmp/arm_disc_info
echo bash /opt/arm/identify.sh /opt/arm/config /tmp/arm_disc_info | at now
```

In identify.sh:

```
export DISC_INFO=$2
source $DISC_INFO
```

**Comment by ahnooie** [comment]
Thanks, I first looked at systemd but couldn't get it to work.  udev is pretty fragile so would be worth moving off of it.  This may also make it easier to work on more distributions.   Are you able to create a PR with these changes?

**Comment by kmarhold** [comment]
Created a pull request - first time I did this, a bit confusing, I hope it worked!

**Comment by kmarhold** [comment]
Alright, I managed to create my first pull request on Github. I hope you didn't get spammed with notifications from the unsuccessful tries...

**Comment by muckngrind4** [comment]
Merged into 1.x and implemented in v2.x
