### ISSUE TITLE
🔧 show HW transcoding support in ui

### ISSUE THREAD

**Issue by 1337-server** [automatic-ripping-machine/automatic-ripping-machine#753]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Would be a nice feature to show if hardware transcoding is availble

### Describe the solution you'd like?

For example in ui settings page

| HW transcoding<br/>Version | Supported          |
|----------------------------|--------------------|
| Intel QuickSync            | :heavy_check_mark: |
| Nvidia NVENC               | :x:                |
| AMD VCE/VCN                | :x:                   |

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cmbernard333** [comment]
Like as a drop down or as a table? I have some ideas on how to do this since I've been looking at the code a lot recently (chasing another bug). I'm not much of a UI designer but I know python well enough.

**Comment by 1337-server** [comment]
![HWtranscode](https://user-images.githubusercontent.com/62730074/222582715-e74ce8d0-ac2a-4f1f-9378-f7d6e3ffddf2.PNG)

This is what I have at the moment.
