### ISSUE TITLE
🐋 CPU temp wont show correct number

### ISSUE THREAD

**Issue by 1337-server** [automatic-ripping-machine/automatic-ripping-machine#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When running docker, CPU wont show correct temp

This may be hardware specific though.

### To Reproduce

1. Install docker
2. Visit ui
3. No cpu temp

### Built from source files ?

- [X] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Show correct cpu temp

### Relevant log output
Output from psutil.sensors_temperatures()
```shell
{
   "nvme":[
      "shwtemp(label=""Composite",
      current=33.85,
      high=74.85,
      critical=79.85)
   ],
   "nct6797":[
      "shwtemp(label=""SYSTIN",
      current=35.0,
      high=80.0,
      critical=80.0),
      "shwtemp(label=""PCH_CPU_TEMP",
      current=0.0,
      "high=None",
      "critical=None)",
      "shwtemp(label=""CPUTIN",
      current=32.0,
      high=115.0,
      critical=115.0),
      "shwtemp(label=""AUXTIN0",
      current=37.0,
      high=115.0,
      critical=115.0),
      "shwtemp(label=""AUXTIN1",
      current=-128.0,
      "high=None",
      "critical=None)",
      "shwtemp(label=""AUXTIN2",
      current=61.0,
      "high=None",
      "critical=None)",
      "shwtemp(label=""AUXTIN3",
      current=-3.0,
      "high=None",
      "critical=None)",
      "shwtemp(label=""SMBUSMASTER 0",
      current=50.0,
      "high=None",
      "critical=None)",
      "shwtemp(label=""PCH_CHIP_CPU_MAX_TEMP",
      current=0.0,
      "high=None",
      "critical=None)",
      "shwtemp(label=""PCH_CHIP_TEMP",
      current=0.0,
      "high=None",
      "critical=None)"
   ],
   "k10temp":[
      "shwtemp(label=""Tctl",
      current=49.625,
      "high=None",
      "critical=None)",
      "shwtemp(label=""Tccd1",
      current=37.75,
      "high=None",
      "critical=None)",
      "shwtemp(label=""Tccd2",
      current=47.0,
      "high=None",
      "critical=None)"
   ]
}
```

### Anything else?

Tested and confirmed that the problem happens outside of docker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonathannlittle** [comment]
I believe the issue is the code is only looking for coretemp to get CPU temps, but not all motherboard chipsets use coretemp. My ARM is on a old AMD Phenom(tm) 9750 Quad-Core and CPU temp was always showing as 0. The motherboard displays the CPU temps via atk0110. 

Output of lm-sensors:
```
radeon-pci-0100
Adapter: PCI adapter
temp1:        +62.0°C

atk0110-acpi-0
Adapter: ACPI interface
Vcore Voltage:        1.31 V  (min =  +0.85 V, max =  +1.60 V)
+12V Voltage:        12.03 V  (min = +10.20 V, max = +13.80 V)
+5V Voltage:          5.08 V  (min =  +4.50 V, max =  +5.50 V)
+3.3V Voltage:        3.31 V  (min =  +2.97 V, max =  +3.63 V)
CPU FAN Speed:      1917 RPM  (min =  800 RPM, max = 7200 RPM)
Chassis FAN Speed:   964 RPM  (min =  800 RPM, max = 7200 RPM)
Chassis2 FAN Speed:    0 RPM  (min =  800 RPM, max = 7200 RPM)
CPU Temperature:     +49.0°C  (high = +65.0°C, crit = +95.0°C)
MB Temperature:      +41.0°C  (high = +45.0°C, crit = +95.0°C)
```
So I edited /opt/arm/arm/ui/settings/ServerUtil.py method get_cpu_temp() at line 45 and added an elif  to the if block:

```
    def get_cpu_temp(self):
        try:
            temps = psutil.sensors_temperatures()
            if coretemp := temps.get('coretemp', None):
                self.cpu_temp = coretemp[0][1]
            elif atk0110 := temps.get('atk0110', None):
                self.cpu_temp = atk0110[0][1]
            else:
                self.cpu_temp = 0
        except EnvironmentError:
            self.cpu_temp = 0
```
Now my CPU temp is displayed.  Just a hack for my situation, but suggest refactoring to include tests for other sensors to support more systems.

**Comment by microtechno9000** [comment]
@jonathannlittle can you post the output from psutil.sensors_temperatures()

**Comment by microtechno9000** [comment]
Had a look at the psutil package [docs](https://psutil.readthedocs.io/en/latest/), and the documentation seems to indicate that it will return 'coretemp' as an output. Checking on both my laptop and server I at least get coretemp returned, and get the same values back from docker running on my laptop. That said though, both systems are intel architecture. If both @jonathannlittle and @1337-server  are running amd chips then could add a catch in for those systems?

```

>>> psutil.sensors_temperatures()
{'acpitz': [
  shwtemp(label='', current=44.0, high=120.0, critical=120.0),
  shwtemp(label='', current=40.0, high=120.0, critical=120.0)],
'coretemp': [
  shwtemp(label='Package id 0', current=44.0, high=100.0, critical=100.0),
  shwtemp(label='Core 0', current=41.0, high=100.0, critical=100.0),
  shwtemp(label='Core 1', current=42.0, high=100.0, critical=100.0),
  shwtemp(label='Core 2', current=41.0, high=100.0, critical=100.0),
  shwtemp(label='Core 3', current=41.0, high=100.0, critical=100.0)],
'nvme': [
  shwtemp(label='Composite', current=22.85, high=78.85, critical=83.85),
  shwtemp(label='Sensor 1', current=22.85, high=65261.85, critical=65261.85)]}
```
and on my server
```
>>> psutil.sensors_temperatures()
{'coretemp': [
  shwtemp(label='Package id 0', current=66.0, high=80.0, critical=98.0),
  shwtemp(label='Core 0', current=57.0, high=80.0, critical=98.0),
  shwtemp(label='Core 1', current=62.0, high=80.0, critical=98.0),
  shwtemp(label='Core 2', current=67.0, high=80.0, critical=98.0),
  shwtemp(label='Core 3', current=56.0, high=80.0, critical=98.0)]}
```

**Comment by shitwolfymakes** [comment]
That explains things, I'm running AMD as well

**Comment by jonathannlittle** [comment]
Confirms what I said:
```
>>> psutil.sensors_temperatures()
{'radeon': [
    shwtemp( label='', current=63.0, high=None, critical=None)
  ], 
 'atk0110': [
    shwtemp( label='CPU Temperature', current=51.0, high=65.0, critical=95.0), 
    shwtemp( label='MB Temperature', current=43.0, high=45.0, critical=95.0)
  ]
}
```
Same ouput as lm_sensors

**Comment by jonathannlittle** [comment]
@shitwolfymakes See what your chipset uses, either install lm-sensors and run the sensors command or with python with psutil.

If you board also uses atk0110 then my edit should work for you too.

**Comment by shitwolfymakes** [comment]
Believe the chipset for my server box is x-470

**Comment by jonathannlittle** [comment]
@microtechno9000 My ARM's motherboard is an Asus M3A78-T Deluxe with chipset 790FX/SB750

@shitwolfymakes simply installing lm-sensors package if you are running linux on your server it should be in your repros

**Comment by jonathannlittle** [comment]
For more info an old PI has this results:
'''
 psutil.sensors_temperatures()
{'cpu_thermal': [shwtemp(label='', current=44.388, high=None, critical=None)]}
'''

**Comment by shitwolfymakes** [comment]
I got `{}` for `psutil.sensors_temperatures()`

**Comment by jonathannlittle** [comment]
You're out of luck. I have an old gateway with an intel motherboard  D945GCL and give the same results. Also lm-sensors when running sensors-detect runs through a whole host of possible sensor and none were found.

**Comment by microtechno9000** [comment]
> You're out of luck. I have an old gateway with an intel motherboard  D945GCL and give the same results. Also lm-sensors when running sensors-detect runs through a whole host of possible sensor and none were found.

same as which, your other machine or pi?

**Comment by sdjernes** [comment]
I have an AMD Rysen 5800X3D system with an AsRock X570 Creator MB and the temp is not showing for me either.

**Comment by microtechno9000** [comment]
@sdjernes can you post your lmsensors and pyutils results please

**Comment by jonathannlittle** [comment]
@microtechno9000 Great, now I can post! For some reason wouldn't let me before. Might I suggest this refactored code that would be more flexible to edit in the future. Note I am new to Python...

    ```
    def get_cpu_temp(self):
        # sensors to test for
        sensors = ['coretemp', 'atk0110', 'nct6797', 'cpu_thermal']
        # init with clear 'not available' value, but you could still use 0
        cpu_temp = 'N/A'
        try:
            temps = psutil.sensors_temperatures()
            for sensor in sensors:
                found_sensor = temps.get(sensor, None)
                if found_sensor:
                    cpu_temp = found_sensor[0][1]
                    break
        except EnvironmentError:
            cpu_temp = 0
        self.cpu_temp = cpu_temp
```

**Comment by microtechno9000** [comment]
nice, yes that is better. will try that

**Comment by jonathannlittle** [comment]
Not sure best practice, but I assume you just want to trap the EnvironmentError to keep it DRY and keep the N/A value condition the last part should be:

```
    except EnvironmentError:
        pass
    self.cpu_temp = cpu_temp
```
