### ISSUE TITLE
🐋 Docker version runs much slower

### ISSUE THREAD

**Issue by thompcha** [automatic-ripping-machine/automatic-ripping-machine#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When I was using the version that was installed using the [automatic installation script](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Ubuntu-20.04-Automatic-Installation) I was able to use my entire CPU and could rip and complete a transcode job before the next rip finished.

I recently had to reformat my PC (long story) and when I went to reinstall ARM, I saw that the script is no longer supported, so I installed the docker image. The instructions suggested that I leave a core available, and since I only have two cores I set `--cpuset='2,3'` inside start_arm_container.sh

Now, my CPU usage never goes above 50% and each transcode job takes forever. If I set cpuset to 0,1,2,3 will my PC crash? How do I stop the docker so I can update start_arm_container.sh and run it again?

### To Reproduce

1. Follow the [docker install](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker) steps found in the wiki
2. In start_arm_container.sh, set set --cpuset='2,3'

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Same performance as non-docker version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
remove the container named `arm-rippers` with `docker rm arm-rippers`
and remove the cpu line in start_arm_container.sh ?

Personally i never use that line.

**Comment by thompcha** [comment]
Thank you, I didn't know it was optional!
