### ISSUE TITLE
Arm does not detect more of 10 DVD 

### ISSUE THREAD

**Issue by ProNow1** [automatic-ripping-machine/automatic-ripping-machine#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

It seems that this software does not detect more of 10 DVD readers.

### To Reproduce

It is enought to install 11 DVD on the pc (i installed 13)

### What OS are you seeing the problem on?

ubuntu-20.04, ubuntu-18.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

https://hub.docker.com/r/1337server/automatic-ripping-machine

### Expected behavior?

All DVD on pc would be seen

### Relevant log output

```shell
-
```

### Anything else?

-
![2023_02_26_18_21_19_3D](https://user-images.githubusercontent.com/126410433/221426055-c51b2257-06a9-439e-9b52-5bcfb150304a.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ProNow1** [comment]
Purtroppo non trovo corrispondenza con il mio problema.
Sembra quasi che qualcosa nel codice del programma limiti l'enumerazione dei dispositivi DVD a 10.  Es:  var[x] dove la x puo' andare da 0 a 9.
PS: Il sistema Ubuntu rileva tutti i DVD installati.

**Comment by 1337-server** [comment]
This is a known issue.

By default ARM only supports 10 drives. If you want you can very easily add support for more than 10 drives yourself by connecting to the container and run both of these commands changing the `sr0` for the drive number you want to add

`mkdir -p /mnt/dev/sr0`
`echo "/dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab`

So for example, the next 2 commands for you would be 

`mkdir -p /mnt/dev/sr10`
`echo "/dev/sr0  /mnt/dev/sr10  udf,iso9660  users,noauto,exec,utf8,ro  0  0" >> /etc/fstab`

And you keep going until you have the correct number of drives.

**TO WORK THESE MUST BE RUN INSIDE THE CONTAINER**
-----

I did add these changes but never submitted the PR: https://github.com/automatic-ripping-machine/automatic-ripping-machine/commit/4e7227a0a946f42d6251fa080a13785097a2cf42

**Comment by ProNow1** [comment]
Good morning i tryed to add the suggested strings (https://github.com/automatic-ripping-machine/automatic-ripping-machine/commit/0f24dcbcec7d075c2464f48a12995673bda39a31) and commands in the container context but without luck ...the arm detects still 10 DVD


# mkdir -m 0777 -p /mnt/dev/sr10
..(to)
# mkdir -m 0777 -p /mnt/dev/sr19

and strings in /etc/fstab 
-----------------------------
/dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
... (to)
/dev/sr19  /mnt/dev/sr19  udf,iso9660  users,noauto,exec,utf8,ro  0  0
--------------------

Could someone help me? NOTE: This is my installer script:

docker run -d \
   -p "8080:8080" \
   -e ARM_UID="1000" \
   -e ARM_GID="1000" \
   -v "/home/arm:/home/arm" \
   -v "/home/arm/Music:/home/arm/Music" \
   -v "/home/arm/logs:/home/arm/logs" \
   -v "/home/arm/media:/home/arm/media" \
   -v "/home/arm/config:/etc/arm/config" \
   --device=/dev/sr0:/dev/sr0 \
   --device=/dev/sr1:/dev/sr1 \
   --device=/dev/sr2:/dev/sr2 \
   --device=/dev/sr3:/dev/sr3 \
   --device=/dev/sr4:/dev/sr4 \
   --device=/dev/sr5:/dev/sr5 \
   --device=/dev/sr6:/dev/sr6 \
   --device=/dev/sr7:/dev/sr7 \
   --device=/dev/sr8:/dev/sr8 \
   --device=/dev/sr9:/dev/sr9 \
   --device=/dev/sr10:/dev/sr10 \
   --device=/dev/sr11:/dev/sr11 \
   --device=/dev/sr12:/dev/sr12 \
   --device=/dev/sr13:/dev/sr13 \
   --device=/dev/sr14:/dev/sr14 \
   --device=/dev/sr15:/dev/sr15 \
   --device=/dev/sr16:/dev/sr16 \
   --device=/dev/sr17:/dev/sr17 \
   --device=/dev/sr18:/dev/sr18 \
   --device=/dev/sr19:/dev/sr19 \
   --privileged \
   --restart "always" \
   --cpuset-cpus='0-10' \
   --name "arm-rippers" \
   1337server/automatic-ripping-machine:latest

Thank you
