### ISSUE TITLE
Any free alternatives to omdbapi?

### ISSUE THREAD

**Issue by vietnamkong** [automatic-ripping-machine/automatic-ripping-machine#77]

**Comment by ahnooie** [comment]
https://www.themoviedb.org/ might be a possibility, it seems to have a decent API.  I believe it requires registration but access is free.

**Comment by kmarhold** [comment]
IMDb has an API of its own, although it's undocumented. For instance:

http://www.imdb.com/xml/find?json=1&q=blade+runner

See https://stackoverflow.com/a/7744369

**Comment by mbenecke** [comment]
I would vote for "the Movie Database" cause is is an lib available on the PyPI at [tmdbsimple](https://pypi.python.org/pypi/tmdbsimple) or [github](https://github.com/celiao/tmdbsimple/)

**Comment by audioeng** [comment]
I agree, tmdb looks good, this project would fall under the developer license, but i think each person would need to register and obtain an API key. 

Not a big deal, it is just another field a user would need to complete in the config. Logic just needs to handle skipping if the value is empty.

**Comment by muckngrind4** [comment]
Looks like omdbapi is free again (for less than 1000 queries per day).
