### ISSUE TITLE
Prevent concurrent duplicate rips from happening

### ISSUE THREAD

**Issue by melangeaddict** [automatic-ripping-machine/automatic-ripping-machine#774]
**Is your feature request related to a problem? Please describe.**
Sometimes after ripping a disc, my system will eject the drive, and then close it again.  This causes ARM to start ripping the disc again, as there isn't a file with the same name to trigger the 'ALLOW_DUPLICATES' setting to prevent it from happening.  So what happens is I will get 4-5 rips of the same disc happening in parallel until one finishes and prevents others, or I access the web portal and cancel them manually.  (Thanks for that, BTW!)  The end result is that I will get multiple copies of the same files taking up unnecessary space and CPU time.

**Describe the solution you'd like**
ARM already checks to see if a log is being created twice, as it will create the same log name with a timestamp at the end of it.  Perhaps an option could be added in the arm.yaml file that if a timestamp is required for the log name, to simply abort and eject the disc again.  

**Describe alternatives you've considered**
None

**Are you able to help code/implement this feature ?**
Possibly

**Additional context**
I am using Ubuntu 20.04 with two disc drives.  (DVD and Blu-Ray)  I have been using ARM since 2018-ish in one form or another, and have been very happy with it. :-)

**Comment by 1337-server** [comment]
Its not an ideal solution but i use this

https://github.com/1337-server/automatic-ripping-machine/issues/82#issuecomment-897338175

This stops the eject bug pulling the drive back in. But another check to stop this would help things.

NOTE: This is already prevented with DVD discs because we use the CRC number to prevent re-ripping

**Comment by 1337-server** [comment]
I went back over this, and it seems that there is no prevent duplicates with Blu-ray, because of the bypass that checks for crc64 number. So we will need to create a fix for this. I'll also look into redoing the bypass to check for active jobs.

I'll update when I have something.

**Comment by shitwolfymakes** [comment]
Easiest move is to use `job.label` when checking completed and in-progress rips for duplicates. The label never changes even if OMDB or manual update changes the job title.

**Comment by melangeaddict** [comment]
I made a dirty hack in my logging.py file to simply abort if line 33 detects that a previous log with the same name exists.  While this works fine for newer movies, if I try to rip multiple older ones who simply have a title of 'DVD_VIDEO.log' it will also spit them out.  I'm moderately trying to find a better solution, but this one is working for now.

**Comment by 1337-server** [comment]
Closing as this was added with #784
