### ISSUE TITLE
🔧 rip longest title

### ISSUE THREAD

**Issue by heatvent** [automatic-ripping-machine/automatic-ripping-machine#783]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like?

Would it possible to add a makemkv option to rip the longest title rather than a full back up of the disk?  Something like determine the length of each title using the output from robot mode and then just rip which ever title has the longest duration?

I would think most of the time this gets the main title. Occasionally, you might end up with an extended cut version or something like that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Set MAINFEATURE to true in the ripper settings

**Comment by heatvent** [comment]
Maybe I am not understanding the documentation but MAINFEATURE requires a BACKUP by makemkv and then handbrake figures out the main title and transcodes, correct?  From the arm.yaml file...

# Have HandBrake transcode the main feature only.  BluRay discs must have RIPMETHOD="backup" for this to work.
# If MAINFEATURE is true, blurays will be backed up to the HD and then HandBrake will go to work on the backed up
# files.  

I was hoping to simply use the output from makemkv (parse robot mode info) to determine the longest duration title and then use makemkv to copy that title only ... and also skip any transcoding.  I'm not sure I could write the code but it determine each title's lengths, determine the longest title, and then when calling makemkvcon, either (a) set the minlength=longest_title_duration (this might still get more than 1 title), or (b) just add the title number as an argument and rip that specific title.

I realize this may not work all of the time depending on the structure of the bluray.  I have some that seem to have the main title listed like 10 times. But for most, the longest is the main title.  

Thank you.

**Comment by shitwolfymakes** [comment]
Try this with MAINFEATURE = True, RIPMETHOD = mkv, and SKIP_TRANSCODING = True

**Comment by 1337-server** [comment]
This should help a lot, its a bash script that could be converted/attached to ARM fairly simply.

```
#!/bin/bash
echo "Starting search for largest title with makemkv..."
# Get the minimum length. This ensures that only the longest title goes to MKV.
long_title=$(makemkvcon -r --progress=-stdout --messages=-stdout info disc:0 | grep cell | awk '{ print $7 }' | tr -d ')","Title' | sort -nr | head -n1 | awk -F: '{print ($1 * 3600) + ($2 * 60) + $3}')

# show lenth in seconds
echo "Found length=${long_title}. Starting ripping largest title"

# Rip DVD
makemkvcon --minlength="$long_title" --decrypt --progress=-stdout --messages=-stdout --directio=true mkv disc:0 all /home/arm | egrep -i 'added|saving|saved'
echo "fin!"
exit;
```
Taken from here -> https://wiki.indie-it.com/wiki/MakeMKV#Script_to_Rip_Disc_Longest_Title_DVD

I did want to work something like this into ARM but i havent had enough time. I would be much better to only rip the titles you are going to save, especially with larger discs.

But i think the problem i encountered before was this would need to be run in 2 parts. First reading and catching the longest title length and then pulling it into python. Then running the second rip command.
Its not overly difficult, it was just time consuming.

Would be a great addition to ARM though.

**Comment by heatvent** [comment]
I tried that script at it doesn't seem to work.  The output "Found length=" just shows a blank. So makemkvcon just sets the minimum length to nothing and all titles are ripped.  I don't know enough about bash scripts to troubleshoot why the long_title code doesn't seem to work correctly. I think "grep cell" might be looking for the word cell.  The title info from makemkvcon should start with TSINFO: with the title number listed first, then the "code" which I think is 9 for duration, and then the value which should be the duration (e.g. TSINFO:0,9,0,"HH:MM:SS") .  So perhaps that script is old/depricated?  I couldn't tell since I am not an expert with makemkvcon and don't have any programming knowledge on bash scripts.  So I am just fishing for a possible explanation.

It seems like similar logic could easily be injected into the makemkv.py script in the bluray section, just add an else if statement:

 elif job.config.RIPMETHOD == "longest_title" and job.disctype == "bluray":
       use makemkvcon to parse title info for longest duration title
       call makemkvcon to rip longest title 

If I knew how to parse the makemkvcon output to find the durations, sort and select the longest, I would modify myself.  It is just a bit beyond my abilities without investing 20-40 hours figuring it out through researching, trial and error.

**Comment by shitwolfymakes** [comment]
I'll keep this in mind when I work on #589

**Comment by heatvent** [comment]
Sounds good.  FYI, there appears to be some existing code for processing individual titles based on length.  It may be possible to use this as a good starting point.

**Comment by 1337-server** [comment]
Find this in your **arm/arm/ripper/makemkv.py**
```
    elif job.config.RIPMETHOD == "mkv" or job.disctype == "dvd":
        get_track_info(mdisc, job)
        # if no maximum length, process the whole disc in one command
        if int(job.config.MAXLENGTH) > 99998:
```
Replace with this
```
    # Rip Blu-ray without enhanced protection or dvd disc
    elif job.config.RIPMETHOD == "mkv" or job.disctype == "dvd":
        get_track_info(mdisc, job)
        if job.config.MAINFEATURE:
            logging.info("Trying to find mainfeature")
            track = models.Track.query.filter_by(job_id=job.job_id).order_by(models.Track.length.desc()).first()
            rip_mainfeature(job, track, logfile, rawpath)
            return rawpath
        # if no maximum length, process the whole disc in one command
        if int(job.config.MAXLENGTH) > 99998:
```
And then adding this anywhere (its a full function so should be outside of all other functions)

```
def rip_mainfeature(job, track, logfile, rawpath):
    # just right
    logging.info(f"Processing track #{track.track_number} as mainfeature. "
                 f"Length is {track.length} seconds.")
    filepathname = os.path.join(rawpath, track.filename)
    logging.info(f"Ripping title {track.track_number} to {shlex.quote(filepathname)}")
    cmd = f'makemkvcon mkv {job.config.MKV_ARGS} -r --progress=-stdout --messages=-stdout ' \
          f'dev:{job.devpath} {track.track_number} {shlex.quote(rawpath)} ' \
          f'--minlength={track.length}'
    # Possibly update db to say track was ripped
    run_makemkv(cmd, logfile)
```

Seems to work in my testing. But i only ran it a couple of times on some dvds, i would need to test on Blu-rays when i get some time.

But it will only run if the rip method is mkv. It would need to be moved around when the logic is redone.

**Comment by heatvent** [comment]
Thanks, I will give this a try and report back.  One quick question should
the following be elif instead of if .. I could see someone having settings
with MAINFEATURE to TRUE and no MAXLENGTH

        # if no maximum length, process the whole disc in one command
        if int(job.config.MAXLENGTH) > 99998:

**Comment by heatvent** [comment]
So I tried it and it seems to not identify the mainfeature ... from the
log.  Not sure if you need more than this.

Thanks

[03-10-2023 14:44:08] INFO ARM: makemkv.get_track_info Using MakeMKV
to get information on all the tracks on the disc. This will take a few
minutes...
[03-10-2023 14:44:08] DEBUG ARM: makemkv.get_track_info Sending
command: makemkvcon -r --progress=-stdout --messages=-stdout
--minlength=600 --cache=1 info disc:0

[03-10-2023 14:44:17] INFO ARM: makemkv.get_track_info Found 2 titles
[03-10-2023 14:44:17] DEBUG ARM: utils.database_updater
no_of_titles=2:<class 'int'>
[03-10-2023 14:44:17] DEBUG ARM: utils.database_updater successfully
written to the database
[03-10-2023 14:44:17] DEBUG ARM: utils.put_track Track #00 Length:
7387 fps: 23.976 aspect: 16:9 Mainfeature: False Source: MakeMKV
[03-10-2023 14:44:17] DEBUG ARM: utils.database_adder Trying to add Track
[03-10-2023 14:44:18] DEBUG ARM: utils.database_adder successfully
written Track to the database
[03-10-2023 14:44:18] DEBUG ARM: utils.put_track Track #01 Length:
1158 fps: 23.976 aspect: 16:9 Mainfeature: False Source: MakeMKV
[03-10-2023 14:44:18] DEBUG ARM: utils.database_adder Trying to add Track
[03-10-2023 14:44:18] DEBUG ARM: utils.database_adder successfully
written Track to the database
[03-10-2023 14:44:18] INFO ARM: makemkv.makemkv Trying to find mainfeature
[03-10-2023 14:44:18] ERROR ARM: arm_ripper.rip_visual_media MakeMKV
did not complete successfully.  Exiting ARM! Error: name 'models' is
not defined
[03-10-2023 14:44:18] ERROR ARM: main.<module> A fatal error has
occurred and ARM is exiting.  See traceback below for details.
[03-10-2023 14:44:18] DEBUG ARM: utils.database_adder Trying to add
Notifications
[03-10-2023 14:44:18] DEBUG ARM: utils.database_adder successfully
written Notifications to the database
[03-10-2023 14:44:18] DEBUG ARM: models.eject Unmounted disc /dev/sr0
[03-10-2023 14:44:23] DEBUG ARM: models.eject Failed to eject /dev/sr0

**Comment by 1337-server** [comment]
Ahh i forgot the import.


Put this at the top of the file

`from arm.models import models`


somewhere near this 
```
from arm.ripper import utils  # noqa: E402
from arm.ui import db  # noqa: F401, E402
import arm.config.config as cfg  # noqa E402
```

**Comment by heatvent** [comment]
That seems to be working .. at least for my first try.

This is great ... thank you!

**Comment by heatvent** [comment]
FYI, I changed a couple of things to get this to work correctly ...

1. I removed "return rawpath"   This was causing it to exit the function rather than complete and eject the disc.
2. Accordingly, I also changed the following to an elif statement rather than if since the makemkv function did not exit at the prior line

        if int(job.config.MAXLENGTH) > 99998:

3. Finall, in the rip_mainfeature function, I changed the makemkvcon minlength from --minlength={track.length} to --minlength={job.config.MINLENGTH}.  What I found is when we get the discinfo we are using MINLENGTH and if you change to the length of the longest track you get a different number of tracks. I think makemkvcon first finds the tracks based on the length, then tries to rip the requested track number.  So you end up with makemkvcon erroring out unless the longest track is the first track.

**Comment by 1337-server** [comment]
@shitwolfymakes, @microtechno9000 - Do we add this into main ? Or just close and reference if people want to add this themselves ?

**Comment by heatvent** [comment]
I think it’s a good add but of course I am a bit biased … at the very least
it doesn’t hurt anything.  So my vote would be to include it.

**Comment by microtechno9000** [comment]
I am lost with the changes above, what has been updated?
At a minimum, some information should go into the wiki on what MAINFEATURE does

**Comment by 1337-server** [comment]
> I am lost with the changes above, what has been updated? At a minimum, some information should go into the wiki on what MAINFEATURE does

Sorry, thought I replied to this.

Right now `MAINFEATURE` behaves differently for DVD and Blu-ray, for
- DVD Handbrake will only rip the main title and not waste time on the other titles. 
- Blu-ray MakeMKV will rip every title and then only save the largest to the new folder and delete all the other titles. This wastes a huge chunk of time and resources.

The above code forces Blu-rays to behave the same was as handbrake does with DVDs, by scanning the disc first and trying to set only the largest title length as the min title length.

**Comment by heatvent** [comment]
Hi, I think the comments.py file needs to be updated for this change. Currently it talks about having to fully backup blurays and handbrake will select the mainfeature. Also, the SKIP_TRANSCODE comments to not address the fact that MAINFEATURE needs to be TRUE for MakeMKV to select the longest title as the main feature.

"SKIP_TRANSCODE": "# Skip transcoding if you want the original MakeMKV files as your final output\n# This will produce the highest quality videos (and use the most storage)\n# Note: RIPMETHOD must be set to \"mkv\" for this feature to work\n# Note: The largest file will be considered to be the \"main feature\" but there are cases when this is not true\n# to avoid losing a desired track, use this feature with an EXTRAS_SUB value that is not \"None\"",

"MAINFEATURE": "# Have HandBrake transcode the main feature only.  BluRay discs must have RIPMETHOD=\"backup\" for this to work.\n# **If MAINFEATURE is true, blurays will be backed up to the HD and then HandBrake will go to work on the backed up\n# files.  \n# This will require libdvdcss2 be installed**.\n# NOTE: For the most part, HandBrake correctly identifies the main feature on movie DVD's, although it is not perfect. \n# However, it does not handle tv shows well at all.  This setting is only used when the video is identified as a movie.",
