### ISSUE TITLE
🐛 Arm UI won't start Alembic Runtime Error

### ISSUE THREAD

**Issue by flammableliquids** [automatic-ripping-machine/automatic-ripping-machine#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I am doing a bare metal installation, (not docker), on ubuntu 20.04. Following installation instructions directly, and using the latest version. 

I am unable to get the application up and running, due to Alembic None Type error.

### To Reproduce

1. Install Ubuntu 20.04
2. run installation instructions, and wait for UI service startup failure.
3. sudo su - arm to switch to arm user, and run pip3 install of the missing python requirements.
4. run python3 /opt/arm/arm/runui.py to find the above errors

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.6.18

### Expected behavior?

Service to launch / ui to start

### Relevant log output

```shell
arm@armcache:~$ python3 /opt/arm/arm/runui.py
[2023-03-14 09:03:51,883] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2023-03-14 09:03:52,001] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 95623e8c5d58
Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 8, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify  # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import app, db
  File "/opt/arm/arm/../arm/ui/__init__.py", line 65, in <module>
    from arm.ui.database.database import route_database  # noqa: E402,F811
  File "/opt/arm/arm/../arm/ui/database/database.py", line 27, in <module>
    armui_cfg = ui_utils.arm_db_cfg()
  File "/opt/arm/arm/../arm/ui/utils.py", line 198, in arm_db_cfg
    db_update = arm_db_check()
  File "/opt/arm/arm/../arm/ui/utils.py", line 166, in arm_db_check
    db_revision = arm_db_get()
  File "/opt/arm/arm/../arm/ui/utils.py", line 145, in arm_db_get
    db_revision = alembic_db.query.first()
  File "/home/arm/.local/lib/python3.8/site-packages/flask_sqlalchemy/model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
  File "/home/arm/.local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 218, in __call__
    sess = self.registry()
  File "/home/arm/.local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 639, in __call__
    key = self.scopefunc()
  File "/home/arm/.local/lib/python3.8/site-packages/flask_sqlalchemy/session.py", line 102, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/home/arm/.local/lib/python3.8/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
all the install scripts ran ok? nothing threw an error?

**Comment by flammableliquids** [comment]
Yep, it ran fine until it tried to start the UI, where it error'ed out.
(There were additional problems with abcde.conf)

I might wipe OS and try again.

**Comment by 1337-server** [comment]
You are using a newer version of `Flask-SQLAlchemy` it looks like you might be using version 3.0 which doesn't work with ARM currently.

If you edit `INSTALL_LOCATION/arm/ui/database/database.py`

Find 
```
route_database = Blueprint('route_database', __name__,
```

Add this before

```
app.app_context().push()
```

And it should get the UI running. But this will have other issues with the rest of the pages, as none of the other code has been updated to work with the newer version.

It is best to force the installation of the recommended version from the requirements.txt from the main branch.

**Comment by flammableliquids** [comment]
So I have now tested this with a completely fresh installation of Ubuntu 20.
And I can confirm that the bare metal installation fails on two fronts:

1. The following python packages are not installed by default (Should probably have been in requirements.txt):
 bcrypt apprise psutil flask flask_sqlalchemy flask_migrate flask_cors flask_wtf flask_login prettytable musicbrainzngs discid robobrowser pydvdid xmltodict
2. Alembic error. 

The above comment code fixed the problem with Alembic.


For anyone who has this problem before it gets fixed:
switch to the arm user and run 
`pip3 install  bcrypt apprise psutil flask flask_sqlalchemy flask_migrate flask_cors flask_wtf flask_login prettytable musicbrainzngs discid robobrowser pydvdid xmltodict`

and edit the database.py as l33t-server indicates above.

**Comment by flammableliquids** [comment]
@microtechno9000  your opinion please:
I think there are some questions in regards to auth.py

I can't seem to find where the login checks against the configuration parameter of DISABLE_LOGIN, I would have thought that the function should check at the start against this parameter. the page should even challenge, it _should_ just redirect...?

My primary problem is that at around line 71. If no users are found in the user tables, the function should return a re-direct, or return something at that point, OR create an admin user. In my opinion I don't believe it should continue on to challenge for username and password when there is nothing to challenge against.

**Comment by microtechno9000** [comment]
@flammableliquids 
At the moment there is no check against the DISABLE_LOGIN you are correct, it should check that and redirect if no login is enabled. I think some of the authentication logic and presentation also needs an update. Once the notification PR is complete, will add it to the next action to complete.

I have updated the auth.py function as part of the notification PR, have a look at [807 file dif](https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/807/files#diff-06535a8e292b532a74491ea6fa754b8d9fdc6c7783a41590f62717afc2b29de3). The change will catch if there is an error in the database, or it is out dated and needs an update

**Comment by microtechno9000** [comment]
@flammableliquids is this still an issue with a fresh install?
@shitwolfymakes or @1337-server if there is something missing from the requirements, would this not fail within the docker build?

**Comment by weeamoo** [comment]
I installed using the install script on a fresh ubuntu install and I needed to follow the steps above to get this to work

**Comment by microtechno9000** [comment]
Work is under way to update ARM for the new version of Flask-SQLAlchemy. However, it breaks a few things so compatibility needs to be checked. Once that has been completed this issue will be updated with the PR status

**Comment by flammableliquids** [comment]
I am in the process of testing against Ubuntu 22.04.2 
Might try a VM of U-20 and test again.

**Comment by RIP-PloKoon** [comment]
Getting the same error after fresh docker install

**Comment by microtechno9000** [comment]
Closed as stale, ARM has progressed quite a few versions. If this issue still persists please re-open and provide additional logs
