### ISSUE TITLE
🔧 Close all notifications button

### ISSUE THREAD

**Issue by iplusplus42** [automatic-ripping-machine/automatic-ripping-machine#790]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

After many rips, notifications on the ARM web UI can stack up quite significantly. Closing all of them manually is a hassle, so a quicker way to close them all at once would be a major improvement.

### Describe the solution you'd like?

Unraid's notification system has a close all notifications button that appears when more than one notification is visible. I thought that a similar solution would work for ARM.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/5349957/224847350-5ea9a86d-9b32-4bfa-bf7a-2e966f8b5dcd.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Seconded. Closing all these notifications one at a time is a pain in the ass.
