### ISSUE TITLE
🐋 Incorrect permissions for cdrom in docker (Failed to open device /dev/sr0)

### ISSUE THREAD

**Issue by jwr1** [automatic-ripping-machine/automatic-ripping-machine#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When inserting a disc with the docker image running, it doesn't load anything and shows an error in the logs `Failed to open device /dev/sr0 to check status`. It also showed a similar error when running `makemkvcon info dev:/dev/sr0` in the docker container, but when I ran the same command as root in the docker container, it worked just fine. I also ran a chmod on `/dev/sr0` and `/dev/sg2` to see if anything would change, and that did make the disc readable. So my guess is either the `arm` user isn't added to the correct group on docker setup, or there aren't the correct permissions for the previous device paths I mentioned.

It's possible I set it up incorrectly as well, but when I was using a previous version of ARM a few months ago, it was working just fine. Here is my docker command in case it helps:
```sh
docker run -d \
    -p "8080:8080" \
    -e ARM_UID="1000" \
    -e ARM_GID="1000" \
    -v "/home/user/Documents/arm/home:/home/arm" \
    -v "/home/user/Documents/arm/music:/home/arm/Music" \
    -v "/home/user/Documents/arm/logs:/home/arm/logs" \
    -v "/home/user/Documents/arm/media:/home/arm/media" \
    -v "/home/user/Documents/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --privileged \
    --restart "always" \
    --name "arm" \
    --cpuset-cpus='2,3,4,5,6,7' \
    automaticrippingmachine/automatic-ripping-machine:latest
```
Everything else besides what I mentioned above seems to be working correctly.

### To Reproduce

(Everything is explained above.)

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

ARM should run like normal, without me having to manually adjust device file permission within the docker container.

### Relevant log output

```shell
[03-17-2023 15:44:25] INFO ARM: Failed to open device /dev/sr0 to check status.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Please provide the output of the following commands when run on the HOST:
```
id -u <username>
id -g <username>
```

**Comment by jwr12135** [comment]
Both 1000, the same as the docker container defines.

**Comment by shitwolfymakes** [comment]
https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker#post-install

**Comment by microtechno9000** [comment]
ARM creates the mount folders during creation of the docker image and sets the permissions to 777. Looking at the permissions set within docker, I am unable to see any errors or issues

```bash
arm@95cd0ae077ec:/mnt/dev$ ls -la
total 92
drwxr-xr-x 23 root root 4096 Mar 13 09:58 .
drwxr-xr-x  1 root root 4096 Mar 13 09:58 ..
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr0
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr1
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr10
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr11
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr12
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr13
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr14
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr15
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr16
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr17
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr18
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr19
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr2
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr20
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr3
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr4
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr5
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr6
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr7
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr8
drwxrwxrwx  2 root root 4096 Mar 13 09:58 sr9
```

```bash
arm@95cd0ae077ec:/mnt/dev/sr1$ ls -la /dev/sr*
brw-rw---- 1 root cdrom 11, 0 Mar 13 09:58 /dev/sr0
brw-rw---- 1 root cdrom 11, 1 Mar 13 11:21 /dev/sr1
brw-rw---- 1 root cdrom 11, 2 Mar 13 11:17 /dev/sr2
```

```bash
arm@95cd0ae077ec:/mnt/dev/sr1$ cat /etc/group | grep cdrom
cdrom:x:24:arm
```

**Comment by microtechno9000** [comment]
Closing this issue as it doesn't cause ARM to fail
