### ISSUE TITLE
DockerHub image and handbrake nvenc issue

### ISSUE THREAD

**Issue by rpelissi** [automatic-ripping-machine/automatic-ripping-machine#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have succesfully running the official docker image in Docker/Portainer with GPU passthought. inside the container in a shell I can see with nvidia-smi command that my GPU is available but the command 
HandBrakeCLI --help | grep -A12 "Select video encoder" does not show nvenc option.
If I run the command:
`HandBrakeCLI --version`
I see the error 
`Cannot load libnvidia-encode.so.1`

I have check online and found this:
https://github.com/HandBrake/HandBrake/issues/1874

So I give it a try and inside the container I did a
`apt update`

And then installed the missing lib from what I think is the version of the nvidia driver:

```
root@a3ecdbc7adc9:/home/arm# nvidia-smi 
Sat Mar 25 13:26:56 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
```

```
root@a3ecdbc7adc9:/home/arm# apt install libnvidia-encode-470
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libnvidia-compute-470 libnvidia-decode-470
The following NEW packages will be installed:
  libnvidia-compute-470 libnvidia-decode-470 libnvidia-encode-470
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 32.9 MB of archives.
After this operation, 142 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 libnvidia-compute-470 amd64 470.161.03-0ubuntu0.20.04.1 [31.5 MB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 libnvidia-decode-470 amd64 470.161.03-0ubuntu0.20.04.1 [1,376 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 libnvidia-encode-470 amd64 470.161.03-0ubuntu0.20.04.1 [42.2 kB]
Fetched 32.9 MB in 5s (7,225 kB/s)              
Selecting previously unselected package libnvidia-compute-470:amd64.
(Reading database ... 42797 files and directories currently installed.)
Preparing to unpack .../libnvidia-compute-470_470.161.03-0ubuntu0.20.04.1_amd64.deb ...
Unpacking libnvidia-compute-470:amd64 (470.161.03-0ubuntu0.20.04.1) ...
dpkg: error processing archive /var/cache/apt/archives/libnvidia-compute-470_470.161.03-0ubuntu0.20.04.1_amd64.deb (--unpack):
 unable to make backup link of './usr/lib/x86_64-linux-gnu/libcuda.so.470.161.03' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package libnvidia-decode-470:amd64.
Preparing to unpack .../libnvidia-decode-470_470.161.03-0ubuntu0.20.04.1_amd64.deb ...
Unpacking libnvidia-decode-470:amd64 (470.161.03-0ubuntu0.20.04.1) ...
Selecting previously unselected package libnvidia-encode-470:amd64.
Preparing to unpack .../libnvidia-encode-470_470.161.03-0ubuntu0.20.04.1_amd64.deb ...
Unpacking libnvidia-encode-470:amd64 (470.161.03-0ubuntu0.20.04.1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libnvidia-compute-470_470.161.03-0ubuntu0.20.04.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@a3ecdbc7adc9:/home/arm# HandBrakeCLI --version
[13:20:53] Compile-time hardening features are enabled
[13:20:53] qsv: not available on this system
[13:20:53] vcn: not available on this system
[13:20:53] nvenc: version 11.1 is available
[13:20:53] nvdec: is not compiled into this build
[13:20:53] hb_init: starting libhb thread
[13:20:53] thread 7f0309008700 started ("libhb")
HandBrake 1.6.1
```

It seems to have an issue during the setup but now the nvenc encoder option seems to be available:

```
root@a3ecdbc7adc9:/home/arm# HandBrakeCLI --help | grep -A12 "Select video encoder"
[13:21:27] Compile-time hardening features are enabled
[13:21:27] qsv: not available on this system
[13:21:27] vcn: not available on this system
[13:21:27] nvenc: version 11.1 is available
[13:21:27] nvdec: is not compiled into this build
[13:21:27] hb_init: starting libhb thread
[13:21:27] thread 7fb2cbdfd700 started ("libhb")
   -e, --encoder <string>  Select video encoder:
                               svt_av1
                               svt_av1_10bit
                               x264
                               x264_10bit
                               nvenc_h264
                               x265
                               x265_10bit
                               x265_12bit
                               nvenc_h265
                               nvenc_h265_10bit
                               mpeg4
                               mpeg2
HandBrake has exited.
```

### To Reproduce

1- Install portainer on debian 11
2- Add the official docker image with the correct GPU passthrough
3- Validate that the container is working
4- Check that the nvidia driver can see the GPU
5- Validate the encoder options using the handbrake command line

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

The nvenc encoding option should work

### Relevant log output

```shell
Please see above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tjkent88** [comment]
This can be fixed by installing the correct encoder inside of the container, 

`apt-get install libnvidia-encode-<Driver main version>`

It looks like your current major version is 470 so for you it will be 

`apt-get install libnvidia-encode-470`

**Comment by 1337-server** [comment]
Are you using the NVIDIA runtime ?

**Comment by rpelissi** [comment]
Hi,
I know that the nvidia-smi tool is working and detect my card in the docker pod.

**Comment by Tjkent88** [comment]
I am also having an issue where the nvidia-smi command does not work at the start I had to update my container to have the required programs. I tried using images with the tags: latest and nvidia

commands added for container:
`/bin/sh -c add-apt-repository ppa:graphics-drivers/ppa -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -y nvidia-driver-525`

image:
[](https://hub.docker.com/r/tjkent88/arm-ripper-nvidia-525)

I am having some separate issues, but I haven't had time in the last few days to look into it. As such I am not positive my solution works, but it did return nvidia-smi when I used it

**Comment by ernenr1** [comment]
I seem to have a very similar issue, but with QSV instead. Have not found a solution yet, but still trying to figure it out!

https://github.com/automatic-ripping-machine/automatic-ripping-machine/discussions/814

**Comment by 1337-server** [comment]
Can you share your docker run command ?

For example...
```
docker run \
-p 8080:8080 \
-v /home/arm:/home/arm \
-v /home/arm/Music:/home/arm/Music \
-v /home/arm/media:/home/arm/media \
-v /etc/arm/config:/etc/arm/config \
-v /home/arm/logs:/home/arm/logs \
--env ARM_GID=1001 \
--env ARM_UID=1001 \
--env NVIDIA_DRIVER_CAPABILITIES=all \
--name arm-rippers \
--device /dev/sr0 \
--device /dev/sg5 \
--gpus all \
automaticrippingmachine/automatic-ripping-machine:test
```

> I seem to have a very similar issue, but with QSV instead. Have not found a solution yet, but still trying to figure it out!
> 
> #814

Intel media SDK is missing in the main build of our docker image. (I have kept track of this here https://github.com/1337-server/automatic-ripping-machine/issues/263) This is the reason QSV doesn't work with ARM docker currently. When I get more free time, ill add it. Or you could do a PR with testing ?

**Comment by 1337-server** [comment]
Can't replicate, tested on both Debian docker and Ubuntu Docker. If this is still an issue, please let us know and ill re-open.

**Comment by 641i130** [comment]
Replicated on a GTX 1060 system.

Transcoding takes forever and no GPU usage is visible. Please request any additional information needed to solve this. 

> add-apt-repository ppa:graphics-drivers/ppa -y && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y nvidia-driver-525
Trying to run this resulted in nothing useful ^

Docker start command:
```
docker run -d \
    -p "8080:8080" \
    -e ARM_UID="1001" \
    -e ARM_GID="1001" \
    -v "/home/arm/nas:/home/arm" \
    -v "/home/arm/nas/Music:/home/arm/Music" \
    -v "/home/arm/nas/logs:/home/arm/logs" \
    -v "/home/arm/nas/media:/home/arm/media" \
    -v "/home/arm/nas/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='2,3,4,5,6,7' \
    automaticrippingmachine/automatic-ripping-machine:latest
```

I don't run this every time though, I run `docker [start container id]`. 

Also, if possible, how would one transcode files on a separate system? I think this would be an easier 'solution' to this issue for me at least.

***Or***, maybe a way to limit how many transcoding jobs are running. 

### Docker Host:
```
neofetch
            .-/+oossssoo+/-.               host@dockers
        `:+ssssssssssssssssss+:`           -------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.6 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: GA-78LMT-USB3 R2 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-75-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 10 hours, 41 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1909 (dpkg), 9 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/1 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: AMD FX-8370 (8) @ 4.000GHz 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: NVIDIA GeForce GTX 1060 6GB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 1652MiB / 32075MiB 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+                             
   /ssssssssssshdmNNNNmyNMMMMhssssss/                              
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

**Comment by Tjkent88** [comment]
This thread is closed, but I'll help you out. 

You can limit the number of transcodes through the settings in the arm-ripper ui

I created this for the time-being until they get to this repair.

https://hub.docker.com/repository/docker/tjkent88/arm-ripper-nvidia-525/general

**Comment by 1337-server** [comment]
> This thread is closed, but I'll help you out.
> 
> You can limit the number of transcodes through the settings in the arm-ripper ui
> 
> I created this for the time-being until they get to this repair.
> 
> https://hub.docker.com/repository/docker/tjkent88/arm-ripper-nvidia-525/general

Please don't do this, this will only cause more problems. Using another image makes it harder to give support as we don't know which version they are running. It also would only work with users that have the driver version 525. And means it would be more complicated to debug.

This was the main reason we don't offer support for even our own personal fork's docker images. It makes things harder. Thank you for trying to help though!



------

OP:
Your run command is missing some important steps to allow the container to use the GPU
Both `--env NVIDIA_DRIVER_CAPABILITIES=all \`
and `--gpus all \`

You are also not passing in both links to each drive, so for instance 
dev/sr0 might be `/dev/sr0` and `/dev/sg5` and if you are using MakeMKV it's always best to include both as recommended by MakeMKV themselves.
See the wiki here for more info on finding this for your own drives. https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Docker-Troubleshooting#makemkv-cant-find-drives

So, for example, a full docker run command might be this
```
docker run -p 8080:8080 \
-v /home/arm:/home/arm -v /home/arm/Music:/home/arm/Music -v /home/arm/media:/home/arm/media -v /etc/arm/config:/etc/arm/config \
-v /home/arm/logs:/home/arm/logs \
--env ARM_GID=1001 \
--env ARM_UID=1001 \
--env NVIDIA_DRIVER_CAPABILITIES=all \
--name arm-rippers \
--device /dev/sr0 \
--device /dev/sg5 \
--gpus all \
automaticrippingmachine/automatic-ripping-machine:latest 
```

**Comment by 641i130** [comment]
Thank you @1337-server I got it to take my gpu. Now, there's an issue where I don't see it using it. 
Is this the case with transcoding jobs that have been stopped prematurely? Or is handbrake just not going to use my GPU unless I start a new job?
