### ISSUE TITLE
Fatal Error: Invalid literal Int() when ripping multi-disk cd

### ISSUE THREAD

**Issue by Cleanup-Crew-From-Discord** [automatic-ripping-machine/automatic-ripping-machine#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I was trying to rip a new Metallica album I picked up today. The second and third disks rip perfectly, but the first disk fails to rip entirely. It crashes out with the following error popup:
![image](https://user-images.githubusercontent.com/92687025/227821271-5f9b0047-5cd6-49ce-91dd-dbf089af2a58.png)
No one-disk albums had issues, and as stated before disks 2 and 3 ripped without a hitch.

The logs are quite disappointing, with a promise of a traceback but nothing below
[Metallica-Master-of-Puppets_167988167137(2).log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/11074864/Metallica-Master-of-Puppets_167988167137.2.log)

### To Reproduce

Try to rip a cd that is a part of a multi-disk album

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

5a8d06e6d071417c1e2b312fea6589bbeccd00a3

### Expected behavior?

Expected disk to rip like all other disks had and not instantly fail

### Relevant log output

```shell
the specific snippet where it just seems to give up

[03-27-2023 01:47:56] DEBUG ARM: music_brainz.music_brainz discid = 30o65YDrQiZDVLOr_og4cVsmKqM-
[03-27-2023 01:47:56] ERROR ARM: main.<module> A fatal error has occurred and ARM is exiting.  See traceback below for details.
[03-27-2023 01:47:56] DEBUG ARM: utils.database_adder Trying to add Notifications
[03-27-2023 01:47:57] DEBUG ARM: utils.database_adder successfully written Notifications to the database
[03-27-2023 01:47:57] DEBUG ARM: models.eject Unmounted disc /dev/sr0
[03-27-2023 01:47:59] DEBUG ARM: models.eject Failed to eject /dev/sr0
```

### Anything else?

using ubuntu 22.04.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Looks like its crashing in `arm/ripper/music_brainz.py` in line 52
it might be something to do with the json that comes back not matching the expected format.

for later: 
using below means it wont catch the exception with logging as its most likely a key error
`    except mb.WebServiceError as exc:`
using this should catch everything and help for logging
`    except Exception as exc:`
on line 69
