### ISSUE TITLE
docker-setup.sh generates an error when setting up under ubuntu 18.04

### ISSUE THREAD

**Issue by littlejeem** [automatic-ripping-machine/automatic-ripping-machine#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

script runs but throws an error and shows incomplete information

### To Reproduce

1: Fresh install of ubuntu server 18.04
2: Follow wiki instructions for setting up docker 
3: Run ```sudo ./docker-setup.sh```
4: Script runs generating error

### What OS are you seeing the problem on?

ubuntu-18.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

N/A

### Expected behavior?

clean finish to script and for last line to tell me where to look.

### Relevant log output

```shell
Creating mount points
./docker-setup.sh: line 94: /home/arm: Is a directory
Installation complete. A template command to run the ARM container is located in: 
```

### Anything else?

Fresh install of ubuntu 18.04 server.

Followed wiki instructions for setting up docker using the install script docker-setup.sh, script errors at very end of the run

```sudo ./docker-setup.sh```

generates

```
Creating mount points
./docker-setup.sh: line 94: /home/arm: Is a directory
Installation complete. A template command to run the ARM container is located in: 
```

Looking at line 94 the script shows:
`echo -e "${RED}Installation complete. A template command to run the ARM container is located in: $(~arm) ${NC}`

should `$(~arm)` not be `$(echo ~arm)`?

Superficial error really as the template command gets generated in the right place anyway.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
I fixed the formatting so its easier to read.

**Comment by shitwolfymakes** [comment]
Thanks, I'm tracking this and planning Actions to test the installer across a matrix of distros

**Comment by microtechno9000** [comment]
Closing as stale, if the issue is still present, please reopen
