### ISSUE TITLE
DVD decryption error with VirtualBox on MacBook host

### ISSUE THREAD

**Issue by jswetzen** [automatic-ripping-machine/automatic-ripping-machine#81]
I have performed identical installations (with Vagrant) on a PC and a MacBook Pro with an internal SuperDrive. The MacBook can only rip unprotected DVDs, and fails others while the PC handles them fine. This isn't an issue with the A.R.M. but with Macs, and possibly only VirtualBox. I was wondering if anyone else has seen this though?

**Comment by ahnooie** [comment]
I don't have a Mac so it's hard to say, I'd be curious if you have the same behavior using an external drive.

**Comment by jswetzen** [comment]
I tried an external drive, but only for Blu-ray. No luck there either. I
didn't fiddle with it much though. USB peripherals and VirtualBox don't
always go well together though.

**Comment by ahnooie** [comment]
Looks like one person commented on the blog post https://b3n.org/automatic-ripping-machine/ that he is  using Virtualbox on a Mac, but I"m not sure if he ever got it working.

**Comment by jswetzen** [comment]
All my DVDs are ripped now anyway, mostly "manually" with handbrake on Mac.
For the difficult ones, like series, I used a Windows PC.
