### ISSUE TITLE
📚 incorrect naming of template run command

### ISSUE THREAD

**Issue by littlejeem** [automatic-ripping-machine/automatic-ripping-machine#817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

When reading through the docker guide for ARM under the section: `Setup ARM Docker` the guide states:

"Save a copy of the template run command for the user to fill in to `~arm/start_arm_container.sh`"

this naming uses underscores. Later on under `Post Install` the guide states:

"Run the container with sudo `./start-arm-container.sh`"

the naming has changed from underscores to dashes, but the file created matches the naming in the first example.

`start_arm_container.sh`

### The page

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker

### If you are able please provide the correction here

"Run the container with sudo `./start-arm-container.sh`" -> "Run the container with sudo `./start_arm_container.sh`"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Wiki updated!

Thanks.
