### ISSUE TITLE
🐋 Absolutely nothing happens when inserting DVD

### ISSUE THREAD

**Issue by Sabinno** [automatic-ripping-machine/automatic-ripping-machine#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

No logs, no active rips, nothing. I can't really give you more than that unless you ask - nothing happens in ARM, that's it. Ask if you want details from something. I'm stumped.

### To Reproduce

1. Run CentOS 9 Stream in a VM
2. Pass through BDR player as SCSI device directly in KVM (https://www.freesoftwareservers.com/display/FREES/KVM+Passthrough+BluRay+drive+directly+to+VM)
3. Confirm DVD shows up (can see title, size, etc) in VM
4. Mount as either read-only or read-write device at /mnt/dev/sr0, doesn't matter whatsoever
5. Run ARM with `podman run -d -p "8080:8080" -e ARM_UID="1003" -e ARM_GID="1003" -v "/home/arm/home_virt:/home/arm:Z" -v "/srv/media/music:/home/arm/Music:z" -v "./logs:/home/arm/logs:Z" -v "/srv/media/videos:/home/arm/media:z" -v "./config:/etc/arm/config:Z" --device="/dev/sr0:/dev/sr0" --name "arm-rippers" docker.io/automaticrippingmachine/automatic-ripping-machine:latest`
6. Resolve SELinux errors by allowing unfettered access to uevent and allow containers to use devices on host
7. Try harder to resolve errors by disabling SELinux entirely, monitoring udev using `udevadm monitor` (yes, it works, the drive triggers something) to ensure it shows up, force `sudo udevadm trigger /dev/sr0` but to no avail
8. Eventually give up and submit bug report after hours of frustration

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

I expect it would just work. There's nothing special about what I'm doing.

### Relevant log output

```shell
N/A
```

### Anything else?

Is there a way to trigger a rip manually from inside the container or something?
Also, note that this is a rootless container being run as an "arm" user. I WILL NOT run containers as root (and neither should anyone else, ever) - this is extremely insecure and I cannot risk my personal data being compromised or system instability due to untrusted code.

I'll help in any way I can.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Why are you mounting /dev/mnt/Sr0 as a volume ?

Was the listed somewhere in the wiki ?

You said you aren't running rootless? But you are running the --privileged flag still ?

The --privileged flag hasn't been needed for a short while now.

**Comment by Sabinno** [comment]
> Why are you mounting /dev/mnt/Sr0 as a volume ?
For testing purposes. I'm honestly not sure why the installation script would need to mount /dev/sr0 at all otherwise. Should I just unmount it and leave it alone, then?
> Was the listed somewhere in the wiki ?
No, but I can't exactly follow the Wiki step for step.
> You said you aren't running rootless? But you are running the --privileged flag still ?
Troubleshooting. Removing it doesn't do anything either.
> The --privileged flag hasn't been needed for a short while now.
I just now read the PR about that, so that's good.
> Edit: Please ready through he wiki as it has the command to run ARM manually for testing. I am on mobile or I would have linked it.
I'll give that a go momentarily and edit this comment to report back.

I edited the OP with my current config.

**Comment by Sabinno** [comment]
I tried to run the ripper manually with `podman run -d -p "8080:8080" -e ARM_UID="1003" -e ARM_GID="1003" -v "/home/arm/home_virt:/home/arm:Z" -v "/srv/media/music:/home/arm/Music:z" -v "./logs:/home/arm/logs:Z" -v "/srv/media/videos:/home/arm/media:z" -v "./config:/etc/arm/config:Z" --device="/dev/sr0:/dev/sr0" --device="/dev/sg0" --name "arm-rippers" docker.io/automaticrippingmachine/automatic-ripping-machine:latest /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0` to no avail.

This is the error message I get:
`Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 24, in <module>
    from arm.ripper import logger, utils, identify, arm_ripper  # noqa: E402
  File "/opt/arm/arm/__init__.py", line 1, in <module>
    import arm.config
  File "/opt/arm/arm/config/__init__.py", line 1, in <module>
    from . import config  # noqa: F401
  File "/opt/arm/arm/config/config.py", line 70, in <module>
    abcde_config = _load_abcde(abcde_config_path)
  File "/opt/arm/arm/config/config.py", line 22, in _load_abcde
    with open(fp, "r") as abcde_read_file:
PermissionError: [Errno 13] Permission denied: '/etc/arm/config/abcde.conf'`

I revoked write access to abcde.conf to the `arm` user because it kept overwriting it with an invalid symlink for no reason. I followed the instructions [here](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/749#issuecomment-1450518221) with no luck - I changed the location of abcde config in `arm.yaml` via the UI and checked the actual config file, but for some reason ARM is not respecting it and trying to look for the inherently nonexistent /etc/arm/config/abcde.conf no matter what.

I think there's more than one bug at play here.

**Comment by Sabinno** [comment]
I was able to temporarily resolve the former bug by disabling SELinux (never a good idea) and got yet another bug:
```
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 142, in <module>
    job = Job(devpath)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/opt/arm/arm/models/models.py", line 81, in __init__
    self.parse_udev()
  File "/opt/arm/arm/models/models.py", line 106, in parse_udev
    device = pyudev.Devices.from_device_file(context, self.devpath)
  File "/usr/local/lib/python3.8/dist-packages/pyudev/device/_device.py", line 241, in from_device_file
    return cls.from_device_number(context, device_type, device_number)
  File "/usr/local/lib/python3.8/dist-packages/pyudev/device/_device.py", line 198, in from_device_number
    raise DeviceNotFoundByNumberError(typ, number)
pyudev._errors.DeviceNotFoundByNumberError: No block device with number 2816
```

Googling this doesn't even bring about any results, so I can't help you here, unfortunately.

**Comment by microtechno9000** [comment]
The error is coming from Models.py line 106

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/f11e357aa5a04cc8fe4d2aed0d768f6e232baab5/arm/models/models.py#L106

the self.devpath will be something like /dev/sr0

Are you using sr0 or sg0, because ARM is only setup and configured to use sr0
