### ISSUE TITLE
🔧 Feature Request: Add Ability to rip Karaoke Disks (CD+G format)

### ISSUE THREAD

**Issue by TallPatrick** [automatic-ripping-machine/automatic-ripping-machine#845]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

ARM currently can rip Videos, Data Disks, and Audio Disks, but there is a rather niche format which is an offshoot of CD called CD+G.  CD+G is primarily used these days for Karaoke, but there are also a few albums which released with graphical content in this format.

Some introductory reading: https://en.wikipedia.org/wiki/CD%2BG

Some more in depth reading about the technical details of cdg: https://jbum.com//cdg_revealed.html

An old open source project which could be integrated or at least looked at as a starting point: http://kibosh.org/cdgtools/

### Describe the solution you'd like?

When a compatible drive is used and cdg content is on the disk, the mp3 tracks and the corresponding cdg files are placed together in a .zip folder.  This is the ideal solution because most Karaoke software will only read these files if they are a .zip which contains the mp3 and the cdg file.  Best practice also is to have both files have the same file name (other than extension), but most karaoke software doesn't strictly require this.

### Describe alternatives you've considered?

I currently rip Karaoke Disks I buy manually, which is a pain now that I've seen how great ARM is at ripping movies.  Trying to rip Karaoke Disks with ARM just gives me the mp3 files, not the mp3+g.

### Anything else?

Some challenges that I can foresee:

- Not all modern drives support reading the mp3+g content, and will just be able to read the mp3 files.  I don't know of a consistent way to determine if a disk drive is even capable of reading the graphics data

- Very few places/companies are making new cdg disks these days as everything is going fully digital and mainly video files are being used.  That said there are still several Karaoke songs which have not been released digitally, but do exist on disks which many karaoke hosts want to digitize.

- The only open source cdg ripping project I was able to find is over 14 years old.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
This isn't possible to add, as none of the dev team have access to this.
