### ISSUE TITLE
🔧 do not over-write "start_arm_container.sh" if it already exists

### ISSUE THREAD

**Issue by TallPatrick** [automatic-ripping-machine/automatic-ripping-machine#862]
### Is this feature missing in the latest version?

- [ ] I'm using the latest release

### Is your feature request related to a problem? Please describe.

When updating to pull down the latest docker image, I didn't realize it would be wiping out my "start_arm_container.sh" script.  It's a minor annoyance to fill it back out, but it would be nice if it detected a file existed there and didn't overwrite it.  Alternatively, if the format of this file is likely to change, I'd love if the install script would rename the old one.

### Describe the solution you'd like?

existing "start_arm_container.sh" script is somehow preserved

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TallPatrick** [comment]
if you can point me to the install script where "start_arm_container.sh" is created, I could probably suggest a change.

**Comment by TallPatrick** [comment]
Pull request #863 should be a rudimentary implementation of this.  I chose to go with the renaming route, to better future proof against updates to the "start_arm_container.sh" template in the future.

**Comment by microtechno9000** [comment]
if you have the docker image already installed and setup, why are you running the install script again?

**Comment by TallPatrick** [comment]
Because I thought that was what I needed to do to get the latest docker image.  was that incorrect?
