### ISSUE TITLE
🐋./start_arm_container.sh: line 18: IMAGE_NAME: command not found

### ISSUE THREAD

**Issue by poppab** [automatic-ripping-machine/automatic-ripping-machine#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When trying to run ARM in Docker I get the following error

**./start_arm_container.sh: line 18: IMAGE_NAME: command not found**

I am not sure what is supposed to go on line 18 instead of IMAGE_NAME in the start_arm_container.sh script.

### To Reproduce

sudo ./start_arm_container.sh 
using the start_arm_container.sh script after editing it per the Docker WIKI.

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

I expected ARM to run in the Docker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
line 18 of the docker config is a user configured field

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/86a880baab048929bcaa1dfcc87dda599153059b/scripts/docker/start_arm_container.sh#L19C8-L19C8

for example my docker start script looks like

`  --name "automatic-ripping-machine" \
    --cpuset-cpus='2,3' \
    automatic-ripping-machine`

**Comment by poppab** [comment]
I thought so but wasn't sure how to fix it. I will try what you have and see if it works. Thanks

**Comment by poppab** [comment]
Well that didn't work. here is what my error is now
arm@arm:/opt/arm/scripts/docker$ sudo ./start_arm_container.sh
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image
./start_arm_container.sh: line 19: --cpuset-cpus=2,3,4,5,6,7: command not found

here is my start_arm_container.sh script:
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -v "<path_to_arm_user_home_folder>:/home/arm" \
    -v "<path_to_music_folder>:/home/arm/Music" \
    -v "<path_to_logs_folder>:/home/arm/logs" \
    -v "<path_to_media_folder>:/home/arm/media" \
    -v "<path_to_config_folder>:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --device="/dev/sr3:/dev/sr4" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='2,3,4,5,6,7' \
    automatic-ripping-machine

**Comment by microtechno9000** [comment]
where you have "path the config", something needs to go there

for example

```
<path_to_arm_user_home_folder>:/home/arm
```
if using a default location of the arm home directory in linux
```
/home/arm:/home/arm
```

**Comment by poppab** [comment]
I did clean install off Ubuntu 20.04 and Docker version of ARM. ARM UI now starts but inserted DVD do not rip

**Comment by microtechno9000** [comment]
can you post your docker run command
