### ISSUE TITLE
Web Status?

### ISSUE THREAD

**Issue by audioeng** [automatic-ripping-machine/automatic-ripping-machine#87]
I am finding myself very much wanting to know how many discs I have queued up for transcoding, and how much space I have on my drive where the raw RIPs are stored.

I have put together the following Python script to provide this basic info, as well as displaying the empty.log file that seems to be where all activity is logged, in reverse order so newest is at top.

https://gist.github.com/audioeng/fd36d74cf5ee7e2eb3ca7e910f74d39e

Run it as the same user that ARM is running as, root in my case so I use sudo. Go to /info/ URI for the Info page with queue, it auto refreshes every 60 seconds.

If anyone else likes this, I can probably make this into a PR, but I don't want to clean it up too much unless others find value in it.

Screenshot:
![screen shot 2017-09-21 at 12 33 49 am](https://user-images.githubusercontent.com/17124213/30679059-9b7aeb44-9e64-11e7-9177-ca11c81d8cad.png)

**Comment by ahnooie** [comment]
Nice, I think it's useful.  ... we really need to get ARM running as not root. |:-)

**Comment by audioeng** [comment]
Ehh, not a huge deal in my opinion, it’s not like I am going to make this
box externally available or doing anything else... but yes, running as
non-root would be preferred.

I’ll look into pulling some of the hard coded locations out to make it more
universal for a pr (free space is just looking at “/“ now, instead of the
variables in the config file.

I’m not sure how to plug it into running on boot, I am just kicking it off
via ssh right now.

**Comment by audioeng** [comment]
Interestingly enough, because I am seeing all of the queued scripts in mostly real time, I think I figured out why the ID_FS_LABEL variable was showing up for the rip but not the transcode, in #85.

I never see the {media}_rip.sh process run as it is called directly from the identify.sh script, whereas the the video_transcode.sh is handed off to batch `(|at now)` to be queued. That is why the rip script has access to the ID_FS_LABEL variable but the transcode script does not.

Not a big deal, as I think moving to the nicer looking label variable would be preferred anyway.

**Comment by audioeng** [comment]
Has anyone had a chance to test out the basic status and log viewing webpage I put together for #90 ?
The only log I have seen on my instance is empty.log, everything is going there, so that is all I am handling at the moment. 

Are others getting other log file names as it looks like the code has in it? If so, I can add the logic in to display the list of log files and allow you to select the one to view.

I find I rarely look at the log now that I can see the queue and disk status. If others find it useful, I could add in other options like cancelling a queued item or something. 

Thanks @ahnooie again for this project, I am making my way through my DVD collection with much greater speed than I was previously, entirely manually!

**Comment by stre1026** [comment]
@audioeng I tried using your script because I think it would be super useful. However, I'm getting an error every time I try to run the script. I'm not a Python expert by any means so I could have screwed something up. This happens when I run it as root or as a normal user. Any ideas?

  File "logserve.py", line 36
    def getsize(path)
                    ^
SyntaxError: invalid syntax

**Comment by audioeng** [comment]
Ahh yes, I missed that as well, darn colons!

**Comment by muckngrind4** [comment]
Manually pulled into V2.
