### ISSUE TITLE
Subtitles not ripping to MP4s

### ISSUE THREAD

**Issue by DeadlyDad** [automatic-ripping-machine/automatic-ripping-machine#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Turning on subtitles only shows 'Chapter 1', etc., in both DVDs and Blu-rays.

### To Reproduce

I followed the step-by-step directions exactly.  Twice.  From bare metal.  The only changes to the default setup are to use the backup method, main feature = true, and output extension mp4.

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

86a880baab048929bcaa1dfcc87dda599153059b

### Expected behavior?

The resulting MP4s to have the proper, English subtitles.

### Relevant log output

```shell
I don't know which parts of the log are relevant, so here is the whole thing, minus the percentage bits.

[LILOSTITCH_US.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/11924447/LILOSTITCH_US.log)
```

### Anything else?

If you need anything else, *PLEASE* let me know.  I'm trying to help a friend rip her whole collection of Disney DVDs/Blu-rays so she can store the originals away safely.

Thank you for your service.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Looks like a config issue.

Try using `-s "1,2,3,4,5,6"` for ` HB_ARGS_DVD: ` and ` HB_ARGS_BD: `
instead of 

```
hb_args_dvd: --subtitle scan -F
hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
```
**Note:**
If you are entering this on the UI it will enter it correctly for you, but if you are editing via the arm.yaml you need to escape the quotes so  `-s "1,2,3,4,5,6"` becomes `-s \"1,2,3,4,5,6\"`. Entering this without quotes in the arm.yaml crashes ARM.

**Comment by DeadlyDad** [comment]
> Looks like a config issue.
> 
> Try using `-s "1,2,3,4,5,6"` for `HB_ARGS_DVD:` and `HB_ARGS_BD:` instead of
> 
> ```
> hb_args_dvd: --subtitle scan -F
> hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
> ```
> 
> **Note:** If you are entering this on the UI it will enter it correctly for you, but if you are editing via the arm.yaml you need to escape the quotes so `-s "1,2,3,4,5,6"` becomes `-s \"1,2,3,4,5,6\"`. Entering this without quotes in the arm.yaml crashes ARM.

That works perfectly so far.  Thanks!

**Comment by 1337-server** [comment]
Glad to hear. I'll close this now.
