### ISSUE TITLE
🐛 Update wget command to use correct branch for Intel QSV Support Script

### ISSUE THREAD

**Issue by cyle1116** [automatic-ripping-machine/automatic-ripping-machine#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

These instructions from the [Adding Intel Quick Sync Support Wiki](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/intel-qsv):

sudo apt install wget
wget sudo apt install wget
wget https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/v2_devel/scripts/ubuntu-quicksync.sh 
sudo chmod +x ubuntu-quicksync.sh
sudo ./ubuntu-quicksync.shsudo chmod +x ubuntu-quicksync.sh
sudo ./ubuntu-quicksync.sh

Has the "v2_devel" branch when it should be "main" now I think

### To Reproduce

Try to open https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/v2_devel/scripts/ubuntu-quicksync.sh 

### What OS are you seeing the problem on?

all

### ARM Release Version or Git hash (You can find this in the arm settings page)

All

### Expected behavior?

URL should be valid

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Thanks, page is now updated!
