### ISSUE TITLE
🔧 Custom Handbrake Json / Preset

### ISSUE THREAD

**Issue by ThePianoMan2255** [automatic-ripping-machine/automatic-ripping-machine#890]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Currently I am just setting up ARM and have a custom JSON I usually use with handbrake CLI, however, I can't seem to use it because ARM uses the -preset tag when a custom json uses an --preset-import-file tag the forum attached shows it.

https://www.truenas.com/community/threads/set-a-custom-preset-for-handbrakecli-in-freenas.58434/#:~:text=Call%20it%20using%20the%20following%20command%20HandBrakeCLI%20--preset-import-file,want%29%22%20-i%20%2Fmnt%2Fpath%2Fto%2Fmedia_file%2Fmy_video.MTS%20-o%20%2Fmnt%2Fpath%2Fto%2Fconverted%2Ffile%2Flocation%2Foutput.mp4%20It%20uses%20PresetName.

I have created my own presets and would really like for the ability to use them. It would be nice as a "custom handbrake preset" checkmark and then it has a path under it in which you can specify the path for the file.

### Describe the solution you'd like?

Would like a setting in ARM settings that allows for custom handbrake presets by json path. 

Custom handbrake preset: yes
Path to preset: /mnt/preset.json

### Describe alternatives you've considered?

ability to edit handbrakecli script, but I have yet to find it in the docker.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Aren't you using the `HB_ARGS_DVD` and  `HB_ARGS_BD` to push in your config ?

So you normally add the custom presets via those with something like this 

`--subtitle scan -F --preset-import-file /mnt/path/to/custom_preset.json -Z "give it a name (any name you want)"`
inside the setting `HB_ARGS_DVD` as, it's a custom file and isn't inside Handbrake by default.

Currently, the `HB_PRESET_DVD` are used for the predefined presets that come baked into HandBrake. You can if you really wanted to use the setting `HB_PRESET_DVD` bake those into your own HandBrake version when compiling.
This can be tricky for newer users to achieve, but is very much possible if you are experienced with coding. But depending on your use case, this may not be worthwhile.
Let me know if this is specifically what you want, and I can help with instructions to make it easier.

Hope this helps.

**Comment by ThePianoMan2255** [comment]
Currently handbrake cli is returning exit code 2, from what I understand this is related to invalid input. Currently I don't have subtitles setup to grab, so I have it setup correctly with 
`--preset-import-file /mnt/path/to/custom_preset.json -Z "give it a name (any name you want)"`

I then have cusom_preset_name in what preset to use and gives me exit code 2. Not sure if its because --preset-import-file is after -preset because if it is in order it would not get inputed until after it is called.

**Comment by ThePianoMan2255** [comment]
`--preset-import-file /mnt/Media_Library/ARM/CPUBLURAYBurn.json -Z "BLURAYBurn"`

gives me 

> Preset import failed, file (/mnt/Media_Library/ARM/CPUBLURAYBurn.json)
HandBrake 1.6.1 (2023071000) - Linux x86_64 - https://handbrake.fr
4 CPUs detected
Invalid preset BLURAYBurn
Valid presets are:
Listed Presets but none are of my preset. 

It seems like this should work, but it doesnt. No feature is required just not as familiar with handbrake CLI as I am with GUI.

**Comment by ThePianoMan2255** [comment]
> `--preset-import-file /mnt/Media_Library/ARM/CPUBLURAYBurn.json -Z "BLURAYBurn"`
> 
> gives me
> 
> > Preset import failed, file (/mnt/Media_Library/ARM/CPUBLURAYBurn.json)
> > HandBrake 1.6.1 (2023071000) - Linux x86_64 - https://handbrake.fr
> > 4 CPUs detected
> > Invalid preset BLURAYBurn
> > Valid presets are:
> > Listed Presets but none are of my preset.
> 
> It seems like this should work, but it doesnt. No feature is required just not as familiar with handbrake CLI as I am with GUI.

I apparently forgot I was writing in Docker context and not host context. testing again now with correctly added volume map with files.

**Comment by ThePianoMan2255** [comment]
After adding the volume, adjusting the path and preset name it is now working. Thank you!
