### ISSUE TITLE
ARM🔧 <title>WebUI

### ISSUE THREAD

**Issue by Mightyretro** [automatic-ripping-machine/automatic-ripping-machine#900]
### Is this feature missing in the latest version?

- [ ] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Hi guys love your project keep it up ;)

1. is it possible to make WebUI to interact and config with remotely "locally lan"?

2. you should implement some options so that ARM or See status "https://www.virtualhere.com/" nice project that makes usb over network.

Ps. Sorry for my english ;)

Kind Regards // Mighty

### Describe the solution you'd like?

Hi guys love your project keep it up ;)

1. is it possible to make WebUI to interact and config with remotely "locally lan"?

2. you should implement some options so that ARM or See status "https://www.virtualhere.com/" nice project that makes usb over network.

Ps. Sorry for my english ;)

Kind Regards // Mighty

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
I presume you are wanting to use a USB drive for ARM?

if you setup the system and the drive appears as a /dev/srX drive then it would work with ARM.

**Comment by Mightyretro** [comment]
Do you also have WebUI? becouse i find this screenshot down below and think it would be handy if you like me "Remote homelab" see ripping status, transcode and media info

https://github.com/automatic-ripping-machine/automatic-ripping-machine/discussions/540

**Comment by microtechno9000** [comment]
From the ARM UI or web page you can see all the status and config of the jobs. All of this is available remotely (within the local LAN) using the docker image.

I am not sure what the remote software you mentioned would allow a user to achieve, that isn't already covered by the UI
