### ISSUE TITLE
🔧 Feature Request: Protection from dumb Blu Ray disc layouts with redundant video tracks

### ISSUE THREAD

**Issue by TallPatrick** [automatic-ripping-machine/automatic-ripping-machine#904]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Today I was ripping Knives Out, and ARM Reported it found 289 titles on the disc from MakeMKV.  I pulled up the disc on my desktop in MakeMKV and was able to confirm that it does in fact have that many titles, because it has a couple hundred copies of the main feature, each taking up about 29GB each (see attached picture for some of them).  In trying to do this, the HDD of my ripping machine filled up very quickly and I had to abandon the job and rip manually.  I've seen other discs laid out this way (see issue I opened #849), this one is by far the most egregious.

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/32583806/6978a088-fc59-4845-bf35-f360b03a8cf5)

### Describe the solution you'd like?

It would be great if there were a way to make an educated guess when ripping that if there are several video titles identified with either a very similar size to the largest title, or if there are several video titles with the same overall length (and that length is over an hour, so you don't skip TV episodes), ARM should only rip the first one on the disc.

### Anything else?

Doing this in a fool-proof way would be hard with unidentified video discs, but there could be an option given to override this new behavior for those edge cases where this would apply.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
This should be already added for DVD's, so it shouldn't be hard to add for Blu-rays

**Comment by 1337-server** [comment]
Thinking about this, doesn't mainfeature currently prevent against this ?

**Comment by TallPatrick** [comment]
@1337-server probably?  Would it still catch this if I'm too slow to set that option before the ripping starts?

Also maybe as a further improvement, if after getting the list of titles from MakeMKV (which should include sizes), if mainfeature is not selected, and the total size of all the titles is greater than the free disk space, mainfeature should be forced on so the rip can at least complete.

**Comment by 1337-server** [comment]
This should already be part of arm if you are using the "mainfeature" setting

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/8a4769fc6671edd0aa36dc99bf23b91b98bbcbda/arm/ripper/makemkv.py#L70
