### ISSUE TITLE
Password Reset or Recovery🔧 <title>

### ISSUE THREAD

**Issue by HughSparks** [automatic-ripping-machine/automatic-ripping-machine#908]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I recently set a new password and seemed to have set it wrong. There is no way as far as I can tell to reset or recover a password.

### Describe the solution you'd like?

A command line tool or file to edit to recover my password with. It would be nice to do it with email but that may not be necessary. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
No there isn't a way to recover the password. however it is possible to turn off the password by modifying the arm.yaml config and turning off the password

**Comment by 1337-server** [comment]
You could also edit the database manually using something like `db browser for sqlite`

The passwords are hashed using `bcrypt.hashpw`
