### ISSUE TITLE
🐛 ARM found 0 new drives

### ISSUE THREAD

**Issue by evrpress** [automatic-ripping-machine/automatic-ripping-machine#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I'm on a Mac (Catalina) and like to use ARM within a docker. So far so good but I'm not able to list my external DVD drive

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/881729/68cce4c7-9a4d-4723-8cfd-7c31ec0f51ca)

Any help is highly appricated.

### To Reproduce

1. Start the docker container
2. Goto http://localhost:8080/settings
3. Click on "[Scan for Drives](http://localhost:8080/systemdrivescan)"

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

2.6.55

### Expected behavior?

Find my DVD drive

### Anything else?

I'm on a Mac running this command to get the container:

```
docker run -d \
   -p "8080:8080" \
   -e ARM_UID="1001" \
   -e ARM_GID="1001" \
   -v "/home/arm:/home/arm" \
   -v "/home/arm/Music:/home/arm/Music" \
   -v "/home/arm/logs:/home/arm/logs" \
   -v "/home/arm/media:/home/arm/media" \
   -v "/home/arm/config:/etc/arm/config" \
   --device=/dev/sr0:/dev/sr0 \
   --device=/dev/sr1:/dev/sr1 \
   --device=/dev/sr2:/dev/sr2 \
   --device=/dev/sr3:/dev/sr3 \
   --privileged \
   --restart "always" \
   --name "arm-rippers" \
   1337server/automatic-ripping-machine:latest
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Without seeing the debug output it is hard to see what us going on.

1. From the settings page could you set ARM to debug 
2. then run the scan again 
3. paste the output from the scan to this post (Webui.log)

**Comment by evrpress** [comment]
Thanks for the quick response!

So I've turned `LOGLEVEL` to "DEBUG"

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/881729/61316b63-c8fb-404b-844b-3509abf13f87)

Then hit the "Scan for Drives" again.

Check the `/home/arm/logs/` and the `/home/arm/logs/progress` directory which are both empty.

Also when I go to "[View Logs](http://localhost:8080/listlogs)" there are no logs

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/881729/8f6b3ded-4bc2-4ec0-91b1-fbc095f3f3f4)

**Comment by evrpress** [comment]
I guess it's related to my CD Drive is maybe not in one of these:

```
...
   --device=/dev/sr0:/dev/sr0 \
   --device=/dev/sr1:/dev/sr1 \
   --device=/dev/sr2:/dev/sr2 \
   --device=/dev/sr3:/dev/sr3 \
...
```

**Comment by 1337-server** [comment]
> I guess it's related to my CD Drive is maybe not in one of these:
> 
> ```
> ...
>    --device=/dev/sr0:/dev/sr0 \
>    --device=/dev/sr1:/dev/sr1 \
>    --device=/dev/sr2:/dev/sr2 \
>    --device=/dev/sr3:/dev/sr3 \
> ...
> ```

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Docker-Troubleshooting#makemkv-cant-find-drives

Find the correct drive and pass it in.

**Comment by evrpress** [comment]
Thanks again!

I tried that already but `lsscsi` is not available on Mac so I use `df` which returns the location of the drive like `/dev/disk2`

The problem is that it also show up **only if a disc is inserted**, if no disk is inserted it's missing.

I've also tried to replace

```
 --device=/dev/sr0:/dev/sr0
```

with

```
 --device=/dev/disk2:/dev/sr0
```

But then I get 

```docker: Error response from daemon: error gathering device information while adding custom device "/dev/disk2": no such file or directory.```

If you could help me find the right search term for Google I'm sure I may find the solution, but since I'm not certain what the problem actually is I'm stuck :(

**Comment by evrpress** [comment]
Well, I guess [this is the reason](https://docs.docker.com/desktop/faqs/general/#can-i-pass-through-a-usb-device-to-a-container) :(

**Comment by 1337-server** [comment]
Doesn't look like this is fixable on our end.
