### ISSUE TITLE
🐋 OMV6 Docker Install "Permission Denied"

### ISSUE THREAD

**Issue by t3dc** [automatic-ripping-machine/automatic-ripping-machine#916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Stepping through the docker install directions, the script errors out just after "pulling image" with the following message:

`permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=automaticrippingmachine%2Fautomatic-ripping-machine&tag=latest": dial unix /var/run/docker.sock: connect: permission denied`

`# ls -al /var/run/docker.sock 
srw-rw---- 1 root docker 0 Aug 12 16:37 /var/run/docker.sock`

I have several other docker containers running on the system without issue. I'm happy to manually build a docker container, but don't see instructions for that.

Any help would be appreciated.

### To Reproduce

`# ./docker-setup.sh`

I also tried su - arm and redoing the install instructions as the arm user. Error is the same.

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

It's not too surprising that the script doesn't work in every possible instance, but a guide to a manual docker install for situations in which the script fails would be very helpful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by t3dc** [comment]
My mistake. I was running as root. Once I properly configured the arm user, it worked fine.

**Comment by caseodilla** [comment]
For posterity, I was experiencing this same error message, and I discovered my problem was that my Docker installation still required sudo to run commands, so I used [this fix](https://askubuntu.com/a/739861) to allow user `arm` to execute the Docker command without sudo.

**Comment by charmarkk** [comment]
> For posterity, I was experiencing this same error message, and I discovered my problem was that my Docker installation still required sudo to run commands, so I used [this fix](https://askubuntu.com/a/739861) to allow user `arm` to execute the Docker command without sudo.

Thanks for this. As someone new to Docker this was helpful! @1337-server this might be helpful to include in docs somewhere.

**Comment by microtechno9000** [comment]
If the docs need updating, was it just that the arm user was not in the docker user group?

**Comment by charmarkk** [comment]
I believe that was it, making that change got it going again. I _think_ I saw it somewhere else in the wiki after looking around for a while, but it wasn't explicitly in the setup guide.
