### ISSUE TITLE
"docker run" requires at least 1 argument.🐋 

### ISSUE THREAD

**Issue by poppab** [automatic-ripping-machine/automatic-ripping-machine#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

when starting ARM as follows:
**arm@arm:~$ sudo ./start_arm_container.sh**

I get this error:
**"docker run" requires at least 1 argument.**
**See 'docker run --help'.**

**Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]**

**Create and run a new container from an image
./start_arm_container.sh: line 15: --device=/dev/sr0:/dev/sr0: No such file or directory**

Here is the start_arm_container.sh file.
#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -v "/home/arm" \
    -v "/home/arm/Music" \
    -v "/home/arm/logs" \
    -v "/media/arm/RIP_Drive/TV_Shows" \
    -v "/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --device="/dev/sr4:/dev/sr4" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='2,3,4,5,6,7' \
    automaticrippingmachine/automatic-ripping-machine:latest

To me it looks like the -d argument should satisfy docker and it should run. Not sure what to fix.

If you see any other errors/things I can fix please let me know about them as well.

Also in addition to editing this file does the arm.yaml file need to be edited to show the locations where files are to be stored?

Thanks
poppab

### To Reproduce

when starting ARM as follows:
**arm@arm:~$ sudo ./start_arm_container.sh**

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Docker/ARM should start

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Thanks for joining ARM

you are missing config for the volumes,  they should have a source and a destination.

https://docs.docker.com/storage/volumes/

`... -v /home/arm:/home/arm ...`

**Comment by poppab** [comment]
I updated the start_arm_container.sh file but I still get the same error message as before. I am an amateur linux user and am not very sure about what to do with this so please any extra help you can give will be greatly appreciated.

"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image
./start_arm_container.sh: line 15: --device=/dev/sr0:/dev/sr0: No such file or directory

Here is the updated ./start_arm_container.sh file. The lines that start with -v are the only things I updated from before:

#!/bin/bash
docker run -d \
    -p "8080:8080" \
    -v "/home/arm:/home/arm" \
   -v "/home/arm/Music:/home/arm/Music" \
   -v "/home/arm/logs:/home/arm/logs" \
   -v "/media/arm/RIP_Drive/TV_Shows:/media/arm/RIP_Drive/TV_Shows" \
   -v "/etc/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --device="/dev/sr4:/dev/sr4" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='2,3,4,5,6,7' \
    automaticrippingmachine/automatic-ripping-machine:latest

**Comment by 1337-server** [comment]
> I updated the start_arm_container.sh file but I still get the same error message as before. I am an amateur linux user and am not very sure about what to do with this so please any extra help you can give will be greatly appreciated.
> 
> "docker run" requires at least 1 argument. See 'docker run --help'.
> 
> Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
> 
> Create and run a new container from an image ./start_arm_container.sh: line 15: --device=/dev/sr0:/dev/sr0: No such file or directory
> 
> Here is the updated ./start_arm_container.sh file. The lines that start with -v are the only things I updated from before:
> 
> #!/bin/bash docker run -d -p "8080:8080" -v "/home/arm:/home/arm" -v "/home/arm/Music:/home/arm/Music" -v "/home/arm/logs:/home/arm/logs" -v "/media/arm/RIP_Drive/TV_Shows:/media/arm/RIP_Drive/TV_Shows" -v "/etc/arm/config:/etc/arm/config" --device="/dev/sr0:/dev/sr0" --device="/dev/sr1:/dev/sr1" --device="/dev/sr2:/dev/sr2" --device="/dev/sr3:/dev/sr3" --device="/dev/sr4:/dev/sr4" --privileged --restart "always" --name "arm-rippers" --cpuset-cpus='2,3,4,5,6,7' automaticrippingmachine/automatic-ripping-machine:latest

You need to make sure those devices actually exist

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Docker-Troubleshooting#makemkv-cant-find-drives

Once you have found the drives that exist, remove the extra --device entries that don't exist

**Comment by poppab** [comment]
Here is the list of drives on my machine. 
arm@arm:~$ sudo lsscsi -g
[sudo] password for arm:

**DVD/BD Drives
[0:0:0:0] cd/dvd HL-DT-ST BDDVDRW CH12LS28 1.00 /dev/sr0 /dev/sg0
[1:0:0:0] cd/dvd HL-DT-ST BD-RE WH16NS60 1.03 /dev/sr1 /dev/sg1
[2:0:0:0] cd/dvd HL-DT-ST DVDRAM GH24NS90 IN00 /dev/sr2 /dev/sg2
[3:0:0:0] cd/dvd PLEXTOR PX-891SAF 1.JN /dev/sr3 /dev/sg3
[4:0:0:0] cd/dvd HL-DT-ST BD-RE WH16NS60 1.02 /dev/sr4 /dev/sg4**

**this is my OS hard Drive
[5:0:0:0] disk ATA WDC WD20EZAZ-00L 0A80 /dev/sda /dev/sg5**

**this is the external drive that I want my movies/TV shows to be saved to.
[6:0:0:0] disk WD easystore 2648 1031 /dev/sdb /dev/sg6 
[6:0:0:1]    enclosu WD       SES Device       1031  -          /dev/sg7 Not sure what this is appears to be related to WD Easystore drive** 

What is the proper way to list **cd/dvd  HL-DT-ST BDDVDRW CH12LS28 1.00  /dev/sr0   /dev/sg0** in the start_arm_container.sh file? If neither way is correct please let me know how they need to be listed.
A. 
--device="/dev/sr0:/dev/sr0" 
--device="/dev/sg0:/dev/sg0"

or

B. 
--device="/dev/sr0:/dev/sg0" 

Using Docker seems much more complicated that the old bare metal PC methods was.
Thanks for your help
poppab

**Comment by 1337-server** [comment]
Its A

**Comment by poppab** [comment]
Gave up on docker. Used old “bare metal PC” version. Got it up and running works fine does all I need without all the complications of Linux and Docker.
