### ISSUE TITLE
🔧 Eject disc as soon as ripping is complete

### ISSUE THREAD

**Issue by blitmap** [automatic-ripping-machine/automatic-ripping-machine#921]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Most of us have a limited number of drives available for ARM.  ARM only seems to eject the disc when the entire ripping + transcoding operation is over.

### Describe the solution you'd like?

I'd like ARM to eject the disc as soon as the ripping/copying operation is finished.  The media may continue being transcoded, but the disc is no longer necessary.  It should be possible to rip-rip-rip 3 discs 1 after another, and have the transcoding of these complete at a later time.

### Describe alternatives you've considered?

None

### Anything else?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Already answered here: https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/FAQ#arm-wont-eject-the-dvd-until-it-finishes-transcoding
