### ISSUE TITLE
🐛 Dev-Guide in wiki broken

### ISSUE THREAD

**Issue by newhinton** [automatic-ripping-machine/automatic-ripping-machine#926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Visiting the dev-section in the wiki leads to an error message that i am not allowed to edit the wiki:
![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/25279821/1f474026-90d6-4d13-8b3d-fd5304e18366)

http://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Dev-quickstart

it leads back to the home-section

### To Reproduce

Visit http://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Dev-quickstart

### What OS are you seeing the problem on?

all

### ARM Release Version or Git hash (You can find this in the arm settings page)

Not Applicable

### Expected behavior?

View the dev-setup-guide

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Ah, that page was deleted. Forgot to get rid of the link on the main page. Thanks for pointing it out!
