### ISSUE TITLE
🔧 'None' in notifications (Music rip)

### ISSUE THREAD

**Issue by j4c3** [automatic-ripping-machine/automatic-ripping-machine#929]
### Is this feature missing in the latest version?

- [ ] I'm using the latest release

### Is your feature request related to a problem? Please describe.

When I rip music, the notifications in the ARM UI, and elsewhere display a message like:
        Found music CD: None. Ripping all tracks

The None feels weird. 

### Describe the solution you'd like?

I took a look at utils.py, and on line 88, and job.label really does contain 'None':
        notify(job, NOTIFY_TITLE, f"Found music CD: {job.label}. Ripping all tracks")

Should it?  job.title has the album title, would that be better, or is job.label not being generated before being passed to the notify function?

This same thing happens with the job complete notifications. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
at the moment the music ripping process doesn't identify the disks 100% of the time based on the disk title. The none is a valid return state for some instances 
Once musicbrainz kicks in and commences the rip the title gets updated, but the early ID isn't super accurate 

It is on the list to resolve

**Comment by microtechno9000** [comment]
Once approved, see if PR #980  fixes this issue for you. If not, will look into this further.

**Comment by 1337-server** [comment]
Please test with latest version. If it's not fixed, ping and we can reopen.
