### ISSUE TITLE
DVD might have a label containing a '/'

### ISSUE THREAD

**Issue by sphaero** [automatic-ripping-machine/automatic-ripping-machine#933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have a DVD which has the following label:
```
(Pdb) job.label
'_DVD_BFIB1165/2_'
```
This results in a log file in a directory which raises the following exception:
```
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 143, in <module>
    log_file = logger.setup_logging(job)
  File "/opt/arm/arm/ripper/logger.py", line 40, in setup_logging
    logging.basicConfig(filename=log_full,
  File "/usr/lib/python3.8/logging/__init__.py", line 1988, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/arm/logs/_DVD_BFIB1165/2_.log'
```

### To Reproduce

To reproduce this run ARM on a DVD with a label containing a '/'

### What OS are you seeing the problem on?

all

### ARM Release Version or Git hash (You can find this in the arm settings page)

A.R.M version: 2.6.12
Current git version:
94483b1b3766a6c5ce35a6df43d8d81ff8d474c1

I still have to update but the offending code (ripper/logger.py) hasn't been updated recently

### Expected behavior?

We could parse the label to a valid filename or we could check whether the path to the log file exists and otherwise create the path?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
Yeah, I can see how this might cause a problem with something like Face/Off. I'll put a copy of it on my list to buy for testing. Thanks, added to the Known Issues wiki page

**Comment by rootlessNL** [comment]
I'm using the following diff as a workaround:

```
index 7cde7ea..a95246b 100755
--- a/arm/ripper/logger.py
+++ b/arm/ripper/logger.py
@@ -27,8 +27,9 @@ def setup_logging(job):
         # set a log_full for empty.log and music_cd.log
         log_full = os.path.join(cfg.arm_config['LOGPATH'], logfile)
     else:
-        log_file_name = f"{job.label}.log"
-        new_log_file = f"{job.label}_{job.stage}.log"
+        valid_label = job.label.replace("/", "_")
+        log_file_name = f"{valid_label}.log"
+        new_log_file = f"{valid_label}_{job.stage}.log"
         temp_log_full = os.path.join(cfg.arm_config['LOGPATH'], log_file_name)
         log_file = new_log_file if os.path.isfile(temp_log_full) else log_file_name
         log_full = os.path.join(cfg.arm_config['LOGPATH'], log_file)

```

**Comment by knightau** [comment]
Similar issue.  TMDB seems to not be able to cope with underscores in titles.  Running a search on a title with underscores between words yields no results, whereas running the same search with spaces works fine.  So, for TMDB purposes, underscores in disk labels should also be replaced with spaces.
