### ISSUE TITLE
📚 Are the AMD VCE support instructions up to date?

### ISSUE THREAD

**Issue by heatvent** [automatic-ripping-machine/automatic-ripping-machine#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

I tried the script to enable AMD VCE and the quicksync script seems to have moved so the wget instructions do not work and if you correct for this, the script just fails in a big way. 

Are these instructions still current or how should VCE be done on the current ARM version?

### The page

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/amd-vce

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Yes those are still correct, but the requirements have been changed by handbrake to a minimum of 
`AMD Radeon RX5000 (RDNA) and RX6000 (RDNA2) series GPU or better`
