### ISSUE TITLE
🐛 makemkvcon default selection profile not working

### ISSUE THREAD

**Issue by heatvent** [automatic-ripping-machine/automatic-ripping-machine#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

There doesn't appear to be a way to use a default selection profile as described in arm.yaml ...

```
# MakeMKV Arguments
# MakeMKV Profile used for controlling Audio Track Selection.
# This is the default profile MakeMKV uses for Audio track selection. Updating this file or changing it is considered
# to be advanced usage of MakeMKV. But this will allow users to alternatively tell makemkv to select HD audio tracks and etc.
# MKV_ARGS: "--profile=/opt/arm/default.mmcp.xml"
# MKV_ARGS: "--debug=-stdout"  # this will enable more detailed logging
MKV_ARGS: ""
```

I believe profiles have been deprecated and default profile settings are in the GUI that somehow pass to makemkvcon. However, I have not been able to find the correct way to pass default profile settings to makemkvcon in a headless environment.

### To Reproduce

Add --profile=/opt/arm/default.mmcp.xml to MKV_ARGS. No effect.

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

latest

### Expected behavior?

Ability to pass a selection profile to makemkvcon so that only certain tracks are copied vs all tracks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
MakeMKV should already be pulling its own default profile when it starts, unless you have created a custom profile in another location. There should be no need to define one in the MakeMKV arguments.

Did you create the file `/opt/arm/default.mmcp.xml` ?

`# MKV_ARGS: "--profile=/opt/arm/default.mmcp.xml"`
I believe this was added as an example of custom location for a profile.


Unless I have misunderstood you ?

**Comment by heatvent** [comment]
Yes, I did and it doesn't seem to have an effect. 

In the default.mmcp.xml that comes with MakeMKV, it says the following...

```
    <!-- This tag is ignored by MakeMKV 1.12.4 and later, do not change it here. Set the app_DefaultSelectionString
         value in preferences. Keep this element in your custom profiles only for compatibility with older MakeMKV versions.
    -->
    <profileSettings
        app_DefaultSelectionString="-sel:all,+sel:(favlang|nolang|single),-sel:(havemulti|havecore),-sel:mvcvideo,=100:all,-10:favlang"
    />
```

There are also random posts over the years on the MakeMKV forums that say profiles were abandoned years ago.  There are a couple of other posts where people are asking the same question but no responses.

This ultimately seems to be a makemkvcon question vs. ARM (outside of the example in arm.yaml). Given the description in arm.yaml (which is exactly what I want to do ... select just he HD english track and subtitles), I was hoping this was something that might be able to be answered here. At the very least, maybe the arm.yaml example in the description needs to be taken out.

**Comment by 1337-server** [comment]
I've seen your thread on MakeMKV forum, could you message back when you get a response and ill open a PR if necessary to remove the example.

Thanks!

**Comment by heatvent** [comment]
It never fails. Only after posting the question can I seem to stumble on the answer.  I first found this post that said settings are stored in different locations for different OSs...

https://forum.makemkv.com/forum/viewtopic.php?f=19&t=22689&p=93341&hilit=drive+speed+control#p93341

So I made some changes to the GUI preferences for "Default Selection Profile" and low and behold they got populated in  HKEY_CURRENT_USER\Software\MakeMKV in the app_DefaultSelectionString setting.

I then went to my ARM machine and opened settings.conf in the /home/arm/.MakeMKV directory and added the following setting:

app_DefaultSelectionString = "whatever selection logic you want"

And voila, it is working.  Very straightforward once you figure this out but otherwise not obvious. My understanding is MakeMKV went away from using the profile file because of a couple of possible reasons. One is the file would/could be in the MakeMKV application directory and would get overwritten or deleted when updated. There may also have been challenges for MakeMKV to figure out which profile setting to use when multiple profiles existed in the directory.

Hope this helps someone else.

I think you can leave the MKV_ARGS but just remove the reference to importing profiles.

**Comment by Queuecumber** [comment]
I know this is old but I wanted to add  that you can still use the profile if you put the `defaultSelection` in the `output` tag, here is mine for example:

```
<?xml version="1.0" encoding="utf-8"?>
<profile>
    <name lang="eng">Minimized Direct Copy with English and Korean</name>
    
    <mkvSettings 
        ignoreForcedSubtitlesFlag="false"
        useISO639Type2T="false"
        setFirstAudioTrackAsDefault="true"
        setFirstSubtitleTrackAsDefault="true"
        setFirstForcedSubtitleTrackAsDefault="true"
        insertFirstChapter00IfMissing="true"
    />

    <outputSettings name="copy" outputFormat="directCopy">
        <description lang="eng">Copy track as is</description>
    </outputSettings>
    
    <trackSettings input="default">
        <output outputSettingsName="copy" 
                defaultSelection="-sel:all,+sel:eng,+sel:kor,-sel:core,-sel:havemulti,-sel:havelossless,-sel:special,0:eng,1:kor">
        </output>
    </trackSettings>
</profile>
```

Most examples show the `output` tag with `defaultSelection="$app_DefaultSelectionString"` but you can put whatever you want there
