### ISSUE TITLE
🐛 ARM not ripping discs on second drive (sr1/sg1); jobs stuck and cannot be abandoned until job starts on sr0/sg0

### ISSUE THREAD

**Issue by LeeNeighoff** [automatic-ripping-machine/automatic-ripping-machine#953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Today I acquired an LG 16NS40 UHD-friendly Blu-ray drive, pre-flashed with 16NS60 v1.00 firmware. Once installed, Ubuntu 23.04 running on the metal mounted it as /dev/sr1 & /dev/sg1, as I already have a very old (MT1939 controller) WH16NS40 drive mounted as /dev/sr0 & /dev/sg0. Upon recreating the container and inserting a disc, ARM created a job with name "None (None)" and ceased to do anything further. The drive then spun down. Ejecting and reinserting the disc creates another "ghost" job, and none of these can be canceled.* They also do not disappear on restart/recreation of the container. Ubuntu sees the disc, and can do anything you'd expect (see below).

*Getting a job to successfully start with my other drive seems to clear out the stuck jobs created when the new drive is used.

The following has been tried:
- Deleting the container and remaking it - no change
- Deleting the container and image, and then remaking it - no change
- Trying regular and UHD Blu-rays, as well as DVDs - no change
- Changing device flags in the Docker run command (including using advice from the [Docker Troubleshooting](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Docker-Troubleshooting#makemkv-cant-find-drives) wiki page) - no change
- Trying just sg0 and sg1 device flags - no change
- Re-downloading the Docker setup and remaking the container - no change
- Running MakeMKV in Ubuntu outside the container - this works perfectly
- Swapping SATA cables on the two drives - see italics below

_Swapping SATA cables on the drives to switch mount points changes this behavior - now the WH16NS60-flashed drive works perfectly (now mounted as /dev/sr0 & /dev/sg0) and the "vanilla" WH16NS40 (now /dev/sr1 & /dev/sg1) drive has these issues._

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/26010345/15d21818-00fa-450b-9ede-81c05bf86331)

### To Reproduce

1. Insert a disc into device sr1.
2. Wait.
3. Disc will be detected by OS and ARM, but ARM will not pull any info from the disc and the job will lock up. ARM will otherwise remain responsive.

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

1853b3662d622d97bb6159a2f5352411cdd849cd

### Expected behavior?

ARM was expected to detect the disc and rip it using MakeMKV.

### Relevant log output

```shell
Log for one job:

[10-04-2023 22:03:13] INFO ARM: ARM version: 2.6.60
[10-04-2023 22:03:13] INFO ARM: Python version: 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]
[10-04-2023 22:03:13] INFO ARM: User is: arm
[10-04-2023 22:03:13] INFO ARM: Alembic head is: 2e0dc31fcb2e
[10-04-2023 22:03:13] INFO ARM: Database version is: 2e0dc31fcb2e
[10-04-2023 22:03:13] INFO ARM: ************* Starting ARM processing at 2023-10-04 22:03:13.736408 *************


Log from ARM:

Wed Oct  4 19:00:49 UTC 2023 Entering docker wrapper
Wed Oct  4 19:00:49 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Wed Oct  4 19:00:54 UTC 2023 Entering docker wrapper
Wed Oct  4 19:00:54 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Wed Oct  4 19:01:35 UTC 2023 Entering docker wrapper
[ARM] Starting ARM for Bluray on sr1
Wed Oct  4 19:01:54 UTC 2023 Entering docker wrapper
[ARM] Starting ARM for Bluray on sr1
Wed Oct  4 22:02:37 UTC 2023 Entering docker wrapper
Wed Oct  4 22:02:37 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Wed Oct  4 22:02:40 UTC 2023 Entering docker wrapper
Wed Oct  4 22:02:40 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Wed Oct  4 22:03:05 UTC 2023 Entering docker wrapper
[ARM] Starting ARM for Bluray on sr1
Wed Oct  4 22:03:24 UTC 2023 Entering docker wrapper
[ARM] Starting ARM for Bluray on sr1
```

### Anything else?

Ubuntu 23.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LeeNeighoff** [comment]
Updated post with additional findings.

**Comment by shitwolfymakes** [comment]
What does the run command for the container look like?

**Comment by LeeNeighoff** [comment]
> What does the run command for the container look like?

This is what I have in the script:

`
docker run -d \
    -p "8080:8080" \
    -v "/home/arm:/home/arm" \
    -v "/mnt/plex-media/Music:/home/arm/music" \
    -v "/home/arm/logs:/home/arm/logs" \
    -v "/mnt/plex-media/rip-work-dir/ripped:/home/arm/media" \
    -v "/etc/arm/config:/etc/arm/config" \
    --device="/dev/sr0:/dev/sr0" \
    --device="/dev/sr1:/dev/sr1" \
    --device="/dev/sr2:/dev/sr2" \
    --device="/dev/sr3:/dev/sr3" \
    --privileged \
    --restart "always" \
    --name "arm-rippers" \
    --cpuset-cpus='2,3,4,5,6,7' \
    automaticrippingmachine/automatic-ripping-machine:latest
`
sr0 is my pre-MT1959 WH16NS40, and sr1 is my MT1959 WH16NS40 with the patched WH16NS60 firmware. I tried removing the extra device arguments as a test, but it didn't seem to affect operation.

**Comment by LeeNeighoff** [comment]
After some additional troubleshooting, I've identified the following:
- Setting two device flags for each drive in the Docker run command (sr0 + sg0, sr1 + sg1) according to the [Docker Troubleshooting](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Docker-Troubleshooting#makemkv-cant-find-drives) page does not change the observed behavior
- Powering down the system and swapping SATA cables swaps the mount points - WH16NS40 becomes sr1 and WH16NS60 becomes sr0
- Now, ARM has zero issue with the WH16NS60-flashed drive, but the behavior it had with that drive now appears when inserting a disk into the WH16NS40 "vanilla" drive

This seems to indicate that it doesn't play nice with whichever drive is set to sr1, but I can't figure out why. Could it be because they're the same model drive, just different revisions and firmwares?

Adding this info to the original post.

**Comment by LeeNeighoff** [comment]
_Sanity update: I may have a few screws loose. After so much troubleshooting, I tried the "Scan for Drives" button on the ARM Settings page in the web GUI, and then inserted a disc. Now it seems to be working perfectly. If this is documented anywhere, I apologize._

**Comment by microtechno9000** [comment]
when I get time, I will amend ARM to auto scan for new installs to avoid some of these errors
