### ISSUE TITLE
🐋 If crash / power outage = ARM corrupt

### ISSUE THREAD

**Issue by ThePianoMan2255** [automatic-ripping-machine/automatic-ripping-machine#956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

After a few power outages / crashes, it corrupts the docker. ARM is the only docker image that does this in my flow. 

### To Reproduce

Unknown, 

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Does not corrupt and runs after crash / power outage.

### Relevant log output

```shell
*** Running /etc/my_init.d/10_syslog-ng.init...
*** Running /etc/my_init.d/arm_user_files_setup.sh...
cp: not writing through dangling symlink '/etc/arm/config/abcde.conf'
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1

*** Killing all processes...
Oct  9 12:06:24 7764cf0f1473 syslog-ng[13]: syslog-ng starting up; version='3.25.1'
Updating arm user id from 1000 to 99...
Updating arm group id from 1000 to 100...
Adding arm user to 'render' group
Oct  9 12:06:32 7764cf0f1473 syslog-ng[13]: syslog-ng shutting down; version='3.25.1'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shitwolfymakes** [comment]
This is a fundamental architectural issue we are tracking, but have no quick fixes for at present. You will need to delete the job and it's associated files, then restart the job.

I have added it to a new [known issues](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Known-Issues) page on the wiki

**Comment by ThePianoMan2255** [comment]
Thank you for the update, unfortunately I have the docker just sitting stopped because it will not run due to the failure. I can't get it to run without completely wiping my configs. Ultimately I have done this multiple times already and just have not had the desire to do the work again, I will hope this issue resolves soon, but bugs are bugs, so, I may be waiting awhile. 

Thanks for the work you are doing !

**Comment by ThePianoMan2255** [comment]
I wanted to clarify because the known issues describes it differently. 

The crashed docker corrupts the entire image / container resulting in it not running, you start it, and it stops, start it and it stops. Unfortunately it does not have anything to do with it booting back up and the job is corrupt.

**Comment by ThePianoMan2255** [comment]
> If you did not change anything in abcde.conf yet, you might be able to get everything up and running again by deleting just this one config file.

I did, however, if all I have to do is back up my abcde.conf and copy it back once fixed each time thats not too bad, will reply back after test.

**Comment by ThePianoMan2255** [comment]
So it appears it can't create the abcde.config, it was already removed from the config folder. which means during power outages it corrupts by losing that config, not being able to recreate it. hmm

**Comment by ThePianoMan2255** [comment]
Update was available but did not relieve the issue. I am wondering if its a permission issue that I am unaware of, this docker is directly from ARM Dockerhub with the settings below. I run a permissions changer on my config files so I can change them within unraid. this could be the main problem and then the uid 99 gid 100 is no longer valid resulting in a crash after a loss of config?

![image](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/61894631/ccce95c9-9f3f-4a3c-9a1f-f7efd5252229)

**Comment by ThePianoMan2255** [comment]
I can confirm after manually placing the config that it restores functionality to the container.
