### ISSUE TITLE
🐛 Using docker container, config/abde.conf is always overwritten by system link

### ISSUE THREAD

**Issue by vangorra** [automatic-ripping-machine/automatic-ripping-machine#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Unable to use a custom abde.conf file as it is overwritten with a symlnk each time the docker container is run.

### To Reproduce

```
# Start off with an empty directory structure.
strider@lothlorien:~$ find ./Downloads/arm/
./Downloads/arm/

# Run the command and ctrl-c a few seconds after running.
strider@lothlorien:~$ ARM_UID=$UID docker run --rm --volume ./Downloads/arm/home:/home/arm --volume ./Downloads/arm/config:/etc/arm/config 1337server/automatic-ripping-machine:latest

# Initial files are confirmed generated.
strider@lothlorien:~$ find ./Downloads/arm/
./Downloads/arm/
./Downloads/arm/home
./Downloads/arm/home/logs
./Downloads/arm/home/db
./Downloads/arm/home/db/arm.db
./Downloads/arm/home/Music
./Downloads/arm/home/media
./Downloads/arm/home/.MakeMKV
./Downloads/arm/config
./Downloads/arm/config/abcde.conf
./Downloads/arm/config/apprise.yaml
./Downloads/arm/config/arm.yaml

# abcdef.conf is replaced with symlink.
strider@lothlorien:~$ ls -al ./Downloads/arm/config/
total 28
drwxr-xr-x 2 strider strider  4096 Nov  3 02:09 .
drwxrwxr-x 4 strider strider  4096 Nov  3 02:09 ..
lrwxrwxrwx 1 root    root       16 Nov  3 02:09 abcde.conf -> /etc/.abcde.conf
-rwxr-xr-x 1 strider strider  4645 Nov  3 02:09 apprise.yaml
-rwxr-xr-x 1 strider strider 11358 Nov  3 02:09 arm.yaml

# Create a new abde.conf file.
strider@lothlorien:~$ rm ./Downloads/arm/config/abcde.conf 
strider@lothlorien:~$ echo "#AAAAAAAAAAAAAAAAAAA" > ./Downloads/arm/config/abcde.conf

# Run the command and ctrl-c a few seconds after running.
strider@lothlorien:~$ ARM_UID=$UID docker run --rm --volume ./Downloads/arm/home:/home/arm --volume ./Downloads/arm/config:/etc/arm/config 1337server/automatic-ripping-machine:latest

# abcde.conf file is replaced with a symlink.
strider@lothlorien:~$ ls -al ./Downloads/arm/config/
total 28
drwxr-xr-x 2 strider strider  4096 Nov  3 02:13 .
drwxrwxr-x 4 strider strider  4096 Nov  3 02:09 ..
lrwxrwxrwx 1 root    root       16 Nov  3 02:13 abcde.conf -> /etc/.abcde.conf
-rwxr-xr-x 1 strider strider  4645 Nov  3 02:09 apprise.yaml
-rwxr-xr-x 1 strider strider 11358 Nov  3 02:09 arm.yaml

```

### What OS are you seeing the problem on?

all

### ARM Release Version or Git hash (You can find this in the arm settings page)

ImageId cf14c5792e85

### Expected behavior?

Similar to the arm.yaml and apprise.yaml files, the abcde.conf file should remain unchanged and the container should use that config file as the authoritative source.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThePianoMan2255** [comment]
It primarily happens after an update to a new version. I have not had it happen just on normal boot.

**Comment by Aesir** [comment]
This was fixed [in main](https://github.com/automatic-ripping-machine/automatic-ripping-machine/commit/81cdd91d2b16642e90e450e066c1b9c53d74fa40) back in Sept but hasn't seemed to have made it into any of the release branches. I'm not sure what the process is here to get the bug fix propagated into a release.

**Comment by 1337-server** [comment]
This should be fixed with the latest release! 

Please ping if you are still having issues.
