### ISSUE TITLE
Add a config parameter to configure makemkv output filename format

### ISSUE THREAD

**Issue by WizardOfYendor1** [automatic-ripping-machine/automatic-ripping-machine#984]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I'm ripping a multidisc TV series (MANY discs) and the metadata lookup is almost always wrong for this particular series/DVDs. So if I don't get to the manual identification in time, I get all kinds of wrong file name directories. Worse yet, the series metadata extracted is of no use identifying what disc or season the content came from.  So I've left looking at timedate stamps to figure out the order of the discs as they were ripped.  I can turn it off, of course, as a work around. 

### Describe the solution you'd like?

If possible allow the makemkv filename template formatting to be added and used as a parameter for the output file names. 

The formatting is defined here: https://forum.makemkv.com/forum/viewtopic.php?f=10&t=18313

Alternatively, an option to always use the disc title (aka "Name") as the root folder. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Work is being done to get ARM to better handle TV Series, it won't be done soon. But it is in progress

**Comment by polskikrol** [comment]
This feature would apply to BOTH ripped CD audio and DVD/BD movies I would think. I have done something in the past with mediainfo to gather media information. ABCDE is nearly 6 years old with the last release being v2.9.3 around March 2018. There is no way to name files based on length for example. If anything, being able to support a scripted method like awk/sed to perform a regex and/or replacement with info gathered from an integration like with mediainfo would probably work. Could take more work, but could also load meta data into a json format in memory and allow variable subs. Not sure if there is a renamer that already exits out of the box in ubuntu.

**Comment by mihawk90** [comment]
> If possible allow the makemkv filename template formatting to be added and used as a parameter for the output file names.
> 
> The formatting is defined here: https://forum.makemkv.com/forum/viewtopic.php?f=10&t=18313

You can already use this, which is what I am currently doing. I'm not using the metadata lookup (no omdb key, I don't like "automagic" metadata fetching I can't control).

`makemkvcon` respects the settings file in `~/.MakeMKV` so you can just use that and add your filename template in the `app_DefaultOutputFileName` key:
```toml
# default: {NAME1}{-:CMNT1}{-:DT}{title:+DFLT}{_t:N2}
app_DefaultOutputFileName = "{NAME1}{-:CMNT1}{-:DT}{title:+DFLT}{_S99E:M2}"
```
