### ISSUE TITLE
📚 missing steps in NVIDIA NVENC support

### ISSUE THREAD

**Issue by kimzrn** [automatic-ripping-machine/automatic-ripping-machine#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

The page do not say anything about how to install drivers or the NVIDIA Container Toolkit

### The page

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/nvidia

### Installing NVIDIA drivers:
Recommended to do immediately after installing ubuntu

1. Installing the drivers on servers and/or for computing purposes
`sudo ubuntu-drivers install --gpgpu`
If you have a desktop environment install drop the --gpgpu

2. Reboot system
`sudo reboot`

### Installing the NVIDIA Container Toolkit:
Do this before point 5 in post installation guide for docker "Run the container with sudo ./start_arm_container.sh" 

1. Adding the repository:
`curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list` 
    
2. Update repository
`sudo apt-get update`
4. Install the NVIDIA Container Toolkit packages:
`sudo apt-get install -y nvidia-container-toolkit`

5. Configure the container runtime by using the nvidia-ctk command:
`sudo nvidia-ctk runtime configure --runtime=docker`

6. Restart the Docker daemon:
`sudo systemctl restart docker`

### Anything else?

The information is collected form this two websites 
https://ubuntu.com/server/docs/nvidia-drivers-installation
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Now added to the wiki!
