### ISSUE TITLE
📚 arm.yaml sample link is broken

### ISSUE THREAD

**Issue by charmarkk** [automatic-ripping-machine/automatic-ripping-machine#995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

The link for the arm.yaml sample is broken. Looks like it was moved due to #716 but the link was never fixed.

### The page

https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/arm.yaml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lg-vlouvet** [comment]
I created a fork with the documentation link updated, but am unable to create a PR into the wiki https://github.com/automatic-ripping-machine/automatic-ripping-machine/compare/v2_devel...lg-vlouvet:automatic-ripping-machine:issue-995-document-fix?expand=1

**Comment by shitwolfymakes** [comment]
Corrected, thanks for catching this!
